//! Object sum type and stable object-kind identifiers.

use super::atom::AtomObj;
use super::function_set::{AnonymousFn, FnSet};
use crate::prelude::*;

#[derive(Clone)]
pub enum Obj {
    Atom(AtomObj),
    FnObj(FnObj),
    Number(Number),
    ImaginaryUnit(ImaginaryUnit),
    EulerNumber(EulerNumber),
    Pi(Pi),
    Add(Add),
    Sub(Sub),
    Mul(Mul),
    Div(Div),
    Mod(Mod),
    Quot(Quot),
    Gcd(Gcd),
    Lcm(Lcm),
    Floor(Floor),
    Ceil(Ceil),
    Min(Min),
    Max(Max),
    Exp(Exp),
    Ln(Ln),
    Sign(Sign),
    Factorial(Factorial),
    Pow(Pow),
    Abs(Abs),
    Sin(Sin),
    Arcsin(Arcsin),
    Cos(Cos),
    Tan(Tan),
    Cot(Cot),
    RealPart(RealPart),
    ImaginaryPart(ImaginaryPart),
    ComplexAbs(ComplexAbs),
    Sqrt(Sqrt),
    Log(Log),
    Union(Union),
    Intersect(Intersect),
    SetMinus(SetMinus),
    FamilyUnion(FamilyUnion),
    FamilyIntersect(FamilyIntersect),
    IndexUnion(IndexUnion),
    IndexIntersect(IndexIntersect),
    PowerSet(PowerSet),
    IndexCart(IndexCart),
    ListSet(ListSet),
    SetBuilder(SetBuilder),
    FnSet(FnSet),
    AnonymousFn(AnonymousFn),
    Cart(Cart),
    CartDim(CartDim),
    Proj(Proj),
    TupleDim(TupleDim),
    Tuple(Tuple),
    FiniteSetSize(FiniteSetSize),
    FiniteSetMax(FiniteSetMax),
    FiniteSetMin(FiniteSetMin),
    FnRange(FnRange),
    Replacement(Replacement),
    Sum(Sum),
    SumOfFiniteSet(SumOfFiniteSet),
    Product(Product),
    ProductOfFiniteSet(ProductOfFiniteSet),
    Reduce(Reduce),
    FiniteSetReduce(FiniteSetReduce),
    Range(Range),
    ClosedRange(ClosedRange),
    FiniteSeqSet(FiniteSeqSet),
    SeqSet(SeqSet),
    FiniteSeqListObj(FiniteSeqListObj),
    ObjAtIndex(ObjAtIndex),
    StandardSet(StandardSet),
    MatrixSet(MatrixSet),
    MatrixListObj(MatrixListObj),
    MatrixAdd(MatrixAdd),
    MatrixSub(MatrixSub),
    MatrixMul(MatrixMul),
    MatrixScalarMul(MatrixScalarMul),
    MatrixPow(MatrixPow),
    StructObj(StructObj),
    ObjAsStructInstanceWithFieldAccess(ObjAsStructInstanceWithFieldAccess),
    InstantiatedTemplateObj(InstantiatedTemplateObj),
    OneSideInfinityIntervalObj(OneSideInfinityIntervalObj),
    IntervalObj(IntervalObj),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum ObjKind {
    Atom = 0,
    FnObj = 1,
    Number = 2,
    Add = 3,
    Sub = 4,
    Mul = 5,
    Div = 6,
    Mod = 7,
    Pow = 8,
    Abs = 9,
    Sqrt = 10,
    Log = 11,
    FiniteSetMax = 12,
    FiniteSetMin = 13,
    Union = 14,
    Intersect = 15,
    SetMinus = 16,
    // 17 was historically occupied by the removed symmetric-difference builtin.
    FamilyUnion = 18,
    FamilyIntersect = 19,
    PowerSet = 20,
    ListSet = 21,
    SetBuilder = 22,
    FnSet = 23,
    AnonymousFn = 24,
    Cart = 25,
    CartDim = 26,
    Proj = 27,
    TupleDim = 28,
    Tuple = 29,
    FiniteSetSize = 30,
    Sum = 31,
    SumOfFiniteSet = 32,
    Product = 33,
    ProductOfFiniteSet = 34,
    Range = 35,
    ClosedRange = 36,
    FiniteSeqSet = 37,
    SeqSet = 38,
    FiniteSeqListObj = 39,
    ObjAtIndex = 40,
    StandardSet = 41,
    MatrixSet = 42,
    MatrixListObj = 43,
    MatrixAdd = 44,
    MatrixSub = 45,
    MatrixMul = 46,
    MatrixScalarMul = 47,
    MatrixPow = 48,
    StructObj = 49,
    ObjAsStructInstanceWithFieldAccess = 50,
    InstantiatedTemplateObj = 51,
    OneSideInfinityIntervalObj = 52,
    IntervalObj = 53,
    Identifier = 54,
    IdentifierWithMod = 55,
    BoundParam = 56,
    // 57-63 were historically binder-source-specific free-parameter kinds.
    FnRange = 64,
    Replacement = 66,
    // 67-68 were historically tuple/cart binder-source-specific kinds.
    IndexCart = 69,
    ImaginaryUnit = 70,
    RealPart = 71,
    ImaginaryPart = 72,
    ComplexAbs = 73,
    EulerNumber = 74,
    Pi = 75,
    Sin = 76,
    Cos = 77,
    Tan = 78,
    Cot = 79,
    Gcd = 80,
    Lcm = 81,
    Floor = 82,
    Ceil = 83,
    Min = 84,
    Max = 85,
    Exp = 86,
    Ln = 87,
    Sign = 88,
    Factorial = 89,
    Reduce = 90,
    FiniteSetReduce = 91,
    Quot = 92,
    IndexUnion = 93,
    IndexIntersect = 94,
    Arcsin = 95,
}

impl ObjKind {
    pub fn as_u8(self) -> u8 {
        self as u8
    }
}

#[cfg(test)]
#[path = "../../tests/unit/object/model/tests.rs"]
mod tests;
