mod collect_monomials;
mod evaluate;
mod monomial;
mod objs_equal_by_rational_expression_simplification;
mod process_division_after_polynomial_simplification;

mod evaluate_div;

pub use evaluate::normalize_decimal_number_string;
pub use objs_equal_by_rational_expression_simplification::objs_equal_by_rational_expression_evaluation;
