use super::stmt::statements;
use crate::ast::stmt::Stmt;
use crate::launch_command::OutputLanguage;
use crate::module_manager::GlobalModuleManager;
use crate::runtime::RuntimeResult;

/// Render an existing parsed AST. No statement is executed or verified.
pub fn to_latex_from_ast(
    stmts: &[Stmt],
    modules: &GlobalModuleManager,
    language: OutputLanguage,
) -> RuntimeResult<String> {
    statements(stmts, modules, language)
}

/// Wrap a generated fragment for XeLaTeX. See README for the required fonts.
pub fn to_latex_document(fragment: &str, language: OutputLanguage) -> String {
    let setup=match language {
        OutputLanguage::Chinese => "\\usepackage[fontset=fandol]{ctex}\n",
        OutputLanguage::ChineseTraditional => "\\usepackage[fontset=none]{ctex}\n\\setCJKmainfont[AutoFakeBold=2]{bsmi00lp.ttf}\n",
        OutputLanguage::Japanese => "\\usepackage{xeCJK}\n\\setCJKmainfont[AutoFakeBold=2]{ipaexm.ttf}\n",
        OutputLanguage::Korean => "\\usepackage{xeCJK}\n\\setCJKmainfont[BoldFont=UnBatangBold.ttf]{UnBatang.ttf}\n",
        OutputLanguage::Arabic => "\\usepackage{polyglossia}\n\\setdefaultlanguage{arabic}\n\\newfontfamily\\arabicfont[Script=Arabic,BoldFont=Amiri-Bold.ttf]{Amiri-Regular.ttf}\n",
        _ => "",
    };
    format!("% Generated by Litex; source parsed, not verified.\n% Compile with XeLaTeX.\n\\documentclass[11pt]{{article}}\n\\usepackage{{amsmath,amssymb}}\n\\usepackage{{fontspec}}\n\\setmainfont[BoldFont=cmunbx.otf,ItalicFont=cmunit.otf]{{cmunrm.otf}}\n\\usepackage[margin=25mm]{{geometry}}\n{setup}\\setlength{{\\parskip}}{{0.6em}}\n\\begin{{document}}\n{fragment}\\end{{document}}\n")
}
