use crate::launch_command::OutputLanguage;

#[derive(Clone, Copy)]
pub(super) enum Phrase {
    Theorem,
    Proof,
    Definition,
    Axiom,
    Strategy,
    Structure,
    Template,
    Sketch,
    Claim,
    Case,
    Base,
    Step,
    Set,
    NonemptySet,
    FiniteSet,
    Let,
    Define,
    Given,
    Choose,
    ByTheorem,
    ApplyTheorem,
    Unfold,
    Witness,
    Evaluate,
    Induction,
    StrongInduction,
    Cases,
    Suppose,
    Goal,
    Contradiction,
    Extension,
    FnExtension,
    Enumerate,
    Iterate,
    RegisterTransitive,
    RegisterSymmetric,
    RegisterReflexive,
    ForEvery,
    ForEveryIf,
    Replacement,
    Preimage,
    Choice,
    Zorn,
    Regularity,
    ReleaseStruct,
    ReleaseObj,
    Trusted,
    AbstractPredicate,
    Algorithm,
    ExpandRange,
    ContradictionMethod,
    IfThen,
}

pub(super) fn phrase(lang: OutputLanguage, key: Phrase) -> &'static str {
    let phrases: [&str; 52] = match lang {
        OutputLanguage::English => [
            "Theorem",
            "Proof",
            "Definition",
            "Axiom",
            "Strategy",
            "Structure",
            "Template",
            "Sketch",
            "Claim",
            "Case",
            "Base case",
            "Induction step",
            "set",
            "nonempty set",
            "finite set",
            "Let @a@.",
            "Define @a@ by @b@.",
            "Let @a@ satisfy @b@.",
            "Choose @a@ from @b@.",
            "By Theorem @a@, we obtain @b@.",
            "Apply Theorem @a@.",
            "By definition, @a@.",
            "Take @a@ as witnesses for @b@.",
            "Evaluate @a@.",
            "Proceed by induction on @a@, starting at @b@.",
            "Proceed by strong induction on @a@, starting at @b@.",
            "Proceed by cases.",
            "Suppose @a@.",
            "We aim to show @a@.",
            "This yields a contradiction: @a@.",
            "Use set extensionality to show @a@.",
            "Use function extensionality to show @a@.",
            "Enumerate the finite domain to show @a@.",
            "Iterate over the finite domain to show @a@.",
            "Register transitivity: @a@.",
            "Register symmetry: @a@.",
            "Register reflexivity: @a@.",
            "For every @a@, we have @b@.",
            "For every @a@ satisfying @b@, we have @c@.",
            "By the replacement axiom, define @a@ using @b@ on @c@.",
            "Choose preimages @a@ for @b@.",
            "Apply the axiom of choice to @a@.",
            "Apply Zorn's lemma to @a@ with order, upper-bound and maximality predicates @b@.",
            "Apply the axiom of regularity to @a@.",
            "Unpack the structure definition of @a@.",
            "Unpack the object definition of @a@.",
            "Assumption (trust)",
            "Abstract predicate",
            "Algorithm",
            "Expand the range membership @a@.",
            "Proceed by contradiction.",
            "If @a@, then @b@.",
        ],
        OutputLanguage::Chinese => [
            "定理",
            "证明",
            "定义",
            "公理",
            "证明策略",
            "结构",
            "模板",
            "证明草图",
            "断言",
            "情形",
            "基础情形",
            "归纳步骤",
            "集合",
            "非空集合",
            "有限集合",
            "设 @a@。",
            "以 @b@ 定义 @a@。",
            "取 @a@，使其满足 @b@。",
            "由 @b@ 选取 @a@。",
            "由定理 @a@，得 @b@。",
            "应用定理 @a@。",
            "根据定义，@a@。",
            "取 @a@ 作为 @b@ 的见证。",
            "计算 @a@。",
            "对 @a@ 从 @b@ 起作数学归纳。",
            "对 @a@ 从 @b@ 起作强归纳。",
            "分情形讨论。",
            "假设 @a@。",
            "现证明 @a@。",
            "由此得到矛盾：@a@。",
            "利用集合外延性证明 @a@。",
            "利用函数外延性证明 @a@。",
            "枚举有限定义域，证明 @a@。",
            "遍历有限定义域，证明 @a@。",
            "登记传递性：@a@。",
            "登记对称性：@a@。",
            "登记自反性：@a@。",
            "对任意 @a@，都有 @b@。",
            "对任意满足 @b@ 的 @a@，都有 @c@。",
            "由替换公理，用 @b@ 在 @c@ 上定义 @a@。",
            "为 @b@ 选取原像 @a@。",
            "对 @a@ 应用选择公理。",
            "对 @a@ 应用佐恩引理，其序关系、上界和极大性谓词为 @b@。",
            "对 @a@ 应用正则公理。",
            "展开 @a@ 的结构定义。",
            "展开 @a@ 的对象定义。",
            "假定（trust）",
            "抽象谓词",
            "算法",
            "展开区间成员关系 @a@。",
            "用反证法证明。",
            "若 @a@，则 @b@。",
        ],
        OutputLanguage::ChineseTraditional => [
            "定理",
            "證明",
            "定義",
            "公理",
            "證明策略",
            "結構",
            "模板",
            "證明草圖",
            "斷言",
            "情形",
            "基礎情形",
            "歸納步驟",
            "集合",
            "非空集合",
            "有限集合",
            "設 @a@。",
            "以 @b@ 定義 @a@。",
            "取 @a@，使其滿足 @b@。",
            "由 @b@ 選取 @a@。",
            "由定理 @a@，得 @b@。",
            "應用定理 @a@。",
            "根據定義，@a@。",
            "取 @a@ 作為 @b@ 的見證。",
            "計算 @a@。",
            "對 @a@ 從 @b@ 起作數學歸納。",
            "對 @a@ 從 @b@ 起作強歸納。",
            "分情形討論。",
            "假設 @a@。",
            "現證明 @a@。",
            "由此得到矛盾：@a@。",
            "利用集合外延性證明 @a@。",
            "利用函數外延性證明 @a@。",
            "枚舉有限定義域，證明 @a@。",
            "遍歷有限定義域，證明 @a@。",
            "登記遞移性：@a@。",
            "登記對稱性：@a@。",
            "登記自反性：@a@。",
            "對任意 @a@，都有 @b@。",
            "對任意滿足 @b@ 的 @a@，都有 @c@。",
            "由替換公理，用 @b@ 在 @c@ 上定義 @a@。",
            "為 @b@ 選取原像 @a@。",
            "對 @a@ 應用選擇公理。",
            "對 @a@ 應用佐恩引理，其序關係、上界和極大性謂詞為 @b@。",
            "對 @a@ 應用正則公理。",
            "展開 @a@ 的結構定義。",
            "展開 @a@ 的物件定義。",
            "假定（trust）",
            "抽象謂詞",
            "演算法",
            "展開區間成員關係 @a@。",
            "用反證法證明。",
            "若 @a@，則 @b@。",
        ],
        OutputLanguage::French => [
            "Théorème",
            "Démonstration",
            "Définition",
            "Axiome",
            "Stratégie de preuve",
            "Structure",
            "Modèle",
            "Esquisse de preuve",
            "Assertion",
            "Cas",
            "Cas initial",
            "Étape de récurrence",
            "ensemble",
            "ensemble non vide",
            "ensemble fini",
            "Soit @a@.",
            "Définissons @a@ par @b@.",
            "Choisissons @a@ satisfaisant @b@.",
            "Choisissons @a@ à partir de @b@.",
            "Par le théorème @a@, nous obtenons @b@.",
            "Appliquons le théorème @a@.",
            "Par définition, @a@.",
            "Prenons @a@ comme témoins de @b@.",
            "Calculons @a@.",
            "Procédons par récurrence sur @a@ à partir de @b@.",
            "Procédons par récurrence forte sur @a@ à partir de @b@.",
            "Distinguons les cas.",
            "Supposons @a@.",
            "Montrons @a@.",
            "Cela donne une contradiction : @a@.",
            "Utilisons l’extensionalité des ensembles pour montrer @a@.",
            "Utilisons l’extensionalité des fonctions pour montrer @a@.",
            "Énumérons le domaine fini pour montrer @a@.",
            "Parcourons le domaine fini pour montrer @a@.",
            "Enregistrons la transitivité : @a@.",
            "Enregistrons la symétrie : @a@.",
            "Enregistrons la réflexivité : @a@.",
            "Pour tout @a@, nous avons @b@.",
            "Pour tout @a@ satisfaisant @b@, nous avons @c@.",
            "Par l’axiome de remplacement, définissons @a@ au moyen de @b@ sur @c@.",
            "Choisissons les antécédents @a@ de @b@.",
            "Appliquons l’axiome du choix à @a@.",
            "Appliquons le lemme de Zorn à @a@ avec les prédicats d’ordre, de majorant et de maximalité @b@.",
            "Appliquons l’axiome de fondation à @a@.",
            "Déployons la définition de la structure @a@.",
            "Déployons la définition de l’objet @a@.",
            "Hypothèse (trust)",
            "Prédicat abstrait",
            "Algorithme",
            "Développons l’appartenance à l’intervalle @a@.",
            "Procédons par l’absurde.",
            "Si @a@, alors @b@.",
        ],
        OutputLanguage::Russian => [
            "Теорема",
            "Доказательство",
            "Определение",
            "Аксиома",
            "Стратегия доказательства",
            "Структура",
            "Шаблон",
            "Набросок доказательства",
            "Утверждение",
            "Случай",
            "База индукции",
            "Шаг индукции",
            "множество",
            "непустое множество",
            "конечное множество",
            "Пусть @a@.",
            "Определим @a@ формулой @b@.",
            "Выберем @a@ так, чтобы @b@.",
            "Выберем @a@ из @b@.",
            "По теореме @a@ получаем @b@.",
            "Применим теорему @a@.",
            "По определению, @a@.",
            "Возьмём @a@ в качестве свидетелей для @b@.",
            "Вычислим @a@.",
            "Проведём индукцию по @a@ начиная с @b@.",
            "Проведём сильную индукцию по @a@ начиная с @b@.",
            "Рассмотрим случаи.",
            "Предположим @a@.",
            "Докажем @a@.",
            "Получаем противоречие: @a@.",
            "Применим экстенсиональность множеств, чтобы доказать @a@.",
            "Применим экстенсиональность функций, чтобы доказать @a@.",
            "Переберём конечную область, чтобы доказать @a@.",
            "Пройдём по конечной области, чтобы доказать @a@.",
            "Зарегистрируем транзитивность: @a@.",
            "Зарегистрируем симметричность: @a@.",
            "Зарегистрируем рефлексивность: @a@.",
            "Для всех @a@ выполняется @b@.",
            "Для всех @a@, удовлетворяющих @b@, выполняется @c@.",
            "По аксиоме замены определим @a@ с помощью @b@ на @c@.",
            "Выберем прообразы @a@ для @b@.",
            "Применим аксиому выбора к @a@.",
            "Применим лемму Цорна к @a@ с предикатами порядка, верхней грани и максимальности @b@.",
            "Применим аксиому регулярности к @a@.",
            "Раскроем определение структуры @a@.",
            "Раскроем определение объекта @a@.",
            "Предположение (trust)",
            "Абстрактный предикат",
            "Алгоритм",
            "Развернём принадлежность диапазону @a@.",
            "Докажем от противного.",
            "Если @a@, то @b@.",
        ],
        OutputLanguage::Spanish => [
            "Teorema",
            "Demostración",
            "Definición",
            "Axioma",
            "Estrategia de demostración",
            "Estructura",
            "Plantilla",
            "Esbozo de demostración",
            "Afirmación",
            "Caso",
            "Caso base",
            "Paso inductivo",
            "conjunto",
            "conjunto no vacío",
            "conjunto finito",
            "Sea @a@.",
            "Definamos @a@ mediante @b@.",
            "Tomemos @a@ que satisfaga @b@.",
            "Elijamos @a@ a partir de @b@.",
            "Por el teorema @a@, obtenemos @b@.",
            "Apliquemos el teorema @a@.",
            "Por definición, @a@.",
            "Tomemos @a@ como testigos de @b@.",
            "Calculemos @a@.",
            "Procedamos por inducción sobre @a@ a partir de @b@.",
            "Procedamos por inducción fuerte sobre @a@ a partir de @b@.",
            "Distinguimos casos.",
            "Supongamos @a@.",
            "Demostremos @a@.",
            "Esto da una contradicción: @a@.",
            "Usemos la extensionalidad de conjuntos para demostrar @a@.",
            "Usemos la extensionalidad de funciones para demostrar @a@.",
            "Enumeremos el dominio finito para demostrar @a@.",
            "Recorramos el dominio finito para demostrar @a@.",
            "Registremos la transitividad: @a@.",
            "Registremos la simetría: @a@.",
            "Registremos la reflexividad: @a@.",
            "Para todo @a@, tenemos @b@.",
            "Para todo @a@ que satisface @b@, tenemos @c@.",
            "Por el axioma de reemplazo, definamos @a@ mediante @b@ sobre @c@.",
            "Elijamos las preimágenes @a@ de @b@.",
            "Apliquemos el axioma de elección a @a@.",
            "Apliquemos el lema de Zorn a @a@ con los predicados de orden, cota superior y maximalidad @b@.",
            "Apliquemos el axioma de regularidad a @a@.",
            "Despleguemos la definición de la estructura @a@.",
            "Despleguemos la definición del objeto @a@.",
            "Supuesto (trust)",
            "Predicado abstracto",
            "Algoritmo",
            "Expandamos la pertenencia al intervalo @a@.",
            "Procedamos por contradicción.",
            "Si @a@, entonces @b@.",
        ],
        OutputLanguage::Arabic => [
            "نظرية",
            "برهان",
            "تعريف",
            "بديهية",
            "استراتيجية البرهان",
            "بنية",
            "قالب",
            "مخطط البرهان",
            "ادعاء",
            "حالة",
            "الحالة الأساسية",
            "خطوة الاستقراء",
            "مجموعة",
            "مجموعة غير فارغة",
            "مجموعة منتهية",
            "ليكن @a@.",
            "نعرّف @a@ بواسطة @b@.",
            "نختار @a@ بحيث يتحقق @b@.",
            "نختار @a@ انطلاقًا من @b@.",
            "باستخدام النظرية @a@ نحصل على @b@.",
            "نطبّق النظرية @a@.",
            "حسب التعريف، @a@.",
            "نأخذ @a@ شهودًا على @b@.",
            "نحسب @a@.",
            "نستخدم الاستقراء على @a@ بدءًا من @b@.",
            "نستخدم الاستقراء القوي على @a@ بدءًا من @b@.",
            "نميّز الحالات.",
            "نفترض @a@.",
            "نريد إثبات @a@.",
            "ينتج عن ذلك تناقض: @a@.",
            "نستخدم امتدادية المجموعات لإثبات @a@.",
            "نستخدم امتدادية الدوال لإثبات @a@.",
            "نعدّد عناصر المجال المنتهي لإثبات @a@.",
            "نجتاز المجال المنتهي لإثبات @a@.",
            "نسجّل خاصية التعدّي: @a@.",
            "نسجّل خاصية التناظر: @a@.",
            "نسجّل خاصية الانعكاس: @a@.",
            "لكل @a@ يتحقق @b@.",
            "لكل @a@ يحقق @b@، يتحقق @c@.",
            "ببديهية الاستبدال نعرّف @a@ باستخدام @b@ على @c@.",
            "نختار الصور العكسية @a@ من أجل @b@.",
            "نطبّق بديهية الاختيار على @a@.",
            "نطبّق لمّة زورن على @a@ مع محمولات الترتيب والحد العلوي والعظمى @b@.",
            "نطبّق بديهية الانتظام على @a@.",
            "نفكّ تعريف البنية @a@.",
            "نفكّ تعريف الكائن @a@.",
            "افتراض (trust)",
            "محمول مجرد",
            "خوارزمية",
            "نوسّع علاقة الانتماء إلى المجال @a@.",
            "نبرهن بالخلف.",
            "إذا تحقق @a@، فإن @b@.",
        ],
        OutputLanguage::Japanese => [
            "定理",
            "証明",
            "定義",
            "公理",
            "証明戦略",
            "構造",
            "テンプレート",
            "証明の概略",
            "主張",
            "場合",
            "基底の場合",
            "帰納段階",
            "集合",
            "空でない集合",
            "有限集合",
            "@a@ とする。",
            "@a@ を @b@ により定義する。",
            "@b@ を満たす @a@ を取る。",
            "@b@ から @a@ を選ぶ。",
            "定理 @a@ より @b@ を得る。",
            "定理 @a@ を適用する。",
            "定義より @a@。",
            "@b@ の証人として @a@ を取る。",
            "@a@ を計算する。",
            "@b@ を初期値として @a@ に関する数学的帰納法を用いる。",
            "@b@ を初期値として @a@ に関する強い帰納法を用いる。",
            "場合分けを行う。",
            "@a@ と仮定する。",
            "@a@ を示す。",
            "これにより矛盾 @a@ を得る。",
            "集合の外延性を用いて @a@ を示す。",
            "関数の外延性を用いて @a@ を示す。",
            "有限な定義域を列挙して @a@ を示す。",
            "有限な定義域を走査して @a@ を示す。",
            "推移性 @a@ を登録する。",
            "対称性 @a@ を登録する。",
            "反射性 @a@ を登録する。",
            "任意の @a@ に対して @b@ が成り立つ。",
            "@b@ を満たす任意の @a@ に対して @c@ が成り立つ。",
            "置換公理により、@c@ 上の @b@ を用いて @a@ を定義する。",
            "@b@ の原像 @a@ を選ぶ。",
            "@a@ に選択公理を適用する。",
            "順序、上界、極大性の述語 @b@ を用いて @a@ にツォルンの補題を適用する。",
            "@a@ に正則性公理を適用する。",
            "@a@ の構造定義を展開する。",
            "@a@ の対象の定義を展開する。",
            "仮定（trust）",
            "抽象述語",
            "アルゴリズム",
            "区間への所属 @a@ を展開する。",
            "背理法を用いる。",
            "@a@ ならば @b@ が成り立つ。",
        ],
        OutputLanguage::Korean => [
            "정리",
            "증명",
            "정의",
            "공리",
            "증명 전략",
            "구조",
            "템플릿",
            "증명 개요",
            "주장",
            "경우",
            "기초 단계",
            "귀납 단계",
            "집합",
            "공집합이 아닌 집합",
            "유한 집합",
            "@a@ 라 하자.",
            "@a@ 를 @b@ 로 정의한다.",
            "@b@ 를 만족하는 @a@ 를 택한다.",
            "@b@ 에서 @a@ 를 택한다.",
            "정리 @a@ 에 의해 @b@ 를 얻는다.",
            "정리 @a@ 를 적용한다.",
            "정의에 의해 @a@.",
            "@b@ 의 증인으로 @a@ 를 택한다.",
            "@a@ 를 계산한다.",
            "@b@ 부터 @a@ 에 대한 수학적 귀납법을 적용한다.",
            "@b@ 부터 @a@ 에 대한 강한 귀납법을 적용한다.",
            "경우를 나누어 논증한다.",
            "@a@ 를 가정하자.",
            "@a@ 를 보이자.",
            "이로부터 모순 @a@ 를 얻는다.",
            "집합의 외연성을 이용하여 @a@ 를 보인다.",
            "함수의 외연성을 이용하여 @a@ 를 보인다.",
            "유한 정의역을 열거하여 @a@ 를 보인다.",
            "유한 정의역을 순회하여 @a@ 를 보인다.",
            "추이성 @a@ 를 등록한다.",
            "대칭성 @a@ 를 등록한다.",
            "반사성 @a@ 를 등록한다.",
            "임의의 @a@ 에 대해 @b@ 가 성립한다.",
            "@b@ 를 만족하는 임의의 @a@ 에 대해 @c@ 가 성립한다.",
            "치환 공리에 의해 @c@ 위의 @b@ 를 사용하여 @a@ 를 정의한다.",
            "@b@ 의 원상 @a@ 를 택한다.",
            "@a@ 에 선택 공리를 적용한다.",
            "순서, 상계, 극대성 술어 @b@ 를 사용하여 @a@ 에 초른의 보조정리를 적용한다.",
            "@a@ 에 정칙 공리를 적용한다.",
            "@a@ 의 구조 정의를 펼친다.",
            "@a@ 의 대상 정의를 펼친다.",
            "가정 (trust)",
            "추상 술어",
            "알고리즘",
            "구간 소속 관계 @a@ 를 전개한다.",
            "귀류법을 사용한다.",
            "@a@ 이면 @b@ 가 성립한다.",
        ],
        OutputLanguage::Vietnamese => [
            "Định lý",
            "Chứng minh",
            "Định nghĩa",
            "Tiên đề",
            "Chiến lược chứng minh",
            "Cấu trúc",
            "Mẫu",
            "Phác thảo chứng minh",
            "Khẳng định",
            "Trường hợp",
            "Trường hợp cơ sở",
            "Bước quy nạp",
            "tập hợp",
            "tập hợp khác rỗng",
            "tập hữu hạn",
            "Cho @a@.",
            "Định nghĩa @a@ bởi @b@.",
            "Chọn @a@ thỏa mãn @b@.",
            "Chọn @a@ từ @b@.",
            "Theo định lý @a@, ta được @b@.",
            "Áp dụng định lý @a@.",
            "Theo định nghĩa, @a@.",
            "Lấy @a@ làm nhân chứng cho @b@.",
            "Tính @a@.",
            "Dùng quy nạp theo @a@ bắt đầu từ @b@.",
            "Dùng quy nạp mạnh theo @a@ bắt đầu từ @b@.",
            "Xét các trường hợp.",
            "Giả sử @a@.",
            "Ta cần chứng minh @a@.",
            "Điều này dẫn đến mâu thuẫn: @a@.",
            "Dùng tính ngoại diên của tập hợp để chứng minh @a@.",
            "Dùng tính ngoại diên của hàm để chứng minh @a@.",
            "Liệt kê miền hữu hạn để chứng minh @a@.",
            "Duyệt miền hữu hạn để chứng minh @a@.",
            "Đăng ký tính bắc cầu: @a@.",
            "Đăng ký tính đối xứng: @a@.",
            "Đăng ký tính phản xạ: @a@.",
            "Với mọi @a@, ta có @b@.",
            "Với mọi @a@ thỏa mãn @b@, ta có @c@.",
            "Theo tiên đề thay thế, định nghĩa @a@ bằng @b@ trên @c@.",
            "Chọn các nghịch ảnh @a@ của @b@.",
            "Áp dụng tiên đề chọn cho @a@.",
            "Áp dụng bổ đề Zorn cho @a@ với các vị từ về thứ tự, chặn trên và tính tối đại @b@.",
            "Áp dụng tiên đề chính quy cho @a@.",
            "Khai triển định nghĩa cấu trúc @a@.",
            "Khai triển định nghĩa đối tượng @a@.",
            "Giả định (trust)",
            "Vị từ trừu tượng",
            "Thuật toán",
            "Khai triển quan hệ thuộc khoảng @a@.",
            "Chứng minh bằng phản chứng.",
            "Nếu @a@ thì @b@.",
        ],
    };
    phrases[key as usize]
}

pub(super) fn sentence(lang: OutputLanguage, key: Phrase, a: &str, b: &str, c: &str) -> String {
    phrase(lang, key)
        .replace("@a@", a)
        .replace("@b@", b)
        .replace("@c@", c)
}
