mod attach_fact_ids_to_stmt_result;
mod by_stmt;
mod exec_axiom_stmt;
mod exec_claim_stmt;
mod exec_def_abstract_prop_stmt;
mod exec_def_algo_stmt;
mod exec_def_prop_stmt;
mod exec_def_struct_stmt;
mod exec_def_template_stmt;
mod exec_def_thm_stmt;
mod exec_define_params_with_set;
mod exec_eval_stmt;
mod exec_goal_proof_block;
mod exec_sketch_stmt;
mod exec_store_definitions;
mod exec_strategy_stmt;
mod exec_tooling_stmt;
mod exec_trust_have_stmt;
mod exec_trust_stmt;
mod exec_try_stmt;
mod exec_verify_then_store_facts;
mod object_introduction;
mod statement_execution;
mod submitted_fact_execution;
mod trusted_statement_execution;
mod verified_statement_execution;

pub use object_introduction::function_equality_support;
pub use object_introduction::function_equality_support as exec_have_fn_equal_shared;
