pub mod by_builtin_algebraic_rewrite_result;
pub mod by_builtin_rule_result;
pub mod by_builtin_strategy_result;
pub mod by_known_algebraic_rewrite_result;
pub mod verification_and_result;

pub use by_builtin_algebraic_rewrite_result::NonEquationalAtomicFactSearchProofByBuiltinAlgebraicRewrite;
pub use by_builtin_rule_result::NonEquationalAtomicFactSearchProofByBuiltinRule;
pub use by_builtin_strategy_result::NonEquationalAtomicFactSearchProofByBuiltinStrategy;
pub use by_known_algebraic_rewrite_result::NonEquationalAtomicFactSearchProofByKnownAlgebraicRewrite;
pub use verification_and_result::{
    NonEquationalAtomicFactSearchedProof, VerifyNonEquationalAtomicFactResult,
};
