//! Equality builtin rules → Normal JSON text.
//!
//! Call site: `rule.rule_id_and_message(lang)` on `EqualitySearchProofByBuiltinRule`.

mod calculation;
mod finite_subset_size;
mod leaves;
mod scalar_identities;
mod text;

use crate::execute::execute_fact_stmt::verify_atomic_fact::verify_equality::verify_equality_by_builtin_rules::EqualitySearchProofByBuiltinRule;
use crate::json_output::explain::fallback::BuiltinRuleText;
use crate::launch_command::OutputLanguage;
use crate::runtime::FactId;

impl EqualitySearchProofByBuiltinRule {
    pub fn rule_id_and_message(&self, lang: OutputLanguage) -> BuiltinRuleText {
        match self {
            Self::ReduceFirstStep(_) => BuiltinRuleText { rule_id: "ReduceFirstStep", rule_name: match lang { OutputLanguage::English => "First left-fold step",
            OutputLanguage::ChineseTraditional => "左折疊的首項遞推",
            OutputLanguage::French => "Première étape du pli gauche",
            OutputLanguage::Russian => "Первый шаг левой свёртки",
            OutputLanguage::Spanish => "Primer paso del pliegue izquierdo",
            OutputLanguage::Arabic => "الخطوة الأولى للطي الأيسر",
            OutputLanguage::Japanese => "左畳み込みの最初のステップ",
            OutputLanguage::Korean => "왼쪽 접기의 첫 단계",
            OutputLanguage::Vietnamese => "Bước đầu của phép gấp trái",
 OutputLanguage::Chinese => "左折叠的首项递推" }.into(), message: match lang { OutputLanguage::English => "A nonempty left fold moves its first term into the seed, preserving operand order",
            OutputLanguage::ChineseTraditional => "非空左折疊依原運算順序將首項併入初值",
            OutputLanguage::French => "Un pli gauche non vide incorpore son premier terme à la valeur initiale en préservant l'ordre des opérandes",
            OutputLanguage::Russian => "Непустая левая свёртка включает первый член в начальное значение, сохраняя порядок операндов",
            OutputLanguage::Spanish => "Un pliegue izquierdo no vacío incorpora el primer término a la semilla conservando el orden de operandos",
            OutputLanguage::Arabic => "الطي الأيسر غير الخالي يدمج الحد الأول في القيمة الابتدائية مع حفظ ترتيب المعاملات",
            OutputLanguage::Japanese => "空でない左畳み込みは被演算子の順序を保ち、最初の項を初期値に組み込みます",
            OutputLanguage::Korean => "비어 있지 않은 왼쪽 접기는 피연산자 순서를 유지하며 첫 항을 초깃값에 합칩니다",
            OutputLanguage::Vietnamese => "Phép gấp trái không rỗng gộp hạng đầu vào giá trị khởi tạo, giữ thứ tự toán hạng",
 OutputLanguage::Chinese => "非空左折叠按原运算顺序将首项并入初值" }.into() },
            Self::ReduceTranslation(_) => BuiltinRuleText { rule_id: "ReduceTranslation", rule_name: match lang { OutputLanguage::English => "Order-preserving fold translation",
            OutputLanguage::ChineseTraditional => "有序折疊的索引平移",
            OutputLanguage::French => "Translation de pli préservant l'ordre",
            OutputLanguage::Russian => "Сдвиг свёртки с сохранением порядка",
            OutputLanguage::Spanish => "Traslación del pliegue conservando el orden",
            OutputLanguage::Arabic => "إزاحة الطي مع حفظ الترتيب",
            OutputLanguage::Japanese => "順序を保つ畳み込みの平行移動",
            OutputLanguage::Korean => "순서를 보존하는 접기 이동",
            OutputLanguage::Vietnamese => "Tịnh tiến phép gấp bảo toàn thứ tự",
 OutputLanguage::Chinese => "有序折叠的索引平移" }.into(), message: match lang { OutputLanguage::English => "Translate both integer endpoints equally and check the corresponding terms without changing operation or seed",
            OutputLanguage::ChineseTraditional => "兩整數端點平移同樣的量，檢查對應項並保持運算和初值一致",
            OutputLanguage::French => "Translater les deux extrémités entières de la même quantité et vérifier les termes correspondants sans changer l'opération ni la valeur initiale",
            OutputLanguage::Russian => "Сдвинуть обе целочисленные границы одинаково и проверить соответствующие члены без изменения операции и начального значения",
            OutputLanguage::Spanish => "Trasladar ambos extremos enteros por igual y comprobar los términos correspondientes sin cambiar la operación ni la semilla",
            OutputLanguage::Arabic => "إزاحة الطرفين الصحيحين بالمقدار نفسه وفحص الحدود المقابلة دون تغيير العملية أو القيمة الابتدائية",
            OutputLanguage::Japanese => "両方の整数端点を等しく移動し、演算と初期値を変えずに対応する項を検査します",
            OutputLanguage::Korean => "두 정수 끝점을 같은 만큼 이동하고 연산과 초깃값을 바꾸지 않고 대응하는 항을 검사합니다",
            OutputLanguage::Vietnamese => "Tịnh tiến hai đầu mút nguyên cùng lượng và kiểm tra các hạng tương ứng mà không đổi phép toán hay giá trị khởi tạo",
 OutputLanguage::Chinese => "两个整数端点平移同样的量，检查对应项并保持运算和初值一致" }.into() },
            Self::ReducePointwise(_) => BuiltinRuleText { rule_id: "ReducePointwise", rule_name: match lang { OutputLanguage::English => "Pointwise fold congruence",
            OutputLanguage::ChineseTraditional => "有序折疊的逐點相等",
            OutputLanguage::French => "Congruence ponctuelle du pli",
            OutputLanguage::Russian => "Поточечная конгруэнтность свёртки",
            OutputLanguage::Spanish => "Congruencia puntual del pliegue",
            OutputLanguage::Arabic => "تطابق الطي نقطة بنقطة",
            OutputLanguage::Japanese => "畳み込みの各点での合同性",
            OutputLanguage::Korean => "접기의 점별 합동",
            OutputLanguage::Vietnamese => "Tương hợp từng điểm của phép gấp",
 OutputLanguage::Chinese => "有序折叠的逐点相等" }.into(), message: match lang { OutputLanguage::English => "Use a checked pointwise proposition over the same interval, operation and seed",
            OutputLanguage::ChineseTraditional => "引用已驗證的逐點命題，保持區間、運算和初值一致",
            OutputLanguage::French => "Utiliser une proposition ponctuelle vérifiée sur le même intervalle avec la même opération et valeur initiale",
            OutputLanguage::Russian => "Использовать проверенное поточечное утверждение на том же интервале с той же операцией и начальным значением",
            OutputLanguage::Spanish => "Usar una proposición puntual comprobada sobre el mismo intervalo, operación y semilla",
            OutputLanguage::Arabic => "استخدام قضية نقطة بنقطة متحقق منها على الفترة والعملية والقيمة الابتدائية نفسها",
            OutputLanguage::Japanese => "同じ区間、演算、初期値に対する検証済みの各点の命題を用います",
            OutputLanguage::Korean => "같은 구간, 연산, 초깃값에 대한 검증된 점별 명제를 사용합니다",
            OutputLanguage::Vietnamese => "Dùng mệnh đề từng điểm đã kiểm tra trên cùng khoảng, phép toán và giá trị khởi tạo",
 OutputLanguage::Chinese => "引用已验证的逐点相等命题，保持区间、运算和初值一致" }.into() },
            Self::AggregateIdentity(crate::execute::execute_fact_stmt::verify_atomic_fact::verify_equality::verify_equality_by_builtin_rules::aggregate_identity_builtin_rule_proof::AggregateIdentityBuiltinRuleProof::FiniteSetProductMemberRemoval(_)) => BuiltinRuleText {
                rule_id: "FiniteSetProductMemberRemoval", rule_name: match lang { OutputLanguage::English => "Remove a member from a finite product",
                OutputLanguage::ChineseTraditional => "有限乘積刪除已有元素",
                OutputLanguage::French => "Retrait d'un membre d'un produit fini",
                OutputLanguage::Russian => "Удаление элемента из конечного произведения",
                OutputLanguage::Spanish => "Retirada de un miembro de producto finito",
                OutputLanguage::Arabic => "حذف عنصر من حاصل ضرب منتهٍ",
                OutputLanguage::Japanese => "有限積からの要素の削除",
                OutputLanguage::Korean => "유한 곱에서 원소 제거",
                OutputLanguage::Vietnamese => "Loại phần tử khỏi tích hữu hạn",
 OutputLanguage::Chinese => "有限乘积删除已有元素" }.into(),
                message: match lang { OutputLanguage::English => "Check membership, the restricted callback and the removed factor; no division or nonzero premise is needed",
                OutputLanguage::ChineseTraditional => "檢查成員關係、限制回呼和被刪除因子；無需除法或非零前提",
                OutputLanguage::French => "Vérifier l'appartenance, la fonction restreinte et le facteur retiré ; aucune division ni prémisse de non-nullité n'est nécessaire",
                OutputLanguage::Russian => "Проверить принадлежность, ограниченную функцию и удалённый множитель; деление и предпосылка ненулевого значения не нужны",
                OutputLanguage::Spanish => "Comprobar pertenencia, función restringida y factor retirado; no se necesita división ni premisa de no nulidad",
                OutputLanguage::Arabic => "فحص الانتماء والدالة المقيدة والعامل المحذوف؛ لا تلزم قسمة أو مقدمة عدم الصفر",
                OutputLanguage::Japanese => "所属、制限した関数、削除する因子を検査します。除算や非ゼロの前提は不要です",
                OutputLanguage::Korean => "소속, 제한된 함수, 제거된 인자를 검사하며 나눗셈이나 0이 아님 전제는 필요하지 않습니다",
                OutputLanguage::Vietnamese => "Kiểm tra sự thuộc về, hàm hạn chế và thừa số bị loại; không cần chia hay tiền đề khác không",
 OutputLanguage::Chinese => "检查成员关系、限制回调和被删除因子；乘法拆分无需除法或非零前提" }.into(),
            },
            Self::CartesianSize(_) => BuiltinRuleText {
                rule_id: "CartesianSize",
                rule_name: match lang { OutputLanguage::English => "Finite Cartesian cardinality",
                OutputLanguage::ChineseTraditional => "有限笛卡兒積的基數",
                OutputLanguage::French => "Cardinal du produit cartésien fini",
                OutputLanguage::Russian => "Мощность конечного декартова произведения",
                OutputLanguage::Spanish => "Cardinalidad cartesiana finita",
                OutputLanguage::Arabic => "عدد عناصر حاصل الضرب الديكارتي المنتهي",
                OutputLanguage::Japanese => "有限直積の濃度",
                OutputLanguage::Korean => "유한 데카르트 곱의 기수",
                OutputLanguage::Vietnamese => "Lực lượng tích Descartes hữu hạn",
 OutputLanguage::Chinese => "有限笛卡尔积的基数" }.into(),
                message: match lang { OutputLanguage::English => "The cardinality of a Cartesian product is the product of the checked finite factor cardinalities",
                OutputLanguage::ChineseTraditional => "笛卡兒積的基數等於已驗證的有限因子基數之乘積",
                OutputLanguage::French => "Le cardinal d'un produit cartésien est le produit des cardinaux vérifiés de ses facteurs finis",
                OutputLanguage::Russian => "Мощность декартова произведения равна произведению проверенных мощностей конечных множителей",
                OutputLanguage::Spanish => "La cardinalidad del producto cartesiano es el producto de las cardinalidades comprobadas de sus factores finitos",
                OutputLanguage::Arabic => "عدد عناصر حاصل الضرب الديكارتي يساوي حاصل ضرب أعداد عناصر العوامل المنتهية المتحقق منها",
                OutputLanguage::Japanese => "直積の濃度は検証済みの有限因子の濃度の積です",
                OutputLanguage::Korean => "데카르트 곱의 기수는 검증된 유한 인자 기수의 곱입니다",
                OutputLanguage::Vietnamese => "Lực lượng tích Descartes là tích các lực lượng của thừa số hữu hạn đã kiểm tra",
 OutputLanguage::Chinese => "笛卡尔积的基数等于各个已验证有限因子的基数乘积" }.into(),
            },
            Self::ReducePartition(_) => BuiltinRuleText {
                rule_id: "ReducePartition",
                rule_name: match lang { OutputLanguage::English => "Adjacent left-fold partition",
                OutputLanguage::ChineseTraditional => "左折疊的相鄰分段",
                OutputLanguage::French => "Partition adjacente du pli gauche",
                OutputLanguage::Russian => "Разбиение левой свёртки на соседние части",
                OutputLanguage::Spanish => "Partición adyacente del pliegue izquierdo",
                OutputLanguage::Arabic => "تقسيم متجاور للطي الأيسر",
                OutputLanguage::Japanese => "左畳み込みの隣接分割",
                OutputLanguage::Korean => "왼쪽 접기의 인접 분할",
                OutputLanguage::Vietnamese => "Phân hoạch kề nhau của phép gấp trái",
 OutputLanguage::Chinese => "左折叠的相邻分段" }.into(),
                message: match lang { OutputLanguage::English => "Continue the same left fold from the first segment's result, with checked adjacent bounds and matching functions, operation and seed",
                OutputLanguage::ChineseTraditional => "檢查相鄰邊界及一致的函數、運算和初值後，從首段結果繼續同一左折疊",
                OutputLanguage::French => "Continuer le même pli gauche depuis le résultat du premier segment, avec des bornes adjacentes vérifiées et des fonctions, opération et valeur initiale concordantes",
                OutputLanguage::Russian => "Продолжить ту же левую свёртку из результата первого отрезка при проверенных соседних границах и совпадающих функциях, операции и начальном значении",
                OutputLanguage::Spanish => "Continuar el mismo pliegue izquierdo desde el resultado del primer segmento con límites adyacentes comprobados y funciones, operación y semilla coincidentes",
                OutputLanguage::Arabic => "متابعة الطي الأيسر نفسه من نتيجة الجزء الأول بحدود متجاورة متحقق منها ودوال وعملية وقيمة ابتدائية متطابقة",
                OutputLanguage::Japanese => "隣接する境界と関数、演算、初期値の一致を検査し、最初の区間の結果から同じ左畳み込みを続けます",
                OutputLanguage::Korean => "인접 경계와 함수, 연산, 초깃값의 일치를 검사하고 첫 구간 결과에서 같은 왼쪽 접기를 이어갑니다",
                OutputLanguage::Vietnamese => "Tiếp tục cùng phép gấp trái từ kết quả đoạn đầu, với biên kề đã kiểm tra và hàm, phép toán, giá trị khởi tạo khớp nhau",
 OutputLanguage::Chinese => "检查相邻边界及一致的函数、运算和初值后，从第一段结果继续同一个左折叠" }.into(),
            },
            Self::ReduceLastStep(_) => BuiltinRuleText {rule_id:"ReduceLastStep",rule_name:match lang {OutputLanguage::English=>"Last fold step",
            OutputLanguage::ChineseTraditional=>"折疊的末端一步",
            OutputLanguage::French=>"Dernière étape du pli",
            OutputLanguage::Russian=>"Последний шаг свёртки",
            OutputLanguage::Spanish=>"Último paso del pliegue",
            OutputLanguage::Arabic=>"الخطوة الأخيرة للطي",
            OutputLanguage::Japanese=>"畳み込みの最後のステップ",
            OutputLanguage::Korean=>"접기의 마지막 단계",
            OutputLanguage::Vietnamese=>"Bước cuối của phép gấp",
OutputLanguage::Chinese=>"折叠的末端一步"}.into(),message:match lang {OutputLanguage::English=>"The nonempty left fold applies its operation to the preceding fold and final term",
            OutputLanguage::ChineseTraditional=>"非空左折疊將運算套用於前段折疊結果與最後一項",
            OutputLanguage::French=>"Le pli gauche non vide applique son opération au pli précédent et au dernier terme",
            OutputLanguage::Russian=>"Непустая левая свёртка применяет операцию к предыдущей свёртке и последнему члену",
            OutputLanguage::Spanish=>"El pliegue izquierdo no vacío aplica su operación al pliegue anterior y al último término",
            OutputLanguage::Arabic=>"الطي الأيسر غير الخالي يطبق عمليته على الطي السابق والحد الأخير",
            OutputLanguage::Japanese=>"空でない左畳み込みは前の畳み込みと最後の項に演算を適用します",
            OutputLanguage::Korean=>"비어 있지 않은 왼쪽 접기는 이전 접기 결과와 마지막 항에 연산을 적용합니다",
            OutputLanguage::Vietnamese=>"Phép gấp trái không rỗng áp dụng phép toán cho phép gấp trước và hạng cuối",
OutputLanguage::Chinese=>"非空左折叠将运算应用于前段折叠结果和最后一项"}.into()},
            Self::FiniteMapSize(p) => BuiltinRuleText {rule_id:p.rule_id(),rule_name:match lang {OutputLanguage::English=>"Finite map cardinality",
            OutputLanguage::ChineseTraditional=>"有限映射的基數",
            OutputLanguage::French=>"Cardinalité d'application finie",
            OutputLanguage::Russian=>"Мощность конечного отображения",
            OutputLanguage::Spanish=>"Cardinalidad de aplicación finita",
            OutputLanguage::Arabic=>"عدد عناصر تطبيق منتهٍ",
            OutputLanguage::Japanese=>"有限写像の濃度",
            OutputLanguage::Korean=>"유한 사상의 기수",
            OutputLanguage::Vietnamese=>"Lực lượng ánh xạ hữu hạn",
OutputLanguage::Chinese=>"有限映射的基数"}.into(),message:match lang {OutputLanguage::English=>"Consume the stored bijection or injection certificate to compare finite cardinalities",
            OutputLanguage::ChineseTraditional=>"使用已儲存的雙射或單射證書比較有限基數",
            OutputLanguage::French=>"Utiliser le certificat stocké de bijection ou d'injection pour comparer les cardinaux finis",
            OutputLanguage::Russian=>"Использовать сохранённый сертификат биекции или инъекции для сравнения конечных мощностей",
            OutputLanguage::Spanish=>"Usar el certificado almacenado de biyección o inyección para comparar cardinalidades finitas",
            OutputLanguage::Arabic=>"استخدام شهادة التقابل أو الحقن المخزنة لمقارنة أعداد العناصر المنتهية",
            OutputLanguage::Japanese=>"保存済みの全単射または単射の証明書で有限濃度を比較します",
            OutputLanguage::Korean=>"저장된 전단사 또는 단사 인증서로 유한 기수를 비교합니다",
            OutputLanguage::Vietnamese=>"Dùng chứng nhận song ánh hoặc đơn ánh đã lưu để so sánh lực lượng hữu hạn",
OutputLanguage::Chinese=>"消费已存双射或单射证书比较有限基数"}.into()},
            Self::ReduceProduct(_) => BuiltinRuleText {rule_id:"ReduceProduct",rule_name:match lang {OutputLanguage::English=>"Multiplication fold",
            OutputLanguage::ChineseTraditional=>"乘法折疊",
            OutputLanguage::French=>"Pli multiplicatif",
            OutputLanguage::Russian=>"Мультипликативная свёртка",
            OutputLanguage::Spanish=>"Pliegue multiplicativo",
            OutputLanguage::Arabic=>"طي ضربي",
            OutputLanguage::Japanese=>"乗法の畳み込み",
            OutputLanguage::Korean=>"곱셈 접기",
            OutputLanguage::Vietnamese=>"Phép gấp nhân",
OutputLanguage::Chinese=>"乘法折叠"}.into(),message:match lang {OutputLanguage::English=>"A multiplication fold with seed one equals the product over the same interval",
            OutputLanguage::ChineseTraditional=>"初值為一的乘法折疊等於同區間上的乘積",
            OutputLanguage::French=>"Un pli multiplicatif de valeur initiale un est égal au produit sur le même intervalle",
            OutputLanguage::Russian=>"Мультипликативная свёртка с начальным значением один равна произведению на том же интервале",
            OutputLanguage::Spanish=>"Un pliegue multiplicativo con semilla uno equivale al producto sobre el mismo intervalo",
            OutputLanguage::Arabic=>"الطي الضربي بقيمة ابتدائية واحد يساوي حاصل الضرب على الفترة نفسها",
            OutputLanguage::Japanese=>"初期値が一の乗法の畳み込みは同じ区間の積に等しいです",
            OutputLanguage::Korean=>"초깃값이 1인 곱셈 접기는 같은 구간의 곱과 같습니다",
            OutputLanguage::Vietnamese=>"Phép gấp nhân với giá trị khởi tạo một bằng tích trên cùng khoảng",
OutputLanguage::Chinese=>"初值为一的乘法折叠等于相同区间上的乘积"}.into()},
            Self::ElementaryArithmetic(p) => BuiltinRuleText {
                rule_id:p.rule_id(), rule_name:match lang {OutputLanguage::English=>"Elementary arithmetic identity",
                OutputLanguage::ChineseTraditional=>"基本算術恆等式",
                OutputLanguage::French=>"Identité arithmétique élémentaire",
                OutputLanguage::Russian=>"Элементарное арифметическое тождество",
                OutputLanguage::Spanish=>"Identidad aritmética elemental",
                OutputLanguage::Arabic=>"هوية حسابية أولية",
                OutputLanguage::Japanese=>"基本的な算術恒等式",
                OutputLanguage::Korean=>"기본 산술 항등식",
                OutputLanguage::Vietnamese=>"Đồng nhất thức số học cơ bản",
OutputLanguage::Chinese=>"基本算术恒等式"}.into(),
                message:match lang {OutputLanguage::English=>"Apply the arithmetic identity with checked domains and stored premises",
                OutputLanguage::ChineseTraditional=>"依已驗證的定義域和已儲存前提套用算術恆等式",
                OutputLanguage::French=>"Appliquer l'identité arithmétique avec les domaines vérifiés et les prémisses stockées",
                OutputLanguage::Russian=>"Применить арифметическое тождество с проверенными областями и сохранёнными предпосылками",
                OutputLanguage::Spanish=>"Aplicar la identidad aritmética con dominios comprobados y premisas almacenadas",
                OutputLanguage::Arabic=>"تطبيق الهوية الحسابية بالمجالات المتحقق منها والمقدمات المخزنة",
                OutputLanguage::Japanese=>"検証済みの定義域と保存済みの前提で算術恒等式を適用します",
                OutputLanguage::Korean=>"검증된 정의역과 저장된 전제로 산술 항등식을 적용합니다",
                OutputLanguage::Vietnamese=>"Áp dụng đồng nhất thức số học với miền đã kiểm tra và tiền đề đã lưu",
OutputLanguage::Chinese=>"依据已验证的定义域和已存前提应用算术恒等式"}.into(),
            },
            Self::TrigComplexIdentity(p) => scalar_identities::trig_complex(p, lang),
            Self::IntegerRangeBuilder(p) => BuiltinRuleText {rule_id:p.rule_id(),rule_name:match lang { OutputLanguage::English => "Integer range comprehension",
            OutputLanguage::ChineseTraditional => "整數區間集合構造",
            OutputLanguage::French => "Compréhension d'intervalle entier",
            OutputLanguage::Russian => "Целочисленное множество по интервалу",
            OutputLanguage::Spanish => "Comprensión de intervalo entero",
            OutputLanguage::Arabic => "بناء مجموعة فترة صحيحة",
            OutputLanguage::Japanese => "整数区間の内包表記",
            OutputLanguage::Korean => "정수 구간 조건제시",
            OutputLanguage::Vietnamese => "Tập dựng khoảng nguyên",
 OutputLanguage::Chinese => "Integer range comprehension" }.into(),message:match lang {
                OutputLanguage::English => "Integer membership with the exact lower and upper endpoint conditions",
                OutputLanguage::ChineseTraditional => "整數成員及精確上下端點條件",
                OutputLanguage::French => "Appartenance entière avec les conditions exactes aux bornes inférieure et supérieure",
                OutputLanguage::Russian => "Целочисленная принадлежность с точными условиями нижней и верхней границ",
                OutputLanguage::Spanish => "Pertenencia entera con las condiciones exactas de los extremos inferior y superior",
                OutputLanguage::Arabic => "انتماء صحيح مع شروط الطرفين الأدنى والأعلى الدقيقة",
                OutputLanguage::Japanese => "正確な下端と上端の条件を伴う整数の所属",
                OutputLanguage::Korean => "정확한 하한과 상한 끝점 조건을 포함한 정수 소속",
                OutputLanguage::Vietnamese => "Thuộc về số nguyên với điều kiện chính xác của đầu mút dưới và trên",

                OutputLanguage::Chinese => "整数成员及对应的上下界条件",
            }.into()},
            Self::ScalarIdentity(p) => scalar_identities::explain(p,lang),
            Self::Calculation(p) => p.rule_id_and_message(lang),
            Self::AggregateIdentity(crate::execute::execute_fact_stmt::verify_atomic_fact::verify_equality::verify_equality_by_builtin_rules::aggregate_identity_builtin_rule_proof::AggregateIdentityBuiltinRuleProof::FiniteSetProductFreshInsertion(_)) => BuiltinRuleText {
                rule_id: "FiniteSetProductFreshInsertion",
                rule_name: match lang { OutputLanguage::English => "Fresh insertion into a finite product",
                OutputLanguage::ChineseTraditional => "有限乘積插入新元素",
                OutputLanguage::French => "Insertion nouvelle dans un produit fini",
                OutputLanguage::Russian => "Вставка нового элемента в конечное произведение",
                OutputLanguage::Spanish => "Inserción nueva en producto finito",
                OutputLanguage::Arabic => "إدراج عنصر جديد في حاصل ضرب منتهٍ",
                OutputLanguage::Japanese => "有限積への新しい要素の挿入",
                OutputLanguage::Korean => "유한 곱에 새 원소 삽입",
                OutputLanguage::Vietnamese => "Chèn phần tử mới vào tích hữu hạn",
 OutputLanguage::Chinese => "有限乘积插入新元素" }.into(),
                message: match lang { OutputLanguage::English => "Checked freshness, agreement of the restricted callback, and the inserted factor",
                OutputLanguage::ChineseTraditional => "已驗證元素不在原集合中、限制回呼一致及插入因子",
                OutputLanguage::French => "Absence initiale vérifiée, concordance de la fonction restreinte et du facteur inséré",
                OutputLanguage::Russian => "Проверено отсутствие элемента, совпадение ограниченной функции и вставленного множителя",
                OutputLanguage::Spanish => "Ausencia inicial comprobada, concordancia de función restringida y factor insertado",
                OutputLanguage::Arabic => "تم التحقق من جدة العنصر وتوافق الدالة المقيدة والعامل المدرج",
                OutputLanguage::Japanese => "要素の新規性、制限した関数と挿入因子の一致を検査しました",
                OutputLanguage::Korean => "원소의 신규성, 제한된 함수의 일치와 삽입된 인자를 검사했습니다",
                OutputLanguage::Vietnamese => "Đã kiểm tra tính mới, sự khớp của hàm hạn chế và thừa số được chèn",
 OutputLanguage::Chinese => "已验证元素不在原集合中、限制回调逐点一致及插入因子相等" }.into(),
            },
            Self::AggregateIdentity(_) => {
                let (name, message) = match lang {
                    OutputLanguage::English => ("Finite aggregate identity", "Verified constant, linear, pointwise, partition or reindexing requirements"),
                    OutputLanguage::ChineseTraditional => ("有限聚合恆等式", "已驗證常量、線性、逐點相等、分段或重編號所需條件"),
                    OutputLanguage::French => ("Identité d'agrégat fini", "Conditions vérifiées de constante, linéarité, égalité ponctuelle, partition ou réindexation"),
                    OutputLanguage::Russian => ("Тождество конечного агрегата", "Проверены условия константы, линейности, поточечного равенства, разбиения или переиндексации"),
                    OutputLanguage::Spanish => ("Identidad de agregado finito", "Requisitos comprobados de constante, linealidad, igualdad puntual, partición o reindexación"),
                    OutputLanguage::Arabic => ("هوية تجميع منتهٍ", "تم التحقق من متطلبات الثابت أو الخطية أو التساوي نقطة بنقطة أو التقسيم أو إعادة الفهرسة"),
                    OutputLanguage::Japanese => ("有限集約の恒等式", "定数、線形性、各点の一致、分割または添字変更の条件を検証しました"),
                    OutputLanguage::Korean => ("유한 집계 항등식", "상수, 선형성, 점별 일치, 분할 또는 재인덱싱 요건을 검증했습니다"),
                    OutputLanguage::Vietnamese => ("Đồng nhất thức tổng hợp hữu hạn", "Đã kiểm tra điều kiện hằng, tuyến tính, từng điểm, phân hoạch hoặc đổi chỉ số"),

                    OutputLanguage::Chinese => ("有限聚合恒等式", "已验证常量、线性、逐点相等、分拆或重编号所需的前提"),
                };
                BuiltinRuleText { rule_id:"AggregateIdentity", rule_name:name.into(), message:message.into() }
            },
            Self::AggregateCalculation(_) => {
                let (name, message) = match lang {
                    OutputLanguage::English => ("Exact finite aggregate calculation", "Enumerate valid arguments, substitute checked function bodies and fold exact values"),
                    OutputLanguage::ChineseTraditional => ("有限聚合精確計算", "列舉合法引數，代入已檢查的函數體並精確折疊數值"),
                    OutputLanguage::French => ("Calcul exact d'agrégat fini", "Énumérer les arguments valides, substituer les corps de fonctions vérifiés et plier les valeurs exactes"),
                    OutputLanguage::Russian => ("Точное вычисление конечного агрегата", "Перебрать допустимые аргументы, подставить проверенные тела функций и свернуть точные значения"),
                    OutputLanguage::Spanish => ("Cálculo exacto de agregado finito", "Enumerar argumentos válidos, sustituir cuerpos de función comprobados y plegar valores exactos"),
                    OutputLanguage::Arabic => ("حساب دقيق لتجميع منتهٍ", "تعداد الوسائط الصالحة وتعويض متون الدوال المتحقق منها وطي القيم الدقيقة"),
                    OutputLanguage::Japanese => ("有限集約の正確な計算", "有効な引数を列挙し、検査済みの関数本体を代入して正確な値を畳み込みます"),
                    OutputLanguage::Korean => ("유한 집계의 정확한 계산", "유효한 인수를 열거하고 검사된 함수 본문을 대입하여 정확한 값을 접습니다"),
                    OutputLanguage::Vietnamese => ("Tính toán chính xác tổng hợp hữu hạn", "Liệt kê đối số hợp lệ, thế thân hàm đã kiểm tra và gấp các giá trị chính xác"),

                    OutputLanguage::Chinese => ("有限聚合精确计算", "枚举合法指标，代入已检查的函数体，并精确累加或累乘"),
                };
                BuiltinRuleText { rule_id:"AggregateCalculation", rule_name:name.into(), message:message.into() }
            },
            Self::SinArcsinLeftInverse(p) => p.rule_id_and_message(lang),
            Self::CosArccosLeftInverse(p) => p.rule_id_and_message(lang),
            Self::TanArctanLeftInverse(p) => p.rule_id_and_message(lang),
            Self::CotArccotLeftInverse(p) => p.rule_id_and_message(lang),
            Self::ArcsinSinRightInverse(p) => p.rule_id_and_message(lang),
            Self::ArccosCosRightInverse(p) => p.rule_id_and_message(lang),
            Self::ArctanTanRightInverse(p) => p.rule_id_and_message(lang),
            Self::ArccotCotRightInverse(p) => p.rule_id_and_message(lang),
            Self::ArcsinExactZero(p) => p.rule_id_and_message(lang),
            Self::ArcsinExactOne(p) => p.rule_id_and_message(lang),
            Self::ArcsinExactNegOne(p) => p.rule_id_and_message(lang),
            Self::ArccosExactOne(p) => p.rule_id_and_message(lang),
            Self::ArccosExactZero(p) => p.rule_id_and_message(lang),
            Self::ArccosExactNegOne(p) => p.rule_id_and_message(lang),
            Self::ArctanExactZero(p) => p.rule_id_and_message(lang),
            Self::ArccotExactZero(p) => p.rule_id_and_message(lang),
            Self::PowerProductSameBase(p) => p.rule_id_and_message(lang),
            Self::PowerOfPower(p) => p.rule_id_and_message(lang),
            Self::PowerOfProduct(p) => p.rule_id_and_message(lang),
            Self::ReciprocalAsNegOnePower(p) => p.rule_id_and_message(lang),
            Self::QuotientAsMulNegOnePower(p) => p.rule_id_and_message(lang),
            Self::OneToAnyPower(p) => p.rule_id_and_message(lang),
            Self::ZeroToPosNatPower(p) => p.rule_id_and_message(lang),
            Self::SqrtSquare(p) => p.rule_id_and_message(lang),
            Self::SqrtZero(p) => p.rule_id_and_message(lang),
            Self::SqrtOne(p) => p.rule_id_and_message(lang),
            Self::SqrtOfSquare(p) => p.rule_id_and_message(lang),
            Self::SqrtProduct(p) => p.rule_id_and_message(lang),
            Self::SqrtQuotient(p) => p.rule_id_and_message(lang),
            Self::AbsOfNegation(p) => p.rule_id_and_message(lang),
            Self::AbsProduct(p) => p.rule_id_and_message(lang),
            Self::AbsSquare(p) => p.rule_id_and_message(lang),
            Self::LogBaseSelf(p) => p.rule_id_and_message(lang),
            Self::LogOfOne(p) => p.rule_id_and_message(lang),
            Self::LogOfPowerSameBase(p) => p.rule_id_and_message(lang),
            Self::LogArgPower(p) => p.rule_id_and_message(lang),
            Self::LogProduct(p) => p.rule_id_and_message(lang),
            Self::LogQuotient(p) => p.rule_id_and_message(lang),
            Self::LogReciprocal(p) => p.rule_id_and_message(lang),
            Self::LogChangeOfBase(p) => p.rule_id_and_message(lang),
            Self::ZeroMod(p) => p.rule_id_and_message(lang),
            Self::ModOne(p) => p.rule_id_and_message(lang),
            Self::OneModAtLeastTwo(p) => p.rule_id_and_message(lang),
            Self::NestedSameModAbsorption(p) => p.rule_id_and_message(lang),
            Self::ModCompatibleSmallerModulus(p) => p.rule_id_and_message(lang),
            Self::MinIdempotent(p) => p.rule_id_and_message(lang),
            Self::MaxIdempotent(p) => p.rule_id_and_message(lang),
            Self::MinCommutative(p) => p.rule_id_and_message(lang),
            Self::MaxCommutative(p) => p.rule_id_and_message(lang),
            Self::AbsAbsAbsorption(p) => p.rule_id_and_message(lang),
            Self::ExpOfLn(p) => p.rule_id_and_message(lang),
            Self::LnOfExp(p) => p.rule_id_and_message(lang),
            Self::FloorOfInteger(p) => p.rule_id_and_message(lang),
            Self::CeilOfInteger(p) => p.rule_id_and_message(lang),
            Self::ModSelfZero(p) => p.rule_id_and_message(lang),
            Self::FloorOfCeilOfInteger(p) => p.rule_id_and_message(lang),
            Self::CeilOfFloorOfInteger(p) => p.rule_id_and_message(lang),
            Self::SqrtOfSquareEqualsAbs(p) => p.rule_id_and_message(lang),
            Self::QuotByOne(p) => p.rule_id_and_message(lang),
            Self::QuotSelfOne(p) => p.rule_id_and_message(lang),
            Self::LcmCommutative(p) => p.rule_id_and_message(lang),
            Self::LcmIdempotentAbs(p) => p.rule_id_and_message(lang),
            Self::GcdCommutative(p) => p.rule_id_and_message(lang),
            Self::GcdIdempotentAbs(p) => p.rule_id_and_message(lang),
            Self::GcdRightZeroAbs(p) => p.rule_id_and_message(lang),
            Self::GcdLeftZeroAbs(p) => p.rule_id_and_message(lang),
            Self::FactorialSuccessor(p) => p.rule_id_and_message(lang),
            Self::AbsNonnegEqualsSelf(p) => p.rule_id_and_message(lang),
            Self::AbsNonposEqualsNegation(p) => p.rule_id_and_message(lang),
            Self::SignOfPositive(p) => p.rule_id_and_message(lang),
            Self::SignOfNegative(p) => p.rule_id_and_message(lang),
            Self::MaxRightWhenLessEqual(p) => p.rule_id_and_message(lang),
            Self::MaxLeftWhenLessEqual(p) => p.rule_id_and_message(lang),
            Self::MinLeftWhenLessEqual(p) => p.rule_id_and_message(lang),
            Self::MinRightWhenLessEqual(p) => p.rule_id_and_message(lang),
            Self::GcdDividesArgument(p) => p.rule_id_and_message(lang),
            Self::ProductModFactorZero(p) => p.rule_id_and_message(lang),
            Self::EqualityFromTwoSidedWeakOrder(p) => p.rule_id_and_message(lang),
            Self::DiffZeroFromEqualOperands(p) => p.rule_id_and_message(lang),
            Self::EqualFromKnownDifferenceZero(p) => p.rule_id_and_message(lang),
            Self::ZeroProductCancel(p) => p.rule_id_and_message(lang),
            Self::SignOfNegation(p) => p.rule_id_and_message(lang),
            Self::SignTimesAbsEqualsArg(p) => p.rule_id_and_message(lang),
            Self::AbsEqualsSignTimesArg(p) => p.rule_id_and_message(lang),
            Self::SignOfProduct(p) => p.rule_id_and_message(lang),
            Self::SubtractionFromKnownAddition(p) => p.rule_id_and_message(lang),
            Self::QuotEuclideanDecomposition(p) => p.rule_id_and_message(lang),
            Self::ModDividendMinusRemainderZero(p) => p.rule_id_and_message(lang),
            Self::SquareSumComponentZero(p) => p.rule_id_and_message(lang),
            Self::MinusOneOddNaturalPower(p) => p.rule_id_and_message(lang),
            Self::LcmGcdProductAbs(p) => p.rule_id_and_message(lang),
            Self::UnionEmptyRight(p) => p.rule_id_and_message(lang),
            Self::UnionEmptyLeft(p) => p.rule_id_and_message(lang),
            Self::IntersectEmptyRight(p) => p.rule_id_and_message(lang),
            Self::IntersectEmptyLeft(p) => p.rule_id_and_message(lang),
            Self::SetMinusSelfEmpty(p) => p.rule_id_and_message(lang),
            Self::SetMinusEmptyRight(p) => p.rule_id_and_message(lang),
            Self::SetMinusEmptyLeft(p) => p.rule_id_and_message(lang),
            Self::UnionCommutative(p) => p.rule_id_and_message(lang),
            Self::IntersectCommutative(p) => p.rule_id_and_message(lang),
            Self::UnionIdempotent(p) => p.rule_id_and_message(lang),
            Self::IntersectIdempotent(p) => p.rule_id_and_message(lang),
            Self::IntersectFromSubset(p) => p.rule_id_and_message(lang),
            Self::EmptySetFromNotNonempty(p) => p.rule_id_and_message(lang),
            Self::PowerSetFiniteSetSize(p) => p.rule_id_and_message(lang),
            Self::UnionAssociative(p) => p.rule_id_and_message(lang),
            Self::IntersectAssociative(p) => p.rule_id_and_message(lang),
            Self::IntersectUnionDistributive(p) => p.rule_id_and_message(lang),
            Self::SetMinusUnionDeMorgan(p) => p.rule_id_and_message(lang),
            Self::SetMinusIntersectDeMorgan(p) => p.rule_id_and_message(lang),
            Self::IntersectSetMinusSelfEmpty(p) => p.rule_id_and_message(lang),
            Self::FiniteSetSumEmpty(p) => p.rule_id_and_message(lang),
            Self::FiniteSetProductEmpty(p) => p.rule_id_and_message(lang),
            Self::FiniteSetReduceEmpty(p) => p.rule_id_and_message(lang),
            Self::ReduceEmpty(p) => p.rule_id_and_message(lang),
            Self::SumEmptyRange(p) => p.rule_id_and_message(lang),
            Self::ProductEmptyRange(p) => p.rule_id_and_message(lang),
            Self::UnionAbsorptionFromSubset(p) => p.rule_id_and_message(lang),
            Self::SetMinusRecoversSubset(p) => p.rule_id_and_message(lang),
            Self::EmptySetFromSizeZero(p) => p.rule_id_and_message(lang),
            Self::FiniteSetEqualFromSubsetSize(p) => p.rule_id_and_message(lang),
            Self::CartProjFactor(p) => p.rule_id_and_message(lang),
            Self::TupleComponentAtIndex(p) => p.rule_id_and_message(lang),
            Self::FiniteSetSizeSetMinus(p) => p.rule_id_and_message(lang),
            Self::FiniteSetSizeUnion(p) => p.rule_id_and_message(lang),
            Self::ClosedRangeSingletonListSet(p) => p.rule_id_and_message(lang),
            Self::SumSingleTerm(p) => p.rule_id_and_message(lang),
            Self::ProductSingleTerm(p) => p.rule_id_and_message(lang),
            Self::ReduceAddZeroEqualsSum(p) => p.rule_id_and_message(lang),
            Self::FiniteSetReduceAddZeroEqualsSum(p) => p.rule_id_and_message(lang),
            Self::PowOfLogInverse(p) => p.rule_id_and_message(lang),
            Self::UnionSetMinusDecomposition(p) => p.rule_id_and_message(lang),
            Self::SetMinusIntersectSelf(p) => p.rule_id_and_message(lang),
            Self::ReOfImaginaryUnit(p) => p.rule_id_and_message(lang),
            Self::ImgOfImaginaryUnit(p) => p.rule_id_and_message(lang),
            Self::ReOfRealEmbedding(p) => p.rule_id_and_message(lang),
            Self::ImgOfRealEmbedding(p) => p.rule_id_and_message(lang),
            Self::ReOfRealPlusI(p) => p.rule_id_and_message(lang),
            Self::ImgOfRealPlusI(p) => p.rule_id_and_message(lang),
            Self::ComplexAbsOfImaginaryUnit(p) => p.rule_id_and_message(lang),
            Self::ModNestedDivisibleAbsorption(p) => p.rule_id_and_message(lang),
            Self::SumSplitLastTerm(p) => p.rule_id_and_message(lang),
            Self::ProductSplitLastTerm(p) => p.rule_id_and_message(lang),
            Self::FiniteSetSumListExpansion(p) => p.rule_id_and_message(lang),
            Self::FiniteSetProductListExpansion(p) => p.rule_id_and_message(lang),
            Self::EulerEqualsExpOne(p) => p.rule_id_and_message(lang),
            Self::LnOfEuler(p) => p.rule_id_and_message(lang),
            Self::ReOfReal(p) => p.rule_id_and_message(lang),
            Self::ImgOfReal(p) => p.rule_id_and_message(lang),
            Self::ReOfRealPlusImagScaled(p) => p.rule_id_and_message(lang),
            Self::ImgOfRealPlusImagScaled(p) => p.rule_id_and_message(lang),
            Self::ComplexAbsOfNonnegReal(p) => p.rule_id_and_message(lang),
            Self::ComplexAbsOfImagScaled(p) => p.rule_id_and_message(lang),
            Self::ClosedRangeLiteralExpansion(p) => p.rule_id_and_message(lang),
            Self::RangeLiteralExpansion(p) => p.rule_id_and_message(lang),
            Self::PowerSetOfEmpty(p) => p.rule_id_and_message(lang),
            Self::PowerSetOfSingleton(p) => p.rule_id_and_message(lang),
            Self::FamilyUnionOfEmpty(p) => p.rule_id_and_message(lang),
            Self::FamilyUnionOfSingleton(p) => p.rule_id_and_message(lang),
            Self::FamilyUnionOfPowerSet(p) => p.rule_id_and_message(lang),
            Self::CartWithEmptyFactor(p) => p.rule_id_and_message(lang),
            Self::UnionOverIntersectDistributive(p) => p.rule_id_and_message(lang),
            Self::SetMinusChainToUnion(p) => p.rule_id_and_message(lang),
            Self::FnRangeOfConstantAnonymousFn(p) => p.rule_id_and_message(lang),
            Self::SeqEqualsFnOnNPos(p) => p.rule_id_and_message(lang),
            Self::FiniteSeqEqualsFnOnOneBasedDomain(p) => p.rule_id_and_message(lang),
            Self::IndexUnionEmptyIndex(p) => p.rule_id_and_message(lang),
            Self::IndexIntersectEmptyIndex(p) => p.rule_id_and_message(lang),
            Self::IndexCartEmptyIndex(p) => p.rule_id_and_message(lang),
            Self::IndexUnionSingleton(p) => p.rule_id_and_message(lang),
            Self::FiniteSeqZeroEqualsFnOnEmpty(p) => p.rule_id_and_message(lang),
            Self::SetBuilderObviouslyEmpty(p) => p.rule_id_and_message(lang),
            Self::ComplexAbsSquaredOfRectForm(p) => p.rule_id_and_message(lang),
            Self::ExpOfSum(p) => p.rule_id_and_message(lang),
            Self::LogBasePower(p) => p.rule_id_and_message(lang),
            Self::ReOfProduct(p) => p.rule_id_and_message(lang),
            Self::ImgOfProduct(p) => p.rule_id_and_message(lang),
            Self::SinOfSum(p) => p.rule_id_and_message(lang),
            Self::CosOfSum(p) => p.rule_id_and_message(lang),
            Self::ReduceSingleTermWithAddZero(p) => p.rule_id_and_message(lang),
            Self::FiniteSetSumFubiniSwap(p) => p.rule_id_and_message(lang),
            Self::FiniteSetSumOverCartesianProduct(p) => p.rule_id_and_message(lang),
            Self::SinOfZero(p) => p.rule_id_and_message(lang),
            Self::CosOfZero(p) => p.rule_id_and_message(lang),
            Self::TanOfZero(p) => p.rule_id_and_message(lang),
            Self::SinOfHalfPi(p) => p.rule_id_and_message(lang),
            Self::CosOfPi(p) => p.rule_id_and_message(lang),
            Self::SinOfPi(p) => p.rule_id_and_message(lang),
            Self::CotOfHalfPi(p) => p.rule_id_and_message(lang),
            Self::PythagoreanIdentity(p) => p.rule_id_and_message(lang)
        }
    }

    pub fn cite_fact_id(&self) -> Option<FactId> {
        match self {
            Self::EqualFromKnownDifferenceZero(p) => Some(p.cite_fact_id),
            _ => None,
        }
    }
}
