//! Equality builtin rules → Normal JSON text.
//!
//! Call site: `rule.rule_id_and_message(lang)` on `EqualitySearchProofByBuiltinRule`.

mod calculation;
mod finite_subset_size;
mod leaves;
mod text;

use crate::execute::execute_fact_stmt::verify_atomic_fact::verify_equality::verify_equality_by_builtin_rules::EqualitySearchProofByBuiltinRule;
use crate::json_output::explain::fallback::BuiltinRuleText;
use crate::launch_command::OutputLanguage;
use crate::runtime::FactId;

impl EqualitySearchProofByBuiltinRule {
    pub fn rule_id_and_message(&self, lang: OutputLanguage) -> BuiltinRuleText {
        match self {
            Self::Calculation(p) => p.rule_id_and_message(lang),
            Self::AggregateIdentity(_) => BuiltinRuleText {
                rule_id: "AggregateIdentity", rule_name: "Finite aggregate identity".into(),
                message: "Verified constant, linear, pointwise, partition or reindexing requirements".into(),
            },
            Self::AggregateCalculation(_) => crate::json_output::explain::fallback::BuiltinRuleText {
                rule_id: "AggregateCalculation",
                rule_name: "Exact finite aggregate calculation".into(),
                message: "Enumerate valid arguments, substitute checked function bodies and fold exact values".into(),
            },
            Self::SinArcsinLeftInverse(p) => p.rule_id_and_message(lang),
            Self::CosArccosLeftInverse(p) => p.rule_id_and_message(lang),
            Self::TanArctanLeftInverse(p) => p.rule_id_and_message(lang),
            Self::CotArccotLeftInverse(p) => p.rule_id_and_message(lang),
            Self::ArcsinSinRightInverse(p) => p.rule_id_and_message(lang),
            Self::ArccosCosRightInverse(p) => p.rule_id_and_message(lang),
            Self::ArctanTanRightInverse(p) => p.rule_id_and_message(lang),
            Self::ArccotCotRightInverse(p) => p.rule_id_and_message(lang),
            Self::ArcsinExactZero(p) => p.rule_id_and_message(lang),
            Self::ArcsinExactOne(p) => p.rule_id_and_message(lang),
            Self::ArcsinExactNegOne(p) => p.rule_id_and_message(lang),
            Self::ArccosExactOne(p) => p.rule_id_and_message(lang),
            Self::ArccosExactZero(p) => p.rule_id_and_message(lang),
            Self::ArccosExactNegOne(p) => p.rule_id_and_message(lang),
            Self::ArctanExactZero(p) => p.rule_id_and_message(lang),
            Self::ArccotExactZero(p) => p.rule_id_and_message(lang),
            Self::PowerProductSameBase(p) => p.rule_id_and_message(lang),
            Self::PowerOfPower(p) => p.rule_id_and_message(lang),
            Self::PowerOfProduct(p) => p.rule_id_and_message(lang),
            Self::ReciprocalAsNegOnePower(p) => p.rule_id_and_message(lang),
            Self::QuotientAsMulNegOnePower(p) => p.rule_id_and_message(lang),
            Self::OneToAnyPower(p) => p.rule_id_and_message(lang),
            Self::ZeroToPosNatPower(p) => p.rule_id_and_message(lang),
            Self::SqrtSquare(p) => p.rule_id_and_message(lang),
            Self::SqrtZero(p) => p.rule_id_and_message(lang),
            Self::SqrtOne(p) => p.rule_id_and_message(lang),
            Self::SqrtOfSquare(p) => p.rule_id_and_message(lang),
            Self::SqrtProduct(p) => p.rule_id_and_message(lang),
            Self::SqrtQuotient(p) => p.rule_id_and_message(lang),
            Self::AbsOfNegation(p) => p.rule_id_and_message(lang),
            Self::AbsProduct(p) => p.rule_id_and_message(lang),
            Self::AbsSquare(p) => p.rule_id_and_message(lang),
            Self::LogBaseSelf(p) => p.rule_id_and_message(lang),
            Self::LogOfOne(p) => p.rule_id_and_message(lang),
            Self::LogOfPowerSameBase(p) => p.rule_id_and_message(lang),
            Self::LogArgPower(p) => p.rule_id_and_message(lang),
            Self::LogProduct(p) => p.rule_id_and_message(lang),
            Self::LogQuotient(p) => p.rule_id_and_message(lang),
            Self::LogReciprocal(p) => p.rule_id_and_message(lang),
            Self::LogChangeOfBase(p) => p.rule_id_and_message(lang),
            Self::ZeroMod(p) => p.rule_id_and_message(lang),
            Self::ModOne(p) => p.rule_id_and_message(lang),
            Self::OneModAtLeastTwo(p) => p.rule_id_and_message(lang),
            Self::NestedSameModAbsorption(p) => p.rule_id_and_message(lang),
            Self::ModCompatibleSmallerModulus(p) => p.rule_id_and_message(lang),
            Self::MinIdempotent(p) => p.rule_id_and_message(lang),
            Self::MaxIdempotent(p) => p.rule_id_and_message(lang),
            Self::MinCommutative(p) => p.rule_id_and_message(lang),
            Self::MaxCommutative(p) => p.rule_id_and_message(lang),
            Self::AbsAbsAbsorption(p) => p.rule_id_and_message(lang),
            Self::ExpOfLn(p) => p.rule_id_and_message(lang),
            Self::LnOfExp(p) => p.rule_id_and_message(lang),
            Self::FloorOfInteger(p) => p.rule_id_and_message(lang),
            Self::CeilOfInteger(p) => p.rule_id_and_message(lang),
            Self::ModSelfZero(p) => p.rule_id_and_message(lang),
            Self::FloorOfCeilOfInteger(p) => p.rule_id_and_message(lang),
            Self::CeilOfFloorOfInteger(p) => p.rule_id_and_message(lang),
            Self::SqrtOfSquareEqualsAbs(p) => p.rule_id_and_message(lang),
            Self::QuotByOne(p) => p.rule_id_and_message(lang),
            Self::QuotSelfOne(p) => p.rule_id_and_message(lang),
            Self::LcmCommutative(p) => p.rule_id_and_message(lang),
            Self::LcmIdempotentAbs(p) => p.rule_id_and_message(lang),
            Self::GcdCommutative(p) => p.rule_id_and_message(lang),
            Self::GcdIdempotentAbs(p) => p.rule_id_and_message(lang),
            Self::GcdRightZeroAbs(p) => p.rule_id_and_message(lang),
            Self::GcdLeftZeroAbs(p) => p.rule_id_and_message(lang),
            Self::FactorialSuccessor(p) => p.rule_id_and_message(lang),
            Self::AbsNonnegEqualsSelf(p) => p.rule_id_and_message(lang),
            Self::AbsNonposEqualsNegation(p) => p.rule_id_and_message(lang),
            Self::SignOfPositive(p) => p.rule_id_and_message(lang),
            Self::SignOfNegative(p) => p.rule_id_and_message(lang),
            Self::MaxRightWhenLessEqual(p) => p.rule_id_and_message(lang),
            Self::MaxLeftWhenLessEqual(p) => p.rule_id_and_message(lang),
            Self::MinLeftWhenLessEqual(p) => p.rule_id_and_message(lang),
            Self::MinRightWhenLessEqual(p) => p.rule_id_and_message(lang),
            Self::GcdDividesArgument(p) => p.rule_id_and_message(lang),
            Self::ProductModFactorZero(p) => p.rule_id_and_message(lang),
            Self::EqualityFromTwoSidedWeakOrder(p) => p.rule_id_and_message(lang),
            Self::DiffZeroFromEqualOperands(p) => p.rule_id_and_message(lang),
            Self::EqualFromKnownDifferenceZero(p) => p.rule_id_and_message(lang),
            Self::ZeroProductCancel(p) => p.rule_id_and_message(lang),
            Self::SignOfNegation(p) => p.rule_id_and_message(lang),
            Self::SignTimesAbsEqualsArg(p) => p.rule_id_and_message(lang),
            Self::AbsEqualsSignTimesArg(p) => p.rule_id_and_message(lang),
            Self::SignOfProduct(p) => p.rule_id_and_message(lang),
            Self::SubtractionFromKnownAddition(p) => p.rule_id_and_message(lang),
            Self::QuotEuclideanDecomposition(p) => p.rule_id_and_message(lang),
            Self::ModDividendMinusRemainderZero(p) => p.rule_id_and_message(lang),
            Self::SquareSumComponentZero(p) => p.rule_id_and_message(lang),
            Self::MinusOneOddNaturalPower(p) => p.rule_id_and_message(lang),
            Self::LcmGcdProductAbs(p) => p.rule_id_and_message(lang),
            Self::UnionEmptyRight(p) => p.rule_id_and_message(lang),
            Self::UnionEmptyLeft(p) => p.rule_id_and_message(lang),
            Self::IntersectEmptyRight(p) => p.rule_id_and_message(lang),
            Self::IntersectEmptyLeft(p) => p.rule_id_and_message(lang),
            Self::SetMinusSelfEmpty(p) => p.rule_id_and_message(lang),
            Self::SetMinusEmptyRight(p) => p.rule_id_and_message(lang),
            Self::SetMinusEmptyLeft(p) => p.rule_id_and_message(lang),
            Self::UnionCommutative(p) => p.rule_id_and_message(lang),
            Self::IntersectCommutative(p) => p.rule_id_and_message(lang),
            Self::UnionIdempotent(p) => p.rule_id_and_message(lang),
            Self::IntersectIdempotent(p) => p.rule_id_and_message(lang),
            Self::IntersectFromSubset(p) => p.rule_id_and_message(lang),
            Self::EmptySetFromNotNonempty(p) => p.rule_id_and_message(lang),
            Self::PowerSetFiniteSetSize(p) => p.rule_id_and_message(lang),
            Self::UnionAssociative(p) => p.rule_id_and_message(lang),
            Self::IntersectAssociative(p) => p.rule_id_and_message(lang),
            Self::IntersectUnionDistributive(p) => p.rule_id_and_message(lang),
            Self::SetMinusUnionDeMorgan(p) => p.rule_id_and_message(lang),
            Self::SetMinusIntersectDeMorgan(p) => p.rule_id_and_message(lang),
            Self::IntersectSetMinusSelfEmpty(p) => p.rule_id_and_message(lang),
            Self::FiniteSetSumEmpty(p) => p.rule_id_and_message(lang),
            Self::FiniteSetProductEmpty(p) => p.rule_id_and_message(lang),
            Self::FiniteSetReduceEmpty(p) => p.rule_id_and_message(lang),
            Self::ReduceEmpty(p) => p.rule_id_and_message(lang),
            Self::SumEmptyRange(p) => p.rule_id_and_message(lang),
            Self::ProductEmptyRange(p) => p.rule_id_and_message(lang),
            Self::UnionAbsorptionFromSubset(p) => p.rule_id_and_message(lang),
            Self::SetMinusRecoversSubset(p) => p.rule_id_and_message(lang),
            Self::EmptySetFromSizeZero(p) => p.rule_id_and_message(lang),
            Self::FiniteSetEqualFromSubsetSize(p) => p.rule_id_and_message(lang),
            Self::CartProjFactor(p) => p.rule_id_and_message(lang),
            Self::TupleComponentAtIndex(p) => p.rule_id_and_message(lang),
            Self::FiniteSetSizeSetMinus(p) => p.rule_id_and_message(lang),
            Self::FiniteSetSizeUnion(p) => p.rule_id_and_message(lang),
            Self::ClosedRangeSingletonListSet(p) => p.rule_id_and_message(lang),
            Self::SumSingleTerm(p) => p.rule_id_and_message(lang),
            Self::ProductSingleTerm(p) => p.rule_id_and_message(lang),
            Self::ReduceAddZeroEqualsSum(p) => p.rule_id_and_message(lang),
            Self::FiniteSetReduceAddZeroEqualsSum(p) => p.rule_id_and_message(lang),
            Self::PowOfLogInverse(p) => p.rule_id_and_message(lang),
            Self::UnionSetMinusDecomposition(p) => p.rule_id_and_message(lang),
            Self::SetMinusIntersectSelf(p) => p.rule_id_and_message(lang),
            Self::ReOfImaginaryUnit(p) => p.rule_id_and_message(lang),
            Self::ImgOfImaginaryUnit(p) => p.rule_id_and_message(lang),
            Self::ReOfRealEmbedding(p) => p.rule_id_and_message(lang),
            Self::ImgOfRealEmbedding(p) => p.rule_id_and_message(lang),
            Self::ReOfRealPlusI(p) => p.rule_id_and_message(lang),
            Self::ImgOfRealPlusI(p) => p.rule_id_and_message(lang),
            Self::ComplexAbsOfImaginaryUnit(p) => p.rule_id_and_message(lang),
            Self::ModNestedDivisibleAbsorption(p) => p.rule_id_and_message(lang),
            Self::SumSplitLastTerm(p) => p.rule_id_and_message(lang),
            Self::ProductSplitLastTerm(p) => p.rule_id_and_message(lang),
            Self::FiniteSetSumListExpansion(p) => p.rule_id_and_message(lang),
            Self::FiniteSetProductListExpansion(p) => p.rule_id_and_message(lang),
            Self::EulerEqualsExpOne(p) => p.rule_id_and_message(lang),
            Self::LnOfEuler(p) => p.rule_id_and_message(lang),
            Self::ReOfReal(p) => p.rule_id_and_message(lang),
            Self::ImgOfReal(p) => p.rule_id_and_message(lang),
            Self::ReOfRealPlusImagScaled(p) => p.rule_id_and_message(lang),
            Self::ImgOfRealPlusImagScaled(p) => p.rule_id_and_message(lang),
            Self::ComplexAbsOfNonnegReal(p) => p.rule_id_and_message(lang),
            Self::ComplexAbsOfImagScaled(p) => p.rule_id_and_message(lang),
            Self::ClosedRangeLiteralExpansion(p) => p.rule_id_and_message(lang),
            Self::RangeLiteralExpansion(p) => p.rule_id_and_message(lang),
            Self::PowerSetOfEmpty(p) => p.rule_id_and_message(lang),
            Self::PowerSetOfSingleton(p) => p.rule_id_and_message(lang),
            Self::FamilyUnionOfEmpty(p) => p.rule_id_and_message(lang),
            Self::CartWithEmptyFactor(p) => p.rule_id_and_message(lang),
            Self::UnionOverIntersectDistributive(p) => p.rule_id_and_message(lang),
            Self::SetMinusChainToUnion(p) => p.rule_id_and_message(lang),
            Self::FnRangeOfConstantAnonymousFn(p) => p.rule_id_and_message(lang),
            Self::SeqEqualsFnOnN(p) => p.rule_id_and_message(lang),
            Self::FiniteSeqEqualsFnOnClosedRange(p) => p.rule_id_and_message(lang),
            Self::IndexUnionEmptyIndex(p) => p.rule_id_and_message(lang),
            Self::IndexIntersectEmptyIndex(p) => p.rule_id_and_message(lang),
            Self::IndexCartEmptyIndex(p) => p.rule_id_and_message(lang),
            Self::IndexUnionSingleton(p) => p.rule_id_and_message(lang),
            Self::FiniteSeqZeroEqualsFnOnEmpty(p) => p.rule_id_and_message(lang),
            Self::SetBuilderObviouslyEmpty(p) => p.rule_id_and_message(lang),
            Self::ComplexAbsSquaredOfRectForm(p) => p.rule_id_and_message(lang),
            Self::ExpOfSum(p) => p.rule_id_and_message(lang),
            Self::LogBasePower(p) => p.rule_id_and_message(lang),
            Self::ReOfProduct(p) => p.rule_id_and_message(lang),
            Self::ImgOfProduct(p) => p.rule_id_and_message(lang),
            Self::SinOfSum(p) => p.rule_id_and_message(lang),
            Self::CosOfSum(p) => p.rule_id_and_message(lang),
            Self::ReduceSingleTermWithAddZero(p) => p.rule_id_and_message(lang),
            Self::FiniteSetSumFubiniSwap(p) => p.rule_id_and_message(lang),
            Self::FiniteSetSumOverCartesianProduct(p) => p.rule_id_and_message(lang),
            Self::SinOfZero(p) => p.rule_id_and_message(lang),
            Self::CosOfZero(p) => p.rule_id_and_message(lang),
            Self::TanOfZero(p) => p.rule_id_and_message(lang),
            Self::SinOfHalfPi(p) => p.rule_id_and_message(lang),
            Self::CosOfPi(p) => p.rule_id_and_message(lang),
            Self::SinOfPi(p) => p.rule_id_and_message(lang),
            Self::CotOfHalfPi(p) => p.rule_id_and_message(lang),
            Self::PythagoreanIdentity(p) => p.rule_id_and_message(lang)
        }
    }

    pub fn cite_fact_id(&self) -> Option<FactId> {
        match self {
            Self::EqualFromKnownDifferenceZero(p) => Some(p.cite_fact_id),
            _ => None
        }
    }
}
