use crate::execute::execute_fact_stmt::verify_atomic_fact::verify_equality::verify_equality_by_builtin_rules::by_scalar_identities::ScalarIdentityBuiltinRuleProof as P;
use crate::json_output::explain::fallback::BuiltinRuleText;
use crate::launch_command::OutputLanguage;

pub(super) fn explain(proof: &P, lang: OutputLanguage) -> BuiltinRuleText {
    let (en, zh, message_en, message_zh) = match proof {
        P::FiniteSetMaxSelection(_) => (
            "Exact finite-set maximum",
            "有限集合最大值精确选取",
            "Select an original rational member and certify every member is no greater",
            "选取原有理数成员并证明每个成员不大于它",
        ),
        P::FiniteSetMinSelection(_) => (
            "Exact finite-set minimum",
            "有限集合最小值精确选取",
            "Select an original rational member and certify every member is no smaller",
            "选取原有理数成员并证明每个成员不小于它",
        ),
        P::AbsZeroArgument(_) => (
            "Zero absolute value",
            "绝对值为零",
            "A real number whose absolute value is zero equals zero",
            "实数的绝对值为零时，该实数等于零",
        ),
        P::FloorNegation(_) => (
            "Floor of a negation",
            "取负后的向下取整",
            "floor(-x) = -ceil(x) for real x",
            "实数 x 满足 floor(-x) = -ceil(x)",
        ),
        P::CeilNegation(_) => (
            "Ceiling of a negation",
            "取负后的向上取整",
            "ceil(-x) = -floor(x) for real x",
            "实数 x 满足 ceil(-x) = -floor(x)",
        ),
        P::FloorIntegerTranslation(_) => (
            "Integer translation of floor",
            "向下取整的整数平移",
            "An integer shift commutes with floor",
            "经验证的整数位移可移出 floor",
        ),
        P::CeilIntegerTranslation(_) => (
            "Integer translation of ceiling",
            "向上取整的整数平移",
            "An integer shift commutes with ceiling",
            "经验证的整数位移可移出 ceil",
        ),
        P::MinMaxAbsorption(_) => (
            "Minimum absorbs maximum",
            "最小值吸收最大值",
            "min(a, max(a, b)) = a for real operands",
            "实数操作数满足 min(a, max(a, b)) = a",
        ),
        P::MaxMinAbsorption(_) => (
            "Maximum absorbs minimum",
            "最大值吸收最小值",
            "max(a, min(a, b)) = a for real operands",
            "实数操作数满足 max(a, min(a, b)) = a",
        ),
        P::LcmZero(_) => (
            "Zero argument of lcm",
            "lcm 的零参数",
            "The least common multiple is zero when either integer argument is zero",
            "lcm 的任一整数参数为零时，结果为零",
        ),
    };
    let (name, message) = match lang {
        OutputLanguage::English => (en, message_en),
        OutputLanguage::ChineseTraditional => match proof {
            P::FiniteSetMaxSelection(_) => ("有限集合最大值精確選取", "選取原有理數成員並證明每個成員不大於它"),
            P::FiniteSetMinSelection(_) => ("有限集合最小值精確選取", "選取原有理數成員並證明每個成員不小於它"),
            P::AbsZeroArgument(_) => ("絕對值為零", "實數的絕對值為零時，該實數等於零"),
            P::FloorNegation(_) => ("取負後的向下取整", "實數 x 滿足 floor(-x) = -ceil(x)"),
            P::CeilNegation(_) => ("取負後的向上取整", "實數 x 滿足 ceil(-x) = -floor(x)"),
            P::FloorIntegerTranslation(_) => ("向下取整的整數平移", "整數位移可移出 floor"),
            P::CeilIntegerTranslation(_) => ("向上取整的整數平移", "整數位移可移出 ceil"),
            P::MinMaxAbsorption(_) => ("最小值吸收最大值", "實數運算元滿足 min(a, max(a, b)) = a"),
            P::MaxMinAbsorption(_) => ("最大值吸收最小值", "實數運算元滿足 max(a, min(a, b)) = a"),
            P::LcmZero(_) => ("lcm 的零引數", "任一整數引數為零時，最小公倍數為零"),
        },
        OutputLanguage::French => match proof {
            P::FiniteSetMaxSelection(_) => ("Maximum exact d'un ensemble fini", "Choisir un membre rationnel original et certifier qu'aucun membre n'est plus grand"),
            P::FiniteSetMinSelection(_) => ("Minimum exact d'un ensemble fini", "Choisir un membre rationnel original et certifier qu'aucun membre n'est plus petit"),
            P::AbsZeroArgument(_) => ("Valeur absolue nulle", "Un réel de valeur absolue nulle est égal à zéro"),
            P::FloorNegation(_) => ("Partie entière inférieure d'un opposé", "floor(-x) = -ceil(x) pour x réel"),
            P::CeilNegation(_) => ("Partie entière supérieure d'un opposé", "ceil(-x) = -floor(x) pour x réel"),
            P::FloorIntegerTranslation(_) => ("Translation entière de la partie entière inférieure", "Une translation entière commute avec floor"),
            P::CeilIntegerTranslation(_) => ("Translation entière de la partie entière supérieure", "Une translation entière commute avec ceil"),
            P::MinMaxAbsorption(_) => ("Le minimum absorbe le maximum", "min(a, max(a, b)) = a pour des opérandes réels"),
            P::MaxMinAbsorption(_) => ("Le maximum absorbe le minimum", "max(a, min(a, b)) = a pour des opérandes réels"),
            P::LcmZero(_) => ("Argument nul de lcm", "Le plus petit commun multiple est nul si l'un des arguments entiers est nul"),
        },
        OutputLanguage::Russian => match proof {
            P::FiniteSetMaxSelection(_) => ("Точный максимум конечного множества", "Выбрать исходный рациональный элемент и подтвердить, что ни один элемент не больше"),
            P::FiniteSetMinSelection(_) => ("Точный минимум конечного множества", "Выбрать исходный рациональный элемент и подтвердить, что ни один элемент не меньше"),
            P::AbsZeroArgument(_) => ("Нулевой модуль", "Вещественное число с нулевым модулем равно нулю"),
            P::FloorNegation(_) => ("Пол отрицания", "floor(-x) = -ceil(x) для вещественного x"),
            P::CeilNegation(_) => ("Потолок отрицания", "ceil(-x) = -floor(x) для вещественного x"),
            P::FloorIntegerTranslation(_) => ("Целочисленный сдвиг пола", "Целочисленный сдвиг коммутирует с floor"),
            P::CeilIntegerTranslation(_) => ("Целочисленный сдвиг потолка", "Целочисленный сдвиг коммутирует с ceil"),
            P::MinMaxAbsorption(_) => ("Минимум поглощает максимум", "min(a, max(a, b)) = a для вещественных операндов"),
            P::MaxMinAbsorption(_) => ("Максимум поглощает минимум", "max(a, min(a, b)) = a для вещественных операндов"),
            P::LcmZero(_) => ("Нулевой аргумент lcm", "Наименьшее общее кратное равно нулю, если один из целых аргументов равен нулю"),
        },
        OutputLanguage::Spanish => match proof {
            P::FiniteSetMaxSelection(_) => ("Máximo exacto de conjunto finito", "Elegir un miembro racional original y certificar que ningún miembro es mayor"),
            P::FiniteSetMinSelection(_) => ("Mínimo exacto de conjunto finito", "Elegir un miembro racional original y certificar que ningún miembro es menor"),
            P::AbsZeroArgument(_) => ("Valor absoluto cero", "Un número real de valor absoluto cero es igual a cero"),
            P::FloorNegation(_) => ("Piso de una negación", "floor(-x) = -ceil(x) para x real"),
            P::CeilNegation(_) => ("Techo de una negación", "ceil(-x) = -floor(x) para x real"),
            P::FloorIntegerTranslation(_) => ("Traslación entera del piso", "Una traslación entera conmuta con floor"),
            P::CeilIntegerTranslation(_) => ("Traslación entera del techo", "Una traslación entera conmuta con ceil"),
            P::MinMaxAbsorption(_) => ("El mínimo absorbe el máximo", "min(a, max(a, b)) = a para operandos reales"),
            P::MaxMinAbsorption(_) => ("El máximo absorbe el mínimo", "max(a, min(a, b)) = a para operandos reales"),
            P::LcmZero(_) => ("Argumento cero de lcm", "El mínimo común múltiplo es cero si cualquiera de los argumentos enteros es cero"),
        },
        OutputLanguage::Arabic => match proof {
            P::FiniteSetMaxSelection(_) => ("قيمة عظمى دقيقة لمجموعة منتهية", "اختيار عنصر نسبي أصلي وإثبات أن كل عنصر لا يزيد عليه"),
            P::FiniteSetMinSelection(_) => ("قيمة صغرى دقيقة لمجموعة منتهية", "اختيار عنصر نسبي أصلي وإثبات أن كل عنصر لا يقل عنه"),
            P::AbsZeroArgument(_) => ("قيمة مطلقة صفرية", "العدد الحقيقي ذو القيمة المطلقة الصفرية يساوي صفرًا"),
            P::FloorNegation(_) => ("أرضية القيمة السالبة", "floor(-x) = -ceil(x) للعدد الحقيقي x"),
            P::CeilNegation(_) => ("سقف القيمة السالبة", "ceil(-x) = -floor(x) للعدد الحقيقي x"),
            P::FloorIntegerTranslation(_) => ("إزاحة صحيحة للأرضية", "الإزاحة الصحيحة تتبادل مع floor"),
            P::CeilIntegerTranslation(_) => ("إزاحة صحيحة للسقف", "الإزاحة الصحيحة تتبادل مع ceil"),
            P::MinMaxAbsorption(_) => ("القيمة الصغرى تمتص القيمة العظمى", "min(a, max(a, b)) = a للمعاملات الحقيقية"),
            P::MaxMinAbsorption(_) => ("القيمة العظمى تمتص القيمة الصغرى", "max(a, min(a, b)) = a للمعاملات الحقيقية"),
            P::LcmZero(_) => ("وسيط صفري لـ lcm", "المضاعف المشترك الأصغر يساوي صفرًا إذا كان أحد الوسيطين الصحيحين صفرًا"),
        },
        OutputLanguage::Japanese => match proof {
            P::FiniteSetMaxSelection(_) => ("有限集合の正確な最大値", "元の有理数の要素を選び、すべての要素がそれ以下であることを証明します"),
            P::FiniteSetMinSelection(_) => ("有限集合の正確な最小値", "元の有理数の要素を選び、すべての要素がそれ以上であることを証明します"),
            P::AbsZeroArgument(_) => ("絶対値がゼロ", "絶対値がゼロである実数はゼロです"),
            P::FloorNegation(_) => ("符号反転の床関数", "実数 x について floor(-x) = -ceil(x)"),
            P::CeilNegation(_) => ("符号反転の天井関数", "実数 x について ceil(-x) = -floor(x)"),
            P::FloorIntegerTranslation(_) => ("床関数の整数平行移動", "整数の平行移動は floor と可換です"),
            P::CeilIntegerTranslation(_) => ("天井関数の整数平行移動", "整数の平行移動は ceil と可換です"),
            P::MinMaxAbsorption(_) => ("最小値による最大値の吸収", "実数の被演算子について min(a, max(a, b)) = a"),
            P::MaxMinAbsorption(_) => ("最大値による最小値の吸収", "実数の被演算子について max(a, min(a, b)) = a"),
            P::LcmZero(_) => ("lcm のゼロ引数", "整数引数のいずれかがゼロなら最小公倍数はゼロです"),
        },
        OutputLanguage::Korean => match proof {
            P::FiniteSetMaxSelection(_) => ("유한 집합의 정확한 최댓값", "원래의 유리수 원소를 선택하고 모든 원소가 그보다 크지 않음을 인증합니다"),
            P::FiniteSetMinSelection(_) => ("유한 집합의 정확한 최솟값", "원래의 유리수 원소를 선택하고 모든 원소가 그보다 작지 않음을 인증합니다"),
            P::AbsZeroArgument(_) => ("절댓값이 0", "절댓값이 0인 실수는 0입니다"),
            P::FloorNegation(_) => ("부호 반전의 바닥 함수", "실수 x에 대해 floor(-x) = -ceil(x)"),
            P::CeilNegation(_) => ("부호 반전의 천장 함수", "실수 x에 대해 ceil(-x) = -floor(x)"),
            P::FloorIntegerTranslation(_) => ("바닥 함수의 정수 평행이동", "정수 평행이동은 floor와 교환됩니다"),
            P::CeilIntegerTranslation(_) => ("천장 함수의 정수 평행이동", "정수 평행이동은 ceil과 교환됩니다"),
            P::MinMaxAbsorption(_) => ("최솟값의 최댓값 흡수", "실수 피연산자에 대해 min(a, max(a, b)) = a"),
            P::MaxMinAbsorption(_) => ("최댓값의 최솟값 흡수", "실수 피연산자에 대해 max(a, min(a, b)) = a"),
            P::LcmZero(_) => ("lcm의 0 인수", "정수 인수 중 하나가 0이면 최소공배수는 0입니다"),
        },
        OutputLanguage::Vietnamese => match proof {
            P::FiniteSetMaxSelection(_) => ("Giá trị lớn nhất chính xác của tập hữu hạn", "Chọn phần tử hữu tỉ gốc và chứng nhận mọi phần tử không lớn hơn nó"),
            P::FiniteSetMinSelection(_) => ("Giá trị nhỏ nhất chính xác của tập hữu hạn", "Chọn phần tử hữu tỉ gốc và chứng nhận mọi phần tử không nhỏ hơn nó"),
            P::AbsZeroArgument(_) => ("Giá trị tuyệt đối bằng không", "Số thực có giá trị tuyệt đối bằng không thì bằng không"),
            P::FloorNegation(_) => ("Hàm sàn của số đối", "floor(-x) = -ceil(x) với x thực"),
            P::CeilNegation(_) => ("Hàm trần của số đối", "ceil(-x) = -floor(x) với x thực"),
            P::FloorIntegerTranslation(_) => ("Tịnh tiến nguyên của hàm sàn", "Tịnh tiến nguyên giao hoán với floor"),
            P::CeilIntegerTranslation(_) => ("Tịnh tiến nguyên của hàm trần", "Tịnh tiến nguyên giao hoán với ceil"),
            P::MinMaxAbsorption(_) => ("Giá trị nhỏ nhất hấp thụ giá trị lớn nhất", "min(a, max(a, b)) = a với các toán hạng thực"),
            P::MaxMinAbsorption(_) => ("Giá trị lớn nhất hấp thụ giá trị nhỏ nhất", "max(a, min(a, b)) = a với các toán hạng thực"),
            P::LcmZero(_) => ("Đối số không của lcm", "Bội chung nhỏ nhất bằng không khi một trong hai đối số nguyên bằng không"),
        },

        OutputLanguage::Chinese => (zh, message_zh),
    };
    BuiltinRuleText {
        rule_id: proof.rule_id(),
        rule_name: name.into(),
        message: message.into(),
    }
}

pub(super) fn trig_complex(
    proof: &crate::execute::execute_fact_stmt::verify_atomic_fact::verify_equality::verify_equality_by_builtin_rules::by_trig_complex_identities::TrigComplexIdentityProof,
    lang: OutputLanguage,
) -> BuiltinRuleText {
    use crate::execute::execute_fact_stmt::verify_atomic_fact::verify_equality::verify_equality_by_builtin_rules::by_trig_complex_identities::TrigComplexIdentityProof as T;
    let (en, zh, message_en, message_zh) = match proof {
        T::SinHalfPiShift(_) => (
            "Sine quarter-turn shift",
            "正弦的半 pi 平移",
            "sin(x+pi/2)=cos(x) for checked real x",
            "经验证的实数 x 满足 sin(x+pi/2)=cos(x)",
        ),
        T::CosHalfPiShift(_) => (
            "Cosine quarter-turn shift",
            "余弦的半 pi 平移",
            "cos(x+pi/2)=-sin(x) for checked real x",
            "经验证的实数 x 满足 cos(x+pi/2)=-sin(x)",
        ),
        T::PeriodicTrig(_) => (
            "Exact periodic trigonometric value",
            "精确周期三角值",
            "Reduce the exact pi coefficient using checked integer periods",
            "依据已验证的整数周期归约精确 pi 系数",
        ),
        T::NumericComplexModulus(_) => (
            "Exact numeric complex modulus",
            "数字复数模长精确计算",
            "Compute exact real/imaginary coordinates and take the nonnegative principal root",
            "精确计算实部与虚部并取非负主根",
        ),
        T::SinDifference => (
            "Sine difference formula",
            "正弦差角公式",
            "sin(x-y)=sin(x)cos(y)-cos(x)sin(y) for checked real arguments",
            "经验证的实数参数满足 sin(x-y)=sin(x)cos(y)-cos(x)sin(y)",
        ),
        T::CosDifference => (
            "Cosine difference formula",
            "余弦差角公式",
            "cos(x-y)=cos(x)cos(y)+sin(x)sin(y) for checked real arguments",
            "经验证的实数参数满足 cos(x-y)=cos(x)cos(y)+sin(x)sin(y)",
        ),
        T::ComplexModulusProduct => (
            "Multiplicativity of complex modulus",
            "复数模的乘法公式",
            "C_abs(z*w)=C_abs(z)*C_abs(w) for checked complex arguments",
            "经验证的复数参数满足 C_abs(z*w)=C_abs(z)*C_abs(w)",
        ),
        _ => (
            "Trigonometric or complex coordinate identity",
            "三角或复坐标恒等式",
            "Apply the trigonometric or complex coordinate identity with checked premises",
            "依据已验证的前提应用三角或复坐标恒等式",
        ),
    };
    let (name, message) = match lang {
        OutputLanguage::English => (en, message_en),
        OutputLanguage::ChineseTraditional => match proof {
            T::SinHalfPiShift(_) => ("正弦的半 pi 平移", "經驗證的實數 x 滿足 sin(x+pi/2)=cos(x)"),
            T::CosHalfPiShift(_) => ("餘弦的半 pi 平移", "經驗證的實數 x 滿足 cos(x+pi/2)=-sin(x)"),
            T::PeriodicTrig(_) => ("精確週期三角值", "以已驗證的整數週期歸約精確 pi 係數"),
            T::NumericComplexModulus(_) => ("數值複數模長精確計算", "精確計算實部與虛部並取非負主根"),
            T::SinDifference => ("正弦差角公式", "經驗證的實數引數滿足 sin(x-y)=sin(x)cos(y)-cos(x)sin(y)"),
            T::CosDifference => ("餘弦差角公式", "經驗證的實數引數滿足 cos(x-y)=cos(x)cos(y)+sin(x)sin(y)"),
            T::ComplexModulusProduct => ("複數模的乘法公式", "經驗證的複數引數滿足 C_abs(z*w)=C_abs(z)*C_abs(w)"),
            _ => ("三角或複數座標恆等式", "依已驗證的前提套用三角或複數座標恆等式"),
        },
        OutputLanguage::French => match proof {
            T::SinHalfPiShift(_) => ("Translation d'un quart de tour du sinus", "sin(x+pi/2)=cos(x) pour x réel vérifié"),
            T::CosHalfPiShift(_) => ("Translation d'un quart de tour du cosinus", "cos(x+pi/2)=-sin(x) pour x réel vérifié"),
            T::PeriodicTrig(_) => ("Valeur trigonométrique périodique exacte", "Réduire le coefficient exact de pi avec des périodes entières vérifiées"),
            T::NumericComplexModulus(_) => ("Module complexe numérique exact", "Calculer les coordonnées réelles et imaginaires exactes et prendre la racine principale non négative"),
            T::SinDifference => ("Formule du sinus d'une différence", "sin(x-y)=sin(x)cos(y)-cos(x)sin(y) pour des arguments réels vérifiés"),
            T::CosDifference => ("Formule du cosinus d'une différence", "cos(x-y)=cos(x)cos(y)+sin(x)sin(y) pour des arguments réels vérifiés"),
            T::ComplexModulusProduct => ("Multiplicativité du module complexe", "C_abs(z*w)=C_abs(z)*C_abs(w) pour des arguments complexes vérifiés"),
            _ => ("Identité trigonométrique ou de coordonnées complexes", "Appliquer l'identité trigonométrique ou de coordonnées complexes avec les prémisses vérifiées"),
        },
        OutputLanguage::Russian => match proof {
            T::SinHalfPiShift(_) => ("Сдвиг синуса на четверть оборота", "sin(x+pi/2)=cos(x) для проверенного вещественного x"),
            T::CosHalfPiShift(_) => ("Сдвиг косинуса на четверть оборота", "cos(x+pi/2)=-sin(x) для проверенного вещественного x"),
            T::PeriodicTrig(_) => ("Точное периодическое тригонометрическое значение", "Сократить точный коэффициент pi по проверенным целочисленным периодам"),
            T::NumericComplexModulus(_) => ("Точный модуль числового комплексного значения", "Точно вычислить действительную и мнимую координаты и взять неотрицательный главный корень"),
            T::SinDifference => ("Формула синуса разности", "sin(x-y)=sin(x)cos(y)-cos(x)sin(y) для проверенных вещественных аргументов"),
            T::CosDifference => ("Формула косинуса разности", "cos(x-y)=cos(x)cos(y)+sin(x)sin(y) для проверенных вещественных аргументов"),
            T::ComplexModulusProduct => ("Мультипликативность комплексного модуля", "C_abs(z*w)=C_abs(z)*C_abs(w) для проверенных комплексных аргументов"),
            _ => ("Тригонометрическое или комплексное координатное тождество", "Применить тригонометрическое или комплексное координатное тождество с проверенными предпосылками"),
        },
        OutputLanguage::Spanish => match proof {
            T::SinHalfPiShift(_) => ("Desplazamiento de un cuarto de vuelta del seno", "sin(x+pi/2)=cos(x) para x real comprobado"),
            T::CosHalfPiShift(_) => ("Desplazamiento de un cuarto de vuelta del coseno", "cos(x+pi/2)=-sin(x) para x real comprobado"),
            T::PeriodicTrig(_) => ("Valor trigonométrico periódico exacto", "Reducir el coeficiente exacto de pi usando períodos enteros comprobados"),
            T::NumericComplexModulus(_) => ("Módulo complejo numérico exacto", "Calcular las coordenadas reales e imaginarias exactas y tomar la raíz principal no negativa"),
            T::SinDifference => ("Fórmula del seno de una diferencia", "sin(x-y)=sin(x)cos(y)-cos(x)sin(y) para argumentos reales comprobados"),
            T::CosDifference => ("Fórmula del coseno de una diferencia", "cos(x-y)=cos(x)cos(y)+sin(x)sin(y) para argumentos reales comprobados"),
            T::ComplexModulusProduct => ("Multiplicatividad del módulo complejo", "C_abs(z*w)=C_abs(z)*C_abs(w) para argumentos complejos comprobados"),
            _ => ("Identidad trigonométrica o de coordenadas complejas", "Aplicar la identidad trigonométrica o de coordenadas complejas con premisas comprobadas"),
        },
        OutputLanguage::Arabic => match proof {
            T::SinHalfPiShift(_) => ("إزاحة الجيب بربع دورة", "sin(x+pi/2)=cos(x) للعدد الحقيقي x المتحقق منه"),
            T::CosHalfPiShift(_) => ("إزاحة جيب التمام بربع دورة", "cos(x+pi/2)=-sin(x) للعدد الحقيقي x المتحقق منه"),
            T::PeriodicTrig(_) => ("قيمة مثلثية دورية دقيقة", "اختزال معامل pi الدقيق باستخدام دورات صحيحة متحقق منها"),
            T::NumericComplexModulus(_) => ("مقياس مركب عددي دقيق", "حساب الإحداثيين الحقيقي والتخيلي بدقة وأخذ الجذر الرئيسي غير السالب"),
            T::SinDifference => ("صيغة جيب الفرق", "sin(x-y)=sin(x)cos(y)-cos(x)sin(y) للوسائط الحقيقية المتحقق منها"),
            T::CosDifference => ("صيغة جيب تمام الفرق", "cos(x-y)=cos(x)cos(y)+sin(x)sin(y) للوسائط الحقيقية المتحقق منها"),
            T::ComplexModulusProduct => ("ضربية المقياس المركب", "C_abs(z*w)=C_abs(z)*C_abs(w) للوسائط المركبة المتحقق منها"),
            _ => ("هوية مثلثية أو إحداثيات مركبة", "تطبيق الهوية المثلثية أو هوية الإحداثيات المركبة بالمقدمات المتحقق منها"),
        },
        OutputLanguage::Japanese => match proof {
            T::SinHalfPiShift(_) => ("正弦の四分の一回転の平行移動", "検証済みの実数 x について sin(x+pi/2)=cos(x)"),
            T::CosHalfPiShift(_) => ("余弦の四分の一回転の平行移動", "検証済みの実数 x について cos(x+pi/2)=-sin(x)"),
            T::PeriodicTrig(_) => ("正確な周期的三角関数値", "検証済みの整数周期を用いて正確な pi の係数を簡約します"),
            T::NumericComplexModulus(_) => ("数値的複素数の正確な絶対値", "実部と虚部を正確に計算し、非負の主平方根を取ります"),
            T::SinDifference => ("正弦の差角公式", "検証済みの実数引数について sin(x-y)=sin(x)cos(y)-cos(x)sin(y)"),
            T::CosDifference => ("余弦の差角公式", "検証済みの実数引数について cos(x-y)=cos(x)cos(y)+sin(x)sin(y)"),
            T::ComplexModulusProduct => ("複素数の絶対値の乗法性", "検証済みの複素数引数について C_abs(z*w)=C_abs(z)*C_abs(w)"),
            _ => ("三角関数または複素座標の恒等式", "検証済みの前提で三角関数または複素座標の恒等式を適用します"),
        },
        OutputLanguage::Korean => match proof {
            T::SinHalfPiShift(_) => ("사인의 4분의 1회전 이동", "검증된 실수 x에 대해 sin(x+pi/2)=cos(x)"),
            T::CosHalfPiShift(_) => ("코사인의 4분의 1회전 이동", "검증된 실수 x에 대해 cos(x+pi/2)=-sin(x)"),
            T::PeriodicTrig(_) => ("정확한 주기 삼각함숫값", "검증된 정수 주기로 정확한 pi 계수를 축약합니다"),
            T::NumericComplexModulus(_) => ("수치 복소수의 정확한 절댓값", "실수부와 허수부를 정확하게 계산하고 음이 아닌 주 제곱근을 취합니다"),
            T::SinDifference => ("사인 차각 공식", "검증된 실수 인수에 대해 sin(x-y)=sin(x)cos(y)-cos(x)sin(y)"),
            T::CosDifference => ("코사인 차각 공식", "검증된 실수 인수에 대해 cos(x-y)=cos(x)cos(y)+sin(x)sin(y)"),
            T::ComplexModulusProduct => ("복소수 절댓값의 곱셈성", "검증된 복소수 인수에 대해 C_abs(z*w)=C_abs(z)*C_abs(w)"),
            _ => ("삼각함수 또는 복소수 좌표 항등식", "검증된 전제로 삼각함수 또는 복소수 좌표 항등식을 적용합니다"),
        },
        OutputLanguage::Vietnamese => match proof {
            T::SinHalfPiShift(_) => ("Dịch sin một phần tư vòng", "sin(x+pi/2)=cos(x) với x thực đã kiểm tra"),
            T::CosHalfPiShift(_) => ("Dịch cos một phần tư vòng", "cos(x+pi/2)=-sin(x) với x thực đã kiểm tra"),
            T::PeriodicTrig(_) => ("Giá trị lượng giác tuần hoàn chính xác", "Rút gọn hệ số pi chính xác bằng các chu kỳ nguyên đã kiểm tra"),
            T::NumericComplexModulus(_) => ("Môđun phức dạng số chính xác", "Tính chính xác tọa độ thực và ảo rồi lấy căn chính không âm"),
            T::SinDifference => ("Công thức sin hiệu", "sin(x-y)=sin(x)cos(y)-cos(x)sin(y) với các đối số thực đã kiểm tra"),
            T::CosDifference => ("Công thức cos hiệu", "cos(x-y)=cos(x)cos(y)+sin(x)sin(y) với các đối số thực đã kiểm tra"),
            T::ComplexModulusProduct => ("Tính nhân của môđun phức", "C_abs(z*w)=C_abs(z)*C_abs(w) với các đối số phức đã kiểm tra"),
            _ => ("Đồng nhất thức lượng giác hoặc tọa độ phức", "Áp dụng đồng nhất thức lượng giác hoặc tọa độ phức với các tiền đề đã kiểm tra"),
        },
 OutputLanguage::Chinese => (zh, message_zh),
    };
    BuiltinRuleText {
        rule_id: proof.rule_id(),
        rule_name: name.into(),
        message: message.into(),
    }
}
