pub const ORIGINALS: &[&str] = &[
    "forall a,b R:\n    a>=0\n    b>0\n    =>:\n        0<=a+b\n",
    "forall a,b R:\n    a>0\n    b>=0\n    =>:\n        0<=a+b\n",
    "forall a,b R:\n    a>0\n    b>0\n    =>:\n        0<=a+b\n",
    "forall a,b,c,d R:\n    b>a\n    d>c\n    =>:\n        a+c<b+d\n",
    "forall a,b,c,d R:\n    b>a\n    c>d\n    =>:\n        a+d<b+c\n",
    "forall x R:\n    x>4\n    =>:\n        2<=x\n",
    "forall x,n Z:\n    n<=x\n    x<n+1\n    =>:\n        x=n\n",
    "forall x,n Z:\n    n<x\n    x<=n+1\n    =>:\n        x=n+1\n",
    "forall x,y R:\n    exp(x)=exp(y)\n    =>:\n        x=y\n",
    "forall x,y R:\n    0<=x\n    x<=y\n    =>:\n        sqrt(x)<=sqrt(y)\n",
    "forall a,b Q*:\n    a*b $in Q*\n",
    "forall x,y R+:\n    ln(x)=ln(y)\n    =>:\n        x=y\n",
    "forall x R+,n N+:\n    (x^n)^(1/n)=x\n",
    "forall b R+,x R,y R+:\n    b!=1\n    b^x=y\n    =>:\n        log(b,y)=x\n",
    "forall b R+,x Z,y R+:\n    b!=1\n    b^x=y\n    =>:\n        log(b,y)=x\n",
    "forall a,b R:\n    0<=a\n    b<0\n    =>:\n        a*b<=0\n",
    "forall a,b R:\n    a>=0\n    0>b\n    =>:\n        a*b<=0\n",
    "forall a,b R:\n    0<a\n    b<0\n    =>:\n        a*b<0\n",
    "forall a,b R:\n    a>0\n    0>b\n    =>:\n        a*b<0\n",
    "forall a,b R:\n    a<0\n    0<b\n    =>:\n        a*b<0\n",
    "forall a,b R:\n    0>a\n    b>0\n    =>:\n        a*b<0\n",
    "forall a R:\n    a>=0\n    =>:\n        0<=a^3\n",
    "forall a R,n R:\n    0<a\n    =>:\n        0<=a^n\n",
    "forall a R,n R:\n    0<a\n    =>:\n        0<a^n\n",
    "forall a R,n R:\n    a>0\n    =>:\n        0<=a^n\n",
    "forall a R,n R:\n    a>0\n    =>:\n        0<a^n\n",
    "forall a R,n N+:\n    a>0\n    =>:\n        0<=a^n\n",
    "forall a R,n Z:\n    a>0\n    =>:\n        0<=a^n\n",
    "forall a R,n N+:\n    a>=0\n    =>:\n        0<=a^n\n",
    "forall a R,n C:\n    0<a\n    n $in R\n    =>:\n        0<a^n\n",
    "forall x,b R:\n    x<=b\n    -x<=b\n    =>:\n        abs(x)<=b\n",
    "forall x,b R:\n    x<=b\n    (-1)*x<=b\n    =>:\n        abs(x)<=b\n",
    "forall x,b R:\n    -b<=x\n    x<=b\n    =>:\n        abs(x)<=b\n",
    "forall x R:\n    x>=0\n    =>:\n        abs(x)=x\n",
    "forall x R:\n    x<0\n    =>:\n        abs(x)=-x\n",
    "forall x R:\n    x<0\n    =>:\n        abs(x)=0-x\n",
    "forall x R:\n    x>4\n    =>:\n        x>=2\n",
    "forall x R:\n    4>x\n    =>:\n        x<=6\n",
    "forall x Z:\n    x>4\n    =>:\n        5<=x\n",
    "forall x Z:\n    4>x\n    =>:\n        x<=3\n",
    "forall x R:\n    (-4)<x\n    =>:\n        (-6)<=x\n",
    "forall x R:\n    x>(-4)\n    =>:\n        x>=(-6)\n",
    "forall x R:\n    x<(-4)\n    =>:\n        x<=(-2)\n",
    "forall x R:\n    (-4)>x\n    =>:\n        (-2)>=x\n",
    "forall a,b,c R:\n    b>a\n    c>=b\n    =>:\n        c>a\n",
    "forall a,b R:\n    a<b\n    =>:\n        -b<-a\n",
    "forall a,b R:\n    a<=b\n    =>:\n        -b<=-a\n",
    "forall x R:\n    x>=2\n    =>:\n        (-1)*x<0\n",
    "forall x,y R:\n    x<=y\n    -x<=y\n    =>:\n        abs(x)<=y\n",
    "forall a,x R+,n Z:\n    a!=1\n    a^n=x\n    =>:\n        log(a,x)=n\n",
    "forall x R+:\n    log(0.5,x) $in Z\n    =>:\n        0.5^log(0.5,x)=x\n",
    "forall a R+:\n    a<1\n    =>:\n        log(a,a)=1\n",
    "forall a R+:\n    a<1\n    =>:\n        log(a,1)=0\n",
    "forall a R+,n Z:\n    a<1\n    =>:\n        log(a,a^n)=n\n",
    "forall x R+:\n    0.5^log(0.5,x)=x\n",
    "forall a,x R+,p R:\n    a!=1\n    a^p=x\n    =>:\n        log(a,x)=p\n",
    "forall n N+:\n    factorial(n)=n*factorial(n-1)\n",
    "forall n N+:\n    factorial(n)=factorial(n-1)*n\n",
    "forall n N+:\n    n*factorial(n-1)=factorial(n)\n",
    "forall n N+:\n    n-1 $in N\n    =>:\n        factorial(n)=n*factorial(n-1)\n",
    "forall a,b R:\n    exp(a-b)=exp(a)/exp(b)\n",
    "forall a,b R:\n    exp(b)!=0\n    =>:\n        exp(a-b)=exp(a)/exp(b)\n",
    "forall a,b R+:\n    ln(a*b)=ln(a)+ln(b)\n",
    "forall a,b R+:\n    ln(a/b)=ln(a)-ln(b)\n",
    "forall a,b R:\n    exp(a)=exp(b)\n    =>:\n        a=b\n",
    "forall a,b R+:\n    ln(a)=ln(b)\n    =>:\n        a=b\n",
    "forall x R+:\n    1<x\n    =>:\n        0<ln(x)\n",
    "forall x R+:\n    x<1\n    =>:\n        ln(x)<0\n",
    "forall a,b R+:\n    a/b $in R+\n",
    "forall a,b R+:\n    a/b $in R+\n    =>:\n        ln(a/b)=ln(a)-ln(b)\n",
    "forall x,y R:\n    0<=x\n    0<=y\n    x=y^2\n    =>:\n        sqrt(x)=y\n",
    "forall x,y R:\n    0<=x\n    0<=y\n    y^2=x\n    =>:\n        sqrt(x)=y\n",
    "forall x,y R:\n    0<=x\n    0<=y\n    x=y^2\n    =>:\n        y=sqrt(x)\n",
    "forall x R:\n    x<=0\n    =>:\n        sqrt(x^2)=-x\n",
    "forall a,b,x R:\n    0<=a\n    0<=b\n    0<=x\n    x=a*b\n    =>:\n        sqrt(x)=sqrt(a)*sqrt(b)\n",
    "forall a,b,x R:\n    0<=a\n    0<=b\n    0<=x\n    a*b=x\n    =>:\n        sqrt(x)=sqrt(a)*sqrt(b)\n",
    "forall a,b,x R:\n    0<=a\n    0<b\n    0<=x\n    x=a/b\n    =>:\n        sqrt(x)=sqrt(a)/sqrt(b)\n",
    "forall a,b,x R:\n    0<=a\n    0<b\n    0<=x\n    a/b=x\n    =>:\n        sqrt(x)=sqrt(a)/sqrt(b)\n",
    "forall a,b R,n Z:\n    0<a\n    0<b\n    n!=0\n    a^n=b^n\n    =>:\n        a=b\n",
    "forall a,b,c R:\n    b!=0\n    a/b=c\n    =>:\n        a=c*b\n",
    "forall a,b,c R:\n    b!=0\n    a=b*c\n    =>:\n        a/b=c\n",
    "forall a,b,c R:\n    b!=0\n    a=c*b\n    =>:\n        a/b=c\n",
    "forall a,b,c C:\n    b!=0\n    a/b=c\n    =>:\n        a=c*b\n",
    "forall a,b,c C:\n    b!=0\n    a=b*c\n    =>:\n        a/b=c\n",
    "forall a,b,c C:\n    b!=0\n    a=c*b\n    =>:\n        a/b=c\n",
    "forall a,b,c Q:\n    b!=0\n    a/b=c\n    =>:\n        a=c*b\n",
    "forall a,b,c Q:\n    b!=0\n    a=b*c\n    =>:\n        a/b=c\n",
    "forall a,b,c Q:\n    b!=0\n    a=c*b\n    =>:\n        a/b=c\n",
    "forall a,b,c Z:\n    b!=0\n    a/b=c\n    =>:\n        a=c*b\n",
    "forall a,b,c Z:\n    b!=0\n    a=b*c\n    =>:\n        a/b=c\n",
    "forall a,b,c Z:\n    b!=0\n    a=c*b\n    =>:\n        a/b=c\n",
    "forall a,b,c,d R:\n    b!=0\n    d!=0\n    a/(b*d)=c\n    =>:\n        a=c*(b*d)\n",
    "forall a,b,c,d C:\n    b!=0\n    d!=0\n    a/(b*d)=c\n    =>:\n        a=c*(b*d)\n",
    "forall a,b,c R+:\n    a/b=c\n    =>:\n        a=c*b\n",
    "forall a,b,c R+:\n    a=b*c\n    =>:\n        a/b=c\n",
    "forall a,b,c R*:\n    a/b=c\n    =>:\n        a=c*b\n",
    "forall a,b,c R:\n    b<0\n    a/b=c\n    =>:\n        a=c*b\n",
    "forall x,n Z:\n    n<=x\n    x<n+1\n    =>:\n        n=x\n",
    "forall x,n Z:\n    n<x\n    x<=n+1\n    =>:\n        n+1=x\n",
    "forall x,n N:\n    n<=x\n    x<n+1\n    =>:\n        x=n\n",
    "forall x,n N:\n    n<=x\n    x<n+1\n    =>:\n        n=x\n",
    "forall x,n N:\n    n<x\n    x<=n+1\n    =>:\n        x=n+1\n",
    "forall x,n N:\n    n<x\n    x<=n+1\n    =>:\n        n+1=x\n",
    "forall x,n N+:\n    n<=x\n    x<n+1\n    =>:\n        x=n\n",
    "forall x,n N+:\n    n<=x\n    x<n+1\n    =>:\n        n=x\n",
    "forall x,n N+:\n    n<x\n    x<=n+1\n    =>:\n        x=n+1\n",
    "forall x,n N+:\n    n<x\n    x<=n+1\n    =>:\n        n+1=x\n",
    "forall a,b Z:\n    b>a\n    =>:\n        a+1<=b\n",
    "forall x,n Z:\n    x>=n\n    n+1>x\n    =>:\n        x=n\n",
    "forall x,n Z:\n    x>n\n    n+1>=x\n    =>:\n        x=n+1\n",
    "forall x Z:\n    0<=x\n    x<1\n    =>:\n        x=0\n",
    "forall x Z:\n    -3<=x\n    x<-2\n    =>:\n        x=-3\n",
    "forall x,n Z:\n    n<x\n    x<=1+n\n    =>:\n        x=1+n\n",
    "forall a,b,c,p,z R:\n    z=0\n    a*b!=z\n    =>:\n        a!=0\n",
    "forall a,b,c,p,z C:\n    z=0\n    a*b!=z\n    =>:\n        a!=0\n",
    "forall a,b,z R:\n    z=0\n    a*b!=z\n    =>:\n        a!=0\n",
    "forall a,b,z C:\n    z=0\n    a*b!=z\n    =>:\n        a!=0\n",
    "forall a,b,c,d Q:\n    b!=0\n    d!=0\n    a/(b*d)=c\n    =>:\n        a=c*(b*d)\n",
    "forall a,b,c,d Z:\n    b!=0\n    d!=0\n    a/(b*d)=c\n    =>:\n        a=c*(b*d)\n",
    "forall a,b,c,d R:\n    b*d!=0\n    a/(b*d)=c\n    =>:\n        a=c*(b*d)\n",
    "forall a,x R+,n Z:\n    a<1\n    log(a,x)=n\n    =>:\n        a^n=x\n",
    "forall x,y R:\n    -1<=x\n    x<=1\n    -pi/2<=y\n    y<=pi/2\n    sin(y)=x\n    =>:\n        arcsin(x)=y\n",
    "forall x,y R:\n    -1<=x\n    x<=1\n    -pi/2<=y\n    y<=pi/2\n    x=sin(y)\n    =>:\n        arcsin(x)=y\n",
    "forall x,y R:\n    -1<=x\n    x<=1\n    (-pi)/2<=y\n    y<=pi/2\n    sin(y)=x\n    =>:\n        arcsin(x)=y\n",
    "forall x,y R:\n    -1<=x\n    x<=1\n    (-pi)/2<=y\n    y<=pi/2\n    x=sin(y)\n    =>:\n        arcsin(x)=y\n",
    "forall x,y R:\n    -1<=x\n    x<=1\n    -(pi/2)<=y\n    y<=pi/2\n    sin(y)=x\n    =>:\n        arcsin(x)=y\n",
    "forall x,y R:\n    -1<=x\n    x<=1\n    -(pi/2)<=y\n    y<=pi/2\n    x=sin(y)\n    =>:\n        arcsin(x)=y\n",
    "forall x,y R:\n    -1<=x\n    x<=1\n    -pi/2<=y\n    y<=pi/2\n    sin(y)=x\n    =>:\n        y=arcsin(x)\n",
    "forall x,y,z R:\n    sin(x+y+z)=sin(x)*cos(y)*cos(z)+cos(x)*sin(y)*cos(z)+cos(x)*cos(y)*sin(z)-sin(x)*sin(y)*sin(z)\n",
    "forall x,y R:\n    cos(x)!=0\n    cos(y)!=0\n    cos(x+y)!=0\n    1-tan(x)*tan(y)!=0\n    =>:\n        tan(x+y)=(tan(x)+tan(y))/(1-tan(x)*tan(y))\n",
    "forall x R:\n    sin(x)!=0\n    =>:\n        sin(-x)!=0\n",
    "forall x R:\n    sin(x)!=0\n    =>:\n        sin(x+pi)!=0\n",
    "forall x R:\n    sin(x)!=0\n    =>:\n        sin(x+2*pi)!=0\n",
    "forall x R:\n    cos(x)!=0\n    =>:\n        cos(-x)!=0\n",
    "forall x R:\n    cos(x)!=0\n    =>:\n        cos(x+pi)!=0\n",
    "forall x R:\n    cos(x)!=0\n    =>:\n        cos(x+2*pi)!=0\n",
    "forall x R:\n    sin(x)!=0\n    cos(x)!=0\n    =>:\n        tan(x)!=0\n",
    "forall x R:\n    sin(x)!=0\n    cos(x)!=0\n    =>:\n        cot(x)!=0\n",
    "forall a Z,m N+:\n    (a%m)%1=a%1\n",
    "e!=1\n",
];
pub const NEGATIVES: &[&str] = &[
    "forall n N:\n    factorial(n)=n*factorial(n-1)\n",
    "forall n N+:\n    factorial(n)=factorial(n-1)\n",
    "forall x,y R:\n    x=y\n",
    "forall x,y R+:\n    x=y\n",
    "forall a,b R:\n    exp(a-b)=exp(a)*exp(b)\n",
    "forall a,b R+:\n    ln(a*b)=ln(a)-ln(b)\n",
    "forall a,b R+:\n    ln(a/b)=ln(a)+ln(b)\n",
    "forall a,b R:\n    ln(a*b)=ln(a)+ln(b)\n",
    "forall x R+:\n    log(1,x)=0\n",
    "forall a,x R+,n Z:\n    a!=1\n    =>:\n        log(a,x)=n\n",
    "forall a,x R+,n Z:\n    a!=1\n    =>:\n        a^n=x\n",
    "forall a,c R,b R*:\n    a=c*b\n",
    "forall a,b,c R:\n    a=c*b\n    =>:\n        a/b=c\n",
    "forall a,c R,b R*:\n    a/b=c\n    =>:\n        a=c/b\n",
    "forall a,b R:\n    a*b $in R+\n",
    "forall a,b Q:\n    a*b $in Q*\n",
    "forall x R:\n    sin(-x)!=0\n",
    "forall x R:\n    cos(-x)!=0\n",
    "forall x R:\n    sin(x)!=0\n    =>:\n        sin(x+pi/2)!=0\n",
    "forall x R:\n    cos(x)!=0\n    =>:\n        cos(x+pi/2)!=0\n",
    "forall x R:\n    sin(x)!=0\n    =>:\n        tan(x)!=0\n",
    "forall x R:\n    cos(x)!=0\n    =>:\n        cot(x)!=0\n",
    "e=1\n",
    "forall x,y,z R:\n    sin(x+y+z)=sin(x)*cos(y)*cos(z)+cos(x)*sin(y)*cos(z)+cos(x)*cos(y)*sin(z)+sin(x)*sin(y)*sin(z)\n",
    "forall x,y R:\n    tan(x+y)=(tan(x)+tan(y))/(1-tan(x)*tan(y))\n",
    "forall a,b R:\n    a<b\n    =>:\n        a+1<=b\n",
    "forall x,n R:\n    n<=x\n    x<n+1\n    =>:\n        x=n\n",
    "forall x,n R:\n    n<x\n    x<=n+1\n    =>:\n        x=n+1\n",
    "forall x,n Z:\n    n<=x\n    x<=n+1\n    =>:\n        x=n\n",
    "forall x,n Z:\n    n<=x\n    x<=n+1\n    =>:\n        x=n+1\n",
    "forall x R:\n    x>4\n    =>:\n        5<=x\n",
    "forall a,b,c R:\n    b>=a\n    c>=b\n    =>:\n        c>a\n",
    "forall a,b,c,d R:\n    b>=a\n    d>=c\n    =>:\n        a+c<b+d\n",
    "forall a,b R:\n    a<b\n    =>:\n        -a<-b\n",
    "forall x R:\n    x>=0\n    =>:\n        -x<0\n",
    "forall x,b R:\n    x<=b\n    =>:\n        abs(x)<=b\n",
    "forall x,y R:\n    x<=y\n    =>:\n        sqrt(x)<=sqrt(y)\n",
    "forall x,y R+:\n    x<=y\n    =>:\n        sqrt(y)<=sqrt(x)\n",
    "forall x,y R:\n    0<=x\n    x=y^2\n    =>:\n        sqrt(x)=y\n",
    "forall x R:\n    x>=0\n    =>:\n        sqrt(x^2)=-x\n",
    "forall a,b,z R:\n    a*b!=z\n    =>:\n        a!=0\n",
    "forall a,b,z R:\n    z=0\n    a*b=z\n    =>:\n        a!=0\n",
    "forall a,b R:\n    a=(-b)\n    =>:\n        a+b!=0\n",
    "forall a,b C:\n    a=(-b)\n    =>:\n        a+b!=0\n",
    "forall a,b R+:\n    a*b<0\n",
    "forall a,b R:\n    0<=a\n    =>:\n        a*b<=0\n",
    "0<ln(1)\n",
    "ln(1)<0\n",
    "forall x,y R:\n    -1<=x\n    x<=1\n    sin(y)=x\n    =>:\n        arcsin(x)=y\n",
    "arcsin(sin(pi))=pi\n",
    "forall a,x R+,p R:\n    a!=1\n    a^p=x\n    =>:\n        log(a,x)=p+1\n",
    "forall x R:\n    x<=0\n    =>:\n        sqrt(x^2)=x\n",
    "forall a,b R+:\n    a^0=b^0\n    =>:\n        a=b\n",
    "forall a,b R*:\n    a^2=b^2\n    =>:\n        a=b\n",
    "forall a,b,x R:\n    0<=x\n    x=a*b\n    =>:\n        sqrt(x)=sqrt(a)*sqrt(b)\n",
    "forall x R:\n    x>=0\n    =>:\n        x $in R+\n",
    "forall a,b C:\n    a^2+b^2=0\n    =>:\n        a=0\n",
    "forall a,b C:\n    a!=0\n    =>:\n        a^2+b^2!=0\n",
];
