pub mod by_equal_ir;
pub mod search_equal_fact_by_calculation;
pub mod search_equal_fact_builtin_rule;
pub mod search_equal_fact_builtin_rule_result;

pub use search_equal_fact_builtin_rule_result::EqualitySearchProofByBuiltinRule;
