pub mod builtin_prop_definition;
pub mod helper;
mod known_premises;
pub mod lookup_known_atomic_fact;
pub mod result;
pub mod search_atomic_except_equality_fact_proof;
pub mod search_atomic_except_equality_fact_proof_by_builtin_rewrite;
pub mod search_atomic_except_equality_fact_proof_by_builtin_rules;
pub mod search_atomic_except_equality_fact_proof_by_builtin_strategy;
pub mod search_atomic_except_equality_fact_proof_by_definition;
pub mod search_atomic_except_equality_fact_proof_by_known;
pub mod search_atomic_except_equality_fact_proof_by_known_atomic_fact;
pub mod search_atomic_except_equality_fact_proof_by_known_forall_fact;
pub mod search_atomic_except_equality_fact_proof_by_known_rewrite;
pub mod search_atomic_except_equality_fact_proof_by_known_special_property;
pub mod search_atomic_except_equality_fact_proof_by_known_strategy;
pub mod verify_atomic_except_equality;

pub use search_atomic_except_equality_fact_proof_by_builtin_rewrite::AtomicExceptEqualityFactSearchProofByBuiltinRewrite;
pub use search_atomic_except_equality_fact_proof_by_builtin_rules::AtomicExceptEqualityFactSearchProofByBuiltinRule;
pub use search_atomic_except_equality_fact_proof_by_builtin_strategy::AtomicExceptEqualityFactSearchProofByBuiltinStrategy;
pub use search_atomic_except_equality_fact_proof_by_known_rewrite::AtomicExceptEqualityFactSearchProofByKnownRewrite;

pub use result::{
    AtomicExceptEqualityFactSearchProofByDefinition,
    AtomicExceptEqualityFactSearchProofByKnownAtomicFact, AtomicExceptEqualityFactSearchedProof,
    BuiltinPropDefinitionProof, SearchProofByKnownStrategy, UserDefinedPropDefinitionProof,
    VerifyAtomicExceptEqualityFactFailed, VerifyAtomicExceptEqualityFactResult,
};

pub use search_atomic_except_equality_fact_proof_by_known_special_property::AtomicExceptEqualityFactSearchProofByKnownSpecialProperty;

pub mod known_fn_standard_return;
#[cfg(test)]
#[path = "../../../../../tests/unit/execute/known_search/tests.rs"]
mod known_search_tests;
