use crate::prelude::*;
impl Runtime {
    /// Verifies one quantifier-free premise generated by a builtin rule.
    /// A premise is a child proof obligation that must be verified before the rule may
    /// conclude its parent fact.
    ///
    /// Compound logical structure does not reset or consume the builtin-rule depth budget:
    /// conjunction and chains verify every atomic leaf, while disjunction first reuses the
    /// complete known `or` fact and otherwise verifies exactly one branch. Every atomic leaf
    /// returns to the bounded atomic premise verifier below.
    ///
    /// Example: list-set membership may use the single premise
    /// `a = 1 or a = 2 or a = 3` to prove `a $in {1, 2, 3}`.
    /// This compound entry is necessary because a known disjunction proves the complete `or`,
    /// not any selected equality; an atomic-only entry would discard exactly that evidence.
    pub(crate) fn verify_builtin_rule_premise(
        &mut self,
        premise: &QuantifierFreeFact,
        builtin_state: &UseBuiltinRuleVerifyState,
    ) -> Result<StmtResult, RuntimeError> {
        match premise {
            QuantifierFreeFact::AtomicFact(atomic_fact) => {
                self.verify_atomic_fact_as_builtin_rule_premise(atomic_fact, builtin_state)
            }
            QuantifierFreeFact::AndFact(and_fact) => {
                self.verify_and_fact_as_builtin_rule_premise(and_fact, builtin_state)
            }
            QuantifierFreeFact::ChainFact(chain_fact) => {
                self.verify_chain_fact_as_builtin_rule_premise(chain_fact, builtin_state)
            }
            QuantifierFreeFact::OrFact(or_fact) => {
                self.verify_or_fact_as_builtin_rule_premise(or_fact, builtin_state)
            }
        }
    }

    fn verify_and_fact_as_builtin_rule_premise(
        &mut self,
        and_fact: &AndFact,
        builtin_state: &UseBuiltinRuleVerifyState,
    ) -> Result<StmtResult, RuntimeError> {
        if let Some(cached_result) =
            self.verify_fact_from_cache_using_display_string(&and_fact.clone().into())
        {
            return Ok(cached_result);
        }

        let mut child_results = Vec::with_capacity(and_fact.facts.len());
        for atomic_fact in &and_fact.facts {
            let result =
                self.verify_atomic_fact_as_builtin_rule_premise(atomic_fact, builtin_state)?;
            if !result.is_true() {
                return Ok(StmtUnknown::new().into());
            }
            child_results.push(result);
        }
        Ok(FactualStmtSuccess::new_with_verified_by_known_fact(
            and_fact.clone().into(),
            VerifiedByResult::wrap_bys(Vec::new()),
            child_results,
        )
        .into())
    }

    fn verify_chain_fact_as_builtin_rule_premise(
        &mut self,
        chain_fact: &ChainFact,
        builtin_state: &UseBuiltinRuleVerifyState,
    ) -> Result<StmtResult, RuntimeError> {
        if let Some(cached_result) =
            self.verify_fact_from_cache_using_display_string(&chain_fact.clone().into())
        {
            return Ok(cached_result);
        }

        let atomic_facts = chain_fact.facts()?;
        let mut child_results = Vec::with_capacity(atomic_facts.len());
        for atomic_fact in &atomic_facts {
            let result =
                self.verify_atomic_fact_as_builtin_rule_premise(atomic_fact, builtin_state)?;
            if !result.is_true() {
                return Ok(StmtUnknown::new().into());
            }
            child_results.push(result);
        }
        Ok(FactualStmtSuccess::new_with_verified_by_known_fact(
            chain_fact.clone().into(),
            VerifiedByResult::wrap_bys(Vec::new()),
            child_results,
        )
        .into())
    }

    fn verify_and_chain_fact_as_builtin_rule_premise(
        &mut self,
        premise: &AndChainAtomicFact,
        builtin_state: &UseBuiltinRuleVerifyState,
    ) -> Result<StmtResult, RuntimeError> {
        match premise {
            AndChainAtomicFact::AtomicFact(atomic_fact) => {
                self.verify_atomic_fact_as_builtin_rule_premise(atomic_fact, builtin_state)
            }
            AndChainAtomicFact::AndFact(and_fact) => {
                self.verify_and_fact_as_builtin_rule_premise(and_fact, builtin_state)
            }
            AndChainAtomicFact::ChainFact(chain_fact) => {
                self.verify_chain_fact_as_builtin_rule_premise(chain_fact, builtin_state)
            }
        }
    }

    fn verify_or_fact_as_builtin_rule_premise(
        &mut self,
        or_fact: &OrFact,
        builtin_state: &UseBuiltinRuleVerifyState,
    ) -> Result<StmtResult, RuntimeError> {
        if let Some(cached_result) =
            self.verify_fact_from_cache_using_display_string(&or_fact.clone().into())
        {
            return Ok(cached_result);
        }
        let known_result = self.verify_or_fact_with_known_or_facts(or_fact)?;
        if known_result.is_true() {
            return Ok(known_result);
        }

        for (selected_index, branch) in or_fact.facts.iter().enumerate() {
            let branch_result =
                self.verify_and_chain_fact_as_builtin_rule_premise(branch, builtin_state)?;
            if !branch_result.is_true() {
                continue;
            }
            return Ok(
                FactualStmtSuccess::new_with_verified_by_builtin_rule_evidence_recording_stmt(
                    or_fact.clone().into(),
                    "builtin premise: one disjunct verified".to_string(),
                    BuiltinRuleEvidence::DisjunctionIntroduction(
                        DisjunctionIntroductionBuiltinRuleEvidence::new(
                            or_fact.clone().into(),
                            branch.clone().into(),
                            selected_index,
                        ),
                    ),
                    vec![branch_result],
                )
                .into(),
            );
        }
        Ok(StmtUnknown::new().into())
    }

    /// Atomic leaf fast path for rules whose premises are already atomic. Keeping this borrowed
    /// form avoids cloning every existing atomic premise merely to wrap it in
    /// [`QuantifierFreeFact::AtomicFact`]. Compound premises must use
    /// [`Runtime::verify_builtin_rule_premise`].
    pub(crate) fn verify_atomic_fact_as_builtin_rule_premise(
        &mut self,
        child: &AtomicFact,
        builtin_state: &UseBuiltinRuleVerifyState,
    ) -> Result<StmtResult, RuntimeError> {
        match child {
            AtomicFact::EqualFact(equal_fact) => {
                let zero_premise_result =
                    self.verify_equal_fact_with_zero_premise_verification(equal_fact)?;
                if zero_premise_result.is_true() || !builtin_state.can_apply_builtin_rule() {
                    return Ok(zero_premise_result);
                }
                self.verify_equal_fact_with_one_premise_producing_builtin_rule(
                    equal_fact,
                    builtin_state,
                )
            }
            _ => {
                let zero_premise_result =
                    self.verify_non_equational_atomic_fact_with_zero_premise_verification(child)?;
                if zero_premise_result.is_true() || !builtin_state.can_apply_builtin_rule() {
                    return Ok(zero_premise_result);
                }
                self.verify_non_equational_atomic_fact_with_one_premise_producing_builtin_rule(
                    child,
                    builtin_state,
                )
            }
        }
    }

    pub(crate) fn verify_builtin_rule_premises(
        &mut self,
        children: &[AtomicFact],
        builtin_state: &UseBuiltinRuleVerifyState,
    ) -> Result<Option<Vec<StmtResult>>, RuntimeError> {
        let mut results = Vec::with_capacity(children.len());
        for child in children {
            let result = self.verify_atomic_fact_as_builtin_rule_premise(child, builtin_state)?;
            if !result.is_true() {
                return Ok(None);
            }
            results.push(result);
        }
        Ok(Some(results))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::Path;

    #[test]
    fn builtin_premise_dispatch_has_one_quantifier_free_entry_and_one_atomic_leaf() {
        let source = include_str!("verify_builtin_rule.rs");
        let implementation = source
            .split("#[cfg(test)]")
            .next()
            .expect("builtin premise implementation must precede its tests");
        let full_verify_state_constructor = ["UseContextVerifyState", "::new("].concat();
        let creates_full_verify_state = implementation
            .match_indices(&full_verify_state_constructor)
            .any(|(index, _)| {
                source[..index]
                    .chars()
                    .next_back()
                    .is_none_or(|ch| !(ch.is_ascii_alphanumeric() || ch == '_'))
            });
        assert!(!creates_full_verify_state);
        assert_eq!(implementation.matches("match premise").count(), 2);
        assert!(implementation.contains("QuantifierFreeFact::AndFact"));
        assert!(implementation.contains("QuantifierFreeFact::ChainFact"));
        assert!(implementation.contains("QuantifierFreeFact::OrFact"));
        assert!(implementation.contains("verify_or_fact_with_known_or_facts"));
        assert!(implementation.contains("DisjunctionIntroductionBuiltinRuleEvidence"));
        assert!(!implementation.contains("verify_fact_full("));
        assert!(!implementation.contains("verify_quantifier_free_fact("));
        assert!(!implementation.contains("verify_quantifier_free_fact_restricted_known_builtin("));
        assert!(
            implementation.contains("verify_equal_fact_with_one_premise_producing_builtin_rule")
        );
        assert!(implementation
            .contains("verify_non_equational_atomic_fact_with_one_premise_producing_builtin_rule"));
    }

    #[test]
    fn automatic_builtin_rule_files_do_not_create_fresh_roots_or_bypass_the_limited_entry() {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src/verify/verify_builtin_rules");
        visit_rust_files(&dir, &mut |path, source| {
            assert!(
                !source.contains("BuiltinRuleVerifyState::new"),
                "{} creates a fresh recursive builtin root",
                path.display()
            );
            assert!(
                !source.contains("verify_atomic_fact_with_builtin_rules("),
                "{} bypasses the depth-limited builtin premise entry point",
                path.display()
            );
        });
    }

    #[test]
    fn quantifier_free_premise_structure_does_not_reset_the_builtin_depth_budget() {
        let line_file = default_line_file();
        let leaf: AtomicFact =
            IsSetFact::new(Number::new("1".to_string()).into(), line_file.clone()).into();
        let premise = QuantifierFreeFact::OrFact(OrFact::new(
            vec![AndChainAtomicFact::AtomicFact(leaf)],
            line_file,
        ));

        let root_state = UseBuiltinRuleVerifyState::new();
        let child_state = root_state.after_applying_builtin_rule();
        let mut child_runtime = Runtime::new();
        child_runtime.new_file_path_new_env_new_name_scope("qff_premise_child_depth.lit");
        let child_result = child_runtime
            .verify_builtin_rule_premise(&premise, &child_state)
            .expect("bounded compound-premise verification should not error");
        assert!(
            child_result.is_unknown(),
            "logical compound structure must not reopen a consumed builtin-rule step"
        );

        let mut root_runtime = Runtime::new();
        root_runtime.new_file_path_new_env_new_name_scope("qff_premise_root_depth.lit");
        let root_result = root_runtime
            .verify_builtin_rule_premise(&premise, &root_state)
            .expect("root compound-premise verification should not error");
        assert!(
            root_result.is_true(),
            "the same atomic leaf should remain available when the root budget is unused"
        );
    }

    #[test]
    fn quantifier_free_and_and_chain_premises_verify_every_atomic_leaf() {
        let line_file = default_line_file();
        let one: Obj = Number::new("1".to_string()).into();
        let two: Obj = Number::new("2".to_string()).into();
        let three: Obj = Number::new("3".to_string()).into();
        let less_one_two: AtomicFact =
            LessFact::new(one.clone(), two.clone(), line_file.clone()).into();
        let less_two_three: AtomicFact =
            LessFact::new(two.clone(), three.clone(), line_file.clone()).into();
        let and_premise = QuantifierFreeFact::AndFact(AndFact::new(
            vec![less_one_two, less_two_three],
            line_file.clone(),
        ));
        let chain_premise = QuantifierFreeFact::ChainFact(ChainFact::new(
            vec![one, two, three],
            vec![
                AtomicName::WithoutMod(LESS.to_string()),
                AtomicName::WithoutMod(LESS.to_string()),
            ],
            line_file,
        ));

        let child_state = UseBuiltinRuleVerifyState::new().after_applying_builtin_rule();
        let mut runtime = Runtime::new();
        runtime.new_file_path_new_env_new_name_scope("qff_and_chain_premises.lit");
        let and_result = runtime
            .verify_builtin_rule_premise(&and_premise, &child_state)
            .expect("conjunction premise verification should not error");
        assert!(and_result.is_true());
        let chain_result = runtime
            .verify_builtin_rule_premise(&chain_premise, &child_state)
            .expect("chain premise verification should not error");
        assert!(chain_result.is_true());
    }

    #[test]
    fn integer_leaf_reuses_known_finiteness_without_opening_a_direct_rule() {
        let mut runtime = Runtime::new();
        runtime.new_file_path_new_env_new_name_scope("integer_leaf_finite_set_size_test.lit");

        let start: Obj = Identifier::new("a".to_string()).into();
        let end: Obj = Identifier::new("b".to_string()).into();
        let set: Obj = ClosedRange::new(start, end).into();
        let size: Obj = FiniteSetSize::new(set.clone()).into();
        let line_file = default_line_file();

        let cold = runtime
            .verify_objects_are_known_integers_in_builtin_leaf(&[&size], &line_file)
            .expect("integer leaf verification should not error");
        assert!(
            cold.is_none(),
            "the integer leaf must not open the direct closed-range finiteness rule"
        );

        let finite_fact: AtomicFact = IsFiniteSetFact::new(set, line_file.clone()).into();
        let finite_result = runtime
            .verify_non_equational_atomic_fact_with_direct_routes(&finite_fact)
            .expect("direct finiteness verification should not error");
        assert!(finite_result.is_true());

        let mut warm = runtime
            .verify_objects_are_known_integers_in_builtin_leaf(&[&size], &line_file)
            .expect("integer leaf verification should not error")
            .expect("known finiteness should type finite_set_size as an integer");
        let size_result = warm
            .pop()
            .expect("finite_set_size integer evidence should be retained")
            .into_factual_success()
            .expect("finite_set_size integer evidence should be factual");
        let VerifiedByResult::BuiltinRule(rule) = size_result.underlying_verified_by() else {
            panic!("finite_set_size membership should keep its builtin rule evidence");
        };
        assert_eq!(
            rule.subgoals.len(),
            1,
            "the known finite-set premise must remain in the proof tree"
        );
    }

    #[test]
    fn direct_evaluation_matchers_are_not_repeated_in_builtin_rule_dispatchers() {
        let non_equational = include_str!("verify_builtin_rules/non_equational_dispatch.rs");
        assert!(!non_equational.contains("verify_prime_fact_by_computation"));

        let equality = include_str!("verify_builtin_rules/equality_dispatch.rs");
        assert!(!equality.contains("objs_match_for_pattern_and_calculation"));
        assert!(!equality.contains("objs_equal_by_rational_expression_evaluation"));

        let numeric_order = include_str!("verify_builtin_rules/number_compare.rs");
        assert_eq!(
            numeric_order
                .matches("verify_number_comparison_builtin_rule(")
                .count(),
            1,
            "number-comparison direct evaluation must be defined once and stay out of the premise-producing rule dispatcher"
        );

        let extrema = include_str!("verify_builtin_rules/order_semantics_builtin.rs");
        assert!(!extrema.contains("verify_finite_set_members_are_at_most"));
        assert!(!extrema.contains("verify_finite_set_members_are_at_least"));
    }

    #[test]
    fn obsolete_mixed_direct_routes_cannot_reappear_in_source() {
        let src = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
        let obsolete = [
            [
                "verify_atomic_fact_with_known_non_forall_facts_then_",
                "with_builtin_rules",
            ]
            .concat(),
            [
                "verify_atomic_fact_with_non_forall_facts_then_",
                "with_builtin_computation",
            ]
            .concat(),
            ["verify_known_non_forall_", "atomic_fact"].concat(),
            ["verify_atomic_fact_by_builtin_", "computation"].concat(),
            ["verify_atomic_fact_with_one_", "builtin_rule"].concat(),
            ["verify_atomic_fact_with_builtin_rules_", "inner"].concat(),
            [
                "verify_non_equational_atomic_fact_with_known_fact_then_",
                "with_builtin_computation",
            ]
            .concat(),
            ["verify_non_equational_atomic_fact_with_", "known_fact("].concat(),
            [
                "verify_non_equational_atomic_fact_by_builtin_",
                "computation",
            ]
            .concat(),
            [
                "verify_non_equational_atomic_fact_with_one_",
                "builtin_rule",
            ]
            .concat(),
            ["verify_equal_fact_with_known_fact_then_", "computation"].concat(),
            ["verify_equal_fact_with_", "leaf_routes"].concat(),
            ["verify_equal_fact_by_builtin_", "computation"].concat(),
            ["verify_equal_fact_with_one_", "builtin_rule"].concat(),
        ];
        visit_rust_files(&src, &mut |path, source| {
            for name in &obsolete {
                assert!(
                    !source.contains(name),
                    "{} reintroduces obsolete cross-family route `{}`",
                    path.display(),
                    name
                );
            }
        });
    }

    #[test]
    fn family_owned_direct_routes_preserve_policy_order_and_boundaries() {
        let equality = include_str!("verify_equality.rs");
        let equality_direct = equality
            .split("pub(crate) fn verify_equal_fact_with_direct_routes(")
            .nth(1)
            .expect("equality owner must expose a direct route")
            .split("pub(crate) fn verify_equal_fact_with_known_fact(")
            .next()
            .expect("known-equality leaf must follow the equality direct route");
        let equality_zero_premise = equality_direct
            .find("verify_equal_fact_with_zero_premise_verification")
            .expect("equality direct route must begin with zero-premise verification");
        let equality_builtin = equality_direct
            .find("verify_equal_fact_with_one_premise_producing_builtin_rule")
            .expect("equality direct route must finish with one premise-producing rule");
        assert!(equality_zero_premise < equality_builtin);

        let equality_zero_premise_impl = equality
            .split("pub(crate) fn verify_equal_fact_with_zero_premise_verification(")
            .nth(1)
            .expect("equality owner must define zero-premise verification")
            .split("pub(crate) fn verify_equal_fact_by_direct_evaluation(")
            .next()
            .expect("direct evaluation must follow zero-premise equality verification");
        let equality_known = equality_zero_premise_impl
            .find("verify_equal_fact_with_known_fact(equal_fact)")
            .expect("zero-premise equality must try known equality first");
        let equality_evaluation = equality_zero_premise_impl
            .find("verify_equal_fact_by_direct_evaluation(equal_fact)")
            .expect("zero-premise equality must try direct evaluation second");
        let equality_known_evaluation = equality_zero_premise_impl
            .find("verify_equal_fact_by_known_equality_then_direct_evaluation(equal_fact)")
            .expect("zero-premise equality must retain known-equality-assisted evaluation");
        let equality_structural = equality_zero_premise_impl
            .find("equal_fact_sides_are_equal_by_terminating_reduction_and_congruence")
            .expect("zero-premise equality must finish with terminating congruence");
        assert!(equality_known < equality_evaluation);
        assert!(equality_evaluation < equality_known_evaluation);
        assert!(equality_known_evaluation < equality_structural);

        let equality_direct_evaluation_impl = equality
            .split("pub(crate) fn verify_equal_fact_by_direct_evaluation(")
            .nth(1)
            .expect("equality owner must define direct evaluation")
            .split("pub(crate) fn verify_equal_fact_with_one_premise_producing_builtin_rule(")
            .next()
            .expect("premise-producing equality rules must follow direct evaluation");
        assert!(!equality_direct_evaluation_impl.contains("UseBuiltinRuleVerifyState"));
        assert!(!equality_direct_evaluation_impl.contains("verify_builtin_rule_premise"));

        let non_equational = include_str!("verify_non_equational_atomic_fact.rs");
        let non_equational_direct = non_equational
            .split("pub(crate) fn verify_non_equational_atomic_fact_with_direct_routes(")
            .nth(1)
            .expect("non-equational owner must expose a direct route")
            .split(
                "pub(crate) fn verify_non_equational_atomic_fact_with_zero_premise_verification(",
            )
            .next()
            .expect("zero-premise verification must follow the non-equational direct route");
        let non_equational_zero_premise = non_equational_direct
            .find("verify_non_equational_atomic_fact_with_zero_premise_verification")
            .expect("non-equational direct route must begin with zero-premise verification");
        let non_equational_builtin = non_equational_direct
            .find("verify_non_equational_atomic_fact_with_one_premise_producing_builtin_rule")
            .expect("non-equational direct route must finish with one premise-producing rule");
        assert!(non_equational_zero_premise < non_equational_builtin);

        let zero_premise_impl = non_equational
            .split(
                "pub(crate) fn verify_non_equational_atomic_fact_with_zero_premise_verification(",
            )
            .nth(1)
            .expect("non-equational owner must define zero-premise verification")
            .split("pub(crate) fn verify_non_equational_atomic_fact_by_direct_evaluation(")
            .next()
            .expect("direct evaluation must follow zero-premise verification");
        let known_index = zero_premise_impl
            .find("verify_non_equational_atomic_fact_with_known_atomic_facts(atomic_fact)")
            .expect("zero-premise verification must try known facts first");
        let evaluation_index = zero_premise_impl
            .find("verify_non_equational_atomic_fact_by_direct_evaluation(atomic_fact)")
            .expect("zero-premise verification must finish with direct evaluation");
        assert!(known_index < evaluation_index);

        let direct_evaluation_impl = non_equational
            .split("pub(crate) fn verify_non_equational_atomic_fact_by_direct_evaluation(")
            .nth(1)
            .expect("non-equational owner must define direct evaluation")
            .split(
                "pub(crate) fn verify_non_equational_atomic_fact_with_one_premise_producing_builtin_rule(",
            )
            .next()
            .expect("premise-producing rules must follow direct evaluation");
        assert!(!direct_evaluation_impl.contains("UseBuiltinRuleVerifyState"));
        assert!(!direct_evaluation_impl.contains("verify_builtin_rule_premise"));

        let strategy = include_str!("verify_builtin_strategy.rs");
        let child_dispatch = strategy
            .split("pub(crate) fn verify_builtin_strategy_child(")
            .nth(1)
            .expect("strategy child dispatcher must exist")
            .split("pub(crate) fn verify_atomic_fact_with_builtin_strategy(")
            .next()
            .expect("top-level strategy dispatcher must follow its child dispatcher");
        assert_eq!(child_dispatch.matches("match atomic_fact").count(), 1);
        assert!(child_dispatch.contains("verify_equal_fact_with_direct_routes"));
        assert!(child_dispatch.contains("verify_non_equational_atomic_fact_with_direct_routes"));

        let known_forall = include_str!("verify_atomic_fact_with_known_forall.rs");
        let forward = known_forall
            .split("fn verify_atomic_fact_with_known_forall_forward(")
            .nth(1)
            .expect("known-forall forward matcher must be shared")
            .split("fn get_matched_atomic_fact_in_fallback_known_forall_fact_in_envs(")
            .next()
            .expect("known-forall lookup must follow the shared matcher");
        assert!(!forward.contains("fact_with_reversed_args"));
        let equality_wrapper = known_forall
            .split("pub(crate) fn verify_equal_fact_with_known_forall(")
            .nth(1)
            .expect("equality must own reverse known-forall retry")
            .split("fn verify_atomic_fact_with_known_forall_forward(")
            .next()
            .expect("shared forward matcher must follow the equality wrapper");
        assert!(equality_wrapper.contains("fact_with_reversed_args"));
    }

    #[test]
    fn structural_equality_uses_one_shape_matcher_only_in_structural_routes() {
        let equality_structural = include_str!("verify_builtin_rules/equality_structural.rs");
        let known_without_evaluation_impl = equality_structural
            .split("pub(crate) fn verify_equal_fact_by_known_equality_without_direct_evaluation(")
            .nth(1)
            .expect("equality must expose a known-only leaf without direct evaluation")
            .split("fn verify_equal_fact_directly_known_only(")
            .next()
            .expect("the direct known-only implementation must follow its memoized entry");
        assert!(!known_without_evaluation_impl
            .contains("two_objs_can_be_calculated_and_equal_by_calculation"));
        let known_only_impl = equality_structural
            .split("pub fn verify_equal_fact_by_known_equality(")
            .nth(1)
            .expect("known-only equality implementation must exist")
            .split("fn verify_equal_fact_directly_known_only(")
            .next()
            .expect("direct known-only implementation must follow the public entry");
        assert!(known_only_impl.contains("verify_equal_fact_directly_known_only("));
        assert!(!known_only_impl.contains("same_shape_and_corresponding_args_match("));
        assert!(
            !equality_structural.contains("try_verify_equality_by_corresponding_known_equalities")
        );
        let direct_known_only_impl = equality_structural
            .split("fn verify_equal_fact_directly_known_only(")
            .nth(1)
            .expect("direct known-only equality implementation must exist")
            .split("pub(crate) fn equal_fact_sides_are_congruent_by_known_equalities(")
            .next()
            .expect("known congruence must follow direct known-only equality");
        assert!(!direct_known_only_impl.contains("resolve_obj"));
        assert!(
            !direct_known_only_impl.contains("two_objs_can_be_calculated_and_equal_by_calculation")
        );
        assert_eq!(
            equality_structural
                .matches("fn same_shape_and_corresponding_args_match")
                .count(),
            1,
            "constructor decomposition must have one implementation",
        );
        let terminating_impl = equality_structural
            .split(
                "pub(crate) fn equal_fact_sides_are_equal_by_terminating_reduction_and_congruence(",
            )
            .nth(1)
            .expect("terminating structural equality implementation must exist")
            .split("pub(crate) fn same_shape_and_corresponding_args_match")
            .next()
            .expect("central matcher must follow terminating comparison");
        let known_index = terminating_impl
            .find("verify_equal_fact_with_known_fact(equal_fact)")
            .expect("terminating comparison must try known equality first");
        let evaluation_index = terminating_impl
            .find("verify_equal_fact_by_direct_evaluation(equal_fact)")
            .expect("terminating comparison must try direct evaluation second");
        let shape_index = terminating_impl
            .find("same_shape_and_corresponding_args_match(")
            .expect("terminating comparison must finish with constructor descent");
        assert!(known_index < evaluation_index);
        assert!(evaluation_index < shape_index);
        assert!(terminating_impl.contains("same_shape_and_corresponding_args_match("));
        assert!(!terminating_impl.contains("verify_equal_fact_with_zero_premise_verification"));

        let equality_dispatch = include_str!("verify_builtin_rules/equality_dispatch.rs");
        assert!(
            !equality_dispatch.contains("try_verify_equality_by_corresponding_known_equalities")
        );
        assert!(!equality_dispatch.contains("verify_equal_fact_by_direct_evaluation"));
        assert!(!equality_dispatch.contains("objs_match_for_pattern_and_calculation"));

        let equality = include_str!("verify_equality.rs");
        let full_equality_impl = equality
            .split("pub fn verify_equal_fact(")
            .nth(1)
            .expect("full equality implementation must exist")
            .split("fn verify_equality_after_one_checked_definition_reduction(")
            .next()
            .expect("direct checked-definition reduction must follow full equality");
        assert!(!full_equality_impl.contains("FnEqualFact"));
        assert!(!full_equality_impl.contains("EqualFact::new("));
        let round_zero_index = full_equality_impl
            .find("if verify_state.is_round_0()")
            .expect("structural equality must be restricted to round zero");
        let structural_index = full_equality_impl
            .find(
                "verify_equal_fact_when_both_sides_have_same_builtin_shape_and_equal_args_recursively",
            )
            .expect("full equality must contain the structural equality route");
        assert!(round_zero_index < structural_index);
        let recursive_structural_impl = equality
            .split(
                "pub(crate) fn verify_equal_fact_when_both_sides_have_same_builtin_shape_and_equal_args_recursively(",
            )
            .nth(1)
            .expect("recursive structural equality implementation must exist")
            .split("fn verify_equal_fact_by_builtin_rules_and_known_equalities(")
            .next()
            .expect("recursive child verifier must follow structural equality");
        assert!(recursive_structural_impl.contains("same_shape_and_corresponding_args_match("));
    }

    #[test]
    fn equality_proof_apis_receive_the_owned_equal_fact() {
        // These helpers own, forward, or decide one equality proof obligation even when their
        // historical names do not contain `equal`. Keeping the complete fact preserves source
        // identity and prevents left/right orientation plus LineFile from drifting independently.
        let owned_equality_target_apis = [
            "try_verify_matrix_power_definition",
            "try_verify_finite_set_size_fn_range_from_known_injection",
            "try_verify_finite_set_size_from_known_bijection",
            "try_trig_quotient_definition",
            "verify_reduce_functions_pointwise_on_set",
            "verify_zero_product_factor_matches_target",
            "try_verify_sum_merge_ordered_pair",
            "verify_finite_set_sum_functions_pointwise_premise",
            "try_verify_intersection_from_subset",
            "try_verify_literal_set_intersection_filter",
            "try_verify_one_subtraction_from_known_addition",
            "try_verify_product_from_known_division_candidate",
            "equality_builtin_match_subgoals",
            "collect_nested_equality_transport_steps",
        ];
        let mut explicitly_checked = vec![false; owned_equality_target_apis.len()];
        visit_rust_files(Path::new("src/verify"), &mut |path, source| {
            for function_tail in source.split("fn ").skip(1) {
                let Some((header, _)) = function_tail.split_once('{') else {
                    continue;
                };
                let Some((name, _)) = header.split_once('(') else {
                    continue;
                };
                let name = name.trim();
                let explicitly_owned = owned_equality_target_apis
                    .iter()
                    .position(|candidate| *candidate == name);
                if let Some(index) = explicitly_owned {
                    explicitly_checked[index] = true;
                }
                let returns_equality_proof_result = (header.contains("-> StmtResult")
                    || header.contains("Option<StmtResult>"))
                    && !header.contains("Vec<StmtResult>");
                let equality_named_proof_api = (name.contains("equal")
                    || name.contains("equality"))
                    && !name.contains("not_equal")
                    && !name.contains("less_equal")
                    && !name.contains("greater_equal")
                    && !name.contains("non_equational")
                    && returns_equality_proof_result;
                if !equality_named_proof_api && explicitly_owned.is_none() {
                    continue;
                }
                assert!(
                    header.contains("&EqualFact"),
                    "equality proof API `{name}` in {} must receive the complete EqualFact",
                    path.display(),
                );
            }
        });
        for (name, found) in owned_equality_target_apis
            .iter()
            .zip(explicitly_checked.iter())
        {
            assert!(
                *found,
                "owned equality target API `{name}` must remain audited"
            );
        }

        let equality = include_str!("verify_equality.rs");
        let known_fact_impl = equality
            .split("pub(crate) fn verify_equal_fact_with_known_fact(")
            .nth(1)
            .expect("known-equality implementation must exist")
            .split("pub(crate) fn verify_equal_fact_with_zero_premise_verification(")
            .next()
            .expect("zero-premise verification must follow known equality");
        assert!(known_fact_impl
            .contains("verify_equal_fact_by_known_equality_without_direct_evaluation(equal_fact)"));
        assert!(!known_fact_impl.contains("EqualFact::new"));
        assert!(equality.contains(
            "fn verify_equal_fact_when_both_sides_have_same_builtin_shape_and_equal_args_recursively(\n        &mut self,\n        equal_fact: &EqualFact,"
        ));
        let structural = include_str!("verify_builtin_rules/equality_structural.rs");
        assert!(structural.contains(
            "pub fn verify_equal_fact_as_builtin_premise(\n        &mut self,\n        equal_fact: &EqualFact,"
        ));
        let dispatcher = include_str!("verify_builtin_rules/equality_dispatch.rs");
        assert!(dispatcher.contains(
            "pub fn verify_equal_fact_by_builtin_rules(\n        &mut self,\n        equal_fact: &EqualFact,"
        ));
    }

    fn visit_rust_files(dir: &Path, f: &mut impl FnMut(&Path, &str)) {
        for entry in fs::read_dir(dir).expect("read builtin rule source directory") {
            let path = entry.expect("read builtin rule directory entry").path();
            if path.is_dir() {
                visit_rust_files(&path, f);
            } else if path.extension().and_then(|value| value.to_str()) == Some("rs") {
                let source = fs::read_to_string(&path).expect("read builtin rule source file");
                f(&path, &source);
            }
        }
    }
}
