#!/usr/bin/env python3
"""Generate the paired Litex local-builtin and Lean-adapter manifests."""

from __future__ import annotations

import argparse
import hashlib
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CATALOG_ROOT = ROOT / "src/verify/local_builtin_catalog"
ADAPTER_ROOT = ROOT / "src/compile_to_lean/local_builtin_adapters"
GENERATED_CATALOG = CATALOG_ROOT / "generated_catalog.rs"
GENERATED_MANIFEST = ADAPTER_ROOT / "generated_manifest.rs"
GENERATED_LEAN = ADAPTER_ROOT / "generated_all.lean"

RULE_PART = re.compile(r"[a-z][a-z0-9_]*\Z")
THEOREM_DECL = re.compile(r"(?m)^\s*theorem\s+([A-Za-z_][A-Za-z0-9_]*)\b")
FORBIDDEN_LEAN = re.compile(
    r"(?m)^\s*(?:import|namespace|section|end|axiom|opaque|unsafe|set_option)\b"
    r"|\b(?:sorry|admit)\b"
)
FORBIDDEN_LITEX = re.compile(
    r"(?m)^\s*(?:trust|axiom|theorem|claim|prop|have|import|use)\b"
)


@dataclass(frozen=True)
class RulePair:
    relative: Path
    rule_id: str
    theorem_name: str
    fingerprint: str
    litex_source: str
    lean_source: str


def schema_fingerprint(source: str) -> str:
    """Whitespace-insensitive v1 fingerprint; runtime rechecks parsed semantics."""

    canonical = " ".join(source.split())
    return hashlib.sha256(("litex-local-schema-v1\0" + canonical).encode()).hexdigest()


def path_identity(relative: Path) -> tuple[str, str]:
    parts = relative.with_suffix("").parts
    if not parts or any(RULE_PART.fullmatch(part) is None for part in parts):
        raise ValueError(
            f"invalid local builtin path {relative}; use lowercase snake_case components"
        )
    return ".".join(parts), "_".join(parts)


def validate_litex(path: Path, source: str) -> None:
    nonempty = [line.strip() for line in source.splitlines() if line.strip()]
    if not nonempty or not nonempty[0].startswith("forall "):
        raise ValueError(f"{path}: schema must start with exactly one forall")
    if sum(line.startswith("forall ") for line in nonempty) != 1:
        raise ValueError(f"{path}: schema must contain exactly one forall")
    if FORBIDDEN_LITEX.search(source):
        raise ValueError(f"{path}: local schemas cannot execute declarations or trust")


def validate_lean(path: Path, source: str, expected_theorem: str) -> None:
    if FORBIDDEN_LEAN.search(source):
        raise ValueError(f"{path}: adapter fragments may contain only a checked theorem")
    declarations = THEOREM_DECL.findall(source)
    if declarations != [expected_theorem]:
        raise ValueError(
            f"{path}: expected exactly `theorem {expected_theorem}`, got {declarations}"
        )


def load_pairs() -> list[RulePair]:
    litex_paths = sorted(CATALOG_ROOT.rglob("*.lit"))
    lean_paths = sorted(ADAPTER_ROOT.rglob("*.lean"))
    lean_relatives = {
        path.relative_to(ADAPTER_ROOT).with_suffix("")
        for path in lean_paths
        if path.name != GENERATED_LEAN.name
    }
    litex_relatives = {
        path.relative_to(CATALOG_ROOT).with_suffix("") for path in litex_paths
    }
    missing_lean = sorted(litex_relatives - lean_relatives)
    missing_litex = sorted(lean_relatives - litex_relatives)
    if missing_lean or missing_litex:
        raise ValueError(
            "unpaired local builtin sources: "
            f"missing Lean={missing_lean}, missing Litex={missing_litex}"
        )

    pairs: list[RulePair] = []
    seen_ids: set[str] = set()
    seen_fingerprints: set[str] = set()
    for relative in sorted(litex_relatives):
        rule_id, theorem_name = path_identity(relative)
        litex_path = (CATALOG_ROOT / relative).with_suffix(".lit")
        lean_path = ADAPTER_ROOT / relative.with_suffix(".lean")
        litex_source = litex_path.read_text()
        lean_source = lean_path.read_text()
        validate_litex(litex_path, litex_source)
        validate_lean(lean_path, lean_source, theorem_name)
        fingerprint = schema_fingerprint(litex_source)
        if rule_id in seen_ids:
            raise ValueError(f"duplicate RuleId {rule_id}")
        if fingerprint in seen_fingerprints:
            raise ValueError(f"duplicate semantic schema fingerprint {fingerprint}")
        seen_ids.add(rule_id)
        seen_fingerprints.add(fingerprint)
        pairs.append(
            RulePair(
                relative=relative,
                rule_id=rule_id,
                theorem_name=theorem_name,
                fingerprint=fingerprint,
                litex_source=litex_source,
                lean_source=lean_source,
            )
        )
    return pairs


def rust_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generated_catalog(pairs: list[RulePair]) -> str:
    lines = [
        "// @generated by src/compile_to_lean/generate_local_builtin_catalog.py; do not edit.",
        "pub(super) const GENERATED_LOCAL_BUILTIN_RULES: &[GeneratedLocalBuiltinRuleSource] = &[",
    ]
    for pair in pairs:
        include_path = pair.relative.with_suffix(".lit").as_posix()
        lines.extend(
            [
                "    GeneratedLocalBuiltinRuleSource {",
                f"        id: {rust_string(pair.rule_id)},",
                f"        semantic_fingerprint: {rust_string(pair.fingerprint)},",
                f"        litex_source: include_str!({rust_string(include_path)}),",
                f"        lean_theorem_name: {rust_string(pair.theorem_name)},",
                "    },",
            ]
        )
    lines.extend(["];", ""])
    return "\n".join(lines)


def generated_manifest(pairs: list[RulePair]) -> str:
    lines = [
        "// @generated by src/compile_to_lean/generate_local_builtin_catalog.py; do not edit.",
        "pub(super) const GENERATED_LOCAL_BUILTIN_ADAPTERS: &[GeneratedLocalBuiltinAdapterSource] = &[",
    ]
    for pair in pairs:
        include_path = pair.relative.with_suffix(".lean").as_posix()
        lines.extend(
            [
                "    GeneratedLocalBuiltinAdapterSource {",
                f"        id: {rust_string(pair.rule_id)},",
                f"        semantic_fingerprint: {rust_string(pair.fingerprint)},",
                f"        theorem_name: {rust_string(pair.theorem_name)},",
                f"        lean_source: include_str!({rust_string(include_path)}),",
                "    },",
            ]
        )
    lines.extend(["];", ""])
    return "\n".join(lines)


def generated_lean(pairs: list[RulePair]) -> str:
    chunks = [
        "-- @generated by src/compile_to_lean/generate_local_builtin_catalog.py; do not edit.",
        "import Mathlib",
        "",
        "namespace Litex.BuiltinRules",
        "",
    ]
    for pair in pairs:
        chunks.append(pair.lean_source.rstrip())
        chunks.append("")
    chunks.extend(["end Litex.BuiltinRules", ""])
    return "\n".join(chunks)


def outputs(pairs: list[RulePair]) -> dict[Path, str]:
    return {
        GENERATED_CATALOG: generated_catalog(pairs),
        GENERATED_MANIFEST: generated_manifest(pairs),
        GENERATED_LEAN: generated_lean(pairs),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    pairs = load_pairs()
    generated = outputs(pairs)
    if args.write:
        for path, source in generated.items():
            path.write_text(source)
        print(f"wrote local builtin catalog with {len(pairs)} paired rules")
        return 0

    stale = [path.relative_to(ROOT) for path, source in generated.items() if not path.exists() or path.read_text() != source]
    if stale:
        print(f"local builtin catalog is stale: {', '.join(map(str, stale))}")
        return 1
    print(f"checked local builtin catalog with {len(pairs)} paired rules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
