//! Surface syntax for `by …` proof statements (one submodule per form).
mod cases;
mod commutative_prop;
mod contra;
mod enumerate;
mod extension;
mod family;
mod fn_cart_tuple;
mod for_stmt;
mod induc;
mod transitive_prop;
pub use cases::ByCasesStmt;
pub use commutative_prop::ByCommutativePropStmt;
pub use contra::ByContraStmt;
pub use enumerate::ByEnumerateFiniteSetStmt;
pub use extension::ByExtensionStmt;
pub use family::ByFamilyAsSetStmt;
pub use fn_cart_tuple::{ByFnAsSetStmt, ByFnSetAsSetStmt, ByTupleAsSetStmt};
pub use for_stmt::{ByForExpansion, ByForStmt, ClosedRangeOrRange};
pub use induc::ByInducStmt;
pub use transitive_prop::ByTransitivePropStmt;
