//! Surface syntax for `by …` proof statements (one submodule per form).
mod antisymmetric_prop;
mod axiom_of_choice;
mod cases;
mod contra;
mod enumerate;
mod extension;
mod finite_set_induc;
mod for_stmt;
mod induc;
mod range;
mod reflexive_prop;
mod regularity_axiom;
mod symmetric_prop;
mod thm;
mod transitive_prop;
mod zorn_lemma;
pub use antisymmetric_prop::ByAntisymmetricPropStmt;
pub use axiom_of_choice::ByAxiomOfChoiceStmt;
pub use cases::ByCasesStmt;
pub use contra::ByContraStmt;
pub use enumerate::ByEnumerateFiniteSetStmt;
pub use extension::ByExtensionStmt;
pub use finite_set_induc::ByFiniteSetInducStmt;
pub use for_stmt::{ByForExpansion, ByForStmt, ClosedRangeOrRange};
pub use induc::ByInducStmt;
pub use range::{ByClosedRangeAsCasesStmt, ByEnumerateRangeStmt};
pub use reflexive_prop::ByReflexivePropStmt;
pub use regularity_axiom::ByRegularityAxiomStmt;
pub use symmetric_prop::BySymmetricPropStmt;
pub use thm::ByThmStmt;
pub use transitive_prop::ByTransitivePropStmt;
pub use zorn_lemma::ByZornLemmaStmt;
