-- @generated by src/to_lean/generate_local_builtin_catalog.py; do not edit.
import Mathlib

namespace Litex.BuiltinRules

theorem algebra_abs_mul
    (x y : ℝ)
    (_hxR : x ∈ (Set.univ : Set ℝ))
    (_hyR : y ∈ (Set.univ : Set ℝ)) : |x * y| = |x| * |y| := by
  exact abs_mul x y

theorem nonzero_div
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (ha : a ≠ 0)
    (hb : b ≠ 0) : a / b ≠ 0 := by
  exact div_ne_zero ha hb

theorem nonzero_mul
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (ha : a ≠ 0)
    (hb : b ≠ 0) : a * b ≠ 0 := by
  exact mul_ne_zero ha hb

theorem order_abs_add_le
    (x y : ℝ)
    (_hxR : x ∈ (Set.univ : Set ℝ))
    (_hyR : y ∈ (Set.univ : Set ℝ)) : |x + y| ≤ |x| + |y| := by
  exact abs_add_le x y

theorem order_abs_eq_neg_of_nonpositive
    (x : ℝ)
    (_hxR : x ∈ (Set.univ : Set ℝ))
    (hx : x ≤ 0) : |x| = (-1 : ℝ) * x := by
  simpa using abs_of_nonpos hx

theorem order_abs_eq_self_of_nonnegative
    (x : ℝ)
    (_hxR : x ∈ (Set.univ : Set ℝ))
    (hx : 0 ≤ x) : |x| = x := by
  exact abs_of_nonneg hx

theorem order_abs_nonnegative
    (x : ℝ)
    (_hxR : x ∈ (Set.univ : Set ℝ)) : 0 ≤ |x| := by
  exact abs_nonneg x

theorem order_abs_positive_of_nonzero
    (x : ℝ)
    (_hxR : x ∈ (Set.univ : Set ℝ))
    (hx : x ≠ 0) : 0 < |x| := by
  exact abs_pos.mpr hx

theorem order_abs_sub_abs_le_abs_add
    (x y : ℝ)
    (_hxR : x ∈ (Set.univ : Set ℝ))
    (_hyR : y ∈ (Set.univ : Set ℝ)) : |x| - |y| ≤ |x + y| := by
  simpa using abs_sub_abs_le_abs_sub x (-y)

theorem order_abs_sub_abs_le_abs_sub
    (x y : ℝ)
    (_hxR : x ∈ (Set.univ : Set ℝ))
    (_hyR : y ∈ (Set.univ : Set ℝ)) : |x| - |y| ≤ |x - y| := by
  exact abs_sub_abs_le_abs_sub x y

theorem order_abs_sub_le_sum
    (x y : ℝ)
    (_hxR : x ∈ (Set.univ : Set ℝ))
    (_hyR : y ∈ (Set.univ : Set ℝ)) : |x - y| ≤ |x| + |y| := by
  simpa using abs_sub_le x 0 y

theorem order_add_le_add
    (a b c d : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (_hcR : c ∈ (Set.univ : Set ℝ))
    (_hdR : d ∈ (Set.univ : Set ℝ))
    (hab : a ≤ b)
    (hcd : c ≤ d) : a + c ≤ b + d := by
  exact add_le_add hab hcd

theorem order_add_le_add_left
    (u a b : ℝ)
    (_huR : u ∈ (Set.univ : Set ℝ))
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (h : a ≤ b) : u + a ≤ u + b := by
  linarith only [h]

theorem order_add_lt_add
    (a b c d : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (_hcR : c ∈ (Set.univ : Set ℝ))
    (_hdR : d ∈ (Set.univ : Set ℝ))
    (hab : a < b)
    (hcd : c < d) : a + c < b + d := by
  exact add_lt_add hab hcd

theorem order_add_lt_add_left
    (u a b : ℝ)
    (_huR : u ∈ (Set.univ : Set ℝ))
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (h : a < b) : u + a < u + b := by
  linarith only [h]

theorem order_add_lt_add_of_le_of_lt
    (a b c d : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (_hcR : c ∈ (Set.univ : Set ℝ))
    (_hdR : d ∈ (Set.univ : Set ℝ))
    (hab : a ≤ b)
    (hcd : c < d) : a + c < b + d := by
  exact add_lt_add_of_le_of_lt hab hcd

theorem order_add_lt_add_of_lt_of_le
    (a b c d : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (_hcR : c ∈ (Set.univ : Set ℝ))
    (_hdR : d ∈ (Set.univ : Set ℝ))
    (hab : a < b)
    (hcd : c ≤ d) : a + c < b + d := by
  exact add_lt_add_of_lt_of_le hab hcd

theorem order_add_nonnegative
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (ha : 0 ≤ a)
    (hb : 0 ≤ b) : 0 ≤ a + b := by
  exact add_nonneg ha hb

theorem order_add_positive
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (ha : 0 < a)
    (hb : 0 < b) : 0 < a + b := by
  exact add_pos ha hb

theorem order_add_positive_of_nonnegative_positive
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (ha : 0 ≤ a)
    (hb : 0 < b) : 0 < a + b := by
  exact add_pos_of_nonneg_of_pos ha hb

theorem order_add_positive_of_positive_nonnegative
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (ha : 0 < a)
    (hb : 0 ≤ b) : 0 < a + b := by
  exact add_pos_of_pos_of_nonneg ha hb

theorem order_div_nonnegative
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (ha : 0 ≤ a)
    (hb : 0 < b) : 0 ≤ a / b := by
  exact div_nonneg ha (le_of_lt hb)

theorem order_div_positive
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (ha : 0 < a)
    (hb : 0 < b) : 0 < a / b := by
  exact div_pos ha hb

theorem order_greater_equal_of_greater
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (h : a > b) : a ≥ b := by
  exact le_of_lt h

theorem order_le_add_of_nonnegative_right
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (hb : 0 ≤ b) : a ≤ a + b := by
  linarith only [hb]

theorem order_le_max_left
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ)) : a ≤ max a b := by
  exact le_max_left a b

theorem order_le_max_right
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ)) : b ≤ max a b := by
  exact le_max_right a b

theorem order_less_equal_of_less
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (h : a < b) : a ≤ b := by
  exact le_of_lt h

theorem order_max_absorb_min_left
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ)) : max a (min a b) = a := by
  exact max_eq_left (min_le_left a b)

theorem order_max_associative
    (a b c : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (_hcR : c ∈ (Set.univ : Set ℝ)) :
    max (max a b) c = max a (max b c) := by
  exact max_assoc a b c

theorem order_max_commutative
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ)) : max a b = max b a := by
  exact max_comm a b

theorem order_max_eq_left_of_le
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (h : b ≤ a) : max a b = a := by
  exact max_eq_left h

theorem order_max_eq_right_of_le
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (h : a ≤ b) : max a b = b := by
  exact max_eq_right h

theorem order_max_idempotent
    (a : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ)) : max a a = a := by
  exact max_self a

theorem order_max_monotone
    (a b c d : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (_hcR : c ∈ (Set.univ : Set ℝ))
    (_hdR : d ∈ (Set.univ : Set ℝ))
    (hac : a ≤ c)
    (hbd : b ≤ d) : max a b ≤ max c d := by
  exact max_le_max hac hbd

theorem order_min_absorb_max_left
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ)) : min a (max a b) = a := by
  exact min_eq_left (le_max_left a b)

theorem order_min_associative
    (a b c : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (_hcR : c ∈ (Set.univ : Set ℝ)) :
    min (min a b) c = min a (min b c) := by
  exact min_assoc a b c

theorem order_min_commutative
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ)) : min a b = min b a := by
  exact min_comm a b

theorem order_min_eq_left_of_le
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (h : a ≤ b) : min a b = a := by
  exact min_eq_left h

theorem order_min_eq_right_of_le
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (h : b ≤ a) : min a b = b := by
  exact min_eq_right h

theorem order_min_idempotent
    (a : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ)) : min a a = a := by
  exact min_self a

theorem order_min_le_left
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ)) : min a b ≤ a := by
  exact min_le_left a b

theorem order_min_le_right
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ)) : min a b ≤ b := by
  exact min_le_right a b

theorem order_min_monotone
    (a b c d : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (_hcR : c ∈ (Set.univ : Set ℝ))
    (_hdR : d ∈ (Set.univ : Set ℝ))
    (hac : a ≤ c)
    (hbd : b ≤ d) : min a b ≤ min c d := by
  exact min_le_min hac hbd

theorem order_mul_nonnegative
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (ha : 0 ≤ a)
    (hb : 0 ≤ b) : 0 ≤ a * b := by
  exact mul_nonneg ha hb

theorem order_mul_positive
    (a b : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (ha : 0 < a)
    (hb : 0 < b) : 0 < a * b := by
  exact mul_pos ha hb

theorem order_neg_abs_le
    (x : ℝ)
    (_hxR : x ∈ (Set.univ : Set ℝ)) : (-1 : ℝ) * |x| ≤ x := by
  simpa using neg_abs_le x

theorem order_neg_le_abs
    (x : ℝ)
    (_hxR : x ∈ (Set.univ : Set ℝ)) : (-1 : ℝ) * x ≤ |x| := by
  simpa using neg_le_abs x

theorem order_self_le_abs
    (x : ℝ)
    (_hxR : x ∈ (Set.univ : Set ℝ)) : x ≤ |x| := by
  exact le_abs_self x

theorem order_sub_le_of_le_of_nonnegative
    (a b c : ℝ)
    (_haR : a ∈ (Set.univ : Set ℝ))
    (_hbR : b ∈ (Set.univ : Set ℝ))
    (_hcR : c ∈ (Set.univ : Set ℝ))
    (hab : a ≤ b)
    (hc : 0 ≤ c) : a - c ≤ b := by
  linarith only [hab, hc]

theorem order_sub_nonnegative_of_less_equal
    (u v : ℝ)
    (_huR : u ∈ (Set.univ : Set ℝ))
    (_hvR : v ∈ (Set.univ : Set ℝ))
    (h : v ≤ u) : 0 ≤ u - v := by
  exact sub_nonneg.mpr h

theorem order_sub_positive_of_less
    (u v : ℝ)
    (_huR : u ∈ (Set.univ : Set ℝ))
    (_hvR : v ∈ (Set.univ : Set ℝ))
    (h : v < u) : 0 < u - v := by
  exact sub_pos.mpr h

theorem set_empty_subset
    {α : Type*}
    (A : Set α)
    (_hA : True) : (∅ : Set α) ⊆ A := by
  exact Set.empty_subset A

theorem set_intersect_associative
    {α : Type*}
    (A B C : Set α)
    (_hA : True)
    (_hB : True)
    (_hC : True) : (A ∩ B) ∩ C = A ∩ (B ∩ C) := by
  exact Set.inter_assoc A B C

theorem set_intersect_commutative
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True) : A ∩ B = B ∩ A := by
  exact Set.inter_comm A B

theorem set_intersect_eq_left_of_subset
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True)
    (h : A ⊆ B) : A ∩ B = A := by
  apply Set.Subset.antisymm
  · intro x hx
    exact hx.1
  · intro x hx
    exact ⟨hx, h hx⟩

theorem set_intersect_eq_right_of_subset
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True)
    (h : B ⊆ A) : A ∩ B = B := by
  apply Set.Subset.antisymm
  · intro x hx
    exact hx.2
  · intro x hx
    exact ⟨h hx, hx⟩

theorem set_intersect_finite
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True)
    (hA : A.Finite)
    (_hBFinite : B.Finite) : (A ∩ B).Finite := by
  apply hA.subset
  intro x hx
  exact hx.1

theorem set_intersect_membership
    {α : Type*}
    (A B : Set α)
    (x : α)
    (_hA : True)
    (_hB : True)
    (hxA : x ∈ A)
    (hxB : x ∈ B) : x ∈ A ∩ B := by
  exact ⟨hxA, hxB⟩

theorem set_intersect_subset_left
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True) : A ∩ B ⊆ A := by
  intro x hx
  exact hx.1

theorem set_intersect_subset_right
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True) : A ∩ B ⊆ B := by
  intro x hx
  exact hx.2

theorem set_intersect_union_distributive
    {α : Type*}
    (A B C : Set α)
    (_hA : True)
    (_hB : True)
    (_hC : True) : A ∩ (B ∪ C) = (A ∩ B) ∪ (A ∩ C) := by
  exact Set.inter_union_distrib_left A B C

theorem set_power_set_finite
    {α : Type*}
    (A : Set α)
    (_hA : True)
    (hA : A.Finite) : (Set.powerset A).Finite := by
  exact hA.powerset

theorem set_power_set_membership_of_subset
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True)
    (h : A ⊆ B) : A ∈ Set.powerset B := by
  exact h

theorem set_power_set_nonempty
    {α : Type*}
    (A : Set α)
    (_hA : True) : (Set.powerset A).Nonempty := by
  refine ⟨∅, ?_⟩
  exact Set.empty_subset A

theorem set_set_minus_finite_left
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True)
    (hA : A.Finite) : (A \ B).Finite := by
  apply hA.subset
  intro x hx
  exact hx.1

theorem set_set_minus_infinite_of_infinite_finite
    {α : Type*}
    (X S : Set α)
    (_hX : True)
    (_hS : True)
    (hX : ¬ X.Finite)
    (hS : S.Finite) : ¬ (X \ S).Finite := by
  classical
  intro hDifference
  apply hX
  apply (hDifference.union hS).subset
  intro x hxX
  by_cases hxS : x ∈ S
  · exact Or.inr hxS
  · exact Or.inl ⟨hxX, hxS⟩

theorem set_set_minus_intersect_de_morgan
    {α : Type*}
    (A B C : Set α)
    (_hA : True)
    (_hB : True)
    (_hC : True) : A \ (B ∩ C) = (A \ B) ∪ (A \ C) := by
  exact Set.diff_inter

theorem set_set_minus_membership
    {α : Type*}
    (A B : Set α)
    (x : α)
    (_hA : True)
    (_hB : True)
    (hxA : x ∈ A)
    (hxB : x ∉ B) : x ∈ A \ B := by
  exact ⟨hxA, hxB⟩

theorem set_set_minus_recover_subset
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True)
    (h : B ⊆ A) : A \ (A \ B) = B := by
  classical
  ext x
  constructor
  · intro hx
    by_contra hxB
    exact hx.2 ⟨hx.1, hxB⟩
  · intro hxB
    exact ⟨h hxB, fun hxAB => hxAB.2 hxB⟩

theorem set_set_minus_subset_left
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True) : A \ B ⊆ A := by
  intro x hx
  exact hx.1

theorem set_set_minus_union_de_morgan
    {α : Type*}
    (A B C : Set α)
    (_hA : True)
    (_hB : True)
    (_hC : True) : A \ (B ∪ C) = (A \ B) ∩ (A \ C) := by
  exact (Set.diff_inter_diff (s := A) (t := B) (u := C)).symm

theorem set_subset_eq_set_minus_recovery
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True)
    (h : B ⊆ A) : B = A \ (A \ B) := by
  classical
  ext x
  constructor
  · intro hxB
    exact ⟨h hxB, fun hxAB => hxAB.2 hxB⟩
  · intro hx
    by_contra hxB
    exact hx.2 ⟨hx.1, hxB⟩

theorem set_subset_union_left
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True) : A ⊆ A ∪ B := by
  intro x hx
  exact Or.inl hx

theorem set_subset_union_right
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True) : B ⊆ A ∪ B := by
  intro x hx
  exact Or.inr hx

theorem set_union_associative
    {α : Type*}
    (A B C : Set α)
    (_hA : True)
    (_hB : True)
    (_hC : True) : (A ∪ B) ∪ C = A ∪ (B ∪ C) := by
  exact Set.union_assoc A B C

theorem set_union_commutative
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True) : A ∪ B = B ∪ A := by
  exact Set.union_comm A B

theorem set_union_empty_left
    {α : Type*}
    (A : Set α)
    (_hA : True) : ∅ ∪ A = A := by
  exact Set.empty_union A

theorem set_union_empty_right
    {α : Type*}
    (A : Set α)
    (_hA : True) : A ∪ ∅ = A := by
  exact Set.union_empty A

theorem set_union_finite
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True)
    (hA : A.Finite)
    (hB : B.Finite) : (A ∪ B).Finite := by
  exact hA.union hB

theorem set_union_idempotent
    {α : Type*}
    (A : Set α)
    (_hA : True) : A ∪ A = A := by
  exact Set.union_self A

theorem set_union_membership_left
    {α : Type*}
    (A B : Set α)
    (x : α)
    (_hA : True)
    (_hB : True)
    (hxA : x ∈ A) : x ∈ A ∪ B := by
  exact Set.mem_union_left B hxA

theorem set_union_membership_right
    {α : Type*}
    (A B : Set α)
    (x : α)
    (_hA : True)
    (_hB : True)
    (hxB : x ∈ B) : x ∈ A ∪ B := by
  exact Set.mem_union_right A hxB

theorem set_union_nonempty_left
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True)
    (hA : A.Nonempty) : (A ∪ B).Nonempty := by
  rcases hA with ⟨x, hx⟩
  exact ⟨x, Set.mem_union_left B hx⟩

theorem set_union_nonempty_right
    {α : Type*}
    (A B : Set α)
    (_hA : True)
    (_hB : True)
    (hB : B.Nonempty) : (A ∪ B).Nonempty := by
  rcases hB with ⟨x, hx⟩
  exact ⟨x, Set.mem_union_right A hx⟩

theorem set_union_subset
    {α : Type*}
    (A B S : Set α)
    (_hA : True)
    (_hB : True)
    (_hS : True)
    (hA : A ⊆ S)
    (hB : B ⊆ S) : A ∪ B ⊆ S := by
  exact Set.union_subset hA hB

end Litex.BuiltinRules
