import Mathlib

namespace Litex

universe u

/-- The Lean universe used by the v2 public ABI. This is an abbreviation for
Lean's ordinary `Type u`, not a new universe containing Mathlib. -/
abbrev u := Type u

/-- Version of this deliberately incompatible target ABI. -/
def abiVersion : Nat := 2

/-- An allowlisted family of primitive representation edges. The compiler
owns the instances it imports; a downstream Lean integration can deliberately
register another mathematical representation without changing `Same`. -/
class BridgeRule (α β : Type u) where
  relation : α → β → Prop

/-- One primitive representation step between values with different (or the
same) Lean carriers at one universe level. -/
def Bridge
    {α β : Type u}
    [rule : BridgeRule α β]
    (x : α)
    (y : β) : Prop :=
  rule.relation x y

instance : BridgeRule ℕ ℂ where
  relation n z := z = (n : ℂ)

instance : BridgeRule ℤ ℂ where
  relation z w := w = (z : ℂ)

instance : BridgeRule ℚ ℂ where
  relation q z := z = (q : ℂ)

instance : BridgeRule ℝ ℂ where
  relation r z := z = (r : ℂ)

instance {α : Type u} {predicate : α → Prop} :
    BridgeRule (Subtype predicate) α where
  relation x y := y = x.val

namespace Bridge

theorem natComplex (n : ℕ) : Bridge n (n : ℂ) := by
  rfl

theorem intComplex (z : ℤ) : Bridge z (z : ℂ) := by
  rfl

theorem ratComplex (q : ℚ) : Bridge q (q : ℂ) := by
  rfl

theorem realComplex (r : ℝ) : Bridge r (r : ℂ) := by
  rfl

theorem subtype
    {α : Type u}
    {predicate : α → Prop}
    (x : Subtype predicate) :
    Bridge x x.val := by
  rfl

end Bridge

/-- Litex semantic equality. It is heterogeneous and is generated by explicit
representation bridges, reflexivity, symmetry, and transitivity. -/
inductive Same : {α β : Type u} → α → β → Prop where
  | base
      {α β : Litex.u.{u}}
      {x : α}
      {y : β}
      [BridgeRule α β] :
      Bridge x y → Same x y
  | refl {α : Litex.u.{u}} (x : α) : Same x x
  | symm
      {α β : Litex.u.{u}}
      {x : α}
      {y : β} :
      Same x y → Same y x
  | trans
      {α β γ : Litex.u.{u}}
      {x : α}
      {y : β}
      {z : γ} :
      Same x y → Same y z → Same x z

namespace Same

/-- Native Lean equality is always a valid proof of Litex semantic equality. -/
theorem ofEq {α : Litex.u.{u}} {x y : α} (h : x = y) : Same x y := by
  subst y
  exact .refl x

theorem natComplex (n : ℕ) : Same n (n : ℂ) :=
  .base (.natComplex n)

theorem intComplex (z : ℤ) : Same z (z : ℂ) :=
  .base (.intComplex z)

theorem ratComplex (q : ℚ) : Same q (q : ℂ) :=
  .base (.ratComplex q)

theorem realComplex (r : ℝ) : Same r (r : ℂ) :=
  .base (.realComplex r)

theorem complexNat (n : ℕ) : Same (n : ℂ) n :=
  .symm (natComplex n)

theorem complexInt (z : ℤ) : Same (z : ℂ) z :=
  .symm (intComplex z)

theorem complexRat (q : ℚ) : Same (q : ℂ) q :=
  .symm (ratComplex q)

theorem complexReal (r : ℝ) : Same (r : ℂ) r :=
  .symm (realComplex r)

theorem subtype
    {α : Type u}
    {predicate : α → Prop}
    (x : Subtype predicate) :
    Same x x.val :=
  .base (.subtype x)

end Same

/-- A Litex set is represented by its exact element carrier. The carrier is
the set extension itself; no additional native `Set.univ` value is stored. -/
structure Set where
  Carrier : Litex.u.{u}

namespace Set

/-- Package an exact Lean carrier as a Litex set. -/
abbrev ofType (α : Litex.u.{u}) : Litex.Set.{u} :=
  ⟨α⟩

end Set

/-- Heterogeneous membership: `x` belongs to `set` when it is semantically the
same as one value in the set's exact carrier. -/
def In
    {α : Litex.u.{u}}
    (x : α)
    (set : Litex.Set.{u}) : Prop :=
  ∃ y : set.Carrier, Same.{u} x y

namespace In

/-- Every value of a set's own carrier belongs to that set automatically. -/
theorem own (set : Litex.Set.{u}) (x : set.Carrier) : In x set :=
  ⟨x, .refl x⟩

/-- Membership is invariant under Litex semantic equality. -/
theorem congr
    {α β : Litex.u.{u}}
    {x : α}
    {y : β}
    (h : Same x y)
    (set : Litex.Set.{u}) :
    In x set ↔ In y set := by
  constructor
  · rintro ⟨z, hxz⟩
    exact ⟨z, .trans (.symm h) hxz⟩
  · rintro ⟨z, hyz⟩
    exact ⟨z, .trans h hyz⟩

/-- Select the exact-carrier representative certified by a Litex membership
proof. This is noncomputable because `In` deliberately stores only existence;
it adds no axiom beyond Lean's ordinary classical choice. -/
noncomputable def rep
    {set : Litex.Set.{u}}
    {α : Litex.u.{u}}
    (x : α)
    (hx : In x set) :
    set.Carrier :=
  Classical.choose hx

/-- The representative selected by `rep` remains semantically equal to the
source value. -/
theorem same_rep
    {set : Litex.Set.{u}}
    {α : Litex.u.{u}}
    (x : α)
    (hx : In x set) :
    Same x (rep x hx) :=
  Classical.choose_spec hx

end In

/-- The first compiler2 function carrier: one named unary Litex application
layer. Its argument remains heterogeneous; the function can be called only
with an explicit proof that the argument belongs to `domain`. -/
structure Fn
    (domain codomain : Litex.Set.{u}) where
  call : {α : Litex.u.{u}} → (x : α) → In x domain → codomain.Carrier

/-- The Litex set of unary functions from `domain` to `codomain`.

`Fn domain codomain` lives one universe above the element carriers because its
`call` field accepts values from any carrier in universe `u`. -/
abbrev fnSet
    (domain codomain : Litex.Set.{u}) :
    Litex.Set.{u + 1} :=
  Set.ofType (Fn domain codomain)

/-- Apply a heterogeneous value known to belong to a unary function set.
Both function membership and argument membership are computational inputs to
the wrapper; Lean's ambient type alone never authorizes a Litex call. -/
noncomputable def fnApply
    {domain codomain : Litex.Set.{u}}
    {α : Litex.u.{u}}
    {β : Litex.u.{u + 1}}
    (f : β)
    (hf : In f (fnSet domain codomain))
    (x : α)
    (hx : In x domain) :
    codomain.Carrier :=
  (In.rep f hf).call x hx

abbrev N : Litex.Set := Set.ofType ℕ
abbrev Z : Litex.Set := Set.ofType ℤ
abbrev Q : Litex.Set := Set.ofType ℚ
abbrev R : Litex.Set := Set.ofType ℝ
abbrev C : Litex.Set := Set.ofType ℂ

/-- A predicate-defined Litex subset. Its exact carrier is the corresponding
subtype, and `Bridge.subtype` relates each member to its base value. -/
def setBuilder
    (base : Litex.Set.{u})
    (predicate : base.Carrier → Prop) :
    Litex.Set.{u} :=
  Set.ofType (Subtype predicate)

/-!
The ordered-numeric layer deliberately lives at Lean universe `0`: Mathlib's
native `ℕ`, `ℤ`, `ℚ`, `ℝ`, and `ℂ` all live there. This does not restrict the
universe-polymorphic `Litex.Set`, `Litex.In`, or `Litex.Same` interfaces.

An open `BridgeRule` registry can contain an incoherent user extension. Facts
which only transport a chosen real representative need no global assumption.
Facts which compare two representatives of the same object explicitly require
`RealCoherence`. Supplying that certificate after installing an unsound bridge
is therefore a visible trust decision, rather than a hidden axiom of the ABI.
-/

/-- `x` has the real representative `r` when Litex semantic equality relates
the (possibly differently typed) value `x` to the native Mathlib real `r`. -/
def AsReal {α : Type} (x : α) (r : ℝ) : Prop :=
  Same x r

/-- The registry-level invariant needed whenever a proof must identify two
real representatives. The core declares the certificate shape but does not
postulate an inhabitant. -/
class RealCoherence : Prop where
  unique :
    ∀ {α : Type} (x : α) {r s : ℝ},
      AsReal x r → AsReal x s → r = s

namespace AsReal

theorem real (r : ℝ) : AsReal r r :=
  .refl r

theorem complex (r : ℝ) : AsReal (r : ℂ) r :=
  Same.complexReal r

theorem nat (n : ℕ) : AsReal n (n : ℝ) :=
  .trans (Same.natComplex n) (Same.complexReal (n : ℝ))

theorem int (z : ℤ) : AsReal z (z : ℝ) :=
  .trans (Same.intComplex z) (Same.complexReal (z : ℝ))

theorem rat (q : ℚ) : AsReal q (q : ℝ) :=
  .trans (Same.ratComplex q) (Same.complexReal (q : ℝ))

/-- Semantic equality transports a chosen real representative. -/
theorem congr
    {α β : Type}
    {x : α}
    {y : β}
    {r : ℝ}
    (hxy : Same x y) :
    AsReal x r ↔ AsReal y r := by
  constructor
  · intro hxr
    exact .trans (.symm hxy) hxr
  · intro hyr
    exact .trans hxy hyr

/-- Values with the same real representative are semantically equal. -/
theorem same
    {α β : Type}
    {x : α}
    {y : β}
    {r : ℝ}
    (hxr : AsReal x r)
    (hyr : AsReal y r) :
    Same x y :=
  .trans hxr (.symm hyr)

theorem unique
    [RealCoherence]
    {α : Type}
    (x : α)
    {r s : ℝ}
    (hxr : AsReal x r)
    (hxs : AsReal x s) :
    r = s :=
  RealCoherence.unique x hxr hxs

end AsReal

/-- Membership in `R` is exactly existence of a real representative. -/
theorem inR_iff_asReal
    {α : Type}
    {x : α} :
    In x R ↔ ∃ r : ℝ, AsReal x r :=
  Iff.rfl

/-- Heterogeneous strict comparison through native Mathlib reals. -/
def Lt
    {α β : Type}
    (x : α)
    (y : β) : Prop :=
  ∃ r s : ℝ, AsReal x r ∧ AsReal y s ∧ r < s

/-- Heterogeneous non-strict comparison through native Mathlib reals. -/
def Le
    {α β : Type}
    (x : α)
    (y : β) : Prop :=
  ∃ r s : ℝ, AsReal x r ∧ AsReal y s ∧ r ≤ s

namespace Lt

theorem intro
    {α β : Type}
    {x : α}
    {y : β}
    {r s : ℝ}
    (hxr : AsReal x r)
    (hys : AsReal y s)
    (hrs : r < s) :
    Lt x y :=
  ⟨r, s, hxr, hys, hrs⟩

theorem congr
    {α α' β β' : Type}
    {x : α}
    {x' : α'}
    {y : β}
    {y' : β'}
    (hxx' : Same x x')
    (hyy' : Same y y') :
    Lt x y ↔ Lt x' y' := by
  constructor
  · rintro ⟨r, s, hxr, hys, hrs⟩
    exact ⟨r, s,
      (AsReal.congr hxx').mp hxr,
      (AsReal.congr hyy').mp hys,
      hrs⟩
  · rintro ⟨r, s, hxr, hys, hrs⟩
    exact ⟨r, s,
      (AsReal.congr hxx').mpr hxr,
      (AsReal.congr hyy').mpr hys,
      hrs⟩

theorem toLe
    {α β : Type}
    {x : α}
    {y : β}
    (h : Lt x y) :
    Le x y := by
  rcases h with ⟨r, s, hxr, hys, hrs⟩
  exact ⟨r, s, hxr, hys, le_of_lt hrs⟩

theorem irrefl
    [RealCoherence]
    {α : Type}
    (x : α) :
    ¬ Lt x x := by
  rintro ⟨r, s, hxr, hxs, hrs⟩
  have hrsEq : r = s := AsReal.unique x hxr hxs
  subst s
  exact (lt_irrefl r) hrs

theorem trans
    [RealCoherence]
    {α β γ : Type}
    {x : α}
    {y : β}
    {z : γ}
    (hxy : Lt x y)
    (hyz : Lt y z) :
    Lt x z := by
  rcases hxy with ⟨r, s, hxr, hys, hrs⟩
  rcases hyz with ⟨s', t, hys', hzt, hst⟩
  have hss' : s = s' := AsReal.unique y hys hys'
  subst s'
  exact ⟨r, t, hxr, hzt, lt_trans hrs hst⟩

end Lt

namespace Le

theorem intro
    {α β : Type}
    {x : α}
    {y : β}
    {r s : ℝ}
    (hxr : AsReal x r)
    (hys : AsReal y s)
    (hrs : r ≤ s) :
    Le x y :=
  ⟨r, s, hxr, hys, hrs⟩

theorem congr
    {α α' β β' : Type}
    {x : α}
    {x' : α'}
    {y : β}
    {y' : β'}
    (hxx' : Same x x')
    (hyy' : Same y y') :
    Le x y ↔ Le x' y' := by
  constructor
  · rintro ⟨r, s, hxr, hys, hrs⟩
    exact ⟨r, s,
      (AsReal.congr hxx').mp hxr,
      (AsReal.congr hyy').mp hys,
      hrs⟩
  · rintro ⟨r, s, hxr, hys, hrs⟩
    exact ⟨r, s,
      (AsReal.congr hxx').mpr hxr,
      (AsReal.congr hyy').mpr hys,
      hrs⟩

theorem reflOfAsReal
    {α : Type}
    {x : α}
    {r : ℝ}
    (hxr : AsReal x r) :
    Le x x :=
  ⟨r, r, hxr, hxr, le_rfl⟩

theorem reflOfInR
    {α : Type}
    {x : α}
    (hx : In x R) :
    Le x x := by
  rcases inR_iff_asReal.mp hx with ⟨r, hxr⟩
  exact reflOfAsReal hxr

theorem trans
    [RealCoherence]
    {α β γ : Type}
    {x : α}
    {y : β}
    {z : γ}
    (hxy : Le x y)
    (hyz : Le y z) :
    Le x z := by
  rcases hxy with ⟨r, s, hxr, hys, hrs⟩
  rcases hyz with ⟨s', t, hys', hzt, hst⟩
  have hss' : s = s' := AsReal.unique y hys hys'
  subst s'
  exact ⟨r, t, hxr, hzt, le_trans hrs hst⟩

end Le

namespace OrderBridge

/-- A native Mathlib real inequality introduces a Litex inequality without
any global coherence assumption. -/
theorem ltOfReal
    {r s : ℝ}
    (h : r < s) :
    Lt r s :=
  Lt.intro (AsReal.real r) (AsReal.real s) h

theorem leOfReal
    {r s : ℝ}
    (h : r ≤ s) :
    Le r s :=
  Le.intro (AsReal.real r) (AsReal.real s) h

theorem ltOfComplexReals
    {r s : ℝ}
    (h : r < s) :
    Lt (r : ℂ) (s : ℂ) :=
  Lt.intro (AsReal.complex r) (AsReal.complex s) h

theorem leOfComplexReals
    {r s : ℝ}
    (h : r ≤ s) :
    Le (r : ℂ) (s : ℂ) :=
  Le.intro (AsReal.complex r) (AsReal.complex s) h

theorem real_lt_iff
    [RealCoherence]
    {r s : ℝ} :
    Lt r s ↔ r < s := by
  constructor
  · rintro ⟨r', s', hrr', hss', hrs⟩
    have hr : r = r' := AsReal.unique r (AsReal.real r) hrr'
    have hs : s = s' := AsReal.unique s (AsReal.real s) hss'
    simpa [hr, hs] using hrs
  · exact ltOfReal

theorem real_le_iff
    [RealCoherence]
    {r s : ℝ} :
    Le r s ↔ r ≤ s := by
  constructor
  · rintro ⟨r', s', hrr', hss', hrs⟩
    have hr : r = r' := AsReal.unique r (AsReal.real r) hrr'
    have hs : s = s' := AsReal.unique s (AsReal.real s) hss'
    simpa [hr, hs] using hrs
  · exact leOfReal

end OrderBridge

end Litex
