import Mathlib

namespace Litex

universe u v w x y

/-- The Lean universe used by the v2 public ABI. This is an abbreviation for
Lean's ordinary `Type u`, not a new universe containing Mathlib. -/
abbrev u := Type u

/-- Version of this deliberately incompatible target ABI. -/
def abiVersion : Nat := 2

/-- Exact one-element carrier used by finite Litex set literals. The source
value indexes the type itself, so the carrier cannot contain another value. -/
inductive SingletonCarrier {α : Type u} (value : α) : Type u where
  | element
deriving Fintype

/-- Compiler-owned primitive representation edges. This class is private so a
downstream file cannot widen Litex semantic equality by installing an
unreviewed carrier relation. -/
private class PrimitiveRule (α β : Type u) where
  relation : α → β → Prop

/-- One primitive representation step between values with different (or the
same) Lean carriers at one universe level. -/
private def Primitive
    {α β : Type u}
    [rule : PrimitiveRule α β]
    (x : α)
    (y : β) : Prop :=
  rule.relation x y

/-- Closed, compiler-owned congruence edges. Unlike primitive carrier
bridges, these edges may consume an existing `Same` proof. -/
private class DerivedRule (α β : Type u) where
  relation : α → β → Prop

private def Derived
    {α β : Type u}
    [rule : DerivedRule α β]
    (x : α)
    (y : β) : Prop :=
  rule.relation x y

private instance : PrimitiveRule ℕ ℂ where
  relation n z := z = (n : ℂ)

private instance : PrimitiveRule ℤ ℂ where
  relation z w := w = (z : ℂ)

private instance : PrimitiveRule ℚ ℂ where
  relation q z := z = (q : ℂ)

private instance : PrimitiveRule ℝ ℂ where
  relation r z := z = (r : ℂ)

private instance {α : Type u} {predicate : α → Prop} :
    PrimitiveRule (Subtype predicate) α where
  relation x y := y = x.val

namespace Primitive

private theorem natComplex (n : ℕ) : Primitive n (n : ℂ) := by
  rfl

private theorem intComplex (z : ℤ) : Primitive z (z : ℂ) := by
  rfl

private theorem ratComplex (q : ℚ) : Primitive q (q : ℂ) := by
  rfl

private theorem realComplex (r : ℝ) : Primitive r (r : ℂ) := by
  rfl

private theorem subtype
    {α : Type u}
    {predicate : α → Prop}
    (x : Subtype predicate) :
    Primitive x x.val := by
  rfl

end Primitive

/-- Litex semantic equality. It is heterogeneous and is generated by explicit
representation bridges, reflexivity, symmetry, and transitivity. -/
inductive Same : {α β : Type u} → α → β → Prop where
  | base
      {α β : Litex.u.{u}}
      {x : α}
      {y : β}
      [PrimitiveRule α β] :
      Primitive x y → Same x y
  | derived
      {α β : Litex.u.{u}}
      {x : α}
      {y : β}
      [DerivedRule α β] :
      Derived x y → Same x y
  | refl {α : Litex.u.{u}} (x : α) : Same x x
  | singleton
      {α : Litex.u.{u}}
      (value : α) :
      Same value
        (@SingletonCarrier.element.{u} α value : SingletonCarrier.{u} value)
  | sumLeft
      {α β : Litex.u.{u}}
      (value : α) :
      Same value (Sum.inl value : Sum α β)
  | sumRight
      {α β : Litex.u.{u}}
      (value : β) :
      Same value (Sum.inr value : Sum α β)
  | symm
      {α β : Litex.u.{u}}
      {x : α}
      {y : β} :
      Same x y → Same y x
  | trans
      {α β γ : Litex.u.{u}}
      {x : α}
      {y : β}
      {z : γ} :
      Same x y → Same y z → Same x z

/-- The reviewed native real/complex operations whose representation
congruence is part of the compiler ABI. -/
private inductive RealComplexDerived : ℝ → ℂ → Prop where
  | add
      {r s : ℝ}
      {z w : ℂ} :
      Same r z → Same s w → RealComplexDerived (r + s) (z + w)
  | sub
      {r s : ℝ}
      {z w : ℂ} :
      Same r z → Same s w → RealComplexDerived (r - s) (z - w)
  | mul
      {r s : ℝ}
      {z w : ℂ} :
      Same r z → Same s w → RealComplexDerived (r * s) (z * w)
  | div
      {r s : ℝ}
      {z w : ℂ} :
      Same r z → Same s w → RealComplexDerived (r / s) (z / w)

private instance : DerivedRule ℝ ℂ where
  relation := RealComplexDerived

namespace Same

/-- Native Lean equality is always a valid proof of Litex semantic equality. -/
theorem ofEq {α : Litex.u.{u}} {x y : α} (h : x = y) : Same x y := by
  subst y
  exact .refl x

theorem natComplex (n : ℕ) : Same n (n : ℂ) :=
  .base (Primitive.natComplex n)

theorem intComplex (z : ℤ) : Same z (z : ℂ) :=
  .base (Primitive.intComplex z)

theorem ratComplex (q : ℚ) : Same q (q : ℂ) :=
  .base (Primitive.ratComplex q)

theorem realComplex (r : ℝ) : Same r (r : ℂ) :=
  .base (Primitive.realComplex r)

theorem complexNat (n : ℕ) : Same (n : ℂ) n :=
  .symm (natComplex n)

theorem complexInt (z : ℤ) : Same (z : ℂ) z :=
  .symm (intComplex z)

theorem complexRat (q : ℚ) : Same (q : ℂ) q :=
  .symm (ratComplex q)

theorem complexReal (r : ℝ) : Same (r : ℂ) r :=
  .symm (realComplex r)

theorem subtype
    {α : Type u}
    {predicate : α → Prop}
    (x : Subtype predicate) :
    Same x x.val :=
  .base (Primitive.subtype x)

/-- Addition respects the closed real-to-complex representation relation. -/
theorem realAddComplex
    {r s : ℝ}
    {z w : ℂ}
    (hr : Same r z)
    (hs : Same s w) :
    Same (r + s) (z + w) :=
  .derived (RealComplexDerived.add hr hs)

/-- Subtraction respects the closed real-to-complex representation relation. -/
theorem realSubComplex
    {r s : ℝ}
    {z w : ℂ}
    (hr : Same r z)
    (hs : Same s w) :
    Same (r - s) (z - w) :=
  .derived (RealComplexDerived.sub hr hs)

/-- Multiplication respects the closed real-to-complex representation relation. -/
theorem realMulComplex
    {r s : ℝ}
    {z w : ℂ}
    (hr : Same r z)
    (hs : Same s w) :
    Same (r * s) (z * w) :=
  .derived (RealComplexDerived.mul hr hs)

/-- Division respects the closed real-to-complex representation relation.
Mathlib division is total; Litex domain clauses remain separate call
requirements and are not erased by this congruence theorem. -/
theorem realDivComplex
    {r s : ℝ}
    {z w : ℂ}
    (hr : Same r z)
    (hs : Same s w) :
    Same (r / s) (z / w) :=
  .derived (RealComplexDerived.div hr hs)

end Same

/-- A Litex set is represented by its exact element carrier. The carrier is
the set extension itself; no additional native `Set.univ` value is stored. -/
structure Set where
  Carrier : Litex.u.{u}

namespace Set

/-- Package an exact Lean carrier as a Litex set. -/
abbrev ofType (α : Litex.u.{u}) : Litex.Set.{u} :=
  ⟨α⟩

/-- A Litex set is nonempty exactly when its exact carrier is inhabited. -/
def Nonempty (set : Litex.Set.{u}) : Prop :=
  _root_.Nonempty set.Carrier

/-- Finiteness is a property of the exact carrier, not a second cardinality
tag attached to a source set value. -/
def Finite (set : Litex.Set.{u}) : Prop :=
  _root_.Finite set.Carrier

/-- Empty finite Litex set carrier. -/
def empty : Litex.Set :=
  ofType PEmpty

/-- Exact singleton set carrier indexed by its sole source value. -/
def singleton {α : Type u} (value : α) : Litex.Set.{u} :=
  ofType (SingletonCarrier.{u} value)

/-- Exact finite coproduct of two Litex set carriers. This is used instead of
a universal boxed value for heterogeneous finite set literals. -/
def coproduct (left right : Litex.Set.{u}) : Litex.Set.{u} :=
  ofType (Sum left.Carrier right.Carrier)

theorem empty_finite : Finite empty := by
  unfold Finite empty
  infer_instance

theorem singleton_finite {α : Type u} (value : α) : Finite (singleton value) := by
  unfold Finite singleton
  apply _root_.Finite.of_surjective
    (fun _ : PUnit =>
      (@SingletonCarrier.element.{u} α value : SingletonCarrier.{u} value))
  intro singletonValue
  cases singletonValue
  exact ⟨PUnit.unit, rfl⟩

theorem coproduct_finite
    (left right : Litex.Set.{u})
    (hleft : Finite left)
    (hright : Finite right) :
    Finite (coproduct left right) := by
  unfold Finite coproduct at *
  letI : _root_.Finite left.Carrier := hleft
  letI : _root_.Finite right.Carrier := hright
  infer_instance

end Set

/-- Heterogeneous membership: `x` belongs to `set` when it is semantically the
same as one value in the set's exact carrier. -/
def In
    {α : Litex.u.{u}}
    (x : α)
    (set : Litex.Set.{u}) : Prop :=
  ∃ y : set.Carrier, Same.{u} x y

namespace In

/-- Every value of a set's own carrier belongs to that set automatically. -/
theorem own (set : Litex.Set.{u}) (x : set.Carrier) : In x set :=
  ⟨x, .refl x⟩

/-- Membership is invariant under Litex semantic equality. -/
theorem congr
    {α β : Litex.u.{u}}
    {x : α}
    {y : β}
    (h : Same x y)
    (set : Litex.Set.{u}) :
    In x set ↔ In y set := by
  constructor
  · rintro ⟨z, hxz⟩
    exact ⟨z, .trans (.symm h) hxz⟩
  · rintro ⟨z, hyz⟩
    exact ⟨z, .trans h hyz⟩

/-- Select the exact-carrier representative certified by a Litex membership
proof. This is noncomputable because `In` deliberately stores only existence;
it adds no axiom beyond Lean's ordinary classical choice. -/
noncomputable def rep
    {set : Litex.Set.{u}}
    {α : Litex.u.{u}}
    (x : α)
    (hx : In x set) :
    set.Carrier :=
  Classical.choose hx

/-- The representative selected by `rep` remains semantically equal to the
source value. -/
theorem same_rep
    {set : Litex.Set.{u}}
    {α : Litex.u.{u}}
    (x : α)
    (hx : In x set) :
    Same x (rep x hx) :=
  Classical.choose_spec hx

end In

/-- Exact binary union carrier. The two sides remain separately typed and are
joined only by the reviewed `Sum` representation bridges in `Same`. -/
def union (left right : Litex.Set.{u}) : Litex.Set.{u} :=
  Set.coproduct left right

/-- Exact binary intersection carrier: one representative from the left side
together with independently checked membership in the right side. -/
def intersect (left right : Litex.Set.{u}) : Litex.Set.{u} :=
  Set.ofType {value : left.Carrier // In value right}

/-- Exact set-difference carrier: one representative from the left side with
a proof that it is absent from the right side. -/
def setMinus (left right : Litex.Set.{u}) : Litex.Set.{u} :=
  Set.ofType {value : left.Carrier // ¬ In value right}

/-- Extension inclusion between two exact Litex set carriers. The element
carrier remains heterogeneous; a subset proof transports `In` evidence and
does not retype the source value. -/
def Subset (left right : Litex.Set.{u}) : Prop :=
  ∀ {alpha : Litex.u.{u}} (x : alpha), In x left → In x right

/-- A power-set member is represented by its exact membership predicate on
the base carrier. Unlike a carrier of arbitrary `Litex.Set` syntax values,
this representation remains finite when the base carrier is finite. -/
abbrev PowerSubset (base : Litex.Set.{u}) : Type (u + 1) :=
  ULift.{u + 1, u} (base.Carrier → Prop)

def powerSubsetSet
    (base : Litex.Set.{u})
    (predicate : PowerSubset base) : Litex.Set.{u} :=
  Set.ofType {value : base.Carrier // predicate.down value}

def powerSubsetOfSet
    (base subset : Litex.Set.{u}) : PowerSubset base :=
  ULift.up (fun value : base.Carrier => In value subset)

def emptyPowerSubset (base : Litex.Set.{u}) : PowerSubset base :=
  ULift.up (fun _ : base.Carrier => False)

/-- A source set and a native power-subset predicate represent the same
mathematical set exactly when their Litex membership extensions agree. -/
private instance (base : Litex.Set.{u}) :
    DerivedRule (Litex.Set.{u}) (PowerSubset base) where
  relation source predicate :=
    Subset source (powerSubsetSet base predicate) ∧
      Subset (powerSubsetSet base predicate) source

/-- Exact power-set carrier. -/
def powerSet (base : Litex.Set.{u}) : Litex.Set.{u + 1} :=
  Set.ofType (PowerSubset base)

/-- Extensional set equality is the closed set/set derived representation
edge. No other carrier can register or manufacture this relation. -/
private instance : DerivedRule (Litex.Set.{u}) (Litex.Set.{u}) where
  relation left right := Subset left right ∧ Subset right left

namespace Same

theorem setExt
    {left right : Litex.Set.{u}}
    (forward : Subset left right)
    (backward : Subset right left) :
    Same left right := by
  apply Same.derived
  change Subset left right ∧ Subset right left
  exact ⟨forward, backward⟩

end Same

namespace SetRules

theorem inUnionLeft
    {left right : Litex.Set.{u}}
    {alpha : Type u}
    {value : alpha}
    (membership : In value left) :
    In value (union left right) := by
  rcases membership with ⟨representative, same⟩
  exact ⟨Sum.inl representative, Same.trans same (Same.sumLeft representative)⟩

theorem inUnionRight
    {left right : Litex.Set.{u}}
    {alpha : Type u}
    {value : alpha}
    (membership : In value right) :
    In value (union left right) := by
  rcases membership with ⟨representative, same⟩
  exact ⟨Sum.inr representative, Same.trans same (Same.sumRight representative)⟩

theorem unionCases
    {left right : Litex.Set.{u}}
    {alpha : Type u}
    {value : alpha}
    (membership : In value (union left right)) :
    In value left ∨ In value right := by
  rcases membership with ⟨representative, same⟩
  cases representative with
  | inl leftValue =>
      exact Or.inl ⟨leftValue, Same.trans same (Same.symm (Same.sumLeft leftValue))⟩
  | inr rightValue =>
      exact Or.inr ⟨rightValue, Same.trans same (Same.symm (Same.sumRight rightValue))⟩

theorem inIntersect
    {left right : Litex.Set.{u}}
    {alpha : Type u}
    {value : alpha}
    (leftMembership : In value left)
    (rightMembership : In value right) :
    In value (intersect left right) := by
  let representative := In.rep value leftMembership
  have sameRepresentative : Same value representative := In.same_rep value leftMembership
  have representativeInRight : In representative right :=
    (In.congr sameRepresentative right).mp rightMembership
  let exactValue : {value : left.Carrier // In value right} :=
    ⟨representative, representativeInRight⟩
  exact ⟨exactValue, Same.trans sameRepresentative (Same.symm (Same.subtype exactValue))⟩

theorem inLeftOfInIntersect
    {left right : Litex.Set.{u}}
    {alpha : Type u}
    {value : alpha}
    (membership : In value (intersect left right)) :
    In value left := by
  rcases membership with ⟨representative, same⟩
  exact ⟨representative.val, Same.trans same (Same.subtype representative)⟩

theorem inRightOfInIntersect
    {left right : Litex.Set.{u}}
    {alpha : Type u}
    {value : alpha}
    (membership : In value (intersect left right)) :
    In value right := by
  rcases membership with ⟨representative, same⟩
  have sameValue : Same value representative.val :=
    Same.trans same (Same.subtype representative)
  exact (In.congr sameValue right).mpr representative.property

theorem notInIntersectOfNotInLeft
    {left right : Litex.Set.{u}}
    {alpha : Type u}
    {value : alpha}
    (notMember : ¬ In value left) :
    ¬ In value (intersect left right) :=
  fun member => notMember (inLeftOfInIntersect member)

theorem notInIntersectOfNotInRight
    {left right : Litex.Set.{u}}
    {alpha : Type u}
    {value : alpha}
    (notMember : ¬ In value right) :
    ¬ In value (intersect left right) :=
  fun member => notMember (inRightOfInIntersect member)

theorem inSetMinus
    {left right : Litex.Set.{u}}
    {alpha : Type u}
    {value : alpha}
    (leftMembership : In value left)
    (rightNonmembership : ¬ In value right) :
    In value (setMinus left right) := by
  let representative := In.rep value leftMembership
  have sameRepresentative : Same value representative := In.same_rep value leftMembership
  have representativeNotInRight : ¬ In representative right := by
    intro member
    exact rightNonmembership ((In.congr sameRepresentative right).mpr member)
  let exactValue : {value : left.Carrier // ¬ In value right} :=
    ⟨representative, representativeNotInRight⟩
  exact ⟨exactValue, Same.trans sameRepresentative (Same.symm (Same.subtype exactValue))⟩

theorem inLeftOfInSetMinus
    {left right : Litex.Set.{u}}
    {alpha : Type u}
    {value : alpha}
    (membership : In value (setMinus left right)) :
    In value left := by
  rcases membership with ⟨representative, same⟩
  exact ⟨representative.val, Same.trans same (Same.subtype representative)⟩

theorem notInRightOfInSetMinus
    {left right : Litex.Set.{u}}
    {alpha : Type u}
    {value : alpha}
    (membership : In value (setMinus left right)) :
    ¬ In value right := by
  rcases membership with ⟨representative, same⟩
  have sameValue : Same value representative.val :=
    Same.trans same (Same.subtype representative)
  intro rightMembership
  exact representative.property ((In.congr sameValue right).mp rightMembership)

theorem emptySubset (set : Litex.Set.{u}) : Subset Set.empty set := by
  intro _ value membership
  rcases membership with ⟨impossible, _⟩
  exact PEmpty.elim impossible

theorem subsetUnionLeft (left right : Litex.Set.{u}) :
    Subset left (union left right) :=
  fun _ membership => inUnionLeft membership

theorem subsetUnionRight (left right : Litex.Set.{u}) :
    Subset right (union left right) :=
  fun _ membership => inUnionRight membership

theorem unionSubset
    {left right target : Litex.Set.{u}}
    (leftSubset : Subset left target)
    (rightSubset : Subset right target) :
    Subset (union left right) target := by
  intro _ value membership
  rcases unionCases membership with leftMembership | rightMembership
  · exact leftSubset value leftMembership
  · exact rightSubset value rightMembership

theorem intersectSubsetLeft (left right : Litex.Set.{u}) :
    Subset (intersect left right) left :=
  fun _ membership => inLeftOfInIntersect membership

theorem intersectSubsetRight (left right : Litex.Set.{u}) :
    Subset (intersect left right) right :=
  fun _ membership => inRightOfInIntersect membership

theorem setMinusSubsetLeft (left right : Litex.Set.{u}) :
    Subset (setMinus left right) left :=
  fun _ membership => inLeftOfInSetMinus membership

theorem unionFinite
    (left right : Litex.Set.{u})
    (leftFinite : Set.Finite left)
    (rightFinite : Set.Finite right) :
    Set.Finite (union left right) :=
  Set.coproduct_finite left right leftFinite rightFinite

theorem intersectFinite
    (left right : Litex.Set.{u})
    (leftFinite : Set.Finite left) :
    Set.Finite (intersect left right) := by
  unfold Set.Finite intersect at *
  letI : _root_.Finite left.Carrier := leftFinite
  infer_instance

theorem setMinusFiniteLeft
    (left right : Litex.Set.{u})
    (leftFinite : Set.Finite left) :
    Set.Finite (setMinus left right) := by
  unfold Set.Finite setMinus at *
  letI : _root_.Finite left.Carrier := leftFinite
  infer_instance

theorem unionNonemptyLeft
    (left right : Litex.Set.{u})
    (leftNonempty : Set.Nonempty left) :
    Set.Nonempty (union left right) := by
  rcases leftNonempty with ⟨value⟩
  exact ⟨Sum.inl value⟩

theorem unionNonemptyRight
    (left right : Litex.Set.{u})
    (rightNonempty : Set.Nonempty right) :
    Set.Nonempty (union left right) := by
  rcases rightNonempty with ⟨value⟩
  exact ⟨Sum.inr value⟩

theorem subsetSamePowerMember
    {subset base : Litex.Set.{u}}
    (subsetBase : Subset subset base) :
    Same subset (powerSubsetOfSet base subset) := by
  apply Same.derived
  change
    Subset subset
        (powerSubsetSet base (powerSubsetOfSet base subset)) ∧
      Subset
        (powerSubsetSet base (powerSubsetOfSet base subset)) subset
  constructor
  · intro _ value membership
    rcases subsetBase value membership with ⟨baseValue, sameBase⟩
    have baseValueMembership : In baseValue subset :=
      (In.congr sameBase subset).mp membership
    let exactValue : {value : base.Carrier // In value subset} :=
      ⟨baseValue, baseValueMembership⟩
    exact
      ⟨exactValue, Same.trans sameBase (Same.symm (Same.subtype exactValue))⟩
  · intro _ value membership
    rcases membership with ⟨exactValue, sameExact⟩
    have sameValue : Same value exactValue.val :=
      Same.trans sameExact (Same.subtype exactValue)
    exact (In.congr sameValue subset).mpr exactValue.property

theorem inPowerSetOfSubset
    {subset base : Litex.Set.{u}}
    (subsetBase : Subset subset base) :
    In subset (powerSet base) :=
  ⟨powerSubsetOfSet base subset,
    subsetSamePowerMember subsetBase⟩

theorem powerSetNonempty (base : Litex.Set.{u}) :
    Set.Nonempty (powerSet base) :=
  ⟨emptyPowerSubset base⟩

theorem powerSetFinite
    (base : Litex.Set.{u})
    (baseFinite : Set.Finite base) :
    Set.Finite (powerSet base) := by
  unfold Set.Finite powerSet
  letI : _root_.Finite base.Carrier := baseFinite
  infer_instance

theorem unionCommutative (left right : Litex.Set.{u}) :
    Same (union left right) (union right left) :=
  Same.setExt
    (fun value membership => by
      rcases unionCases membership with leftMember | rightMember
      · exact inUnionRight leftMember
      · exact inUnionLeft rightMember)
    (fun value membership => by
      rcases unionCases membership with rightMember | leftMember
      · exact inUnionRight rightMember
      · exact inUnionLeft leftMember)

theorem unionAssociative (left middle right : Litex.Set.{u}) :
    Same (union (union left middle) right) (union left (union middle right)) :=
  Same.setExt
    (fun value membership => by
      rcases unionCases membership with leftMiddle | rightMember
      · rcases unionCases leftMiddle with leftMember | middleMember
        · exact inUnionLeft leftMember
        · exact inUnionRight (inUnionLeft middleMember)
      · exact inUnionRight (inUnionRight rightMember))
    (fun value membership => by
      rcases unionCases membership with leftMember | middleRight
      · exact inUnionLeft (inUnionLeft leftMember)
      · rcases unionCases middleRight with middleMember | rightMember
        · exact inUnionLeft (inUnionRight middleMember)
        · exact inUnionRight rightMember)

theorem unionIdempotent (set : Litex.Set.{u}) : Same (union set set) set :=
  Same.setExt
    (fun _ membership => (unionCases membership).elim id id)
    (fun _ membership => inUnionLeft membership)

theorem unionEmptyRight (set : Litex.Set.{u}) : Same (union set Set.empty) set :=
  Same.setExt
    (fun _ membership => by
      rcases unionCases membership with member | impossible
      · exact member
      · rcases impossible with ⟨empty, _⟩
        exact PEmpty.elim empty)
    (fun _ membership => inUnionLeft membership)

theorem unionEmptyLeft (set : Litex.Set.{u}) : Same (union Set.empty set) set :=
  Same.trans (unionCommutative Set.empty set) (unionEmptyRight set)

theorem intersectCommutative (left right : Litex.Set.{u}) :
    Same (intersect left right) (intersect right left) :=
  Same.setExt
    (fun _ membership =>
      inIntersect (inRightOfInIntersect membership) (inLeftOfInIntersect membership))
    (fun _ membership =>
      inIntersect (inRightOfInIntersect membership) (inLeftOfInIntersect membership))

theorem intersectAssociative (left middle right : Litex.Set.{u}) :
    Same (intersect (intersect left middle) right)
      (intersect left (intersect middle right)) :=
  Same.setExt
    (fun _ membership =>
      inIntersect
        (inLeftOfInIntersect (inLeftOfInIntersect membership))
        (inIntersect
          (inRightOfInIntersect (inLeftOfInIntersect membership))
          (inRightOfInIntersect membership)))
    (fun _ membership =>
      inIntersect
        (inIntersect
          (inLeftOfInIntersect membership)
          (inLeftOfInIntersect (inRightOfInIntersect membership)))
        (inRightOfInIntersect (inRightOfInIntersect membership)))

theorem intersectEqLeftOfSubset
    {left right : Litex.Set.{u}}
    (leftSubset : Subset left right) :
    Same (intersect left right) left :=
  Same.setExt
    (intersectSubsetLeft left right)
    (fun value membership => inIntersect membership (leftSubset value membership))

theorem intersectEqRightOfSubset
    {left right : Litex.Set.{u}}
    (rightSubset : Subset right left) :
    Same (intersect left right) right :=
  Same.setExt
    (intersectSubsetRight left right)
    (fun value membership => inIntersect (rightSubset value membership) membership)

theorem intersectUnionDistributive (left middle right : Litex.Set.{u}) :
    Same (intersect left (union middle right))
      (union (intersect left middle) (intersect left right)) :=
  Same.setExt
    (fun value membership => by
      have leftMembership := inLeftOfInIntersect membership
      rcases unionCases (inRightOfInIntersect membership) with middleMembership | rightMembership
      · exact inUnionLeft (inIntersect leftMembership middleMembership)
      · exact inUnionRight (inIntersect leftMembership rightMembership))
    (fun value membership => by
      rcases unionCases membership with middleMembership | rightMembership
      · exact inIntersect
          (inLeftOfInIntersect middleMembership)
          (inUnionLeft (inRightOfInIntersect middleMembership))
      · exact inIntersect
          (inLeftOfInIntersect rightMembership)
          (inUnionRight (inRightOfInIntersect rightMembership)))

theorem setMinusIntersectDeMorgan (left middle right : Litex.Set.{u}) :
    Same (setMinus left (intersect middle right))
      (union (setMinus left middle) (setMinus left right)) :=
  Same.setExt
    (fun value membership => by
      have leftMembership := inLeftOfInSetMinus membership
      have notIntersection := notInRightOfInSetMinus membership
      classical
      by_cases middleMembership : In value middle
      · exact inUnionRight (inSetMinus leftMembership (fun rightMembership =>
          notIntersection (inIntersect middleMembership rightMembership)))
      · exact inUnionLeft (inSetMinus leftMembership middleMembership))
    (fun value membership => by
      rcases unionCases membership with notMiddle | notRight
      · exact inSetMinus
          (inLeftOfInSetMinus notMiddle)
          (notInIntersectOfNotInLeft (notInRightOfInSetMinus notMiddle))
      · exact inSetMinus
          (inLeftOfInSetMinus notRight)
          (notInIntersectOfNotInRight (notInRightOfInSetMinus notRight)))

theorem setMinusUnionDeMorgan (left middle right : Litex.Set.{u}) :
    Same (setMinus left (union middle right))
      (intersect (setMinus left middle) (setMinus left right)) :=
  Same.setExt
    (fun value membership => by
      have leftMembership := inLeftOfInSetMinus membership
      have notUnion := notInRightOfInSetMinus membership
      exact inIntersect
        (inSetMinus leftMembership (fun middleMembership =>
          notUnion (inUnionLeft middleMembership)))
        (inSetMinus leftMembership (fun rightMembership =>
          notUnion (inUnionRight rightMembership))))
    (fun value membership =>
      inSetMinus
        (inLeftOfInSetMinus (inLeftOfInIntersect membership))
        (fun unionMembership => by
          rcases unionCases unionMembership with middleMembership | rightMembership
          · exact (notInRightOfInSetMinus (inLeftOfInIntersect membership)) middleMembership
          · exact (notInRightOfInSetMinus (inRightOfInIntersect membership)) rightMembership))

theorem setMinusRecoverSubset
    {left subset : Litex.Set.{u}}
    (subsetLeft : Subset subset left) :
    Same (setMinus left (setMinus left subset)) subset :=
  Same.setExt
    (fun value membership => by
      have leftMembership := inLeftOfInSetMinus membership
      have notDifference := notInRightOfInSetMinus membership
      classical
      by_contra notSubset
      exact notDifference (inSetMinus leftMembership notSubset))
    (fun value membership =>
      inSetMinus
        (subsetLeft value membership)
        (fun differenceMembership =>
          (notInRightOfInSetMinus differenceMembership) membership))

end SetRules

/-- The first compiler function carrier: one named unary Litex application
layer. Its argument remains heterogeneous; the function can be called only
with an explicit proof that the argument belongs to `domain`. -/
structure Fn
    (domain : Litex.Set.{u})
    (codomain : Litex.Set.{v}) where
  call : {α : Litex.u.{u}} → (x : α) → In x domain → codomain.Carrier

/-- A unary Litex function with source-domain clauses. Applicability remains
propositional: a call needs both membership in `domain` and the exact
source predicate instantiated at the argument. -/
structure FnWhere
    (domain : Litex.Set.{u})
    (codomain : Litex.Set.{v})
    (requires : {α : Litex.u.{u}} → α → Prop) where
  call :
    {α : Litex.u.{u}} →
    (x : α) →
    In x domain →
    requires x →
    codomain.Carrier

/-- The Litex set of unary functions from `domain` to `codomain`.

`Fn domain codomain` lives in `max (u + 1) v`: its `call` field accepts values
from any carrier in the domain universe and returns the exact codomain
carrier. This permits a base-universe function to return another function
set without collapsing either source application layer. -/
abbrev fnSet
    (domain : Litex.Set.{u})
    (codomain : Litex.Set.{v}) :
    Litex.Set.{max (u + 1) v} :=
  Set.ofType (Fn domain codomain)

/-- The exact carrier of unary functions with source-domain clauses. -/
abbrev fnSetWhere
    (domain : Litex.Set.{u})
    (codomain : Litex.Set.{v})
    (requires : {α : Litex.u.{u}} → α → Prop) :
    Litex.Set.{max (u + 1) v} :=
  Set.ofType (FnWhere domain codomain requires)

/-- Apply a heterogeneous value known to belong to a unary function set.
Both function membership and argument membership are computational inputs to
the wrapper; Lean's ambient type alone never authorizes a Litex call. -/
noncomputable def fnApply
    {domain : Litex.Set.{u}}
    {codomain : Litex.Set.{v}}
    {α : Litex.u.{u}}
    {β : Litex.u.{max (u + 1) v}}
    (f : β)
    (hf : In f (fnSet domain codomain))
    (x : α)
    (hx : In x domain) :
    codomain.Carrier :=
  (In.rep f hf).call x hx

/-- Apply a function already represented by the exact `Fn` carrier. The
membership proof remains an explicit checked input, while no representative
choice is needed for the function value itself. -/
def fnApplyOwn
    {domain : Litex.Set.{u}}
    {codomain : Litex.Set.{v}}
    (f : Fn domain codomain)
    (_hf : In f (fnSet domain codomain))
    {α : Litex.u.{u}}
    (x : α)
    (hx : In x domain) :
    codomain.Carrier :=
  f.call x hx

/-- Apply a heterogeneous value known to belong to a domain-constrained
function set. -/
noncomputable def fnApplyWhere
    {domain : Litex.Set.{u}}
    {codomain : Litex.Set.{v}}
    {requires : {α : Litex.u.{u}} → α → Prop}
    {α : Litex.u.{u}}
    {β : Litex.u.{max (u + 1) v}}
    (f : β)
    (hf : In f (fnSetWhere domain codomain requires))
    (x : α)
    (hx : In x domain)
    (hrequires : requires x) :
    codomain.Carrier :=
  (In.rep f hf).call x hx hrequires

/-- Exact-carrier application for a compiler-constructed function with
source-domain clauses. -/
def fnApplyWhereOwn
    {domain : Litex.Set.{u}}
    {codomain : Litex.Set.{v}}
    {requires : {α : Litex.u.{u}} → α → Prop}
    (f : FnWhere domain codomain requires)
    (_hf : In f (fnSetWhere domain codomain requires))
    {α : Litex.u.{u}}
    (x : α)
    (hx : In x domain)
    (hrequires : requires x) :
    codomain.Carrier :=
  f.call x hx hrequires

/-!
`FnTelescope` is the native carrier for one source application layer with any
finite number of parameters. A parameter node retains its exact Litex set and
membership proof. Later nodes may depend on the earlier value and proof, so
dependent parameter sets, domain clauses, and return sets remain explicit.
One telescope is one Litex application layer; a function-valued `done` set
starts the next source layer rather than silently currying the current one.
-/

inductive FnTelescope : Type (max 1 (v + 1)) where
  | done (codomain : Litex.Set.{v})
  | parameter
      (domain : Litex.Set)
      (next : {α : Type} → (x : α) → In x domain → FnTelescope)
  | requirement
      (condition : Prop)
      (next : condition → FnTelescope)

namespace FnTelescope

/-- Exact Lean carrier described by a source-layer telescope. -/
def Carrier : Litex.FnTelescope.{v} → Type (max 1 v)
  | .done codomain => ULift.{max 1 v, v} codomain.Carrier
  | .parameter domain next =>
      {α : Type} → (x : α) → (hx : In x domain) → Carrier (next x hx)
  | .requirement condition next =>
      (hcondition : condition) → Carrier (next hcondition)

end FnTelescope

/-- Exact Litex set of values implementing one dependent source-layer
telescope. -/
abbrev fnTelescopeSet
    (signature : Litex.FnTelescope.{v}) :
    Litex.Set.{max 1 v} :=
  Set.ofType (FnTelescope.Carrier signature)

/-- Select the exact telescope carrier from a heterogeneous membership proof.
Arguments are subsequently supplied in the source layer's retained order. -/
noncomputable def fnTelescopeApply
    {signature : Litex.FnTelescope.{v}}
    {β : Type (max 1 v)}
    (f : β)
    (hf : In f (fnTelescopeSet signature)) :
    FnTelescope.Carrier signature :=
  In.rep f hf

/-- The exact-carrier application route avoids representative choice for a
compiler-constructed telescope function while retaining the checked
membership certificate as an explicit input. -/
def fnTelescopeApplyOwn
    {signature : Litex.FnTelescope.{v}}
    (f : FnTelescope.Carrier signature)
    (_hf : In f (fnTelescopeSet signature)) :
    FnTelescope.Carrier signature :=
  f

abbrev N : Litex.Set := Set.ofType ℕ
abbrev Z : Litex.Set := Set.ofType ℤ
abbrev Q : Litex.Set := Set.ofType ℚ
abbrev R : Litex.Set := Set.ofType ℝ
abbrev C : Litex.Set := Set.ofType ℂ

/-- A predicate-defined Litex subset. Its exact carrier is the corresponding
subtype, and the compiler-owned subtype edge relates each member to its base
value. -/
def setBuilder
    (base : Litex.Set.{u})
    (predicate : base.Carrier → Prop) :
    Litex.Set.{u} :=
  Set.ofType (Subtype predicate)

/-- Positive naturals use the exact subtype of native naturals carrying their
strict-positivity proof. This is not an alias of `N`: membership retains the
refining predicate in the carrier. -/
abbrev NPos : Litex.Set := setBuilder N (fun n => 0 < n)

/-- Half-open integer range with its exact Mathlib finite carrier. -/
def range (start finish : ℤ) : Litex.Set :=
  Set.ofType {z : ℤ // z ∈ Finset.Ico start finish}

/-- Closed integer range with its exact Mathlib finite carrier. -/
def closedRange (start finish : ℤ) : Litex.Set :=
  Set.ofType {z : ℤ // z ∈ Finset.Icc start finish}

theorem range_finite (start finish : ℤ) : Set.Finite (range start finish) := by
  unfold Set.Finite range
  infer_instance

theorem closedRange_finite (start finish : ℤ) :
    Set.Finite (closedRange start finish) := by
  unfold Set.Finite closedRange
  infer_instance

/-- Empty tail of a typed heterogeneous tuple/sequence spine. -/
inductive HNil where
  | nil

/-- One typed heterogeneous spine cell. The carrier type is determined by
the concrete head and tail types; no universal object is stored. -/
structure HCons (alpha : Type u) (tail : Type v) where
  head : alpha
  rest : tail

/-- Structural tuple evidence and its source arity. -/
class TupleShape (alpha : Type u) where
  dimension : Nat

instance : TupleShape HNil where
  dimension := 0

instance [TupleShape tail] : TupleShape (HCons alpha tail) where
  dimension := TupleShape.dimension tail + 1

def IsTuple {alpha : Type u} (_value : alpha) : Prop :=
  Nonempty (TupleShape alpha)

theorem hcons_isTuple [TupleShape tail] (head : alpha) (rest : tail) :
    IsTuple (HCons.mk head rest) :=
  ⟨inferInstance⟩

def tupleDim [TupleShape alpha] (_value : alpha) : ℂ :=
  TupleShape.dimension alpha

/-- Exact one-based index carrier for a compiler-declared indexed tuple. -/
abbrev TupleIndex (dimension : Nat) : Type :=
  {index : ℤ // index ∈ Finset.Icc 1 (dimension : ℤ)}

/-- A declared indexed tuple keeps its checked dimension at the type level and
stores one uniform exact coordinate carrier.  This is not a universal object
box: the compiler selects `alpha` from the verified coordinate expression. -/
structure IndexedTuple (dimension : Nat) (alpha : Type u) where
  coordinate : TupleIndex dimension → alpha

instance : TupleShape (IndexedTuple dimension alpha) where
  dimension := dimension

/-- Checked one-based coordinate projection. -/
def indexedTupleAt
    (tuple : IndexedTuple dimension alpha)
    (index : TupleIndex dimension) : alpha :=
  tuple.coordinate index

/-- Sequence literals use the same exact typed spine under a distinct wrapper
so tuple-only facts cannot be inferred from a sequence by Lean typing. -/
structure SequenceLiteral (payload : Type u) where
  value : payload

def sequenceSet (values : Litex.Set.{u}) :=
  fnSet NPos values

/-- The archived compiler only exposed the following higher constructors as
proof-free object terms plus reflexive equality. Their native ABI therefore
uses operator-specific typed syntax values until a verifier-owned semantic
membership adapter is selected; this is deliberately not a universal object
box. -/
structure BigUnionExpr (family : Type u) where
  source : family

structure BigIntersectExpr (family : Type u) where
  source : family

def bigUnion (family : alpha) : BigUnionExpr alpha := ⟨family⟩
def bigIntersect (family : alpha) : BigIntersectExpr alpha := ⟨family⟩

structure GeneralCartExpr (index : Type u) (family : Type v) (selector : Type w) where
  indexSet : index
  familySet : family
  familyFunction : selector

def generalCart (index : alpha) (family : beta) (selector : gamma) :
    GeneralCartExpr alpha beta gamma :=
  ⟨index, family, selector⟩

structure SumExpr (start : Type u) (finish : Type v) (function : Type w) where
  lower : start
  upper : finish
  body : function

def sum (start : alpha) (finish : beta) (function : gamma) :
    SumExpr alpha beta gamma :=
  ⟨start, finish, function⟩

structure ProductExpr (start : Type u) (finish : Type v) (function : Type w) where
  lower : start
  upper : finish
  body : function

def product (start : alpha) (finish : beta) (function : gamma) :
    ProductExpr alpha beta gamma :=
  ⟨start, finish, function⟩

structure ReduceExpr
    (start : Type u) (finish : Type v) (function : Type w)
    (operation : Type x) (seed : Type y) where
  lower : start
  upper : finish
  body : function
  reducer : operation
  initial : seed

def reduce (start : alpha) (finish : beta) (function : gamma)
    (operation : delta) (seed : epsilon) :
    ReduceExpr alpha beta gamma delta epsilon :=
  ⟨start, finish, function, operation, seed⟩

structure FiniteSumExpr (set : Type u) (function : Type v) where
  sourceSet : set
  body : function

def finiteSetSum (set : alpha) (function : beta) : FiniteSumExpr alpha beta :=
  ⟨set, function⟩

structure FiniteProductExpr (set : Type u) (function : Type v) where
  sourceSet : set
  body : function

def finiteSetProduct (set : alpha) (function : beta) : FiniteProductExpr alpha beta :=
  ⟨set, function⟩

structure FiniteReduceExpr
    (set : Type u) (function : Type v) (operation : Type w) (seed : Type x) where
  sourceSet : set
  body : function
  reducer : operation
  initial : seed

def finiteSetReduce (set : alpha) (function : beta) (operation : gamma) (seed : delta) :
    FiniteReduceExpr alpha beta gamma delta :=
  ⟨set, function, operation, seed⟩

/-- Positive reals use the exact subtype of native reals carrying their
strict-positivity proof. -/
abbrev RPos : Litex.Set := setBuilder R (fun r => 0 < r)

/-- Nonzero integers retain a complex source representative together with the
exact integer-membership and semantic-nonzero certificates used by Litex. -/
abbrev ZStar : Litex.Set :=
  setBuilder C (fun z => In z Z ∧ ¬ Same z (0 : ℂ))

/-- Nonzero rationals retain a complex source representative together with the
exact rational-membership and semantic-nonzero certificates used by Litex. -/
abbrev QStar : Litex.Set :=
  setBuilder C (fun z => In z Q ∧ ¬ Same z (0 : ℂ))

/-- Nonzero reals retain a complex source representative together with the
exact real-membership and semantic-nonzero certificates used by Litex. -/
abbrev RStar : Litex.Set :=
  setBuilder C (fun z => In z R ∧ ¬ Same z (0 : ℂ))

/-- Nonzero complexes retain a complex source representative together with the
exact complex-membership and semantic-nonzero certificates used by Litex. -/
abbrev CStar : Litex.Set :=
  setBuilder C (fun z => In z C ∧ ¬ Same z (0 : ℂ))

/-!
The ordered-numeric layer deliberately lives at Lean universe `0`: Mathlib's
native `ℕ`, `ℤ`, `ℚ`, `ℝ`, and `ℂ` all live there. This does not restrict the
universe-polymorphic `Litex.Set`, `Litex.In`, or `Litex.Same` interfaces.

Primitive and native-operation representation edges are closed inside this
header. Facts which only transport a chosen real representative need no global
assumption. General order does not compare independently selected
representatives: it uses the one canonical real observation of the compiler's
current numeric carrier, `Complex.re`, and therefore reduces directly to
Mathlib order.
-/

/-- `x` has the real representative `r` when Litex semantic equality relates
the (possibly differently typed) value `x` to the native Mathlib real `r`. -/
def AsReal {α : Type} (x : α) (r : ℝ) : Prop :=
  Same x r

namespace AsReal

theorem real (r : ℝ) : AsReal r r :=
  .refl r

theorem complex (r : ℝ) : AsReal (r : ℂ) r :=
  Same.complexReal r

theorem nat (n : ℕ) : AsReal n (n : ℝ) :=
  .trans (Same.natComplex n) (Same.complexReal (n : ℝ))

theorem int (z : ℤ) : AsReal z (z : ℝ) :=
  .trans (Same.intComplex z) (Same.complexReal (z : ℝ))

theorem rat (q : ℚ) : AsReal q (q : ℝ) :=
  .trans (Same.ratComplex q) (Same.complexReal (q : ℝ))

/-- Semantic equality transports a chosen real representative. -/
theorem congr
    {α β : Type}
    {x : α}
    {y : β}
    {r : ℝ}
    (hxy : Same x y) :
    AsReal x r ↔ AsReal y r := by
  constructor
  · intro hxr
    exact .trans (.symm hxy) hxr
  · intro hyr
    exact .trans hxy hyr

/-- Values with the same real representative are semantically equal. -/
theorem same
    {α β : Type}
    {x : α}
    {y : β}
    {r : ℝ}
    (hxr : AsReal x r)
    (hyr : AsReal y r) :
    Same x y :=
  .trans hxr (.symm hyr)

end AsReal

/-- Membership in `R` is exactly existence of a real representative. -/
theorem inR_iff_asReal
    {α : Type}
    {x : α} :
    In x R ↔ ∃ r : ℝ, AsReal x r :=
  Iff.rfl

/-!
Zero-ended source comparisons use a canonical Mathlib zero instead of
selecting a second real representative for the Litex numeral `0`. This is the
constructive order bridge used by sign rules: a proof of `0 < x` or `0 ≤ x`
contains exactly one representative of `x`, and its order certificate is an
ordinary Mathlib real inequality.
-/

/-- Canonical lowering of a source comparison `0 < x`. -/
def Positive
    {α : Type}
    (x : α) : Prop :=
  ∃ r : ℝ, AsReal x r ∧ 0 < r

/-- Canonical lowering of a source comparison `0 ≤ x`. -/
def Nonnegative
    {α : Type}
    (x : α) : Prop :=
  ∃ r : ℝ, AsReal x r ∧ 0 ≤ r

namespace Positive

theorem intro
    {α : Type}
    {x : α}
    {r : ℝ}
    (hxr : AsReal x r)
    (hr : 0 < r) :
    Positive x :=
  ⟨r, hxr, hr⟩

theorem toNonnegative
    {α : Type}
    {x : α}
    (hx : Positive x) :
    Nonnegative x := by
  rcases hx with ⟨r, hxr, hr⟩
  exact ⟨r, hxr, le_of_lt hr⟩

theorem congr
    {α β : Type}
    {x : α}
    {y : β}
    (hxy : Same x y) :
    Positive x ↔ Positive y := by
  constructor
  · rintro ⟨r, hxr, hr⟩
    exact ⟨r, (AsReal.congr hxy).mp hxr, hr⟩
  · rintro ⟨r, hyr, hr⟩
    exact ⟨r, (AsReal.congr hxy).mpr hyr, hr⟩

end Positive

namespace Nonnegative

theorem intro
    {α : Type}
    {x : α}
    {r : ℝ}
    (hxr : AsReal x r)
    (hr : 0 ≤ r) :
    Nonnegative x :=
  ⟨r, hxr, hr⟩

theorem congr
    {α β : Type}
    {x : α}
    {y : β}
    (hxy : Same x y) :
    Nonnegative x ↔ Nonnegative y := by
  constructor
  · rintro ⟨r, hxr, hr⟩
    exact ⟨r, (AsReal.congr hxy).mp hxr, hr⟩
  · rintro ⟨r, hyr, hr⟩
    exact ⟨r, (AsReal.congr hxy).mpr hyr, hr⟩

end Nonnegative

/-- The canonical Mathlib-ordered observation of a compiled Litex numeric
object. Source admission into the ordered-real fragment is verifier-owned;
once admitted, every occurrence of the same `ℕ`/`ℤ`/`ℚ`/`ℝ`-lowered complex
term has exactly this one observation. -/
def OrderValue (z : ℂ) : ℝ :=
  z.re

/-- Litex strict order on its current numeric carrier. This is a custom Litex
relation with a definitional route to Mathlib's native real order. -/
def Lt (x y : ℂ) : Prop :=
  OrderValue x < OrderValue y

/-- Litex non-strict order on its current numeric carrier. -/
def Le (x y : ℂ) : Prop :=
  OrderValue x ≤ OrderValue y

/-- A bounded positive-natural function parameter is compared through one
source complex observation. This keeps the telescope requirement usable for a
heterogeneous argument while retaining the exact Litex `index <= length`
premise supplied by statement verification. -/
def positiveNaturalParameterLessEqualNaturalBound
    {α : Type}
    (index : α)
    (length : Nat) :
    Prop :=
  ∃ complexIndex : Complex,
    Litex.Same index complexIndex ∧
      Litex.Le complexIndex (length : Complex)

theorem positiveNaturalParameterLessEqualNaturalBoundOfComplex
    {index : Complex}
    {length : Nat}
    (indexLessEqualLength : Litex.Le index (length : Complex)) :
    positiveNaturalParameterLessEqualNaturalBound index length :=
  ⟨index, Litex.Same.refl index, indexLessEqualLength⟩

/-- One finite sequence is exactly the positive-natural function telescope
whose retained source-domain clause bounds the index by `length`. The
membership proof for the `N+` parameter selects the native natural used by
that clause; no zero-based `Fin` carrier silently changes source indexing. -/
def finiteSequenceSignature
    (values : Litex.Set.{u})
    (length : Nat) :
  Litex.FnTelescope.{u} :=
  .parameter Litex.NPos (fun {_alpha : Type} index _indexMembership =>
    .requirement
      (positiveNaturalParameterLessEqualNaturalBound index length)
      (fun _ => .done values))

def finiteSequenceSet (values : Litex.Set.{u}) (length : Nat) :=
  Litex.fnTelescopeSet (finiteSequenceSignature values length)

/-- A matrix is one source application layer with two positive-natural
parameters and the two retained one-based bounds. -/
def matrixSignature
    (values : Litex.Set.{u})
    (rowCount columnCount : Nat) :
    Litex.FnTelescope.{u} :=
  .parameter Litex.NPos (fun {_rowAlpha : Type} row _rowMembership =>
    .parameter Litex.NPos (fun {_columnAlpha : Type} column _columnMembership =>
      .requirement
        (positiveNaturalParameterLessEqualNaturalBound row rowCount ∧
          positiveNaturalParameterLessEqualNaturalBound column columnCount)
        (fun _ => .done values)))

def matrixSet
    (values : Litex.Set.{u})
    (rowCount columnCount : Nat) :=
  Litex.fnTelescopeSet (matrixSignature values rowCount columnCount)

namespace Lt

theorem intro
    {x y : ℂ}
    (hxy : OrderValue x < OrderValue y) :
    Lt x y :=
  hxy

theorem toLe
    {x y : ℂ}
    (h : Lt x y) :
    Le x y :=
  le_of_lt h

theorem irrefl
    (x : ℂ) :
    ¬ Lt x x :=
  lt_irrefl (OrderValue x)

theorem trans
    {x y z : ℂ}
    (hxy : Lt x y)
    (hyz : Lt y z) :
    Lt x z :=
  lt_trans hxy hyz

theorem transLe
    {x y z : ℂ}
    (hxy : Lt x y)
    (hyz : Le y z) :
    Lt x z :=
  lt_of_lt_of_le hxy hyz

end Lt

namespace Le

theorem intro
    {x y : ℂ}
    (hxy : OrderValue x ≤ OrderValue y) :
    Le x y :=
  hxy

theorem refl (x : ℂ) : Le x x :=
  le_refl (OrderValue x)

theorem reflOfAsReal
    {x : ℂ}
    {r : ℝ}
    (_hxr : AsReal x r) :
    Le x x :=
  refl x

theorem reflOfInR
    {x : ℂ}
    (_hx : In x R) :
    Le x x :=
  refl x

theorem trans
    {x y z : ℂ}
    (hxy : Le x y)
    (hyz : Le y z) :
    Le x z :=
  le_trans hxy hyz

theorem transLt
    {x y z : ℂ}
    (hxy : Le x y)
    (hyz : Lt y z) :
    Lt x z :=
  lt_of_le_of_lt hxy hyz

end Le

namespace OrderBridge

/-- A native Mathlib real inequality introduces a Litex inequality without
any global coherence assumption. -/
theorem ltOfReal
    {r s : ℝ}
    (h : r < s) :
    Lt (r : ℂ) (s : ℂ) := by
  simpa [Lt, OrderValue] using h

theorem leOfReal
    {r s : ℝ}
    (h : r ≤ s) :
    Le (r : ℂ) (s : ℂ) := by
  simpa [Le, OrderValue] using h

theorem ltOfComplexReals
    {r s : ℝ}
    (h : r < s) :
    Lt (r : ℂ) (s : ℂ) :=
  ltOfReal h

theorem leOfComplexReals
    {r s : ℝ}
    (h : r ≤ s) :
    Le (r : ℂ) (s : ℂ) :=
  leOfReal h

theorem positiveOfComplexReal
    {r : ℝ}
    (h : 0 < r) :
    Positive (r : ℂ) :=
  Positive.intro (AsReal.complex r) h

theorem nonnegativeOfComplexReal
    {r : ℝ}
    (h : 0 ≤ r) :
    Nonnegative (r : ℂ) :=
  Nonnegative.intro (AsReal.complex r) h

theorem real_lt_iff
    {r s : ℝ} :
    Lt (r : ℂ) (s : ℂ) ↔ r < s := by
  simp [Lt, OrderValue]

theorem real_le_iff
    {r s : ℝ} :
    Le (r : ℂ) (s : ℂ) ↔ r ≤ s := by
  simp [Le, OrderValue]

end OrderBridge

/-- The current compiler numeric carrier's exact natural-primality wrapper.
The equality conjunct prevents a non-natural complex value from being
classified through truncation or a host-language coercion. -/
def Prime (value : ℂ) : Prop :=
  ∃ natural : ℕ, value = (natural : ℂ) ∧ Nat.Prime natural

/-- Exact natural coprimality on the current complex-valued compiler carrier. -/
def Coprime (left right : ℂ) : Prop :=
  ∃ leftNatural rightNatural : ℕ,
    left = (leftNatural : ℂ) ∧
      right = (rightNatural : ℂ) ∧
        Nat.Coprime leftNatural rightNatural

theorem primeOfNat (natural : ℕ) (prime : Nat.Prime natural) :
    Prime (natural : ℂ) :=
  ⟨natural, rfl, prime⟩

theorem notPrimeOfNat (natural : ℕ) (notPrime : ¬ Nat.Prime natural) :
    ¬ Prime (natural : ℂ) := by
  rintro ⟨other, equalCast, otherPrime⟩
  have equalNatural : natural = other := by
    exact_mod_cast equalCast
  exact notPrime (equalNatural ▸ otherPrime)

theorem coprimeOfNat
    (left right : ℕ)
    (coprime : Nat.Coprime left right) :
    Coprime (left : ℂ) (right : ℂ) :=
  ⟨left, right, rfl, rfl, coprime⟩

theorem notCoprimeOfNat
    (left right : ℕ)
    (notCoprime : ¬ Nat.Coprime left right) :
    ¬ Coprime (left : ℂ) (right : ℂ) := by
  rintro ⟨otherLeft, otherRight, equalLeftCast, equalRightCast, otherCoprime⟩
  have equalLeft : left = otherLeft := by
    exact_mod_cast equalLeftCast
  have equalRight : right = otherRight := by
    exact_mod_cast equalRightCast
  exact notCoprime (equalLeft ▸ equalRight ▸ otherCoprime)

end Litex
