import Mathlib

namespace Litex

universe u

/-- The Lean universe used by the v2 public ABI. This is an abbreviation for
Lean's ordinary `Type u`, not a new universe containing Mathlib. -/
abbrev u := Type u

/-- Version of this deliberately incompatible target ABI. -/
def abiVersion : Nat := 2

/-- An allowlisted family of primitive representation edges. The compiler
owns the instances it imports; a downstream Lean integration can deliberately
register another mathematical representation without changing `Same`. -/
class BridgeRule (α β : Type u) where
  relation : α → β → Prop

/-- One primitive representation step between values with different (or the
same) Lean carriers at one universe level. -/
def Bridge
    {α β : Type u}
    [rule : BridgeRule α β]
    (x : α)
    (y : β) : Prop :=
  rule.relation x y

instance : BridgeRule ℕ ℂ where
  relation n z := z = (n : ℂ)

instance : BridgeRule ℤ ℂ where
  relation z w := w = (z : ℂ)

instance : BridgeRule ℚ ℂ where
  relation q z := z = (q : ℂ)

instance : BridgeRule ℝ ℂ where
  relation r z := z = (r : ℂ)

instance {α : Type u} {predicate : α → Prop} :
    BridgeRule (Subtype predicate) α where
  relation x y := y = x.val

namespace Bridge

theorem natComplex (n : ℕ) : Bridge n (n : ℂ) := by
  rfl

theorem intComplex (z : ℤ) : Bridge z (z : ℂ) := by
  rfl

theorem ratComplex (q : ℚ) : Bridge q (q : ℂ) := by
  rfl

theorem realComplex (r : ℝ) : Bridge r (r : ℂ) := by
  rfl

theorem subtype
    {α : Type u}
    {predicate : α → Prop}
    (x : Subtype predicate) :
    Bridge x x.val := by
  rfl

end Bridge

/-- Litex semantic equality. It is heterogeneous and is generated by explicit
representation bridges, reflexivity, symmetry, and transitivity. -/
inductive Same : {α β : Type u} → α → β → Prop where
  | base
      {α β : Litex.u.{u}}
      {x : α}
      {y : β}
      [BridgeRule α β] :
      Bridge x y → Same x y
  | refl {α : Litex.u.{u}} (x : α) : Same x x
  | symm
      {α β : Litex.u.{u}}
      {x : α}
      {y : β} :
      Same x y → Same y x
  | trans
      {α β γ : Litex.u.{u}}
      {x : α}
      {y : β}
      {z : γ} :
      Same x y → Same y z → Same x z

namespace Same

/-- Native Lean equality is always a valid proof of Litex semantic equality. -/
theorem ofEq {α : Litex.u.{u}} {x y : α} (h : x = y) : Same x y := by
  subst y
  exact .refl x

theorem natComplex (n : ℕ) : Same n (n : ℂ) :=
  .base (.natComplex n)

theorem intComplex (z : ℤ) : Same z (z : ℂ) :=
  .base (.intComplex z)

theorem ratComplex (q : ℚ) : Same q (q : ℂ) :=
  .base (.ratComplex q)

theorem realComplex (r : ℝ) : Same r (r : ℂ) :=
  .base (.realComplex r)

theorem complexNat (n : ℕ) : Same (n : ℂ) n :=
  .symm (natComplex n)

theorem complexInt (z : ℤ) : Same (z : ℂ) z :=
  .symm (intComplex z)

theorem complexRat (q : ℚ) : Same (q : ℂ) q :=
  .symm (ratComplex q)

theorem complexReal (r : ℝ) : Same (r : ℂ) r :=
  .symm (realComplex r)

theorem subtype
    {α : Type u}
    {predicate : α → Prop}
    (x : Subtype predicate) :
    Same x x.val :=
  .base (.subtype x)

end Same

/-- A Litex set is represented by its exact element carrier. The carrier is
the set extension itself; no additional native `Set.univ` value is stored. -/
structure Set where
  Carrier : Litex.u.{u}

namespace Set

/-- Package an exact Lean carrier as a Litex set. -/
abbrev ofType (α : Litex.u.{u}) : Litex.Set.{u} :=
  ⟨α⟩

end Set

/-- Heterogeneous membership: `x` belongs to `set` when it is semantically the
same as one value in the set's exact carrier. -/
def In
    {α : Litex.u.{u}}
    (x : α)
    (set : Litex.Set.{u}) : Prop :=
  ∃ y : set.Carrier, Same.{u} x y

namespace In

/-- Every value of a set's own carrier belongs to that set automatically. -/
theorem own (set : Litex.Set.{u}) (x : set.Carrier) : In x set :=
  ⟨x, .refl x⟩

/-- Membership is invariant under Litex semantic equality. -/
theorem congr
    {α β : Litex.u.{u}}
    {x : α}
    {y : β}
    (h : Same x y)
    (set : Litex.Set.{u}) :
    In x set ↔ In y set := by
  constructor
  · rintro ⟨z, hxz⟩
    exact ⟨z, .trans (.symm h) hxz⟩
  · rintro ⟨z, hyz⟩
    exact ⟨z, .trans h hyz⟩

end In

abbrev N : Litex.Set := Set.ofType ℕ
abbrev Z : Litex.Set := Set.ofType ℤ
abbrev Q : Litex.Set := Set.ofType ℚ
abbrev R : Litex.Set := Set.ofType ℝ
abbrev C : Litex.Set := Set.ofType ℂ

/-- A predicate-defined Litex subset. Its exact carrier is the corresponding
subtype, and `Bridge.subtype` relates each member to its base value. -/
def setBuilder
    (base : Litex.Set.{u})
    (predicate : base.Carrier → Prop) :
    Litex.Set.{u} :=
  Set.ofType (Subtype predicate)

end Litex
