-- Generated by compiler from 11_ObjectDefinitions.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_11_ObjectDefinitions

noncomputable def x := (1 : ℂ)

theorem __fact0 : Litex.Same x (1 : ℂ) := by
  exact (by
  unfold x
  exact Litex.Same.refl (1 : ℂ))

noncomputable def y := (1 : ℂ)

theorem __fact1 : Litex.In y Litex.R := by
  exact (by
  unfold y
  exact Litex.Rules.complexRealInR 1)

theorem __fact2 : Litex.Same y (1 : ℂ) := by
  exact (by
  unfold y
  exact Litex.Same.refl (1 : ℂ))

theorem local_definition :
    Litex.Same (2 : ℂ) (2 : ℂ) := by
  let z := (2 : ℂ)
  have __step1 : Litex.Same z (2 : ℂ) := by
    exact (by
    unfold z
    exact Litex.Same.refl (2 : ℂ))
  have __step2 : Litex.Same z (2 : ℂ) := by
    exact __step1
  exact Litex.Same.refl (2 : ℂ)

end __Compiler_11_ObjectDefinitions
