-- Generated by compiler from 12_NamedFunction.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_12_NamedFunction

noncomputable def id : Litex.Fn Litex.R Litex.R :=
  { call := fun {__alpha} (__arg : __alpha) __arg_in => Litex.In.rep __arg __arg_in }

theorem __fact0 : Litex.In id (Litex.fnSet Litex.R Litex.R) := by
  exact Litex.In.own (Litex.fnSet Litex.R Litex.R) id

theorem __fact1 : Litex.Same id ({ call := fun {__alpha} (__arg : __alpha) __arg_in => Litex.In.rep __arg __arg_in } : Litex.Fn Litex.R Litex.R) := by
  unfold id
  exact Litex.Same.refl ({ call := fun {__alpha} (__arg : __alpha) __arg_in => Litex.In.rep __arg __arg_in } : Litex.Fn Litex.R Litex.R)

theorem __fact2 : Litex.Same (Litex.fnApplyOwn id __fact0 (1 : ℂ) (Litex.Rules.complexRealInR 1)) (1 : ℂ) := by
  exact (by
  unfold Litex.fnApplyOwn id
  exact Litex.Same.symm (Litex.In.same_rep (1 : ℂ) (Litex.Rules.complexRealInR 1)))

noncomputable def inc : Litex.Fn Litex.R Litex.R :=
  { call := fun {__alpha} (__arg : __alpha) __arg_in => (Litex.In.rep __arg __arg_in + (1 : ℝ)) }

theorem __fact3 : Litex.In inc (Litex.fnSet Litex.R Litex.R) := by
  exact Litex.In.own (Litex.fnSet Litex.R Litex.R) inc

theorem __fact4 : Litex.Same inc ({ call := fun {__alpha} (__arg : __alpha) __arg_in => (Litex.In.rep __arg __arg_in + (1 : ℝ)) } : Litex.Fn Litex.R Litex.R) := by
  unfold inc
  exact Litex.Same.refl ({ call := fun {__alpha} (__arg : __alpha) __arg_in => (Litex.In.rep __arg __arg_in + (1 : ℝ)) } : Litex.Fn Litex.R Litex.R)

theorem __fact5 : Litex.Same (Litex.fnApplyOwn inc __fact3 (1 : ℂ) (Litex.Rules.complexRealInR 1)) ((1 : ℂ) + (1 : ℂ)) := by
  exact (by
  unfold Litex.fnApplyOwn inc
  exact Litex.Same.realAddComplex (Litex.Same.symm (Litex.In.same_rep (1 : ℂ) (Litex.Rules.complexRealInR 1))) (Litex.Same.realComplex (1 : ℝ)))

noncomputable def reciprocal : Litex.FnWhere Litex.R Litex.R (fun {__alpha} (__arg : __alpha) => ¬ Litex.Same __arg (0 : ℂ)) :=
  { call := fun {__alpha} (__arg : __alpha) __arg_in __arg_domain => ((1 : ℝ) / Litex.In.rep __arg __arg_in) }

theorem __fact6 : Litex.In reciprocal (Litex.fnSetWhere Litex.R Litex.R (fun {__alpha} (__arg : __alpha) => ¬ Litex.Same __arg (0 : ℂ))) := by
  exact Litex.In.own (Litex.fnSetWhere Litex.R Litex.R (fun {__alpha} (__arg : __alpha) => ¬ Litex.Same __arg (0 : ℂ))) reciprocal

theorem __fact7 : Litex.Same reciprocal ({ call := fun {__alpha} (__arg : __alpha) __arg_in __arg_domain => ((1 : ℝ) / Litex.In.rep __arg __arg_in) } : Litex.FnWhere Litex.R Litex.R (fun {__alpha} (__arg : __alpha) => ¬ Litex.Same __arg (0 : ℂ))) := by
  unfold reciprocal
  exact Litex.Same.refl ({ call := fun {__alpha} (__arg : __alpha) __arg_in __arg_domain => ((1 : ℝ) / Litex.In.rep __arg __arg_in) } : Litex.FnWhere Litex.R Litex.R (fun {__alpha} (__arg : __alpha) => ¬ Litex.Same __arg (0 : ℂ)))

theorem __fact8 :
    ∀ (a : ℂ) (__h8_1 : Litex.In a Litex.R) (__h8_2 : ¬ Litex.Same a (0 : ℂ)),
      Litex.Same (Litex.fnApplyWhereOwn reciprocal __fact6 a (__h8_1) (__h8_2)) ((1 : ℂ) / a) := by
  intro a __h8_1 __h8_2
  exact (by
  unfold Litex.fnApplyWhereOwn reciprocal
  exact Litex.Same.realDivComplex (Litex.Same.realComplex (1 : ℝ)) (Litex.Same.symm (Litex.In.same_rep a (__h8_1))))

end __Compiler_12_NamedFunction
