-- Generated by compiler from 13_PredicateDefinitions.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_13_PredicateDefinitions

def is_unit_pair {__carrier1 : Type} (x : __carrier1) {__carrier2 : Type} (y : __carrier2) : Prop :=
  Litex.In x Litex.R ∧ Litex.In y Litex.R ∧ Litex.Same x (1 : ℂ) ∧ Litex.Same y (1 : ℂ)

theorem __fact0 : Litex.Same (1 : ℂ) (1 : ℂ) := by
  exact Litex.Same.refl (1 : ℂ)

theorem __fact1 : is_unit_pair (1 : ℂ) (1 : ℂ) := by
  exact (by
  unfold is_unit_pair
  exact ⟨Litex.Rules.complexRealInR 1, Litex.Rules.complexRealInR 1, __fact0, __fact0⟩)

theorem __fact2 : Litex.In (1 : ℂ) Litex.R := by
  exact (by
  have __definition := __fact1
  unfold is_unit_pair at __definition
  exact __definition.1)

theorem __fact3 : Litex.Same (1 : ℂ) (1 : ℂ) := by
  exact (by
  have __definition := __fact1
  unfold is_unit_pair at __definition
  exact __definition.2.2.1)

end __Compiler_13_PredicateDefinitions
