-- Generated by StmtResultToLeanCompiler from 14_SetBuilderAndChoice.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_14_SetBuilderAndChoice

abbrev S : Litex.Set := (Litex.setBuilder Litex.R (fun (x : Litex.R.Carrier) => Litex.Same x x))

theorem __fact0 : True := by
  exact True.intro

theorem __fact1 : Litex.Same S (Litex.setBuilder Litex.R (fun (x : Litex.R.Carrier) => Litex.Same x x)) := by
  exact Litex.Same.refl (Litex.setBuilder Litex.R (fun (x : Litex.R.Carrier) => Litex.Same x x))

theorem __fact2 : Litex.Same S S := by
  exact Litex.Same.refl S

theorem __fact3 : Litex.In (1 : ℂ) (Litex.setBuilder Litex.R (fun (x : Litex.R.Carrier) => Litex.Same x (1 : ℂ))) := by
  exact ⟨⟨(1 : ℝ), Litex.Same.trans (Litex.Same.realComplex ((1 : ℝ))) (Litex.Same.refl (1 : ℂ))⟩, Litex.Same.transNoObservation (Litex.Same.symmNoObservation (Litex.Same.withoutObservation (Litex.Same.realComplex ((1 : ℝ))))) (Litex.Same.symmNoObservation (Litex.Same.subtypeNoObservation ⟨(1 : ℝ), Litex.Same.trans (Litex.Same.realComplex ((1 : ℝ))) (Litex.Same.refl (1 : ℂ))⟩))⟩

theorem __fact4 : Litex.In (1 : ℂ) Litex.R := by
  exact Litex.Rules.inBaseOfInSetBuilder (__fact3)

theorem __fact5 : Litex.Same (1 : ℂ) (1 : ℂ) := by
  exact (by
  rcases Litex.Rules.inSetBuilder_iff.mp (__fact3) with ⟨__rep, __predicate, __same⟩
  have __selected := __predicate
  exact Litex.Same.trans (Litex.Same.symm (Litex.Same.symm __same)) (__selected))

def is_one (x : (Litex.R).Carrier) : Prop :=
  (Litex.In x Litex.R) ∧ (Litex.Same x (1 : ℂ))

theorem __fact6 : Litex.Same (1 : ℂ) (1 : ℂ) := by
  exact __fact5

theorem __fact7 : is_one (1 : ℝ) := by
  exact (by
  unfold is_one
  exact ⟨Litex.In.own Litex.R (1 : ℝ), Litex.Same.trans (Litex.Same.symm (Litex.Same.symm (Litex.Same.realComplex ((1 : ℝ))))) ((by simpa [Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using (__fact6)))⟩)

theorem __fact8 : Litex.In (1 : ℂ) (Litex.setBuilder Litex.R (fun (x : Litex.R.Carrier) => is_one (x : ℝ))) := by
  exact ⟨⟨(1 : ℝ), (by simpa using (__fact7))⟩, Litex.Same.transNoObservation (Litex.Same.symmNoObservation (Litex.Same.withoutObservation (Litex.Same.realComplex ((1 : ℝ))))) (Litex.Same.symmNoObservation (Litex.Same.subtypeNoObservation ⟨(1 : ℝ), (by simpa using (__fact7))⟩))⟩

theorem __fact9 : Litex.In (1 : ℂ) Litex.R := by
  exact Litex.Rules.inBaseOfInSetBuilder (__fact8)

theorem __fact10 : is_one (1 : ℝ) := by
  exact (show is_one (1 : ℝ) from (by
  rcases Litex.Rules.inSetBuilder_iff.mp (__fact8) with ⟨__rep, __predicate, __same⟩
  have __selected := __predicate
  have __transported : is_one ((1 : ℝ) : ℝ) := (by
  have __source := __selected
  unfold is_one at __source ⊢
  exact ⟨Litex.In.own Litex.R ((1 : ℝ) : ℝ), Litex.Same.trans (Litex.Same.symm (Litex.Same.trans (Litex.Same.ofEq (by rfl)) (Litex.Same.trans (Litex.Same.symm (Litex.Same.realComplex (((1 : ℝ) : ℝ)))) (Litex.Same.symm (Litex.Same.realComplex ((1 : ℝ))))))) (__source.2)⟩)
  simpa [Litex.In.rep, Litex.Rules.complexRealInR, Litex.Rules.complexAddInR, Litex.Rules.complexSubInR, Litex.Rules.complexMulInR, Litex.Rules.complexDivInR, Litex.Rules.inROfInRPos] using __transported))

noncomputable def chosen : Litex.R.Carrier :=
  Classical.choice (Litex.Rules.realNonempty)

theorem __fact11 : Litex.In chosen Litex.R := by
  exact Litex.In.own Litex.R chosen

theorem __fact12 : Litex.In chosen Litex.R := by
  exact __fact11

end __Compiler_14_SetBuilderAndChoice
