-- Generated by compiler from 15_BuiltinStrategy.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_15_BuiltinStrategy

theorem __fact0 :
    ∀ (a : ℂ) (__h0_1 : Litex.In a Litex.R) (b : ℂ) (__h0_2 : Litex.In b Litex.R),
      Litex.In (a + b) Litex.R := by
  intro a __h0_1 b __h0_2
  have __c0_0 : Litex.In (a + b) Litex.R := (by
  have __components : Litex.In a Litex.R ∧ Litex.In b Litex.R := ⟨__h0_1, __h0_2⟩
  exact Litex.Rules.complexAddInR (__components.1) (__components.2))
  exact __c0_0

theorem __fact1 :
    ∀ (a : ℂ) (__h1_1 : Litex.In a Litex.R) (b : ℂ) (__h1_2 : Litex.In b Litex.R),
      Litex.In (a - b) Litex.R := by
  intro a __h1_1 b __h1_2
  have __c1_0 : Litex.In (a - b) Litex.R := (by
  have __components : Litex.In a Litex.R ∧ Litex.In b Litex.R := ⟨__h1_1, __h1_2⟩
  exact Litex.Rules.complexSubInR (__components.1) (__components.2))
  exact __c1_0

theorem __fact2 :
    ∀ (a : ℂ) (__h2_1 : Litex.In a Litex.R) (b : ℂ) (__h2_2 : Litex.In b Litex.R),
      Litex.In (a * b) Litex.R := by
  intro a __h2_1 b __h2_2
  have __c2_0 : Litex.In (a * b) Litex.R := (by
  have __components : Litex.In a Litex.R ∧ Litex.In b Litex.R := ⟨__h2_1, __h2_2⟩
  exact Litex.Rules.complexMulInR (__components.1) (__components.2))
  exact __c2_0

theorem __fact3 :
    ∀ (a : ℂ) (__h3_1 : Litex.In a Litex.R) (b : ℂ) (__h3_2 : Litex.In b Litex.R) (__h3_3 : ¬ Litex.Same b (0 : ℂ)),
      Litex.In (a / b) Litex.R := by
  intro a __h3_1 b __h3_2 __h3_3
  have __c3_0 : Litex.In (a / b) Litex.R := (by
  have __components : Litex.In a Litex.R ∧ Litex.In b Litex.R := ⟨__h3_1, __h3_2⟩
  exact Litex.Rules.complexDivInR (__components.1) (__components.2))
  exact __c3_0

theorem __fact4 :
    ∀ (a : ℂ) (__h4_1 : Litex.In a Litex.R) (b : ℂ) (__h4_2 : Litex.In b Litex.R) (c : ℂ) (__h4_3 : Litex.In c Litex.R) (d : ℂ) (__h4_4 : Litex.In d Litex.R) (__h4_5 : Litex.Positive a) (__h4_6 : Litex.Nonnegative b) (__h4_7 : Litex.Nonnegative c) (__h4_8 : Litex.Nonnegative d),
      Litex.Positive ((a + b) + (c + d)) := by
  intro a __h4_1 b __h4_2 c __h4_3 d __h4_4 __h4_5 __h4_6 __h4_7 __h4_8
  have __c4_0 : Litex.Positive ((a + b) + (c + d)) := Litex.Rules.complexAddPositiveLeftStrict (Litex.Rules.complexAddPositiveLeftStrict (__h4_5) (__h4_6)) (Litex.Rules.complexAddNonnegative (__h4_7) (__h4_8))
  exact __c4_0

theorem __fact5 :
    ∀ (a : ℂ) (__h5_1 : Litex.In a Litex.R) (b : ℂ) (__h5_2 : Litex.In b Litex.R) (c : ℂ) (__h5_3 : Litex.In c Litex.R) (d : ℂ) (__h5_4 : Litex.In d Litex.R) (__h5_5 : Litex.Nonnegative a) (__h5_6 : Litex.Nonnegative b) (__h5_7 : Litex.Nonnegative c) (__h5_8 : Litex.Positive d),
      Litex.Positive ((a + b) + (c + d)) := by
  intro a __h5_1 b __h5_2 c __h5_3 d __h5_4 __h5_5 __h5_6 __h5_7 __h5_8
  have __c5_0 : Litex.Positive ((a + b) + (c + d)) := Litex.Rules.complexAddPositiveRightStrict (Litex.Rules.complexAddNonnegative (__h5_5) (__h5_6)) (Litex.Rules.complexAddPositiveRightStrict (__h5_7) (__h5_8))
  exact __c5_0

theorem __fact6 :
    ∀ (a : ℂ) (__h6_1 : Litex.In a Litex.R) (b : ℂ) (__h6_2 : Litex.In b Litex.R) (__h6_3 : Litex.Nonnegative a) (__h6_4 : Litex.Nonnegative b),
      Litex.Nonnegative (a * b) := by
  intro a __h6_1 b __h6_2 __h6_3 __h6_4
  have __c6_0 : Litex.Nonnegative (a * b) := Litex.Rules.complexMulNonnegative (__h6_3) (__h6_4)
  exact __c6_0

theorem __fact7 :
    ∀ (a : ℂ) (__h7_1 : Litex.In a Litex.R) (b : ℂ) (__h7_2 : Litex.In b Litex.R) (__h7_3 : Litex.Positive a) (__h7_4 : Litex.Positive b),
      Litex.Positive (a * b) := by
  intro a __h7_1 b __h7_2 __h7_3 __h7_4
  have __c7_0 : Litex.Positive (a * b) := Litex.Rules.complexMulPositive (__h7_3) (__h7_4)
  exact __c7_0

theorem __fact8 :
    ∀ (a : ℂ) (__h8_1 : Litex.In a Litex.R) (b : ℂ) (__h8_2 : Litex.In b Litex.R) (__h8_3 : Litex.Nonnegative a) (__h8_4 : Litex.Positive b),
      Litex.Nonnegative (a / b) := by
  intro a __h8_1 b __h8_2 __h8_3 __h8_4
  have __c8_0 : Litex.Nonnegative (a / b) := Litex.Rules.complexDivNonnegative (__h8_3) (__h8_4)
  exact __c8_0

theorem __fact9 :
    ∀ (a : ℂ) (__h9_1 : Litex.In a Litex.R) (b : ℂ) (__h9_2 : Litex.In b Litex.R) (__h9_3 : Litex.Positive a) (__h9_4 : Litex.Positive b),
      Litex.Positive (a / b) := by
  intro a __h9_1 b __h9_2 __h9_3 __h9_4
  have __c9_0 : Litex.Positive (a / b) := Litex.Rules.complexDivPositive (__h9_3) (__h9_4)
  exact __c9_0

end __Compiler_15_BuiltinStrategy
