-- Generated by compiler from 15_BuiltinStrategy.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_15_BuiltinStrategy

theorem __fact0 :
    ∀ (a : ℂ) (__h0_1 : Litex.In a Litex.R) (b : ℂ) (__h0_2 : Litex.In b Litex.R) (c : ℂ) (__h0_3 : Litex.In c Litex.R) (d : ℂ) (__h0_4 : Litex.In d Litex.R) (__h0_5 : Litex.Lt (0 : ℂ) a) (__h0_6 : Litex.Le (0 : ℂ) b) (__h0_7 : Litex.Le (0 : ℂ) c) (__h0_8 : Litex.Le (0 : ℂ) d),
      Litex.Lt (0 : ℂ) ((a + b) + (c + d)) := by
  intro a __h0_1 b __h0_2 c __h0_3 d __h0_4 __h0_5 __h0_6 __h0_7 __h0_8
  exact Litex.Rules.complexAddPositiveLeftStrict (Litex.Rules.complexAddPositiveLeftStrict (__h0_5) (__h0_6)) (Litex.Rules.complexAddNonnegative (__h0_7) (__h0_8))

end __Compiler_15_BuiltinStrategy
