-- Generated by StmtResultToLeanCompiler from 16_StandardSetHierarchy.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_16_StandardSetHierarchy

theorem __fact0 :
    ∀ (__p1 : ℂ) (__type1 : Litex.In __p1 Litex.N), Litex.In __p1 Litex.Z := by
  intro n __h0_1
  have __infer0_0 : Litex.Nonnegative n := Litex.Rules.nonnegativeOfInN (__h0_1)
  have __infer0_1 : Litex.Nonpositive ((-1 : ℂ) * (((Litex.In.rep n __h0_1 : ℕ)) : ℂ)) := Litex.Rules.complexNegativeOneMulNonpositive ((Litex.Nonnegative.congr (Litex.Same.trans (Litex.In.same_rep n (__h0_1)) (Litex.Same.natComplex (Litex.In.rep n __h0_1)))).mp (__infer0_0))
  have __c0_0 : Litex.In n Litex.Z := Litex.Rules.inZOfInN (__h0_1)
  exact __c0_0

theorem __fact1 :
    ∀ (__p1 : ℂ) (__type1 : Litex.In __p1 Litex.N), Litex.In __p1 Litex.Q := by
  intro n __h1_1
  have __infer1_0 : Litex.Nonnegative n := Litex.Rules.nonnegativeOfInN (__h1_1)
  have __infer1_1 : Litex.Nonpositive ((-1 : ℂ) * (((Litex.In.rep n __h1_1 : ℕ)) : ℂ)) := Litex.Rules.complexNegativeOneMulNonpositive ((Litex.Nonnegative.congr (Litex.Same.trans (Litex.In.same_rep n (__h1_1)) (Litex.Same.natComplex (Litex.In.rep n __h1_1)))).mp (__infer1_0))
  have __c1_0 : Litex.In n Litex.Q := Litex.Rules.inQOfInZ (Litex.Rules.inZOfInN (__h1_1))
  exact __c1_0

theorem __fact2 :
    ∀ (__p1 : ℂ) (__type1 : Litex.In __p1 Litex.N), Litex.In __p1 Litex.R := by
  intro n __h2_1
  have __infer2_0 : Litex.Nonnegative n := Litex.Rules.nonnegativeOfInN (__h2_1)
  have __infer2_1 : Litex.Nonpositive ((-1 : ℂ) * (((Litex.In.rep n __h2_1 : ℕ)) : ℂ)) := Litex.Rules.complexNegativeOneMulNonpositive ((Litex.Nonnegative.congr (Litex.Same.trans (Litex.In.same_rep n (__h2_1)) (Litex.Same.natComplex (Litex.In.rep n __h2_1)))).mp (__infer2_0))
  have __c2_0 : Litex.In n Litex.R := Litex.Rules.inROfInQ (Litex.Rules.inQOfInZ (Litex.Rules.inZOfInN (__h2_1)))
  exact __c2_0

theorem __fact3 :
    ∀ (__p1 : ℂ) (__type1 : Litex.In __p1 Litex.N), Litex.In __p1 Litex.C := by
  intro n __h3_1
  have __infer3_0 : Litex.Nonnegative n := Litex.Rules.nonnegativeOfInN (__h3_1)
  have __infer3_1 : Litex.Nonpositive ((-1 : ℂ) * (((Litex.In.rep n __h3_1 : ℕ)) : ℂ)) := Litex.Rules.complexNegativeOneMulNonpositive ((Litex.Nonnegative.congr (Litex.Same.trans (Litex.In.same_rep n (__h3_1)) (Litex.Same.natComplex (Litex.In.rep n __h3_1)))).mp (__infer3_0))
  have __c3_0 : Litex.In n Litex.C := Litex.Rules.inCOfInR (Litex.Rules.inROfInQ (Litex.Rules.inQOfInZ (Litex.Rules.inZOfInN (__h3_1))))
  exact __c3_0

theorem __fact4 :
    ∀ (__p1 : ℂ) (__type1 : Litex.In __p1 Litex.Z), Litex.In __p1 Litex.Q := by
  intro z __h4_1
  have __c4_0 : Litex.In z Litex.Q := Litex.Rules.inQOfInZ (__h4_1)
  exact __c4_0

theorem __fact5 :
    ∀ (__p1 : ℂ) (__type1 : Litex.In __p1 Litex.Z), Litex.In __p1 Litex.R := by
  intro z __h5_1
  have __c5_0 : Litex.In z Litex.R := Litex.Rules.inROfInQ (Litex.Rules.inQOfInZ (__h5_1))
  exact __c5_0

theorem __fact6 :
    ∀ (__p1 : ℂ) (__type1 : Litex.In __p1 Litex.Z), Litex.In __p1 Litex.C := by
  intro z __h6_1
  have __c6_0 : Litex.In z Litex.C := Litex.Rules.inCOfInR (Litex.Rules.inROfInQ (Litex.Rules.inQOfInZ (__h6_1)))
  exact __c6_0

theorem __fact7 :
    ∀ (__p1 : ℂ) (__type1 : Litex.In __p1 Litex.Q), Litex.In __p1 Litex.R := by
  intro q __h7_1
  have __c7_0 : Litex.In q Litex.R := Litex.Rules.inROfInQ (__h7_1)
  exact __c7_0

theorem __fact8 :
    ∀ (__p1 : ℂ) (__type1 : Litex.In __p1 Litex.Q), Litex.In __p1 Litex.C := by
  intro q __h8_1
  have __c8_0 : Litex.In q Litex.C := Litex.Rules.inCOfInR (Litex.Rules.inROfInQ (__h8_1))
  exact __c8_0

theorem __fact9 :
    ∀ (__p1 : ℂ) (__type1 : Litex.In __p1 Litex.R), Litex.In __p1 Litex.C := by
  intro r __h9_1
  have __c9_0 : Litex.In r Litex.C := Litex.Rules.inCOfInR (__h9_1)
  exact __c9_0

end __Compiler_16_StandardSetHierarchy
