-- Generated by compiler from 18_RationalNaturalClosures.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_18_RationalNaturalClosures

theorem __fact0 :
    ∀ (a : ℂ) (__h0_1 : Litex.In a Litex.Q) (b : ℂ) (__h0_2 : Litex.In b Litex.Q),
      Litex.In (a + b) Litex.Q := by
  intro a __h0_1 b __h0_2
  exact (by
  have __components : Litex.In a Litex.Q ∧ Litex.In b Litex.Q := ⟨__h0_1, __h0_2⟩
  exact Litex.Rules.complexAddInQ (__components.1) (__components.2))

theorem __fact1 :
    ∀ (a : ℂ) (__h1_1 : Litex.In a Litex.Q) (b : ℂ) (__h1_2 : Litex.In b Litex.Q),
      Litex.In (a - b) Litex.Q := by
  intro a __h1_1 b __h1_2
  exact (by
  have __components : Litex.In a Litex.Q ∧ Litex.In b Litex.Q := ⟨__h1_1, __h1_2⟩
  exact Litex.Rules.complexSubInQ (__components.1) (__components.2))

theorem __fact2 :
    ∀ (a : ℂ) (__h2_1 : Litex.In a Litex.Q) (b : ℂ) (__h2_2 : Litex.In b Litex.Q),
      Litex.In (a * b) Litex.Q := by
  intro a __h2_1 b __h2_2
  exact (by
  have __components : Litex.In a Litex.Q ∧ Litex.In b Litex.Q := ⟨__h2_1, __h2_2⟩
  exact Litex.Rules.complexMulInQ (__components.1) (__components.2))

theorem __fact3 :
    ∀ (a : ℂ) (__h3_1 : Litex.In a Litex.Q) (b : ℂ) (__h3_2 : Litex.In b Litex.Q) (__h3_3 : ¬ Litex.Same b (0 : ℂ)),
      Litex.In (a / b) Litex.Q := by
  intro a __h3_1 b __h3_2 __h3_3
  exact (by
  have __components : Litex.In a Litex.Q ∧ Litex.In b Litex.Q := ⟨__h3_1, __h3_2⟩
  exact Litex.Rules.complexDivInQ (__components.1) (__components.2))

theorem __fact4 :
    ∀ (a : ℂ) (__h4_1 : Litex.In a Litex.N) (b : ℂ) (__h4_2 : Litex.In b Litex.N),
      Litex.In (a + b) Litex.N := by
  intro a __h4_1 b __h4_2
  exact Litex.Rules.complexAddInN (__h4_1) (__h4_2)

theorem __fact5 :
    ∀ (a : ℂ) (__h5_1 : Litex.In a Litex.N) (b : ℂ) (__h5_2 : Litex.In b Litex.N),
      Litex.In (a * b) Litex.N := by
  intro a __h5_1 b __h5_2
  exact Litex.Rules.complexMulInN (__h5_1) (__h5_2)

end __Compiler_18_RationalNaturalClosures
