-- Generated by StmtResultToLeanCompiler from 1_SetSystem.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_1_SetSystem

namespace __Sketch01

abbrev A : Litex.Set := Litex.R

theorem __fact0 : True := by
  exact True.intro

theorem __fact1 : Litex.Same A Litex.R := by
  exact Litex.Same.refl Litex.R

abbrev B : Litex.Set := Litex.C

theorem __fact2 : True := by
  exact True.intro

theorem __fact3 : Litex.Same B Litex.C := by
  exact Litex.Same.refl Litex.C

theorem __fact4 :
    ∀ {__carrier1 : Type} (__p1 : __carrier1) (__type1 : Litex.In __p1 A) {__carrier2 : Type} (__p2 : __carrier2) (__type2 : Litex.In __p2 B) (__domain1 : Litex.Same __p1 __p2), (Litex.In __p2 A) ∧ (Litex.In __p1 B) := by
  intro __carrier1 a __h16 __carrier2 b __h18 __domain1
  have __infer4_0 : Litex.In a Litex.R := by
    simpa [A] using (__h16)
  have __infer4_1 : Litex.In b Litex.C := by
    simpa [B] using (__h18)
  have __prior4_0 : Litex.In b A := (by
    unfold A
    exact ((Litex.In.congr (__domain1) Litex.R).mp (__infer4_0)))
  have __infer4_2 : Litex.In b Litex.R := by
    simpa [A] using (__prior4_0)
  have __infer4_3 : Litex.In b Litex.R := by
    simpa [A] using (__prior4_0)
  have __prior4_1 : Litex.In a B := (by
    unfold B
    exact ((Litex.In.congr (__domain1) Litex.C).mpr (__infer4_1)))
  have __infer4_4 : Litex.In a Litex.C := by
    simpa [B] using (__prior4_1)
  have __infer4_5 : Litex.In a Litex.C := by
    simpa [B] using (__prior4_1)
  exact ⟨__prior4_0, __prior4_1⟩

end __Sketch01

theorem __fact0 : Litex.Same (1 : ℂ) (1 : ℂ) := by
  exact Litex.Same.refl (1 : ℂ)

end __Compiler_1_SetSystem
