-- Generated by compiler from 22_NonzeroNumericCarriers.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_22_NonzeroNumericCarriers

theorem __fact0 :
    ∀ (z : ℂ) (__h0_1 : Litex.In z Litex.Z) (__h0_2 : ¬ Litex.Same z (0 : ℂ)),
      Litex.In z Litex.ZStar := by
  intro z __h0_1 __h0_2
  exact Litex.Rules.inZStarOfInZNotSameZero (__h0_1) (__h0_2)

theorem __fact1 :
    ∀ (q : ℂ) (__h1_1 : Litex.In q Litex.Q) (__h1_2 : ¬ Litex.Same q (0 : ℂ)),
      Litex.In q Litex.QStar := by
  intro q __h1_1 __h1_2
  exact Litex.Rules.inQStarOfInQNotSameZero (__h1_1) (__h1_2)

theorem __fact2 :
    ∀ (r : ℂ) (__h2_1 : Litex.In r Litex.R) (__h2_2 : ¬ Litex.Same r (0 : ℂ)),
      Litex.In r Litex.RStar := by
  intro r __h2_1 __h2_2
  exact Litex.Rules.inRStarOfInRNotSameZero (__h2_1) (__h2_2)

theorem __fact3 :
    ∀ (c : ℂ) (__h3_1 : Litex.In c Litex.C) (__h3_2 : ¬ Litex.Same c (0 : ℂ)),
      Litex.In c Litex.CStar := by
  intro c __h3_1 __h3_2
  exact Litex.Rules.inCStarOfInCNotSameZero (__h3_1) (__h3_2)

theorem __fact4 :
    ∀ (z : ℂ) (__h4_1 : Litex.In z Litex.ZStar),
      ¬ Litex.Same z (0 : ℂ) ∧ Litex.In z Litex.Z ∧ Litex.In z Litex.Q ∧ Litex.In z Litex.R ∧ Litex.In z Litex.C ∧ Litex.In z Litex.QStar ∧ Litex.In z Litex.RStar ∧ Litex.In z Litex.CStar := by
  intro z __h4_1
  have __i4_0 : ¬ Litex.Same z (0 : ℂ) := Litex.Rules.notSameZeroOfInZStar (__h4_1)
  exact ⟨__i4_0, Litex.Rules.inZOfInZStar (__h4_1), Litex.Rules.inQOfInZ (Litex.Rules.inZOfInZStar (__h4_1)), Litex.Rules.inROfInQ (Litex.Rules.inQOfInZ (Litex.Rules.inZOfInZStar (__h4_1))), Litex.Rules.inCOfInR (Litex.Rules.inROfInQ (Litex.Rules.inQOfInZ (Litex.Rules.inZOfInZStar (__h4_1)))), Litex.Rules.inQStarOfInZStar (__h4_1), Litex.Rules.inRStarOfInQStar (Litex.Rules.inQStarOfInZStar (__h4_1)), Litex.Rules.inCStarOfInRStar (Litex.Rules.inRStarOfInQStar (Litex.Rules.inQStarOfInZStar (__h4_1)))⟩

theorem __fact5 :
    ∀ (q : ℂ) (__h5_1 : Litex.In q Litex.QStar),
      ¬ Litex.Same q (0 : ℂ) ∧ Litex.In q Litex.Q ∧ Litex.In q Litex.R ∧ Litex.In q Litex.C ∧ Litex.In q Litex.RStar ∧ Litex.In q Litex.CStar := by
  intro q __h5_1
  have __i5_0 : ¬ Litex.Same q (0 : ℂ) := Litex.Rules.notSameZeroOfInQStar (__h5_1)
  exact ⟨__i5_0, Litex.Rules.inQOfInQStar (__h5_1), Litex.Rules.inROfInQ (Litex.Rules.inQOfInQStar (__h5_1)), Litex.Rules.inCOfInR (Litex.Rules.inROfInQ (Litex.Rules.inQOfInQStar (__h5_1))), Litex.Rules.inRStarOfInQStar (__h5_1), Litex.Rules.inCStarOfInRStar (Litex.Rules.inRStarOfInQStar (__h5_1))⟩

theorem __fact6 :
    ∀ (r : ℂ) (__h6_1 : Litex.In r Litex.RStar),
      ¬ Litex.Same r (0 : ℂ) ∧ Litex.In r Litex.R ∧ Litex.In r Litex.C ∧ Litex.In r Litex.CStar := by
  intro r __h6_1
  have __i6_0 : ¬ Litex.Same r (0 : ℂ) := Litex.Rules.notSameZeroOfInRStar (__h6_1)
  exact ⟨__i6_0, Litex.Rules.inROfInRStar (__h6_1), Litex.Rules.inCOfInR (Litex.Rules.inROfInRStar (__h6_1)), Litex.Rules.inCStarOfInRStar (__h6_1)⟩

theorem __fact7 :
    ∀ (c : ℂ) (__h7_1 : Litex.In c Litex.CStar),
      ¬ Litex.Same c (0 : ℂ) ∧ Litex.In c Litex.C := by
  intro c __h7_1
  have __i7_0 : ¬ Litex.Same c (0 : ℂ) := Litex.Rules.notSameZeroOfInCStar (__h7_1)
  exact ⟨__i7_0, Litex.Rules.inCOfInCStar (__h7_1)⟩

end __Compiler_22_NonzeroNumericCarriers
