-- Generated by StmtResultToLeanCompiler from 29_IndexedTupleCompilerEnvironment.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_29_IndexedTupleCompilerEnvironment

theorem __coordinates_dimension_check1 : Litex.In (3 : ℂ) Litex.NPos := by
  exact Litex.Rules.complexEqNatInNPos (3 : ℂ) 3 (by norm_num) (by norm_num)

theorem __coordinates_dimension_check2 : Litex.Le (2 : ℂ) (3 : ℂ) := by
  exact Litex.OrderBridge.leOfComplexReals (by norm_num)

noncomputable def coordinates : Litex.IndexedTuple 3 ℂ :=
  ⟨fun __index => ((((__index.val : ℤ) : ℂ)) + (1 : ℂ))⟩

theorem __fact0 : Litex.IsTuple coordinates := by
  exact ⟨inferInstance⟩

theorem __fact1 : Litex.Same (Litex.tupleDim coordinates) (3 : ℂ) := by
  exact Litex.Same.ofEq (by rfl)

theorem __fact2 :
    ∀ {__tuple_index_carrier : Type} (__tuple_index : __tuple_index_carrier) (__tuple_index_in : Litex.In __tuple_index (Litex.closedRange (1 : ℤ) (3 : ℤ))),
      Litex.Same (Litex.indexedTupleAt coordinates (Litex.In.rep __tuple_index __tuple_index_in)) (((((Litex.In.rep __tuple_index __tuple_index_in)).val : ℤ) : ℂ) + (1 : ℂ)) := by
  intro __tuple_index_carrier __tuple_index __tuple_index_in
  exact Litex.Same.ofEq (by rfl)

end __Compiler_29_IndexedTupleCompilerEnvironment
