-- Generated by StmtResultToLeanCompiler from 30_IndexedSequenceCompilerEnvironment.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_30_IndexedSequenceCompilerEnvironment

noncomputable def shifted_sequence : Litex.Fn Litex.NPos Litex.R :=
  { call := fun {__alpha} (__arg : __alpha) __arg_in => (((((Litex.In.rep __arg __arg_in).val : ℕ) : ℝ)) + (1 : ℝ)) }

theorem __fact0 : Litex.In shifted_sequence (Litex.sequenceSet Litex.R) := by
  exact Litex.In.own (Litex.sequenceSet Litex.R) shifted_sequence

theorem __fact1 : Litex.In shifted_sequence (Litex.fnSet Litex.NPos Litex.R) := by
  exact Litex.In.own (Litex.fnSet Litex.NPos Litex.R) shifted_sequence

theorem __fact2 : Litex.Same shifted_sequence ({ call := fun {__alpha} (__arg : __alpha) __arg_in => (((((Litex.In.rep __arg __arg_in).val : ℕ) : ℝ)) + (1 : ℝ)) } : Litex.Fn Litex.NPos Litex.R) := by
  unfold shifted_sequence
  exact Litex.Same.refl ({ call := fun {__alpha} (__arg : __alpha) __arg_in => (((((Litex.In.rep __arg __arg_in).val : ℕ) : ℝ)) + (1 : ℝ)) } : Litex.Fn Litex.NPos Litex.R)

theorem __fact3 : Litex.Same (Litex.fnApplyCarrier (domain := Litex.NPos) (codomain := Litex.R) shifted_sequence ((Litex.In.own (Litex.fnSet Litex.NPos Litex.R) shifted_sequence)) (⟨2, by norm_num⟩ : Litex.NPos.Carrier)) ((2 : ℂ) + (1 : ℂ)) := by
  exact Litex.Same.trans ((by
  unfold Litex.fnApplyCarrier shifted_sequence
  exact Litex.Same.realAddComplex ((by
  have __selected := Litex.In.rep_exact (⟨2, by norm_num⟩ : Litex.NPos.Carrier) (Litex.In.own Litex.NPos (⟨2, by norm_num⟩ : Litex.NPos.Carrier))
  convert (Litex.Same.realComplex (2 : ℝ)) using 1
  · exact congrArg (fun value : Litex.NPos.Carrier => (((value.val : ℕ) : ℝ))) __selected
  · norm_num)) (Litex.Same.realComplex (1 : ℝ)))) (Litex.Same.refl ((2 : ℂ) + (1 : ℂ)))

end __Compiler_30_IndexedSequenceCompilerEnvironment
