-- Generated by StmtResultToLeanCompiler from 30_IndexedSequenceCompilerEnvironment.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_30_IndexedSequenceCompilerEnvironment

noncomputable def shifted_sequence : Litex.Fn Litex.NPos Litex.R :=
  { call := fun {__alpha} (__arg : __alpha) __arg_in => (((((Litex.In.rep __arg __arg_in).val : ℕ) : ℝ)) + (1 : ℝ)) }

theorem __fact0 : Litex.In shifted_sequence (Litex.sequenceSet Litex.R) := by
  exact Litex.In.own (Litex.sequenceSet Litex.R) shifted_sequence

theorem __fact1 : Litex.In shifted_sequence (Litex.fnSet Litex.NPos Litex.R) := by
  exact Litex.In.own (Litex.fnSet Litex.NPos Litex.R) shifted_sequence

theorem __fact2 : Litex.Same shifted_sequence ({ call := fun {__alpha} (__arg : __alpha) __arg_in => (((((Litex.In.rep __arg __arg_in).val : ℕ) : ℝ)) + (1 : ℝ)) } : Litex.Fn Litex.NPos Litex.R) := by
  unfold shifted_sequence
  exact Litex.Same.refl ({ call := fun {__alpha} (__arg : __alpha) __arg_in => (((((Litex.In.rep __arg __arg_in).val : ℕ) : ℝ)) + (1 : ℝ)) } : Litex.Fn Litex.NPos Litex.R)

theorem __fact3 : Litex.Same (Litex.fnApplyOwn shifted_sequence __fact0 (2 : ℂ) (Litex.Rules.complexEqNatInNPos (2 : ℂ) 2 (by norm_num) (by norm_num))) ((2 : ℂ) + (1 : ℂ)) := by
  exact (by
  unfold Litex.fnApplyOwn shifted_sequence
  exact Litex.Same.realAddComplex (Litex.Same.symm (Litex.Same.trans (Litex.In.same_rep (2 : ℂ) (Litex.Rules.complexEqNatInNPos (2 : ℂ) 2 (by norm_num) (by norm_num))) (Litex.Same.trans (Litex.Same.subtype (Litex.In.rep (2 : ℂ) (Litex.Rules.complexEqNatInNPos (2 : ℂ) 2 (by norm_num) (by norm_num)))) (Litex.AsReal.nat ((Litex.In.rep (2 : ℂ) (Litex.Rules.complexEqNatInNPos (2 : ℂ) 2 (by norm_num) (by norm_num)))).val)))) (Litex.Same.realComplex (1 : ℝ)))

end __Compiler_30_IndexedSequenceCompilerEnvironment
