-- Generated by StmtResultToLeanCompiler from 31_FiniteSequenceCompilerEnvironment.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_31_FiniteSequenceCompilerEnvironment

noncomputable def bounded_sequence : Litex.FnTelescope.Carrier ((Litex.FnTelescope.parameter Litex.NPos (fun {__alpha1 : Type} (__arg1 : __alpha1) (__arg1_in : Litex.In __arg1 Litex.NPos) => (Litex.FnTelescope.requirement (Litex.positiveNaturalParameterLessEqualNaturalBound __arg1 (3 : Nat)) (fun __domain => (Litex.FnTelescope.done Litex.R))))) : Litex.FnTelescope.{0}) :=
  fun {__alpha1 : Type} (__arg1 : __alpha1) (__arg1_in : Litex.In __arg1 Litex.NPos) => fun __arg_domain => ULift.up ((((((Litex.In.rep __arg1 __arg1_in).val : ℕ) : ℝ)) + (1 : ℝ)))

theorem __fact0 : Litex.In (@bounded_sequence) (Litex.finiteSequenceSet.{0} Litex.R (3 : Nat)) := by
  exact Litex.In.own (Litex.finiteSequenceSet.{0} Litex.R (3 : Nat)) (@bounded_sequence)

theorem __fact1 : Litex.In (@bounded_sequence) (Litex.fnTelescopeSet ((Litex.FnTelescope.parameter Litex.NPos (fun {__alpha1 : Type} (__arg1 : __alpha1) (__arg1_in : Litex.In __arg1 Litex.NPos) => (Litex.FnTelescope.requirement (Litex.positiveNaturalParameterLessEqualNaturalBound __arg1 (3 : Nat)) (fun __domain => (Litex.FnTelescope.done Litex.R))))) : Litex.FnTelescope.{0})) := by
  exact Litex.In.own (Litex.fnTelescopeSet ((Litex.FnTelescope.parameter Litex.NPos (fun {__alpha1 : Type} (__arg1 : __alpha1) (__arg1_in : Litex.In __arg1 Litex.NPos) => (Litex.FnTelescope.requirement (Litex.positiveNaturalParameterLessEqualNaturalBound __arg1 (3 : Nat)) (fun __domain => (Litex.FnTelescope.done Litex.R))))) : Litex.FnTelescope.{0})) (@bounded_sequence)

theorem __fact2 : Litex.Same (@bounded_sequence) (fun {__alpha1 : Type} (__arg1 : __alpha1) (__arg1_in : Litex.In __arg1 Litex.NPos) => fun __arg_domain => ULift.up ((((((Litex.In.rep __arg1 __arg1_in).val : ℕ) : ℝ)) + (1 : ℝ))) : Litex.FnTelescope.Carrier ((Litex.FnTelescope.parameter Litex.NPos (fun {__alpha1 : Type} (__arg1 : __alpha1) (__arg1_in : Litex.In __arg1 Litex.NPos) => (Litex.FnTelescope.requirement (Litex.positiveNaturalParameterLessEqualNaturalBound __arg1 (3 : Nat)) (fun __domain => (Litex.FnTelescope.done Litex.R))))) : Litex.FnTelescope.{0})) := by
  unfold bounded_sequence
  exact Litex.Same.refl (fun {__alpha1 : Type} (__arg1 : __alpha1) (__arg1_in : Litex.In __arg1 Litex.NPos) => fun __arg_domain => ULift.up ((((((Litex.In.rep __arg1 __arg1_in).val : ℕ) : ℝ)) + (1 : ℝ))) : Litex.FnTelescope.Carrier ((Litex.FnTelescope.parameter Litex.NPos (fun {__alpha1 : Type} (__arg1 : __alpha1) (__arg1_in : Litex.In __arg1 Litex.NPos) => (Litex.FnTelescope.requirement (Litex.positiveNaturalParameterLessEqualNaturalBound __arg1 (3 : Nat)) (fun __domain => (Litex.FnTelescope.done Litex.R))))) : Litex.FnTelescope.{0}))

theorem __fact3 : @Litex.Same _ _ (Litex.ComplexObserver.none _) (Litex.ComplexObserver.none _) ((((Litex.fnTelescopeApplyOwn (signature := ((Litex.FnTelescope.parameter Litex.NPos (fun {__alpha1 : Type} (__arg1 : __alpha1) (__arg1_in : Litex.In __arg1 Litex.NPos) => (Litex.FnTelescope.requirement (Litex.positiveNaturalParameterLessEqualNaturalBound __arg1 (3 : Nat)) (fun __domain => (Litex.FnTelescope.done Litex.R))))) : Litex.FnTelescope.{0})) (@bounded_sequence) ((Litex.In.own (Litex.fnTelescopeSet ((Litex.FnTelescope.parameter Litex.NPos (fun {__alpha1 : Type} (__arg1 : __alpha1) (__arg1_in : Litex.In __arg1 Litex.NPos) => (Litex.FnTelescope.requirement (Litex.positiveNaturalParameterLessEqualNaturalBound __arg1 (3 : Nat)) (fun __domain => (Litex.FnTelescope.done Litex.R))))) : Litex.FnTelescope.{0})) (@bounded_sequence)))) (⟨2, by norm_num⟩ : Litex.NPos.Carrier) (Litex.In.own Litex.NPos (⟨2, by norm_num⟩ : Litex.NPos.Carrier))) (⟨((2 : ℕ) : ℂ), (Litex.Same.transNoObservation (Litex.Same.subtypeNoObservation ((⟨2, by norm_num⟩ : Litex.NPos.Carrier))) (Litex.Same.natComplexNoObservation (((⟨2, by norm_num⟩ : Litex.NPos.Carrier)).val))), (by simpa using ((Litex.OrderBridge.leOfComplexReals (by norm_num) : Litex.Le ((2 : ℂ)) ((3 : ℂ)))))⟩))).down ((2 : ℂ) + (1 : ℂ)) := by
  exact Litex.Same.transNoObservation ((by
  unfold Litex.fnTelescopeApplyOwn bounded_sequence
  exact Litex.Same.realAddComplexNoObservation (Litex.Same.withoutObservation ((by
  have __selected := Litex.In.rep_exact (⟨2, by norm_num⟩ : Litex.NPos.Carrier) (Litex.In.own Litex.NPos (⟨2, by norm_num⟩ : Litex.NPos.Carrier))
  convert (Litex.Same.realComplex (2 : ℝ)) using 1
  · exact congrArg (fun value : Litex.NPos.Carrier => (((value.val : ℕ) : ℝ))) __selected
  · norm_num))) (Litex.Same.withoutObservation (Litex.Same.realComplex (1 : ℝ))))) (Litex.Same.reflNoObservation ((2 : ℂ) + (1 : ℂ)))

end __Compiler_31_FiniteSequenceCompilerEnvironment
