-- Generated by StmtResultToLeanCompiler from 33_NonemptySetWitnessCompilerEnvironment.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_33_NonemptySetWitnessCompilerEnvironment

theorem __fact0 : Litex.Set.Nonempty (Litex.Set.coproduct (Litex.Set.singleton (1 : ℂ)) (Litex.Set.coproduct (Litex.Set.singleton (2 : ℂ)) Litex.Set.empty)) := by
  have __nonempty_membership : Litex.In (1 : ℂ) (Litex.Set.coproduct (Litex.Set.singleton (1 : ℂ)) (Litex.Set.coproduct (Litex.Set.singleton (2 : ℂ)) Litex.Set.empty)) := by
    exact ⟨Sum.inl (Litex.SingletonCarrier.element), Litex.Same.trans (Litex.Same.refl (1 : ℂ)) (Litex.Same.trans (Litex.Same.singleton (1 : ℂ)) (Litex.Same.sumLeft (Litex.SingletonCarrier.element)))⟩
  rcases __nonempty_membership with ⟨__nonempty_witness, __nonempty_same⟩
  exact ⟨__nonempty_witness⟩

end __Compiler_33_NonemptySetWitnessCompilerEnvironment
