-- Generated by StmtResultToLeanCompiler from 34_PredicateBackedWitnessResultComposition.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_34_PredicateBackedWitnessResultComposition

def has_copy (a : (Litex.R).Carrier) : Prop :=
  (Litex.In a Litex.R) ∧ (∃ (x : (Litex.R).Carrier), ∃ (__type_x : Litex.In x Litex.R), Litex.Same x a)

theorem __fact0 : has_copy (2 : ℝ) := by
  unfold has_copy
  exact ⟨Litex.In.own Litex.R (2 : ℝ), (by
  rcases ((show ∃ (x : (Litex.R).Carrier), ∃ (__type_x : Litex.In x Litex.R), Litex.Same x (2 : ℂ) from (by
  have __step0_0 : Litex.Same (2 : ℂ) (2 : ℂ) := by
    exact Litex.Same.refl (2 : ℂ)
  exact ⟨(2 : ℝ), (Litex.In.own Litex.R (2 : ℝ)), (Litex.Same.trans (Litex.Same.symm (Litex.Same.symm (Litex.Same.realComplex ((2 : ℝ))))) (__step0_0))⟩))) with ⟨__transport_witness, __transport_membership, __transport_body⟩
  exact ⟨__transport_witness, __transport_membership, Litex.Same.trans (__transport_body) (Litex.Same.symm (Litex.Same.realComplex ((2 : ℝ))))⟩)⟩

theorem __fact1 : Litex.In (2 : ℝ) Litex.R := by
  exact (by
  have __definition := __fact0
  unfold has_copy at __definition
  simpa [Litex.fnApply, Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using __definition.1)

theorem __fact2 : ∃ (x : (Litex.R).Carrier), ∃ (__type_x : Litex.In x Litex.R), Litex.Same x (2 : ℝ) := by
  exact (by
  have __definition := __fact0
  unfold has_copy at __definition
  simpa [Litex.fnApply, Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using __definition.2)

end __Compiler_34_PredicateBackedWitnessResultComposition
