-- Generated by StmtResultToLeanCompiler from 41_ClearCompilerEnvironmentLayer.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_41_ClearCompilerEnvironmentLayer

abbrev A : Litex.Set := Litex.R

namespace __AfterClear01

abbrev A : Litex.Set := Litex.C

end __AfterClear01

end __Compiler_41_ClearCompilerEnvironmentLayer
