-- Generated by StmtResultToLeanCompiler from 47_DefinedPredicateInferenceCompilerEnvironment.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_47_DefinedPredicateInferenceCompilerEnvironment

def same_set (x : Litex.Set) (y : Litex.Set) : Prop :=
  (True) ∧ (True) ∧ (Litex.Same x y)

theorem __litex_registered_transitive_same_set_0 :
    ∀ (x : Litex.Set) (y : Litex.Set) (z : Litex.Set) (__domain_f16 : same_set x y) (__domain_f18 : same_set y z),
      same_set x z := by
  intro x y z __domain_f16 __domain_f18
  have __step0_0 : Litex.Same x y := by
    exact (show Litex.Same x y from (by
    have __definition := __domain_f16
    unfold same_set at __definition
    simpa [Litex.fnApply, Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using __definition.2.2))
  have __step0_1 : Litex.Same y z := by
    exact (show Litex.Same y z from (by
    have __definition := __domain_f18
    unfold same_set at __definition
    simpa [Litex.fnApply, Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using __definition.2.2))
  have __step0_2 : Litex.Same x z := by
    exact Litex.Same.trans (__step0_0) (__step0_1)
  have __step0_3 : same_set x z := by
    exact (by
    unfold same_set
    exact ⟨True.intro, True.intro, (by simpa [Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using (__step0_2))⟩)
  have __c0_0 : same_set x z := __step0_3
  exact __c0_0

axiom __fact1 : same_set Litex.R Litex.C

theorem __fact2 : True := by
  exact (by
  have __definition := __fact1
  unfold same_set at __definition
  simpa [Litex.fnApply, Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using __definition.1)

theorem __fact3 : True := by
  exact (by
  have __definition := __fact1
  unfold same_set at __definition
  simpa [Litex.fnApply, Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using __definition.2.1)

theorem __fact4 : Litex.Same Litex.R Litex.C := by
  exact (by
  have __definition := __fact1
  unfold same_set at __definition
  simpa [Litex.fnApply, Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using __definition.2.2)

axiom __fact5 : same_set Litex.C Litex.N

theorem __fact6 : True := by
  exact (by
  have __definition := __fact5
  unfold same_set at __definition
  simpa [Litex.fnApply, Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using __definition.2.1)

theorem __fact7 : Litex.Same Litex.C Litex.N := by
  exact (by
  have __definition := __fact5
  unfold same_set at __definition
  simpa [Litex.fnApply, Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using __definition.2.2)

theorem __fact8 : (same_set Litex.R Litex.C) ∧ (same_set Litex.C Litex.N) := by
  exact ⟨__fact1, __fact5⟩

theorem __fact9 : same_set Litex.R Litex.N := by
  exact __litex_registered_transitive_same_set_0 Litex.R Litex.C Litex.N ((__fact8).1) ((__fact8).2)

theorem __fact10 : same_set Litex.R Litex.N := by
  exact __fact9

theorem __fact11 : Litex.Same Litex.R Litex.N := by
  exact (by
  have __definition := __fact10
  unfold same_set at __definition
  simpa [Litex.fnApply, Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using __definition.2.2)

end __Compiler_47_DefinedPredicateInferenceCompilerEnvironment
