-- Generated by StmtResultToLeanCompiler from 52_IntegerRangeIterationResultComposition.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_52_IntegerRangeIterationResultComposition

theorem __fact0 :
    ∀ (__p1 : ℂ) (__type1 : Litex.In __p1 (Litex.range (0 : ℤ) (3 : ℤ))), Litex.Lt (((((Litex.In.rep n __type1)).val : ℤ)) : ℂ) (3 : ℂ) := by
  intro n __type1
  have __range_bounds := ((Litex.In.rep n __type1)).property
  simp only [Finset.mem_Ico] at __range_bounds
  have __range_value_cases : ((Litex.In.rep n __type1)).val = (0 : ℤ) ∨ ((Litex.In.rep n __type1)).val = (1 : ℤ) ∨ ((Litex.In.rep n __type1)).val = (2 : ℤ) := by omega
  have __assignment_cases : Litex.Same n (0 : ℂ) ∨ Litex.Same n (1 : ℂ) ∨ Litex.Same n (2 : ℂ) := by
    rcases __range_value_cases with __range_value_case1 | __range_value_case2 | __range_value_case3
    ·
      exact Or.inl (Litex.Same.trans (Litex.Same.trans (Litex.In.same_rep n __type1) (Litex.Same.subtype (Litex.In.rep n __type1))) (by simpa [__range_value_case1] using Litex.Same.intComplex ((Litex.In.rep n __type1)).val))
    ·
      exact Or.inr (Or.inl (Litex.Same.trans (Litex.Same.trans (Litex.In.same_rep n __type1) (Litex.Same.subtype (Litex.In.rep n __type1))) (by simpa [__range_value_case2] using Litex.Same.intComplex ((Litex.In.rep n __type1)).val)))
    ·
      exact Or.inr (Or.inr (Litex.Same.trans (Litex.Same.trans (Litex.In.same_rep n __type1) (Litex.Same.subtype (Litex.In.rep n __type1))) (by simpa [__range_value_case3] using Litex.Same.intComplex ((Litex.In.rep n __type1)).val)))
  rcases __assignment_cases with __assignment1 | __assignment2 | __assignment3
  ·
    have __assignment1_in_z : Litex.In n Litex.Z := Litex.Rules.complexEqIntInZ (((((Litex.In.rep n __type1)).val : ℤ) : ℂ)) (((Litex.In.rep n __type1)).val : ℤ) (by rfl)
    exact (by
  norm_num [Litex.Lt, Litex.Le, Litex.OrderValue, __range_value_case1])
  ·
    have __assignment2_in_z : Litex.In n Litex.Z := Litex.Rules.complexEqIntInZ (((((Litex.In.rep n __type1)).val : ℤ) : ℂ)) (((Litex.In.rep n __type1)).val : ℤ) (by rfl)
    exact (by
  norm_num [Litex.Lt, Litex.Le, Litex.OrderValue, __range_value_case2])
  ·
    have __assignment3_in_z : Litex.In n Litex.Z := Litex.Rules.complexEqIntInZ (((((Litex.In.rep n __type1)).val : ℤ) : ℂ)) (((Litex.In.rep n __type1)).val : ℤ) (by rfl)
    exact (by
  norm_num [Litex.Lt, Litex.Le, Litex.OrderValue, __range_value_case3])

end __Compiler_52_IntegerRangeIterationResultComposition
