-- Generated by StmtResultToLeanCompiler from 53_RuntimeResolvedComparisonFromDefinitionResults.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_53_RuntimeResolvedComparisonFromDefinitionResults

noncomputable def a := (1 : ℂ)

theorem __fact0 : Litex.In a Litex.R := by
  unfold a
  exact Litex.Rules.complexRealInR (1 : ℝ)

theorem __fact1 : Litex.Same a (1 : ℂ) := by
  unfold a
  exact Litex.Same.refl (1 : ℂ)

noncomputable def b := (2 : ℂ)

theorem __fact2 : Litex.In b Litex.R := by
  unfold b
  exact Litex.Rules.complexRealInR (2 : ℝ)

theorem __fact3 : Litex.Same b (2 : ℂ) := by
  unfold b
  exact Litex.Same.refl (2 : ℂ)

theorem __fact4 : Litex.Nonnegative (a + b) := by
  exact (by
  unfold a b
  exact (Litex.Rules.complexEqRealNonnegative (((1 : ℂ) + (2 : ℂ))) (3 : ℝ) (by norm_num) (by norm_num)))

theorem __fact5 : Litex.Nonpositive ((-1 : ℂ) * (a + b)) := by
  exact Litex.Rules.complexNegativeOneMulNonpositive (__fact4)

end __Compiler_53_RuntimeResolvedComparisonFromDefinitionResults
