-- Generated by StmtResultToLeanCompiler from 54_ComplexAlgebraicCalculation.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_54_ComplexAlgebraicCalculation

theorem __fact0 : Litex.Same (((2 : ℂ) * Complex.I) + (1 : ℂ)) (((Complex.I * Complex.I) + (2 : ℂ)) + ((2 : ℂ) * Complex.I)) := by
  exact Litex.Same.ofEq (by
  ring_nf <;> norm_num [Complex.I_mul_I] <;> ring)

theorem __fact1 : Litex.Same (((1 : ℂ) + Complex.I) * ((1 : ℂ) - Complex.I)) (2 : ℂ) := by
  exact Litex.Same.ofEq (by
  ring_nf <;> norm_num [Complex.I_mul_I] <;> ring)

theorem __fact2 : Litex.Same ((1 : ℂ) / Complex.I) (((-1 : ℂ) * (1 : ℂ)) * Complex.I) := by
  exact Litex.Same.ofEq (by
  ring_nf <;> norm_num [Complex.I_mul_I] <;> ring)

theorem __fact3 :
    ∀ (__p1 : ℂ) (__type1 : Litex.In __p1 Litex.C), Litex.Same (((Litex.In.rep __p1 __type1 : ℂ) + Complex.I) * ((Litex.In.rep __p1 __type1 : ℂ) - Complex.I)) (((Litex.In.rep __p1 __type1 : ℂ) * (Litex.In.rep __p1 __type1 : ℂ)) + (1 : ℂ)) := by
  intro z __h3_1
  have __c3_0 : Litex.Same (((Litex.In.rep z __h3_1 : ℂ) + Complex.I) * ((Litex.In.rep z __h3_1 : ℂ) - Complex.I)) (((Litex.In.rep z __h3_1 : ℂ) * (Litex.In.rep z __h3_1 : ℂ)) + (1 : ℂ)) := Litex.Same.ofEq (by
    ring_nf <;> norm_num [Complex.I_mul_I] <;> ring)
  exact __c3_0

end __Compiler_54_ComplexAlgebraicCalculation
