-- Generated by StmtResultToLeanCompiler from 57_KnownForallFactIdProvenance.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_57_KnownForallFactIdProvenance

def first_left (x : (Litex.R).Carrier) : Prop :=
  (Litex.In x Litex.R) ∧ (Litex.Same x x)

def first_right (x : (Litex.R).Carrier) : Prop :=
  (Litex.In x Litex.R) ∧ (Litex.Same x x)

def second_left (x : (Litex.R).Carrier) : Prop :=
  (Litex.In x Litex.R) ∧ (Litex.Same x x)

def second_right (x : (Litex.R).Carrier) : Prop :=
  (Litex.In x Litex.R) ∧ (Litex.Same x x)

theorem paired_source :
    ∀ (x : (Litex.R).Carrier) (__h17 : Litex.In x Litex.R),
      (((first_left (x : ℝ)) ∧ (first_right (x : ℝ)))) ∧ (((second_left (x : ℝ)) ∧ (second_right (x : ℝ)))) := by
  intro x __h17
  have __step0_0 : first_left (x : ℝ) := by
    exact (by
    unfold first_left
    exact ⟨Litex.In.own Litex.R (x : ℝ), Litex.Same.refl ((x : ℝ))⟩)
  have __step0_1 : first_right (x : ℝ) := by
    exact (by
    unfold first_right
    exact ⟨Litex.In.own Litex.R (x : ℝ), Litex.Same.refl ((x : ℝ))⟩)
  have __step0_2 : second_left (x : ℝ) := by
    exact (by
    unfold second_left
    exact ⟨Litex.In.own Litex.R (x : ℝ), Litex.Same.refl ((x : ℝ))⟩)
  have __step0_3 : second_right (x : ℝ) := by
    exact (by
    unfold second_right
    exact ⟨Litex.In.own Litex.R (x : ℝ), Litex.Same.refl ((x : ℝ))⟩)
  have __c0_0 : (first_left (x : ℝ)) ∧ (first_right (x : ℝ)) := ⟨__step0_0, __step0_1⟩
  have __c0_1 : (second_left (x : ℝ)) ∧ (second_right (x : ℝ)) := ⟨__step0_2, __step0_3⟩
  exact ⟨__c0_0, __c0_1⟩

theorem __fact1 : (first_left (2 : ℝ)) ∧ (first_right (2 : ℝ)) := by
  exact (by
  simpa [Litex.In.rep, Litex.fnApply, Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using (paired_source (2 : ℝ) ((Litex.In.congr (Litex.Same.symm (Litex.Same.realComplex ((2 : ℝ)))) Litex.R).mp (Litex.Rules.complexRealInR (2 : ℝ)))).1)

theorem __fact2 : Litex.In (2 : ℝ) Litex.R := by
  exact (by
  have __definition := (__fact1).1
  unfold first_left at __definition
  simpa [Litex.fnApply, Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using __definition.1)

theorem __fact3 : Litex.Same (2 : ℝ) (2 : ℝ) := by
  exact (by
  have __definition := (__fact1).1
  unfold first_left at __definition
  simpa [Litex.fnApply, Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using __definition.2)

theorem __fact4 : (second_left (2 : ℝ)) ∧ (second_right (2 : ℝ)) := by
  exact (by
  simpa [Litex.In.rep, Litex.fnApply, Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using (paired_source (2 : ℝ) (__fact2)).2)

end __Compiler_57_KnownForallFactIdProvenance
