-- Generated by StmtResultToLeanCompiler from 59_TransparentLetResolution.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_59_TransparentLetResolution

noncomputable def f : Litex.Fn Litex.R Litex.R :=
  { call := fun {__alpha} (__arg : __alpha) __arg_in => Litex.In.rep __arg __arg_in }

theorem __fact0 : Litex.In f (Litex.fnSet Litex.R Litex.R) := by
  exact Litex.In.own (Litex.fnSet Litex.R Litex.R) f

theorem __fact1 : Litex.Same f ({ call := fun {__alpha} (__arg : __alpha) __arg_in => Litex.In.rep __arg __arg_in } : Litex.Fn Litex.R Litex.R) := by
  unfold f
  exact Litex.Same.refl ({ call := fun {__alpha} (__arg : __alpha) __arg_in => Litex.In.rep __arg __arg_in } : Litex.Fn Litex.R Litex.R)

noncomputable def g := f

theorem __fact2 : Litex.Same g f := by
  unfold g
  exact Litex.Same.refl f

theorem __fact3 : Litex.Same (Litex.fnApplyOwn g (Litex.In.own (Litex.fnSet Litex.R Litex.R) g) (1 : ℂ) (Litex.Rules.complexRealInR (1 : ℝ))) (1 : ℂ) := by
  exact (by
  unfold g
  exact ((by
  unfold Litex.fnApplyOwn f
  exact Litex.Same.symm (Litex.In.same_rep (1 : ℂ) (Litex.Rules.complexRealInR (1 : ℝ))))))

end __Compiler_59_TransparentLetResolution
