-- Generated by StmtResultToLeanCompiler from 63_ScalarOperatorBuiltins.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_63_ScalarOperatorBuiltins

theorem __fact0 :
    ∀ (__p1 : (Litex.R).Carrier) (__type1 : Litex.In (α := (Litex.R).Carrier) __p1 Litex.R) (__p2 : (Litex.R).Carrier) (__type2 : Litex.In (α := (Litex.R).Carrier) __p2 Litex.R), (Litex.Same (Litex.abs (((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) * ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ))) ((Litex.abs ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)) * (Litex.abs ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)))) ∧ (Litex.Le (Litex.abs (((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) + ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ))) ((Litex.abs ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)) + (Litex.abs ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)))) ∧ (Litex.Le (Litex.abs (((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) - ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ))) ((Litex.abs ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)) + (Litex.abs ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)))) ∧ (Litex.Le ((Litex.abs ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)) - (Litex.abs ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ))) (Litex.abs (((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) + ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)))) ∧ (Litex.Le ((Litex.abs ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)) - (Litex.abs ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ))) (Litex.abs (((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) - ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)))) := by
  intro x __h8 y __h9
  have __prior0_0 : Litex.Same (Litex.abs ((((Litex.In.rep x __h8 : ℝ)) : ℂ) * (((Litex.In.rep y __h9 : ℝ)) : ℂ))) ((Litex.abs (((Litex.In.rep x __h8 : ℝ)) : ℂ)) * (Litex.abs (((Litex.In.rep y __h9 : ℝ)) : ℂ))) := Litex.Rules.absMul (((Litex.In.rep x __h8 : ℝ)) : ℂ) (((Litex.In.rep y __h9 : ℝ)) : ℂ)
  have __prior0_1 : Litex.Le (Litex.abs ((((Litex.In.rep x __h8 : ℝ)) : ℂ) + (((Litex.In.rep y __h9 : ℝ)) : ℂ))) ((Litex.abs (((Litex.In.rep x __h8 : ℝ)) : ℂ)) + (Litex.abs (((Litex.In.rep y __h9 : ℝ)) : ℂ))) := Litex.Rules.absAddLe (((Litex.In.rep x __h8 : ℝ)) : ℂ) (((Litex.In.rep y __h9 : ℝ)) : ℂ)
  have __prior0_2 : Litex.Le (Litex.abs ((((Litex.In.rep x __h8 : ℝ)) : ℂ) - (((Litex.In.rep y __h9 : ℝ)) : ℂ))) ((Litex.abs (((Litex.In.rep x __h8 : ℝ)) : ℂ)) + (Litex.abs (((Litex.In.rep y __h9 : ℝ)) : ℂ))) := Litex.Rules.absSubLeSum (((Litex.In.rep x __h8 : ℝ)) : ℂ) (((Litex.In.rep y __h9 : ℝ)) : ℂ)
  have __prior0_3 : Litex.Le ((Litex.abs (((Litex.In.rep x __h8 : ℝ)) : ℂ)) - (Litex.abs (((Litex.In.rep y __h9 : ℝ)) : ℂ))) (Litex.abs ((((Litex.In.rep x __h8 : ℝ)) : ℂ) + (((Litex.In.rep y __h9 : ℝ)) : ℂ))) := Litex.Rules.absSubAbsLeAbsAdd (((Litex.In.rep x __h8 : ℝ)) : ℂ) (((Litex.In.rep y __h9 : ℝ)) : ℂ)
  have __prior0_4 : Litex.Le ((Litex.abs (((Litex.In.rep x __h8 : ℝ)) : ℂ)) - (Litex.abs (((Litex.In.rep y __h9 : ℝ)) : ℂ))) (Litex.abs ((((Litex.In.rep x __h8 : ℝ)) : ℂ) - (((Litex.In.rep y __h9 : ℝ)) : ℂ))) := Litex.Rules.absSubAbsLeAbsSub (((Litex.In.rep x __h8 : ℝ)) : ℂ) (((Litex.In.rep y __h9 : ℝ)) : ℂ)
  exact ⟨__prior0_0, __prior0_1, __prior0_2, __prior0_3, __prior0_4⟩

theorem __fact1 :
    ∀ (__p1 : (Litex.R).Carrier) (__type1 : Litex.In (α := (Litex.R).Carrier) __p1 Litex.R), (Litex.Nonnegative (Litex.abs ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ))) ∧ (Litex.Le ((-1 : ℂ) * (Litex.abs ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ))) ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)) ∧ (Litex.Le ((-1 : ℂ) * ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)) (Litex.abs ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ))) ∧ (Litex.Le ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) (Litex.abs ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ))) := by
  intro x __h21
  have __prior1_0 : Litex.Nonnegative (Litex.abs (((Litex.In.rep x __h21 : ℝ)) : ℂ)) := Litex.Rules.absNonnegative (((Litex.In.rep x __h21 : ℝ)) : ℂ)
  have __prior1_1 : Litex.Le ((-1 : ℂ) * (Litex.abs (((Litex.In.rep x __h21 : ℝ)) : ℂ))) (((Litex.In.rep x __h21 : ℝ)) : ℂ) := Litex.Rules.negAbsLe (((Litex.In.rep x __h21 : ℝ)) : ℂ)
  have __prior1_2 : Litex.Le ((-1 : ℂ) * (((Litex.In.rep x __h21 : ℝ)) : ℂ)) (Litex.abs (((Litex.In.rep x __h21 : ℝ)) : ℂ)) := Litex.Rules.negLeAbs (((Litex.In.rep x __h21 : ℝ)) : ℂ)
  have __prior1_3 : Litex.Le (((Litex.In.rep x __h21 : ℝ)) : ℂ) (Litex.abs (((Litex.In.rep x __h21 : ℝ)) : ℂ)) := Litex.Rules.selfLeAbs (((Litex.In.rep x __h21 : ℝ)) : ℂ)
  exact ⟨__prior1_0, __prior1_1, __prior1_2, __prior1_3⟩

theorem __fact2 :
    ∀ (__p1 : (Litex.R).Carrier) (__type1 : Litex.In (α := (Litex.R).Carrier) __p1 Litex.R) (__p2 : (Litex.R).Carrier) (__type2 : Litex.In (α := (Litex.R).Carrier) __p2 Litex.R), (Litex.Le (Litex.min ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)) ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)) ∧ (Litex.Le (Litex.min ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)) ∧ (Litex.Le ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) (Litex.max ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ))) ∧ (Litex.Le ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ) (Litex.max ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ))) ∧ (Litex.Same (Litex.min ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)) (Litex.min ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ) ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ))) ∧ (Litex.Same (Litex.max ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)) (Litex.max ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ) ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ))) ∧ (Litex.Same (Litex.min ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) (Litex.max ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ))) __p1) ∧ (Litex.Same (Litex.max ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) (Litex.min ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ))) __p1) := by
  intro a __h37 b __h38
  have __prior2_0 : Litex.Le (Litex.min (((Litex.In.rep a __h37 : ℝ)) : ℂ) (((Litex.In.rep b __h38 : ℝ)) : ℂ)) (((Litex.In.rep a __h37 : ℝ)) : ℂ) := Litex.Rules.minLeLeft (Litex.In.rep a __h37 : ℝ) (Litex.In.rep b __h38 : ℝ)
  have __prior2_1 : Litex.Le (Litex.min (((Litex.In.rep a __h37 : ℝ)) : ℂ) (((Litex.In.rep b __h38 : ℝ)) : ℂ)) (((Litex.In.rep b __h38 : ℝ)) : ℂ) := Litex.Rules.minLeRight (Litex.In.rep a __h37 : ℝ) (Litex.In.rep b __h38 : ℝ)
  have __prior2_2 : Litex.Le (((Litex.In.rep a __h37 : ℝ)) : ℂ) (Litex.max (((Litex.In.rep a __h37 : ℝ)) : ℂ) (((Litex.In.rep b __h38 : ℝ)) : ℂ)) := Litex.Rules.leMaxLeft (Litex.In.rep a __h37 : ℝ) (Litex.In.rep b __h38 : ℝ)
  have __prior2_3 : Litex.Le (((Litex.In.rep b __h38 : ℝ)) : ℂ) (Litex.max (((Litex.In.rep a __h37 : ℝ)) : ℂ) (((Litex.In.rep b __h38 : ℝ)) : ℂ)) := Litex.Rules.leMaxRight (Litex.In.rep a __h37 : ℝ) (Litex.In.rep b __h38 : ℝ)
  have __prior2_4 : Litex.Same (Litex.min (((Litex.In.rep a __h37 : ℝ)) : ℂ) (((Litex.In.rep b __h38 : ℝ)) : ℂ)) (Litex.min (((Litex.In.rep b __h38 : ℝ)) : ℂ) (((Litex.In.rep a __h37 : ℝ)) : ℂ)) := Litex.Rules.minCommutative (Litex.In.rep a __h37 : ℝ) (Litex.In.rep b __h38 : ℝ)
  have __prior2_5 : Litex.Same (Litex.max (((Litex.In.rep a __h37 : ℝ)) : ℂ) (((Litex.In.rep b __h38 : ℝ)) : ℂ)) (Litex.max (((Litex.In.rep b __h38 : ℝ)) : ℂ) (((Litex.In.rep a __h37 : ℝ)) : ℂ)) := Litex.Rules.maxCommutative (Litex.In.rep a __h37 : ℝ) (Litex.In.rep b __h38 : ℝ)
  have __prior2_6 : Litex.Same (Litex.min (((Litex.In.rep a __h37 : ℝ)) : ℂ) (Litex.max (((Litex.In.rep a __h37 : ℝ)) : ℂ) (((Litex.In.rep b __h38 : ℝ)) : ℂ))) a := Litex.Same.trans (Litex.Rules.minAbsorbMaxLeft (Litex.In.rep a __h37 : ℝ) (Litex.In.rep b __h38 : ℝ)) (Litex.Same.trans (Litex.Same.symm (Litex.Same.realComplex ((Litex.In.rep a __h37 : ℝ)))) (Litex.Same.ofEq (by simp [Litex.In.rep])))
  have __prior2_7 : Litex.Same (Litex.max (((Litex.In.rep a __h37 : ℝ)) : ℂ) (Litex.min (((Litex.In.rep a __h37 : ℝ)) : ℂ) (((Litex.In.rep b __h38 : ℝ)) : ℂ))) a := Litex.Same.trans (Litex.Rules.maxAbsorbMinLeft (Litex.In.rep a __h37 : ℝ) (Litex.In.rep b __h38 : ℝ)) (Litex.Same.trans (Litex.Same.symm (Litex.Same.realComplex ((Litex.In.rep a __h37 : ℝ)))) (Litex.Same.ofEq (by simp [Litex.In.rep])))
  exact ⟨__prior2_0, __prior2_1, __prior2_2, __prior2_3, __prior2_4, __prior2_5, __prior2_6, __prior2_7⟩

theorem __fact3 :
    ∀ (__p1 : (Litex.R).Carrier) (__type1 : Litex.In (α := (Litex.R).Carrier) __p1 Litex.R), (Litex.Same (Litex.min ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)) __p1) ∧ (Litex.Same (Litex.max ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)) __p1) := by
  intro a __h51
  have __prior3_0 : Litex.Same (Litex.min (((Litex.In.rep a __h51 : ℝ)) : ℂ) (((Litex.In.rep a __h51 : ℝ)) : ℂ)) a := Litex.Same.trans (Litex.Rules.minIdempotent (Litex.In.rep a __h51 : ℝ)) (Litex.Same.trans (Litex.Same.symm (Litex.Same.realComplex ((Litex.In.rep a __h51 : ℝ)))) (Litex.Same.ofEq (by simp [Litex.In.rep])))
  have __prior3_1 : Litex.Same (Litex.max (((Litex.In.rep a __h51 : ℝ)) : ℂ) (((Litex.In.rep a __h51 : ℝ)) : ℂ)) a := Litex.Same.trans (Litex.Rules.maxIdempotent (Litex.In.rep a __h51 : ℝ)) (Litex.Same.trans (Litex.Same.symm (Litex.Same.realComplex ((Litex.In.rep a __h51 : ℝ)))) (Litex.Same.ofEq (by simp [Litex.In.rep])))
  exact ⟨__prior3_0, __prior3_1⟩

theorem __fact4 :
    ∀ (__p1 : (Litex.R).Carrier) (__type1 : Litex.In (α := (Litex.R).Carrier) __p1 Litex.R) (__p2 : (Litex.R).Carrier) (__type2 : Litex.In (α := (Litex.R).Carrier) __p2 Litex.R) (__p3 : (Litex.R).Carrier) (__type3 : Litex.In (α := (Litex.R).Carrier) __p3 Litex.R), (Litex.Same (Litex.min (Litex.min ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)) ((((Litex.In.rep __p3 __type3) : ℝ)) : ℂ)) (Litex.min ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) (Litex.min ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ) ((((Litex.In.rep __p3 __type3) : ℝ)) : ℂ)))) ∧ (Litex.Same (Litex.max (Litex.max ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)) ((((Litex.In.rep __p3 __type3) : ℝ)) : ℂ)) (Litex.max ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) (Litex.max ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ) ((((Litex.In.rep __p3 __type3) : ℝ)) : ℂ)))) := by
  intro a __h60 b __h61 c __h62
  have __prior4_0 : Litex.Same (Litex.min (Litex.min (((Litex.In.rep a __h60 : ℝ)) : ℂ) (((Litex.In.rep b __h61 : ℝ)) : ℂ)) (((Litex.In.rep c __h62 : ℝ)) : ℂ)) (Litex.min (((Litex.In.rep a __h60 : ℝ)) : ℂ) (Litex.min (((Litex.In.rep b __h61 : ℝ)) : ℂ) (((Litex.In.rep c __h62 : ℝ)) : ℂ))) := Litex.Rules.minAssociative (Litex.In.rep a __h60 : ℝ) (Litex.In.rep b __h61 : ℝ) (Litex.In.rep c __h62 : ℝ)
  have __prior4_1 : Litex.Same (Litex.max (Litex.max (((Litex.In.rep a __h60 : ℝ)) : ℂ) (((Litex.In.rep b __h61 : ℝ)) : ℂ)) (((Litex.In.rep c __h62 : ℝ)) : ℂ)) (Litex.max (((Litex.In.rep a __h60 : ℝ)) : ℂ) (Litex.max (((Litex.In.rep b __h61 : ℝ)) : ℂ) (((Litex.In.rep c __h62 : ℝ)) : ℂ))) := Litex.Rules.maxAssociative (Litex.In.rep a __h60 : ℝ) (Litex.In.rep b __h61 : ℝ) (Litex.In.rep c __h62 : ℝ)
  exact ⟨__prior4_0, __prior4_1⟩

theorem __fact5 :
    ∀ (__p1 : (Litex.R).Carrier) (__type1 : Litex.In (α := (Litex.R).Carrier) __p1 Litex.R) (__p2 : (Litex.R).Carrier) (__type2 : Litex.In (α := (Litex.R).Carrier) __p2 Litex.R) (__domain1 : Litex.Le ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)), (Litex.Same (Litex.min ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)) __p1) ∧ (Litex.Same (Litex.max ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)) __p2) := by
  intro a __h71 b __h72 __domain_f73
  have __prior5_0 : Litex.Same (Litex.min (((Litex.In.rep a __h71 : ℝ)) : ℂ) (((Litex.In.rep b __h72 : ℝ)) : ℂ)) a := Litex.Same.trans (Litex.Rules.minEqLeftOfLe (Litex.In.rep a __h71 : ℝ) (Litex.In.rep b __h72 : ℝ) (__domain_f73)) (Litex.Same.trans (Litex.Same.symm (Litex.Same.realComplex ((Litex.In.rep a __h71 : ℝ)))) (Litex.Same.ofEq (by simp [Litex.In.rep])))
  have __prior5_1 : Litex.Same (Litex.max (((Litex.In.rep a __h71 : ℝ)) : ℂ) (((Litex.In.rep b __h72 : ℝ)) : ℂ)) b := Litex.Same.trans (Litex.Rules.maxEqRightOfLe (Litex.In.rep a __h71 : ℝ) (Litex.In.rep b __h72 : ℝ) (__domain_f73)) (Litex.Same.trans (Litex.Same.symm (Litex.Same.realComplex ((Litex.In.rep b __h72 : ℝ)))) (Litex.Same.ofEq (by simp [Litex.In.rep])))
  exact ⟨__prior5_0, __prior5_1⟩

theorem __fact6 :
    ∀ (__p1 : (Litex.R).Carrier) (__type1 : Litex.In (α := (Litex.R).Carrier) __p1 Litex.R) (__p2 : (Litex.R).Carrier) (__type2 : Litex.In (α := (Litex.R).Carrier) __p2 Litex.R) (__p3 : (Litex.R).Carrier) (__type3 : Litex.In (α := (Litex.R).Carrier) __p3 Litex.R) (__p4 : (Litex.R).Carrier) (__type4 : Litex.In (α := (Litex.R).Carrier) __p4 Litex.R) (__domain1 : Litex.Le ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p3 __type3) : ℝ)) : ℂ)) (__domain2 : Litex.Le ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ) ((((Litex.In.rep __p4 __type4) : ℝ)) : ℂ)), (Litex.Le (Litex.min ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)) (Litex.min ((((Litex.In.rep __p3 __type3) : ℝ)) : ℂ) ((((Litex.In.rep __p4 __type4) : ℝ)) : ℂ))) ∧ (Litex.Le (Litex.max ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)) (Litex.max ((((Litex.In.rep __p3 __type3) : ℝ)) : ℂ) ((((Litex.In.rep __p4 __type4) : ℝ)) : ℂ))) := by
  intro a __h85 b __h86 c __h87 d __h88 __domain_f89 __domain_f90
  have __prior6_0 : Litex.Le (Litex.min (((Litex.In.rep a __h85 : ℝ)) : ℂ) (((Litex.In.rep b __h86 : ℝ)) : ℂ)) (Litex.min (((Litex.In.rep c __h87 : ℝ)) : ℂ) (((Litex.In.rep d __h88 : ℝ)) : ℂ)) := Litex.Rules.minMonotone (Litex.In.rep a __h85 : ℝ) (Litex.In.rep b __h86 : ℝ) (Litex.In.rep c __h87 : ℝ) (Litex.In.rep d __h88 : ℝ) (__domain_f89) (__domain_f90)
  have __prior6_1 : Litex.Le (Litex.max (((Litex.In.rep a __h85 : ℝ)) : ℂ) (((Litex.In.rep b __h86 : ℝ)) : ℂ)) (Litex.max (((Litex.In.rep c __h87 : ℝ)) : ℂ) (((Litex.In.rep d __h88 : ℝ)) : ℂ)) := Litex.Rules.maxMonotone (Litex.In.rep a __h85 : ℝ) (Litex.In.rep b __h86 : ℝ) (Litex.In.rep c __h87 : ℝ) (Litex.In.rep d __h88 : ℝ) (__domain_f89) (__domain_f90)
  exact ⟨__prior6_0, __prior6_1⟩

theorem __fact7 :
    ∀ (__p1 : (Litex.R).Carrier) (__type1 : Litex.In (α := (Litex.R).Carrier) __p1 Litex.R) (__domain1 : Litex.Le (0 : ℂ) ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)), Litex.Same (Litex.abs ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)) __p1 := by
  intro x __h97 __domain_f98
  have __prior7_0 : Litex.Same (Litex.abs (((Litex.In.rep x __h97 : ℝ)) : ℂ)) x := Litex.Same.trans (Litex.Rules.absEqSelfOfLe (Litex.In.rep x __h97 : ℝ) (__domain_f98)) (Litex.Same.trans (Litex.Same.symm (Litex.Same.realComplex ((Litex.In.rep x __h97 : ℝ)))) (Litex.Same.ofEq (by simp [Litex.In.rep])))
  exact __prior7_0

theorem __fact8 :
    ∀ (__p1 : (Litex.R).Carrier) (__type1 : Litex.In (α := (Litex.R).Carrier) __p1 Litex.R) (__domain1 : Litex.Le ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) (0 : ℂ)), Litex.Same (Litex.abs ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)) ((-1 : ℂ) * ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)) := by
  intro x __h105 __domain_f106
  have __infer8_0 : Litex.Nonnegative ((-1 : ℂ) * (((Litex.In.rep x __h105 : ℝ)) : ℂ)) := Litex.Rules.complexNegativeOneMulNonnegative (Litex.Rules.realCastNonpositive (Litex.In.rep x __h105 : ℝ) (__domain_f106))
  have __prior8_0 : Litex.Same (Litex.abs (((Litex.In.rep x __h105 : ℝ)) : ℂ)) ((-1 : ℂ) * (((Litex.In.rep x __h105 : ℝ)) : ℂ)) := Litex.Rules.absEqNegOfLe (Litex.In.rep x __h105 : ℝ) (__domain_f106)
  exact __prior8_0

theorem __fact9 :
    ∀ (__p1 : (Litex.R).Carrier) (__type1 : Litex.In (α := (Litex.R).Carrier) __p1 Litex.R) (__domain1 : ¬ @Litex.Same _ _ (Litex.ComplexObserver.none _) (Litex.ComplexObserver.none _) __p1 (0 : ℂ)), Litex.Positive (Litex.abs ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ)) := by
  intro x __h113 __domain_f114
  have __prior9_0 : Litex.Positive (Litex.abs (((Litex.In.rep x __h113 : ℝ)) : ℂ)) := Litex.Rules.absPositiveOfNotSameNoObservation x (Litex.In.rep x __h113 : ℝ) (Litex.Same.transNoObservation (Litex.Same.withoutObservation (Litex.In.same_rep x (__h113))) (Litex.Same.realComplexNoObservation ((Litex.In.rep x __h113 : ℝ)))) (__domain_f114)
  exact __prior9_0

theorem __fact10 :
    ∀ (__p1 : (Litex.R).Carrier) (__type1 : Litex.In (α := (Litex.R).Carrier) __p1 Litex.R) (__p2 : (Litex.R).Carrier) (__type2 : Litex.In (α := (Litex.R).Carrier) __p2 Litex.R) (__domain1 : Litex.Le (0 : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)), Litex.Le ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) (((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) + ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)) := by
  intro a __h121 b __h122 __domain_f123
  have __prior10_0 : Litex.Le (((Litex.In.rep a __h121 : ℝ)) : ℂ) ((((Litex.In.rep a __h121 : ℝ)) : ℂ) + (((Litex.In.rep b __h122 : ℝ)) : ℂ)) := Litex.Rules.realCastLeAddOfNonnegativeRight (Litex.In.rep a __h121 : ℝ) (Litex.In.rep b __h122 : ℝ) (__domain_f123)
  exact __prior10_0

theorem __fact11 :
    ∀ (__p1 : (Litex.R).Carrier) (__type1 : Litex.In (α := (Litex.R).Carrier) __p1 Litex.R) (__p2 : (Litex.R).Carrier) (__type2 : Litex.In (α := (Litex.R).Carrier) __p2 Litex.R) (__p3 : (Litex.R).Carrier) (__type3 : Litex.In (α := (Litex.R).Carrier) __p3 Litex.R) (__domain1 : Litex.Le ((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ)) (__domain2 : Litex.Le (0 : ℂ) ((((Litex.In.rep __p3 __type3) : ℝ)) : ℂ)), Litex.Le (((((Litex.In.rep __p1 __type1) : ℝ)) : ℂ) - ((((Litex.In.rep __p3 __type3) : ℝ)) : ℂ)) ((((Litex.In.rep __p2 __type2) : ℝ)) : ℂ) := by
  intro a __h132 b __h133 c __h134 __domain_f135 __domain_f136
  have __prior11_0 : Litex.Le ((((Litex.In.rep a __h132 : ℝ)) : ℂ) - (((Litex.In.rep c __h134 : ℝ)) : ℂ)) (((Litex.In.rep b __h133 : ℝ)) : ℂ) := Litex.Rules.realCastSubLeOfLeOfNonnegative (Litex.In.rep a __h132 : ℝ) (Litex.In.rep b __h133 : ℝ) (Litex.In.rep c __h134 : ℝ) (__domain_f135) (__domain_f136)
  exact __prior11_0

end __Compiler_63_ScalarOperatorBuiltins
