-- Generated by StmtResultToLeanCompiler from 65_ImplicitNumericBinder.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_65_ImplicitNumericBinder

def nested_natural_reflexivity (anchor : (Litex.R).Carrier) : Prop :=
  (Litex.In anchor Litex.R) ∧ (∀ {__carrier1 : Type} (__p1 : __carrier1) (__type1 : Litex.In __p1 Litex.N), Litex.Same __p1 __p1)

theorem __fact0 :
    ∀ {__carrier1 : Type} (__p1 : __carrier1) (__type1 : Litex.In __p1 Litex.N), Litex.Same __p1 __p1 := by
  intro __carrier1 n __h11
  have __infer0_0 : Litex.Le (0 : ℂ) (((Litex.In.rep n __h11 : ℕ)) : ℂ) := Litex.Rules.naturalRepNonnegative (__h11)
  have __infer0_1 : Litex.Nonpositive ((-1 : ℂ) * (((Litex.In.rep n __h11 : ℕ)) : ℂ)) := Litex.Rules.complexNegativeOneMulNonpositive (Litex.Rules.realCastNonnegative ((Litex.In.rep n __h11 : ℕ) : ℝ) (__infer0_0))
  have __prior0_0 : Litex.Same n n := Litex.Same.refl n
  exact __prior0_0

theorem __fact1 : nested_natural_reflexivity (0 : ℝ) := by
  exact (by
  unfold nested_natural_reflexivity
  exact ⟨Litex.In.own Litex.R (0 : ℝ), (by simpa [Litex.fnApplyOwn, Litex.abs, Complex.ext_iff, Real.norm_eq_abs] using (@__fact0))⟩)

theorem __fact2 :
    ∀ {__carrier1 : Type} (__p1 : __carrier1) (__type1 : Litex.In __p1 Litex.R), Litex.Same __p1 __p1 := by
  intro __carrier1 r __h20
  have __prior2_0 : Litex.Same r r := Litex.Same.refl r
  exact __prior2_0

theorem __fact3 :
    ∀ (__p1 : ℤ), Litex.Same __p1 __p1 := by
  intro z
  have __prior3_0 : Litex.Same z z := Litex.Same.refl z
  exact __prior3_0

theorem __fact4 :
    ∀ (__p1 : (Litex.RPos).Carrier) (__type1 : Litex.In __p1 Litex.RPos), Litex.Same __p1 __p1 := by
  intro epsilon __h31
  have __infer4_2 : Litex.Lt (0 : ℂ) ((((epsilon).val : ℝ)) : ℂ) := Litex.Rules.positiveRealCarrierPositive (__h31)
  have __prior4_0 : Litex.Same epsilon epsilon := Litex.Same.refl epsilon
  exact __prior4_0

end __Compiler_65_ImplicitNumericBinder
