-- Generated by StmtResultToLeanCompiler from 67_LocalRealCompleteness.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_67_LocalRealCompleteness

theorem local_real_completeness :
    ∀ (S : Litex.Set) {__carrier0_2 : Type} (upper : __carrier0_2) (__h16 : Litex.In upper Litex.R) (__domain1 : Litex.Subset S Litex.R) (__domain2 : Litex.Set.Nonempty S) (__domain3 : ∀ {__carrier1 : Type} (__p1 : __carrier1) (__type1 : Litex.In __p1 Litex.R) (__domain1 : Litex.In __p1 S), Litex.Le (((Litex.In.rep __p1 __type1 : ℝ)) : ℂ) (((Litex.In.rep upper __h16 : ℝ)) : ℂ)),
      ∃ (L : ℂ), ∃ (__type_L : Litex.In L Litex.R), Litex.RealLeastUpperBound S L := by
  intro S __carrier0_2 upper __h16 __domain1 __domain2 __domain3
  have __step1 : ∃ (lub : ℂ), ∃ (__type_lub : Litex.In lub Litex.R), Litex.RealLeastUpperBound S lub := by
    exact Litex.Rules.realLeastUpperBoundExists S upper (__domain1) (__domain2) (__h16) (__domain3)
  have __c0_0 : ∃ (L : ℂ), ∃ (__type_L : Litex.In L Litex.R), Litex.RealLeastUpperBound S L := __step1
  exact __c0_0

end __Compiler_67_LocalRealCompleteness
