-- Generated by StmtResultToLeanCompiler from 6_FactReplay.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_6_FactReplay

theorem __fact0 :
    ∀ (__p1 : Litex.Set) (__p2 : Litex.Set) (__domain1 : Litex.Same __p1 __p2), Litex.Same __p2 __p1 := by
  intro a b __domain_f7
  have __prior0_0 : Litex.Same b a := Litex.Same.symm (__domain_f7)
  exact __prior0_0

theorem __fact1 :
    ∀ (__p1 : Litex.Set) (__p2 : Litex.Set) (__p3 : Litex.Set) (__domain1 : Litex.Same __p1 __p2) (__domain2 : Litex.Same __p2 __p3), Litex.Same __p1 __p3 := by
  intro a b c __domain_f19 __domain_f20
  have __prior1_0 : Litex.Same a c := Litex.Same.trans (__domain_f19) (__domain_f20)
  exact __prior1_0

theorem __fact2 :
    ∀ (__p1 : Litex.Set) (__p2 : Litex.Set) (__domain1 : ¬ @Litex.Same _ _ (Litex.ComplexObserver.none _) (Litex.ComplexObserver.none _) __p1 __p2), ¬ @Litex.Same _ _ (Litex.ComplexObserver.none _) (Litex.ComplexObserver.none _) __p2 __p1 := by
  intro a b __domain_f29
  have __prior2_0 : ¬ @Litex.Same _ _ (Litex.ComplexObserver.none _) (Litex.ComplexObserver.none _) b a := Litex.Rules.notSameSymm (__domain_f29)
  exact __prior2_0

theorem __fact3 :
    ∀ (__p1 : Litex.Set) (__p2 : Litex.Set) (__domain1 : Litex.Same __p1 __p2), Litex.Same __p2 __p1 := __fact0

end __Compiler_6_FactReplay
