-- Generated by StmtResultToLeanCompiler from 7_PropositionalFacts.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_7_PropositionalFacts

theorem __fact0 : Litex.Same (1 : ℂ) (1 : ℂ) ∧ Litex.Same (2 : ℂ) (2 : ℂ) := by
  exact ⟨Litex.Same.refl (1 : ℂ), Litex.Same.refl (2 : ℂ)⟩

theorem __fact1 :
    ∀ (__p1 : Litex.Set) (__p2 : Litex.Set) (__domain1 : Litex.Same __p1 __p1) (__domain2 : Litex.Same __p2 __p2), Litex.Same __p1 __p1 ∧ Litex.Same __p2 __p2 := by
  intro a b __domain1 __domain2
  have __c1_0 : Litex.Same a a ∧ Litex.Same b b := ⟨__domain1, __domain2⟩
  exact __c1_0

theorem __fact2 :
    ∀ (__p1 : Litex.Set) (__p2 : Litex.Set) (__domain1 : Litex.Same __p1 __p1), Litex.Same __p1 __p1 ∨ Litex.Same __p2 __p2 := by
  intro a b __domain1
  have __c2_0 : Litex.Same a a ∨ Litex.Same b b := Or.inl (__domain1)
  exact __c2_0

theorem __fact3 :
    ∀ (__p1 : Litex.Set) (__p2 : Litex.Set) (__p3 : Litex.Set) (__p4 : Litex.Set) (__domain1 : ¬ Litex.Same __p1 __p2 ∧ ¬ Litex.Same __p3 __p4), ¬ Litex.Same __p3 __p4 := by
  intro a b c d __domain1
  have __infer3_0 : ¬ Litex.Same a b := (__domain1).1
  have __infer3_1 : ¬ Litex.Same c d := (__domain1).2
  have __c3_0 : ¬ Litex.Same c d := __infer3_1
  exact __c3_0

end __Compiler_7_PropositionalFacts
