-- Generated by compiler from 7_PropositionalFacts.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_7_PropositionalFacts

theorem __fact0 : Litex.Same (1 : ℂ) (1 : ℂ) ∧ Litex.Same (2 : ℂ) (2 : ℂ) := by
  exact ⟨Litex.Same.refl (1 : ℂ), Litex.Same.refl (2 : ℂ)⟩

theorem __fact1 :
    ∀ (a : Litex.Set) (b : Litex.Set) (__h1_3 : Litex.Same a a) (__h1_4 : Litex.Same b b),
      Litex.Same a a ∧ Litex.Same b b := by
  intro a b __h1_3 __h1_4
  have __c1_0 : Litex.Same a a ∧ Litex.Same b b := ⟨__h1_3, __h1_4⟩
  exact __c1_0

theorem __fact2 :
    ∀ (a : Litex.Set) (b : Litex.Set) (__h2_3 : Litex.Same a a),
      Litex.Same a a ∨ Litex.Same b b := by
  intro a b __h2_3
  have __c2_0 : Litex.Same a a ∨ Litex.Same b b := Or.inl (__h2_3)
  exact __c2_0

theorem __fact3 :
    ∀ (a : Litex.Set) (b : Litex.Set) (c : Litex.Set) (d : Litex.Set) (__h3_5 : ¬ Litex.Same a b ∧ ¬ Litex.Same c d),
      ¬ Litex.Same c d := by
  intro a b c d __h3_5
  have __i3_0 : ¬ Litex.Same c d := (__h3_5).2
  have __c3_0 : ¬ Litex.Same c d := __i3_0
  exact __c3_0

end __Compiler_7_PropositionalFacts
