-- Generated by compiler from 8_ProofScopes.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_8_ProofScopes

theorem one_eq_one :
    Litex.Same (1 : ℂ) (1 : ℂ) := by
  exact Litex.Same.refl (1 : ℂ)

theorem __fact1 : Litex.Same (2 : ℂ) (2 : ℂ) := by
  have __step1 : Litex.Same (2 : ℂ) (2 : ℂ) := by
    exact Litex.Same.refl (2 : ℂ)
  exact __step1

example : Litex.Same (3 : ℂ) (3 : ℂ) := by
  have __step1 : Litex.Same (3 : ℂ) (3 : ℂ) := by
    exact Litex.Same.refl (3 : ℂ)
  exact __step1

end __Compiler_8_ProofScopes
