-- Generated by StmtResultToLeanCompiler from 8_ProofScopes.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_8_ProofScopes

theorem one_eq_one :
    Litex.Same (1 : ℂ) (1 : ℂ) := by
  have __c0_0 : Litex.Same (1 : ℂ) (1 : ℂ) := Litex.Same.refl (1 : ℂ)
  exact __c0_0

theorem local_reflexivity :
    ∀ (x : ℂ) (__h1_1 : Litex.In x Litex.R),
      Litex.Same x x := by
  intro x __h1_1
  have __step1 : Litex.Same x x := by
    exact Litex.Same.refl x
  have __c1_0 : Litex.Same x x := __step1
  exact __c1_0

theorem __fact2 : Litex.Same (1 : ℂ) (1 : ℂ) := by
  exact (local_reflexivity (1 : ℂ) (Litex.Rules.complexRealInR (1 : ℝ)))

theorem __fact3 : Litex.Same (2 : ℂ) (2 : ℂ) := by
  have __step1 : Litex.Same (2 : ℂ) (2 : ℂ) := by
    exact Litex.Same.refl (2 : ℂ)
  exact __step1

example : Litex.Same (3 : ℂ) (3 : ℂ) := by
  have __step1 : Litex.Same (3 : ℂ) (3 : ℂ) := by
    exact Litex.Same.refl (3 : ℂ)
  exact __step1

end __Compiler_8_ProofScopes
