-- Generated by compiler from 9_CasesAndContradiction.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_9_CasesAndContradiction

theorem cases_and_contra :
    Litex.Same (2 : ℂ) (2 : ℂ) := by
  have __step1 : Litex.Same (1 : ℂ) (1 : ℂ) := by
    exact (by
    have __case1 : Litex.Same (1 : ℂ) (1 : ℂ) := Litex.Same.refl (1 : ℂ)
    have __case1_step1 : Litex.Same (2 : ℂ) (2 : ℂ) := by
      exact (by
      classical
      by_contra __reverse
      exact (__reverse) (Litex.Same.refl (2 : ℂ)))
    exact __case1)
  exact Litex.Same.refl (2 : ℂ)

end __Compiler_9_CasesAndContradiction
