-- Generated by StmtResultToLeanCompiler from main.lit. DO NOT EDIT.
import Litex

set_option linter.style.nameCheck false

namespace __Compiler_main

theorem litex_real_lt_to_le :
    ∀ (a : ℂ) (__h0_1 : Litex.In a Litex.R) (b : ℂ) (__h0_2 : Litex.In b Litex.R) (__domain1 : Litex.Lt (((Litex.In.rep a __h0_1 : ℝ)) : ℂ) (((Litex.In.rep b __h0_2 : ℝ)) : ℂ)),
      Litex.Le (((Litex.In.rep a __h0_1 : ℝ)) : ℂ) (((Litex.In.rep b __h0_2 : ℝ)) : ℂ) := by
  intro a __h0_1 b __h0_2 __domain1
  have __c0_0 : Litex.Le (((Litex.In.rep a __h0_1 : ℝ)) : ℂ) (((Litex.In.rep b __h0_2 : ℝ)) : ℂ) := Litex.Lt.toLe (__domain1)
  exact __c0_0

namespace Native

theorem litex_real_lt_to_le (a b : ℝ) (__domain1 : a < b) : a ≤ b := by
  exact Litex.OrderBridge.real_le_iff.mp
    (Litex.Lt.toLe (Litex.OrderBridge.ltOfReal __domain1))

end Native

end __Compiler_main
