import Litex

namespace LitexCompiled.file_lean_x2f_examples_x2f_decimal_x5f_and_x5f_fraction_x2f_statement_x2e_lit

universe u v1
variable {M : Litex.Semantics.{u}}

theorem fact_1 : ∀ {_Host_i1 : Type v1} [_rep_i1 : Litex.Representation M _Host_i1] (_value_i1 : Litex.Obj (M := M) _Host_i1) (_h_param_i1 : Litex.In _value_i1 (Litex.C (M := M))), Litex.Same (Litex.add _value_i1 (Litex.number (M := M) (0.125 : ℂ)) _h_param_i1 (Litex.numberInC (M := M) (0.125 : ℂ))) (Litex.add _value_i1 (Litex.div (Litex.number (M := M) (1 : ℂ)) (Litex.number (M := M) (8 : ℂ)) (Litex.numberInC (M := M) (1 : ℂ)) (Litex.numberInC (M := M) (8 : ℂ)) (Litex.NativeBridge.notSameOfDenoteNumber (Litex.number (M := M) (8 : ℂ)) (Litex.number (M := M) (0 : ℂ)) (8 : ℂ) (0 : ℂ) (Litex.NativeBridge.denoteNumber (M := M) (8 : ℂ)) (Litex.NativeBridge.denoteNumber (M := M) (0 : ℂ)) (by norm_num))) _h_param_i1 (Litex.NativeBridge.inOfDenoteNumber (Litex.div (Litex.number (M := M) (1 : ℂ)) (Litex.number (M := M) (8 : ℂ)) (Litex.numberInC (M := M) (1 : ℂ)) (Litex.numberInC (M := M) (8 : ℂ)) (Litex.NativeBridge.notSameOfDenoteNumber (Litex.number (M := M) (8 : ℂ)) (Litex.number (M := M) (0 : ℂ)) (8 : ℂ) (0 : ℂ) (Litex.NativeBridge.denoteNumber (M := M) (8 : ℂ)) (Litex.NativeBridge.denoteNumber (M := M) (0 : ℂ)) (by norm_num))) ((1 : ℂ) / (8 : ℂ)) (Litex.C (M := M)) (((Litex.NativeBridge.denoteDiv (Litex.number (M := M) (1 : ℂ)) (Litex.number (M := M) (8 : ℂ)) (Litex.numberInC (M := M) (1 : ℂ)) (Litex.numberInC (M := M) (8 : ℂ)) (Litex.NativeBridge.notSameOfDenoteNumber (Litex.number (M := M) (8 : ℂ)) (Litex.number (M := M) (0 : ℂ)) (8 : ℂ) (0 : ℂ) (Litex.NativeBridge.denoteNumber (M := M) (8 : ℂ)) (Litex.NativeBridge.denoteNumber (M := M) (0 : ℂ)) (by norm_num)) (1 : ℂ) (8 : ℂ) (Litex.NativeBridge.denoteNumber (M := M) (1 : ℂ)) (Litex.NativeBridge.denoteNumber (M := M) (8 : ℂ)))).trans (congrArg M.number (by norm_num : ((1 : ℂ) / (8 : ℂ)) = ((1 : ℂ) / (8 : ℂ))))) (Litex.numberInC (M := M) ((1 : ℂ) / (8 : ℂ))))) :=
  (by
    intro _Host_i1 _rep_i1 _value_i1 _h_param_i1
    exact (congrArg₂ M.addValue (Litex.sameRefl _value_i1) (Litex.NativeBridge.sameOfDenoteNumber (Litex.number (M := M) (0.125 : ℂ)) (Litex.div (Litex.number (M := M) (1 : ℂ)) (Litex.number (M := M) (8 : ℂ)) (Litex.numberInC (M := M) (1 : ℂ)) (Litex.numberInC (M := M) (8 : ℂ)) (Litex.NativeBridge.notSameOfDenoteNumber (Litex.number (M := M) (8 : ℂ)) (Litex.number (M := M) (0 : ℂ)) (8 : ℂ) (0 : ℂ) (Litex.NativeBridge.denoteNumber (M := M) (8 : ℂ)) (Litex.NativeBridge.denoteNumber (M := M) (0 : ℂ)) (by norm_num))) (0.125 : ℂ) ((1 : ℂ) / (8 : ℂ)) (Litex.NativeBridge.denoteNumber (M := M) (0.125 : ℂ)) (Litex.NativeBridge.denoteDiv (Litex.number (M := M) (1 : ℂ)) (Litex.number (M := M) (8 : ℂ)) (Litex.numberInC (M := M) (1 : ℂ)) (Litex.numberInC (M := M) (8 : ℂ)) (Litex.NativeBridge.notSameOfDenoteNumber (Litex.number (M := M) (8 : ℂ)) (Litex.number (M := M) (0 : ℂ)) (8 : ℂ) (0 : ℂ) (Litex.NativeBridge.denoteNumber (M := M) (8 : ℂ)) (Litex.NativeBridge.denoteNumber (M := M) (0 : ℂ)) (by norm_num)) (1 : ℂ) (8 : ℂ) (Litex.NativeBridge.denoteNumber (M := M) (1 : ℂ)) (Litex.NativeBridge.denoteNumber (M := M) (8 : ℂ))) (by norm_num)))
  )
end LitexCompiled.file_lean_x2f_examples_x2f_decimal_x5f_and_x5f_fraction_x2f_statement_x2e_lit
