mod core;
mod definition;
mod function_membership;
mod function_properties;
mod known_facts;
pub(super) mod non_equational;
pub(super) mod numeric_membership;
pub mod set_relations;
mod transparent_definition;
mod universal_search;
