name = "litex_to_lean_compiler2"
version = "0.1.0"
defaultTargets = ["Litex", "Compiler2Examples"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.28.0"

[[lean_lib]]
name = "Litex"

[[lean_lib]]
name = "Compiler2Examples"
srcDir = "examples"
roots = ["SetSystem", "OrderSystem"]
