name = "stmt_result_to_lean_compiler"
version = "0.1.0"
defaultTargets = ["Litex"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.31.0"

[[lean_lib]]
name = "Litex"

[[lean_lib]]
name = "LitexGenerate"
srcDir = "../showcases/litex_to_lean_mathlib_pipeline/showcase2"

[[lean_lib]]
name = "LitexToMathlib"
srcDir = "../showcases/litex_to_lean_mathlib_pipeline/showcase2"
