pub mod by_builtin_strategy_result;
pub mod known_equality_graph;
pub mod search_equal_fact_by_rational_with_nonzero_premises;
pub mod search_equal_fact_proof_by_builtin_algebraic_rewrite;
pub mod search_equal_fact_proof_by_known_algebraic_rewrite;
pub mod search_equal_fact_proof_by_known_equality;
pub mod verify_equal_fact;
pub mod verify_equality_by_builtin_rules;

pub use by_builtin_strategy_result::EqualitySearchProofByBuiltinStrategy;
pub use search_equal_fact_proof_by_builtin_algebraic_rewrite::EqualitySearchProofByBuiltinAlgebraicRewrite;
pub use search_equal_fact_proof_by_known_algebraic_rewrite::EqualitySearchProofByKnownAlgebraicRewrite;
pub use verify_equality_by_builtin_rules::EqualitySearchProofByBuiltinRule;
