pub mod by_builtin_algebraic_rewrite_result;
pub mod by_builtin_rule_result;
pub mod by_builtin_strategy_result;
pub mod by_known_algebraic_rewrite_result;
pub mod verify_equal_fact;

pub use by_builtin_algebraic_rewrite_result::EqualitySearchProofByBuiltinAlgebraicRewrite;
pub use by_builtin_rule_result::EqualitySearchProofByBuiltinRule;
pub use by_builtin_strategy_result::EqualitySearchProofByBuiltinStrategy;
pub use by_known_algebraic_rewrite_result::EqualitySearchProofByKnownAlgebraicRewrite;
pub use verify_equal_fact::equal_fact_from_let;
