name = "litex_to_lean_mathlib_pipeline_showcase1"
version = "0.1.0"
defaultTargets = ["Final"]
packagesDir = "../../../lean/.lake/packages"

[[require]]
name = "stmt_result_to_lean_compiler"
path = "../../../lean"

[[lean_lib]]
name = "Generated"

[[lean_lib]]
name = "Adapter"

[[lean_lib]]
name = "Final"
