use crate::fact::{AtomicFact, Fact};
use crate::litex_to_lean_ir::{
    LitexToLeanDefObjStmtIr, LitexToLeanFactIr, LitexToLeanFactProofIr, LitexToLeanFactStatementIr,
    LitexToLeanFunctionApplicationIr, LitexToLeanFunctionTypeIr, LitexToLeanNormalizationKindIr,
    LitexToLeanObjectIr, LitexToLeanParameterTypeIr, LitexToLeanProofBlockStmtIr,
    LitexToLeanProofRuleIr, LitexToLeanStandardSetIr, LitexToLeanStatementIr,
    LitexToLeanWellDefinednessCertificateIr,
};
use crate::obj::{obj_equality_key, AtomObj, Obj, StandardSet};
use crate::rational_expression::objs_equal_by_rational_expression_evaluation;
use crate::result::{WellDefinedFunctionContract, WellDefinednessRequirementRole};
use crate::stmt::parameter_def::ParamType;
use crate::symbol::SymbolId;
use std::collections::HashMap;
use std::path::Path;

const LESS_EQUAL_OF_LESS_RULE_ID: &str = "order.less_equal_of_less";
const LESS_EQUAL_OF_LESS_FINGERPRINT: &str =
    "990acd86094d0a1d3c750541cac271a185c4d399c1277d2fdebac77b98130788";

pub fn emit_file(ir: &[LitexToLeanStatementIr], source_label: &str) -> Result<String, String> {
    let mut declarations = Vec::new();
    let mut fact_index = 0;
    let mut context = RenderContext::default();
    for statement in ir {
        emit_statement(statement, &mut declarations, &mut fact_index, &mut context)?;
    }
    if declarations.is_empty() {
        return Err("compiler2 requires at least one verified fact".into());
    }

    let file_name = Path::new(source_label)
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| format!("invalid source label `{source_label}`"))?;
    let stem = Path::new(file_name)
        .file_stem()
        .and_then(|name| name.to_str())
        .ok_or_else(|| format!("invalid source label `{source_label}`"))?;
    let namespace = format!("__Compiler2_{}", lean_identifier(stem));
    Ok(format!(
        "-- Generated by compiler2 from {file_name}. DO NOT EDIT.\n\
         import Litex.Rules\n\n\
         set_option linter.style.nameCheck false\n\n\
         namespace {namespace}\n\n{}\n\n\
         end {namespace}\n",
        declarations.join("\n\n")
    ))
}

fn emit_statement(
    statement: &LitexToLeanStatementIr,
    declarations: &mut Vec<String>,
    fact_index: &mut usize,
    context: &mut RenderContext,
) -> Result<(), String> {
    match statement {
        LitexToLeanStatementIr::ProofBlock(LitexToLeanProofBlockStmtIr::SketchStmt(sketch)) => {
            for step in &sketch.block.steps {
                emit_statement(step, declarations, fact_index, context)?;
            }
        }
        LitexToLeanStatementIr::DefObjStmt(LitexToLeanDefObjStmtIr::HaveObjEqualStmt(
            definition,
        )) => declarations.extend(emit_named_set_aliases(definition, context)?),
        LitexToLeanStatementIr::Fact(fact) => {
            let theorem_name = format!("__fact{fact_index}");
            declarations.push(emit_fact_statement(fact, *fact_index, context)?);
            if let Some(fact_id) = fact.source.fact_id {
                context.fact_names.insert(fact_id, theorem_name);
            }
            *fact_index += 1;
        }
        other => {
            return Err(format!(
                "unsupported compiler2 statement outside the current fact/set slice: {other:?}"
            ));
        }
    }
    Ok(())
}

fn emit_fact_statement(
    statement: &LitexToLeanFactStatementIr,
    theorem_index: usize,
    context: &RenderContext,
) -> Result<String, String> {
    if !statement.stored_projections.is_empty() || !statement.inferred_facts.is_empty() {
        return Err(format!(
            "compiler2 fact `{}` has unsupported stored projections or inferred facts",
            statement.source.proposition
        ));
    }
    match &statement.source.proposition {
        Fact::ForallFact(_) => emit_forall_fact(
            &statement.source,
            &statement.well_definedness,
            theorem_index,
            context,
        ),
        Fact::AtomicFact(AtomicFact::EqualFact(_)) => emit_atomic_equality_fact(
            &statement.source,
            &statement.well_definedness,
            theorem_index,
            context,
        ),
        other => Err(format!(
            "compiler2 currently emits atomic equality or `forall`, not `{other}`"
        )),
    }
}

fn emit_atomic_equality_fact(
    source: &LitexToLeanFactIr,
    well_definedness: &LitexToLeanWellDefinednessCertificateIr,
    theorem_index: usize,
    context: &RenderContext,
) -> Result<String, String> {
    let proposition = render_fact(&source.proposition, context)?;
    let mut proof_lines =
        emit_closed_numeric_well_definedness(well_definedness, theorem_index, context)?;
    proof_lines.push(format!("  exact {}", render_proof(source, context)?));
    Ok(format!(
        "theorem __fact{theorem_index} : {proposition} := by\n{}",
        proof_lines.join("\n")
    ))
}

fn emit_closed_numeric_well_definedness(
    certificate: &LitexToLeanWellDefinednessCertificateIr,
    theorem_index: usize,
    context: &RenderContext,
) -> Result<Vec<String>, String> {
    if !certificate.target_requirements.is_empty()
        || !certificate.parameter_facts.is_empty()
        || !certificate.binder_scopes.is_empty()
    {
        return Err(
            "atomic equality has unsupported target, parameter, or binder WD evidence".into(),
        );
    }
    for root_id in &certificate.root_obj_ids {
        if !certificate
            .objects
            .iter()
            .any(|object| object.well_defined_obj_id == *root_id)
        {
            return Err(format!(
                "WD root references unavailable object `{root_id:?}`"
            ));
        }
    }
    for root_use in &certificate.root_proof_uses {
        if !certificate
            .objects
            .iter()
            .any(|object| object.well_defined_obj_id == root_use.well_defined_obj_id)
        {
            return Err(format!(
                "WD proof use references unavailable object `{:?}`",
                root_use.well_defined_obj_id
            ));
        }
    }
    for source_use in &certificate.source_object_uses {
        let object = certificate
            .objects
            .iter()
            .find(|object| object.well_defined_obj_id == source_use.well_defined_obj_id)
            .ok_or_else(|| {
                format!(
                    "WD source use references unavailable object `{:?}`",
                    source_use.well_defined_obj_id
                )
            })?;
        if obj_equality_key(&source_use.source_object) != obj_equality_key(&object.source_object) {
            return Err("WD source use changed its retained object".into());
        }
    }
    for object in &certificate.objects {
        if !object.function_contracts.is_empty()
            || !object.ambient_binder_scope_ids.is_empty()
            || object.owned_binder_scope_id.is_some()
        {
            return Err(format!(
                "closed numeric WD object `{}` gained function or binder evidence",
                object.source_object
            ));
        }
        if object.intrinsic_result_set.as_ref().is_some_and(|set| {
            !matches!(
                set,
                LitexToLeanObjectIr::StandardSet(LitexToLeanStandardSetIr::Complex)
            )
        }) {
            return Err("closed numeric WD object has an unsupported intrinsic result set".into());
        }
        render_obj(&object.source_object, context)?;
        for child_use in &object.child_uses {
            let child = certificate
                .objects
                .iter()
                .find(|candidate| candidate.well_defined_obj_id == child_use.obj_id)
                .ok_or_else(|| {
                    format!(
                        "WD child references unavailable object `{:?}`",
                        child_use.obj_id
                    )
                })?;
            if obj_equality_key(&child.source_object) != obj_equality_key(&child_use.source_object)
            {
                return Err("WD child use changed its retained object".into());
            }
        }
        for fact_id in &object.well_defined_fact_ids {
            if !certificate
                .facts
                .iter()
                .any(|fact| fact.well_defined_fact_id == *fact_id)
            {
                return Err(format!(
                    "WD object references unavailable fact `{fact_id:?}`"
                ));
            }
        }
        for requirement in &object.target_requirements {
            let fact = certificate
                .facts
                .iter()
                .find(|fact| fact.well_defined_fact_id == requirement.well_defined_fact_id)
                .ok_or_else(|| {
                    format!(
                        "WD requirement references unavailable fact `{:?}`",
                        requirement.well_defined_fact_id
                    )
                })?;
            if fact.expected_proposition.to_string() != requirement.expected_proposition.to_string()
            {
                return Err("WD requirement changed its expected proposition".into());
            }
        }
    }

    let mut lines = Vec::new();
    for (index, fact) in certificate.facts.iter().enumerate() {
        if !fact.ambient_binder_scope_ids.is_empty()
            || fact.expected_proposition.to_string() != fact.fact.proposition.to_string()
        {
            return Err("closed numeric WD fact changed scope or proposition".into());
        }
        let proposition = render_fact(&fact.fact.proposition, context)?;
        let proof = render_proof(&fact.fact, context)?;
        lines.push(format!(
            "  have __wd{theorem_index}_{index} : {proposition} := {proof}"
        ));
    }
    Ok(lines)
}

fn emit_named_set_aliases(
    source: &crate::litex_to_lean_ir::LitexToLeanHaveObjEqualStmtIr,
    context: &mut RenderContext,
) -> Result<Vec<String>, String> {
    if source.definitions.is_empty() || source.facts.len() != source.definitions.len() * 2 {
        return Err("named set definition has unsupported certificate shape".into());
    }
    let mut declarations = Vec::new();
    for definition in &source.definitions {
        if definition.param_type != LitexToLeanParameterTypeIr::Set {
            return Err(format!(
                "compiler2 named object `{}` is not declared as a set",
                definition.name
            ));
        }
        let value = render_set_definition_value(&definition.value)?;
        let name = lean_identifier(&definition.name);
        if context
            .symbol_names
            .insert(definition.symbol_id, name.clone())
            .is_some()
        {
            return Err(format!(
                "duplicate compiler2 symbol identity for `{}`",
                definition.name
            ));
        }
        declarations.push(format!("abbrev {name} : Litex.Set := {value}"));
    }
    Ok(declarations)
}

fn render_set_definition_value(value: &LitexToLeanObjectIr) -> Result<&'static str, String> {
    match value {
        LitexToLeanObjectIr::StandardSet(LitexToLeanStandardSetIr::Real) => Ok("Litex.R"),
        LitexToLeanObjectIr::StandardSet(LitexToLeanStandardSetIr::Complex) => Ok("Litex.C"),
        _ => Err(format!(
            "unsupported compiler2 named set definition value `{value:?}`"
        )),
    }
}

fn emit_forall_fact(
    source: &LitexToLeanFactIr,
    well_definedness: &LitexToLeanWellDefinednessCertificateIr,
    theorem_index: usize,
    outer_context: &RenderContext,
) -> Result<String, String> {
    let Fact::ForallFact(forall) = &source.proposition else {
        return Err("compiler2 currently emits `forall` facts only".into());
    };
    let LitexToLeanFactProofIr::ForallIntroduction {
        parameter_premises,
        premises,
        inferred_premises,
        conclusions,
    } = &source.proof
    else {
        return Err("verified forall is missing ForallIntroduction evidence".into());
    };
    let params = forall
        .params_def_with_type
        .collect_param_bindings_with_types();
    if params.len() != parameter_premises.len() {
        return Err("forall parameter evidence count does not match source binders".into());
    }
    if forall.dom_facts.len() != premises.len() {
        return Err("forall domain evidence count does not match source premises".into());
    }
    if forall.then_facts.len() != conclusions.len() {
        return Err("forall conclusion evidence count does not match source conclusions".into());
    }

    let mut context = outer_context.clone();
    context.well_definedness = Some(well_definedness.clone());
    let mut binders = Vec::new();
    let mut intro_names = Vec::new();
    for (parameter_index, ((binding, param_type), premise)) in
        params.iter().zip(parameter_premises.iter()).enumerate()
    {
        let name = lean_identifier(binding.name());
        context.symbol_names.insert(binding.id(), name.clone());
        if matches!(param_type, ParamType::Set(_)) {
            validate_set_parameter_premise(binding.id(), &premise.fact)?;
            binders.push(format!("({name} : Litex.Set)"));
            intro_names.push(name);
            continue;
        }

        let set = parameter_set(param_type)?;
        let carrier_name = format!("__carrier{theorem_index}_{}", parameter_index + 1);
        match set {
            Obj::FnSet(_) => {
                binders.push(format!("{{{carrier_name} : Type 1}}"));
                intro_names.push(carrier_name.clone());
                binders.push(format!("({name} : {carrier_name})"));
            }
            set if set_requires_heterogeneous_carrier(set) => {
                binders.push(format!("{{{carrier_name} : Type}}"));
                intro_names.push(carrier_name.clone());
                binders.push(format!("({name} : {carrier_name})"));
            }
            _ => binders.push(format!("({name} : ℂ)")),
        }
        intro_names.push(name.clone());

        let expected = format!("Litex.In {name} {}", render_obj(set, &context)?);
        let actual = render_fact(&premise.fact, &context)?;
        if actual != expected {
            return Err(format!(
                "parameter evidence mismatch: expected `{expected}`, found `{actual}`"
            ));
        }
        let hypothesis = format!("__h{theorem_index}_{}", parameter_index + 1);
        binders.push(format!("({hypothesis} : {actual})"));
        intro_names.push(hypothesis.clone());
        context.fact_names.insert(premise.fact_id, hypothesis);
        if let Obj::FnSet(function_set) = set {
            let function = LitexToLeanFunctionTypeIr::lower(function_set)?;
            validate_unary_function_type(&function)?;
            context.function_bindings.insert(
                premise.fact_id,
                FunctionBinding {
                    function,
                    membership_proof_name: format!("__h{theorem_index}_{}", parameter_index + 1),
                },
            );
        }
    }

    for (premise_index, premise) in premises.iter().enumerate() {
        let actual = render_fact(&premise.fact, &context)?;
        let hypothesis = format!(
            "__h{theorem_index}_{}",
            parameter_premises.len() + premise_index + 1
        );
        binders.push(format!("({hypothesis} : {actual})"));
        intro_names.push(hypothesis.clone());
        context.fact_names.insert(premise.fact_id, hypothesis);
    }

    // Alias-derived inferred premises are verifier context, not theorem
    // binders. Validate that their propositions are in this emitter's
    // supported language, but leave their FactIds unavailable: if a target
    // proof actually cites one, proof rendering fails closed until compiler2
    // has an explicit adapter for that inference route.
    for inferred in inferred_premises {
        render_fact(&inferred.proposition, &context)?;
    }

    let conclusion_types = conclusions
        .iter()
        .map(|conclusion| render_fact(&conclusion.proposition, &context))
        .collect::<Result<Vec<_>, _>>()?;
    let conclusion_type = conjunction(&conclusion_types);
    let conclusion_proofs = conclusions
        .iter()
        .map(|conclusion| render_proof(conclusion, &context))
        .collect::<Result<Vec<_>, _>>()?;
    let proof = if conclusion_proofs.len() == 1 {
        format!("  exact {}", conclusion_proofs[0])
    } else {
        format!("  exact ⟨{}⟩", conclusion_proofs.join(", "))
    };

    Ok(format!(
        "theorem __fact{theorem_index} :\n    ∀ {},\n      {conclusion_type} := by\n  intro {}\n{proof}",
        binders.join(" "),
        intro_names.join(" ")
    ))
}

#[derive(Clone, Default)]
struct RenderContext {
    symbol_names: HashMap<SymbolId, String>,
    fact_names: HashMap<crate::common::fact_id::FactId, String>,
    function_bindings: HashMap<crate::common::fact_id::FactId, FunctionBinding>,
    well_definedness: Option<LitexToLeanWellDefinednessCertificateIr>,
}

#[derive(Clone)]
struct FunctionBinding {
    function: LitexToLeanFunctionTypeIr,
    membership_proof_name: String,
}

fn render_proof(fact: &LitexToLeanFactIr, context: &RenderContext) -> Result<String, String> {
    match &fact.proof {
        LitexToLeanFactProofIr::Memo { proof } => {
            let unwrapped = LitexToLeanFactIr {
                fact_id: fact.fact_id,
                proposition: fact.proposition.clone(),
                proof: proof.as_ref().clone(),
            };
            render_proof(&unwrapped, context)
        }
        LitexToLeanFactProofIr::KnownFactCitation { source_fact_id } => context
            .fact_names
            .get(source_fact_id)
            .cloned()
            .ok_or_else(|| format!("unavailable cited fact `{source_fact_id}`")),
        LitexToLeanFactProofIr::RuleApplication {
            rule,
            parameter_requirements,
            premises,
        } => match rule {
            LitexToLeanProofRuleIr::ObjectReflexivity
                if parameter_requirements.is_empty() && premises.is_empty() =>
            {
                let (left, right) = equality_parts(&fact.proposition)?;
                if obj_equality_key(left) != obj_equality_key(right) {
                    return Err("object-reflexivity certificate changed its equality".into());
                }
                Ok(format!("Litex.Same.refl {}", render_obj(left, context)?))
            }
            LitexToLeanProofRuleIr::Normalization {
                kind: LitexToLeanNormalizationKindIr::RationalExpressionSimplification,
            } if parameter_requirements.is_empty() && premises.is_empty() => {
                let (left, right) = equality_parts(&fact.proposition)?;
                if !objs_equal_by_rational_expression_evaluation(left, right) {
                    return Err(
                        "rational-normalization certificate does not match its equality".into(),
                    );
                }
                render_obj(left, context)?;
                render_obj(right, context)?;
                Ok("Litex.Same.ofEq (by norm_num)".into())
            }
            LitexToLeanProofRuleIr::ClosedStandardMembership
                if parameter_requirements.is_empty() && premises.is_empty() =>
            {
                let (element, set) = membership_parts(&fact.proposition)?;
                if !matches!(set, Obj::StandardSet(StandardSet::C)) {
                    return Err("compiler2 closed membership currently supports C only".into());
                }
                Ok(format!(
                    "Litex.Rules.complexInC {}",
                    render_obj(element, context)?
                ))
            }
            LitexToLeanProofRuleIr::EqualityRewrite(rewrite) => emit_membership_equality_rewrite(
                fact,
                rewrite.steps.len(),
                parameter_requirements,
                premises,
                context,
            ),
            LitexToLeanProofRuleIr::RegisteredRule(rule) => {
                emit_registered_rule(fact, rule, parameter_requirements, premises, context)
            }
            other => Err(format!("unsupported verified proof rule: {other:?}")),
        },
        other => Err(format!("unsupported verified proof evidence: {other:?}")),
    }
}

fn emit_membership_equality_rewrite(
    target: &LitexToLeanFactIr,
    rewrite_step_count: usize,
    parameter_requirements: &[LitexToLeanFactIr],
    premises: &[LitexToLeanFactIr],
    context: &RenderContext,
) -> Result<String, String> {
    if rewrite_step_count != 1 || !parameter_requirements.is_empty() || premises.len() != 2 {
        return Err("membership equality rewrite has unsupported certificate shape".into());
    }
    let (target_element, target_set) = membership_parts(&target.proposition)?;
    let (source_element, source_set) = membership_parts(&premises[0].proposition)?;
    if obj_equality_key(target_set) != obj_equality_key(source_set) {
        return Err("membership rewrite changed the set object".into());
    }
    let (left, right) = equality_parts(&premises[1].proposition)?;
    let source_key = obj_equality_key(source_element);
    let target_key = obj_equality_key(target_element);
    let left_key = obj_equality_key(left);
    let right_key = obj_equality_key(right);
    let direction = if source_key == left_key && target_key == right_key {
        "mp"
    } else if source_key == right_key && target_key == left_key {
        "mpr"
    } else {
        return Err("membership rewrite operands do not match equality evidence".into());
    };
    let membership = render_proof(&premises[0], context)?;
    let equality = render_proof(&premises[1], context)?;
    let set = render_obj(target_set, context)?;
    Ok(format!(
        "(Litex.In.congr {equality} {set}).{direction} {membership}"
    ))
}

fn emit_registered_rule(
    target: &LitexToLeanFactIr,
    rule: &crate::litex_to_lean_ir::LitexToLeanRegisteredRuleApplicationIr,
    parameter_requirements: &[LitexToLeanFactIr],
    premises: &[LitexToLeanFactIr],
    context: &RenderContext,
) -> Result<String, String> {
    if rule.rule_id.as_str() != LESS_EQUAL_OF_LESS_RULE_ID
        || rule.semantic_fingerprint.as_hex() != LESS_EQUAL_OF_LESS_FINGERPRINT
        || rule.parameter_requirement_count != 2
        || rule.premise_count != 1
        || rule.bindings.len() != 2
        || parameter_requirements.len() != 2
        || premises.len() != 1
    {
        return Err(format!(
            "unsupported or changed registered rule certificate `{}`",
            rule.rule_id.as_str()
        ));
    }
    for requirement in parameter_requirements {
        render_proof(requirement, context)?;
    }
    let (less_left, less_right) = less_parts(&premises[0].proposition)?;
    let (le_left, le_right) = less_equal_parts(&target.proposition)?;
    if obj_equality_key(less_left) != obj_equality_key(le_left)
        || obj_equality_key(less_right) != obj_equality_key(le_right)
    {
        return Err("less-to-less-equal rule changed its operands".into());
    }
    Ok(format!(
        "Litex.Lt.toLe {}",
        render_proof(&premises[0], context)?
    ))
}

fn render_fact(fact: &Fact, context: &RenderContext) -> Result<String, String> {
    let Fact::AtomicFact(atomic) = fact else {
        return Err(format!("unsupported compiler2 fact `{fact}`"));
    };
    match atomic {
        AtomicFact::InFact(fact) => Ok(format!(
            "Litex.In {} {}",
            render_obj(&fact.element, context)?,
            render_obj(&fact.set, context)?
        )),
        AtomicFact::EqualFact(fact) => Ok(format!(
            "Litex.Same {} {}",
            render_obj(&fact.left, context)?,
            render_obj(&fact.right, context)?
        )),
        AtomicFact::LessFact(fact) => Ok(format!(
            "Litex.Lt {} {}",
            render_obj(&fact.left, context)?,
            render_obj(&fact.right, context)?
        )),
        AtomicFact::LessEqualFact(fact) => Ok(format!(
            "Litex.Le {} {}",
            render_obj(&fact.left, context)?,
            render_obj(&fact.right, context)?
        )),
        _ => Err(format!("unsupported compiler2 atomic fact `{fact}`")),
    }
}

fn render_obj(obj: &Obj, context: &RenderContext) -> Result<String, String> {
    match obj {
        Obj::Atom(AtomObj::Forall(parameter)) => context
            .symbol_names
            .get(&parameter.symbol.id())
            .cloned()
            .ok_or_else(|| format!("unbound compiler2 symbol `{obj}`")),
        Obj::Atom(AtomObj::Def(parameter)) => context
            .symbol_names
            .get(&parameter.symbol.id())
            .cloned()
            .ok_or_else(|| format!("unbound compiler2 symbol `{obj}`")),
        Obj::Atom(AtomObj::Identifier(identifier)) => identifier
            .symbol
            .as_ref()
            .and_then(|symbol| context.symbol_names.get(&symbol.id()))
            .cloned()
            .ok_or_else(|| format!("unbound compiler2 symbol `{obj}`")),
        Obj::Number(number)
            if !number.normalized_value.is_empty()
                && number
                    .normalized_value
                    .chars()
                    .all(|character| character.is_ascii_digit()) =>
        {
            Ok(format!("({} : ℂ)", number.normalized_value))
        }
        Obj::Add(addition) => Ok(format!(
            "({} + {})",
            render_obj(addition.left.as_ref(), context)?,
            render_obj(addition.right.as_ref(), context)?
        )),
        Obj::FnSet(function_set) => {
            let function = LitexToLeanFunctionTypeIr::lower(function_set)?;
            render_function_set(&function, context)
        }
        Obj::FnObj(application) => {
            let LitexToLeanObjectIr::FunctionApplication(application) =
                LitexToLeanObjectIr::lower(&application.clone().into())?
            else {
                return Err("function application lowered to a non-application object".into());
            };
            render_function_application(&application, context)
        }
        Obj::StandardSet(set) => render_standard_set(*set).map(str::to_string),
        _ => Err(format!("unsupported compiler2 object `{obj}`")),
    }
}

fn validate_set_parameter_premise(symbol_id: SymbolId, premise: &Fact) -> Result<(), String> {
    let Fact::AtomicFact(AtomicFact::IsSetFact(is_set)) = premise else {
        return Err(format!(
            "set parameter retained non-set evidence `{premise}`"
        ));
    };
    let Obj::Atom(atom) = &is_set.set else {
        return Err("set parameter evidence targets a non-symbol object".into());
    };
    if atom.symbol_ref().map(|symbol| symbol.id()) != Some(symbol_id) {
        return Err("set parameter evidence changed its SymbolId".into());
    }
    Ok(())
}

fn set_requires_heterogeneous_carrier(set: &Obj) -> bool {
    matches!(
        set,
        Obj::Atom(AtomObj::Forall(_)) | Obj::Atom(AtomObj::Identifier(_))
    )
}

fn validate_unary_function_type(function: &LitexToLeanFunctionTypeIr) -> Result<(), String> {
    if function.parameters.len() != 1 || !function.domain_facts.is_empty() {
        return Err(
            "compiler2 function-set MVP supports exactly one parameter and no domain facts".into(),
        );
    }
    if matches!(
        function.return_set.as_ref(),
        LitexToLeanObjectIr::FunctionSet { .. }
    ) {
        return Err("compiler2 function-set MVP supports one application layer only".into());
    }
    Ok(())
}

fn render_function_set(
    function: &LitexToLeanFunctionTypeIr,
    context: &RenderContext,
) -> Result<String, String> {
    validate_unary_function_type(function)?;
    let domain = render_set_ir(&function.parameters[0].set, context)?;
    let codomain = render_set_ir(function.return_set.as_ref(), context)?;
    Ok(format!("(Litex.fnSet {domain} {codomain})"))
}

fn render_set_ir(object: &LitexToLeanObjectIr, context: &RenderContext) -> Result<String, String> {
    match object {
        LitexToLeanObjectIr::Symbol { symbol_id, name } => context
            .symbol_names
            .get(symbol_id)
            .cloned()
            .ok_or_else(|| format!("unbound compiler2 set symbol `{name}`")),
        LitexToLeanObjectIr::StandardSet(set) => match set {
            LitexToLeanStandardSetIr::Real => Ok("Litex.R".into()),
            LitexToLeanStandardSetIr::Complex => Ok("Litex.C".into()),
            other => Err(format!(
                "unsupported compiler2 function domain/codomain `{other:?}`"
            )),
        },
        other => Err(format!(
            "unsupported compiler2 function domain/codomain `{other:?}`"
        )),
    }
}

fn render_function_application(
    application: &LitexToLeanFunctionApplicationIr,
    context: &RenderContext,
) -> Result<String, String> {
    if application.argument_layers.len() != 1
        || application.source_argument_layers.len() != 1
        || application.argument_layers[0].len() != 1
        || application.source_argument_layers[0].len() != 1
    {
        return Err(
            "compiler2 function application MVP supports one unary source layer only".into(),
        );
    }
    let LitexToLeanObjectIr::Symbol { .. } = application.head.as_ref() else {
        return Err("compiler2 function application MVP requires a named head".into());
    };
    let certificate = context
        .well_definedness
        .as_ref()
        .ok_or_else(|| "function application has no active WD certificate".to_string())?;
    let source_use = certificate
        .source_object_uses
        .iter()
        .find(|source_use| source_use.source_occurrence_id == application.source_occurrence_id)
        .ok_or_else(|| {
            format!(
                "function application occurrence {} has no exact WD object use",
                application.source_occurrence_id.value()
            )
        })?;
    let object = certificate
        .objects
        .iter()
        .find(|object| object.well_defined_obj_id == source_use.well_defined_obj_id)
        .ok_or_else(|| "function application WD object is missing".to_string())?;
    if obj_equality_key(&object.source_object) != obj_equality_key(&application.source_application)
    {
        return Err("function application WD object changed its source occurrence".into());
    }
    let [WellDefinedFunctionContract::StoredMembershipFact(contract_fact_id)] =
        object.function_contracts.as_slice()
    else {
        return Err(
            "named unary application requires one verifier-selected membership FactId".into(),
        );
    };
    let binding = context
        .function_bindings
        .get(contract_fact_id)
        .ok_or_else(|| format!("unavailable function membership FactId `{contract_fact_id}`"))?;
    validate_unary_function_type(&binding.function)?;

    let argument_requirement = certificate
        .target_requirements
        .iter()
        .find(|requirement| {
            requirement.source_occurrence_id == application.source_occurrence_id
                && requirement.role
                    == WellDefinednessRequirementRole::FunctionArgumentMembership {
                        layer_index: 0,
                        parameter_index: 0,
                    }
        })
        .ok_or_else(|| {
            "unary application has no exact argument-membership requirement".to_string()
        })?;
    let argument_fact = certificate
        .facts
        .iter()
        .find(|fact| fact.well_defined_fact_id == argument_requirement.well_defined_fact_id)
        .ok_or_else(|| "unary application argument-membership proof is missing".to_string())?;
    if argument_fact.expected_proposition.to_string()
        != argument_requirement.expected_proposition.to_string()
    {
        return Err("unary application argument requirement changed proposition".into());
    }
    let argument_membership = render_proof(&argument_fact.fact, context)?;
    let head = render_ir_symbol(application.head.as_ref(), context)?;
    let argument = render_obj(&application.source_argument_layers[0][0], context)?;
    Ok(format!(
        "(Litex.fnApply {head} {} {argument} {argument_membership})",
        binding.membership_proof_name
    ))
}

fn render_ir_symbol(
    object: &LitexToLeanObjectIr,
    context: &RenderContext,
) -> Result<String, String> {
    let LitexToLeanObjectIr::Symbol { symbol_id, name } = object else {
        return Err("expected a compiler2 symbol".into());
    };
    context
        .symbol_names
        .get(symbol_id)
        .cloned()
        .ok_or_else(|| format!("unbound compiler2 symbol `{name}`"))
}

fn parameter_set(param_type: &ParamType) -> Result<&Obj, String> {
    match param_type {
        ParamType::Obj(set) => Ok(set),
        _ => Err(format!(
            "unsupported compiler2 parameter type `{param_type}`"
        )),
    }
}

fn render_standard_set(set: StandardSet) -> Result<&'static str, String> {
    match set {
        StandardSet::R => Ok("Litex.R"),
        StandardSet::C => Ok("Litex.C"),
        _ => Err(format!("unsupported compiler2 standard set `{set}`")),
    }
}

fn membership_parts(fact: &Fact) -> Result<(&Obj, &Obj), String> {
    match fact {
        Fact::AtomicFact(AtomicFact::InFact(fact)) => Ok((&fact.element, &fact.set)),
        _ => Err(format!("expected membership fact, found `{fact}`")),
    }
}

fn equality_parts(fact: &Fact) -> Result<(&Obj, &Obj), String> {
    match fact {
        Fact::AtomicFact(AtomicFact::EqualFact(fact)) => Ok((&fact.left, &fact.right)),
        _ => Err(format!("expected equality fact, found `{fact}`")),
    }
}

fn less_parts(fact: &Fact) -> Result<(&Obj, &Obj), String> {
    match fact {
        Fact::AtomicFact(AtomicFact::LessFact(fact)) => Ok((&fact.left, &fact.right)),
        _ => Err(format!("expected less-than fact, found `{fact}`")),
    }
}

fn less_equal_parts(fact: &Fact) -> Result<(&Obj, &Obj), String> {
    match fact {
        Fact::AtomicFact(AtomicFact::LessEqualFact(fact)) => Ok((&fact.left, &fact.right)),
        _ => Err(format!("expected less-equal fact, found `{fact}`")),
    }
}

fn conjunction(facts: &[String]) -> String {
    match facts {
        [] => "True".to_string(),
        [only] => only.clone(),
        _ => facts.join(" ∧ "),
    }
}

fn lean_identifier(source: &str) -> String {
    let mut result = source
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character
            } else {
                '_'
            }
        })
        .collect::<String>();
    if result.is_empty() {
        result.push('_');
    }
    result
}
