//! Atomic-except-equality builtin rules → Normal JSON text.
//!
//! Call site: `rule.rule_name_and_message(lang)` on
//! `AtomicExceptEqualityFactSearchProofByBuiltinRule`. Each family enum and
//! leaf proof owns its copy here (not in `project_normal`).

mod cite;
mod greater;
mod greater_equal;
mod in_fact;
mod is_cart;
mod is_finite_set;
mod is_nonempty_set;
mod is_set;
mod is_tuple;
mod less;
mod less_equal;
mod misc_result;
mod not_equal;
mod not_greater;
mod not_greater_equal;
mod not_in_fact;
mod not_is_finite_set;
mod not_is_nonempty_set;
mod not_less;
mod not_less_equal;
mod not_subset;
mod not_superset;
mod subset;
mod superset;

use crate::execute::execute_fact_stmt::verify_atomic_fact::verify_atomic_except_equality::search_atomic_except_equality_fact_proof_by_builtin_rules::AtomicExceptEqualityFactSearchProofByBuiltinRule;
use crate::json_output::explain::BuiltinRuleText;
use crate::launch_command::OutputLanguage;
use crate::runtime::FactId;

use self::cite::cite_from_atomic_builtin_rule;

impl AtomicExceptEqualityFactSearchProofByBuiltinRule {
    pub fn rule_name_and_message_en(&self) -> BuiltinRuleText {
        match self {
            Self::BijectiveFact(bf) => bf.rule_name_and_message_en(),
            Self::CoprimeFact(cf) => cf.rule_name_and_message_en(),
            Self::DvdFact(df) => df.rule_name_and_message_en(),
            Self::GreaterEqualFact(gef) => gef.rule_name_and_message_en(),
            Self::GreaterFact(gf) => gf.rule_name_and_message_en(),
            Self::InFact(if_) => if_.rule_name_and_message_en(),
            Self::InjectiveFact(if_) => if_.rule_name_and_message_en(),
            Self::IsCartFact(icf) => icf.rule_name_and_message_en(),
            Self::IsChoiceFunctionForFact(icfff) => icfff.rule_name_and_message_en(),
            Self::IsFiniteSetFact(ifsf) => ifsf.rule_name_and_message_en(),
            Self::IsNonemptySetFact(insf) => insf.rule_name_and_message_en(),
            Self::IsSetFact(isf) => isf.rule_name_and_message_en(),
            Self::IsTupleFact(itf) => itf.rule_name_and_message_en(),
            Self::LessEqualFact(lef) => lef.rule_name_and_message_en(),
            Self::LessFact(lf) => lf.rule_name_and_message_en(),
            Self::NormalAtomicFact(naf) => naf.rule_name_and_message_en(),
            Self::NotBijectiveFact(nbf) => nbf.rule_name_and_message_en(),
            Self::NotCoprimeFact(ncf) => ncf.rule_name_and_message_en(),
            Self::NotDvdFact(ndf) => ndf.rule_name_and_message_en(),
            Self::NotEqualFact(nef) => nef.rule_name_and_message_en(),
            Self::NotGreaterEqualFact(ngef) => ngef.rule_name_and_message_en(),
            Self::NotGreaterFact(ngf) => ngf.rule_name_and_message_en(),
            Self::NotInFact(nif) => nif.rule_name_and_message_en(),
            Self::NotInjectiveFact(nif) => nif.rule_name_and_message_en(),
            Self::NotIsCartFact(nicf) => nicf.rule_name_and_message_en(),
            Self::NotIsChoiceFunctionForFact(nicfff) => nicfff.rule_name_and_message_en(),
            Self::NotIsFiniteSetFact(nifsf) => nifsf.rule_name_and_message_en(),
            Self::NotIsNonemptySetFact(ninsf) => ninsf.rule_name_and_message_en(),
            Self::NotIsSetFact(nisf) => nisf.rule_name_and_message_en(),
            Self::NotIsTupleFact(nitf) => nitf.rule_name_and_message_en(),
            Self::NotLessEqualFact(nlef) => nlef.rule_name_and_message_en(),
            Self::NotLessFact(nlf) => nlf.rule_name_and_message_en(),
            Self::NotNormalAtomicFact(nnaf) => nnaf.rule_name_and_message_en(),
            Self::NotPrimeFact(npf) => npf.rule_name_and_message_en(),
            Self::NotProperSubsetFact(npsf) => npsf.rule_name_and_message_en(),
            Self::NotProperSupersetFact(npsf) => npsf.rule_name_and_message_en(),
            Self::NotSubsetFact(nsf) => nsf.rule_name_and_message_en(),
            Self::NotSupersetFact(nsf) => nsf.rule_name_and_message_en(),
            Self::NotSurjectiveFact(nsf) => nsf.rule_name_and_message_en(),
            Self::PrimeFact(pf) => pf.rule_name_and_message_en(),
            Self::ProperSubsetFact(psf) => psf.rule_name_and_message_en(),
            Self::ProperSupersetFact(psf) => psf.rule_name_and_message_en(),
            Self::SubsetFact(sf) => sf.rule_name_and_message_en(),
            Self::SupersetFact(sf) => sf.rule_name_and_message_en(),
            Self::SurjectiveFact(sf) => sf.rule_name_and_message_en(),
        }
    }

    pub fn rule_name_and_message_zh(&self) -> BuiltinRuleText {
        match self {
            Self::BijectiveFact(bf) => bf.rule_name_and_message_zh(),
            Self::CoprimeFact(cf) => cf.rule_name_and_message_zh(),
            Self::DvdFact(df) => df.rule_name_and_message_zh(),
            Self::GreaterEqualFact(gef) => gef.rule_name_and_message_zh(),
            Self::GreaterFact(gf) => gf.rule_name_and_message_zh(),
            Self::InFact(if_) => if_.rule_name_and_message_zh(),
            Self::InjectiveFact(if_) => if_.rule_name_and_message_zh(),
            Self::IsCartFact(icf) => icf.rule_name_and_message_zh(),
            Self::IsChoiceFunctionForFact(icfff) => icfff.rule_name_and_message_zh(),
            Self::IsFiniteSetFact(ifsf) => ifsf.rule_name_and_message_zh(),
            Self::IsNonemptySetFact(insf) => insf.rule_name_and_message_zh(),
            Self::IsSetFact(isf) => isf.rule_name_and_message_zh(),
            Self::IsTupleFact(itf) => itf.rule_name_and_message_zh(),
            Self::LessEqualFact(lef) => lef.rule_name_and_message_zh(),
            Self::LessFact(lf) => lf.rule_name_and_message_zh(),
            Self::NormalAtomicFact(naf) => naf.rule_name_and_message_zh(),
            Self::NotBijectiveFact(nbf) => nbf.rule_name_and_message_zh(),
            Self::NotCoprimeFact(ncf) => ncf.rule_name_and_message_zh(),
            Self::NotDvdFact(ndf) => ndf.rule_name_and_message_zh(),
            Self::NotEqualFact(nef) => nef.rule_name_and_message_zh(),
            Self::NotGreaterEqualFact(ngef) => ngef.rule_name_and_message_zh(),
            Self::NotGreaterFact(ngf) => ngf.rule_name_and_message_zh(),
            Self::NotInFact(nif) => nif.rule_name_and_message_zh(),
            Self::NotInjectiveFact(nif) => nif.rule_name_and_message_zh(),
            Self::NotIsCartFact(nicf) => nicf.rule_name_and_message_zh(),
            Self::NotIsChoiceFunctionForFact(nicfff) => nicfff.rule_name_and_message_zh(),
            Self::NotIsFiniteSetFact(nifsf) => nifsf.rule_name_and_message_zh(),
            Self::NotIsNonemptySetFact(ninsf) => ninsf.rule_name_and_message_zh(),
            Self::NotIsSetFact(nisf) => nisf.rule_name_and_message_zh(),
            Self::NotIsTupleFact(nitf) => nitf.rule_name_and_message_zh(),
            Self::NotLessEqualFact(nlef) => nlef.rule_name_and_message_zh(),
            Self::NotLessFact(nlf) => nlf.rule_name_and_message_zh(),
            Self::NotNormalAtomicFact(nnaf) => nnaf.rule_name_and_message_zh(),
            Self::NotPrimeFact(npf) => npf.rule_name_and_message_zh(),
            Self::NotProperSubsetFact(npsf) => npsf.rule_name_and_message_zh(),
            Self::NotProperSupersetFact(npsf) => npsf.rule_name_and_message_zh(),
            Self::NotSubsetFact(nsf) => nsf.rule_name_and_message_zh(),
            Self::NotSupersetFact(nsf) => nsf.rule_name_and_message_zh(),
            Self::NotSurjectiveFact(nsf) => nsf.rule_name_and_message_zh(),
            Self::PrimeFact(pf) => pf.rule_name_and_message_zh(),
            Self::ProperSubsetFact(psf) => psf.rule_name_and_message_zh(),
            Self::ProperSupersetFact(psf) => psf.rule_name_and_message_zh(),
            Self::SubsetFact(sf) => sf.rule_name_and_message_zh(),
            Self::SupersetFact(sf) => sf.rule_name_and_message_zh(),
            Self::SurjectiveFact(sf) => sf.rule_name_and_message_zh(),
        }
    }

    pub fn rule_name_and_message_zh_hant(&self) -> BuiltinRuleText {
        match self {
            Self::BijectiveFact(bf) => bf.rule_name_and_message_zh_hant(),
            Self::CoprimeFact(cf) => cf.rule_name_and_message_zh_hant(),
            Self::DvdFact(df) => df.rule_name_and_message_zh_hant(),
            Self::GreaterEqualFact(gef) => gef.rule_name_and_message_zh_hant(),
            Self::GreaterFact(gf) => gf.rule_name_and_message_zh_hant(),
            Self::InFact(if_) => if_.rule_name_and_message_zh_hant(),
            Self::InjectiveFact(if_) => if_.rule_name_and_message_zh_hant(),
            Self::IsCartFact(icf) => icf.rule_name_and_message_zh_hant(),
            Self::IsChoiceFunctionForFact(icfff) => icfff.rule_name_and_message_zh_hant(),
            Self::IsFiniteSetFact(ifsf) => ifsf.rule_name_and_message_zh_hant(),
            Self::IsNonemptySetFact(insf) => insf.rule_name_and_message_zh_hant(),
            Self::IsSetFact(isf) => isf.rule_name_and_message_zh_hant(),
            Self::IsTupleFact(itf) => itf.rule_name_and_message_zh_hant(),
            Self::LessEqualFact(lef) => lef.rule_name_and_message_zh_hant(),
            Self::LessFact(lf) => lf.rule_name_and_message_zh_hant(),
            Self::NormalAtomicFact(naf) => naf.rule_name_and_message_zh_hant(),
            Self::NotBijectiveFact(nbf) => nbf.rule_name_and_message_zh_hant(),
            Self::NotCoprimeFact(ncf) => ncf.rule_name_and_message_zh_hant(),
            Self::NotDvdFact(ndf) => ndf.rule_name_and_message_zh_hant(),
            Self::NotEqualFact(nef) => nef.rule_name_and_message_zh_hant(),
            Self::NotGreaterEqualFact(ngef) => ngef.rule_name_and_message_zh_hant(),
            Self::NotGreaterFact(ngf) => ngf.rule_name_and_message_zh_hant(),
            Self::NotInFact(nif) => nif.rule_name_and_message_zh_hant(),
            Self::NotInjectiveFact(nif) => nif.rule_name_and_message_zh_hant(),
            Self::NotIsCartFact(nicf) => nicf.rule_name_and_message_zh_hant(),
            Self::NotIsChoiceFunctionForFact(nicfff) => nicfff.rule_name_and_message_zh_hant(),
            Self::NotIsFiniteSetFact(nifsf) => nifsf.rule_name_and_message_zh_hant(),
            Self::NotIsNonemptySetFact(ninsf) => ninsf.rule_name_and_message_zh_hant(),
            Self::NotIsSetFact(nisf) => nisf.rule_name_and_message_zh_hant(),
            Self::NotIsTupleFact(nitf) => nitf.rule_name_and_message_zh_hant(),
            Self::NotLessEqualFact(nlef) => nlef.rule_name_and_message_zh_hant(),
            Self::NotLessFact(nlf) => nlf.rule_name_and_message_zh_hant(),
            Self::NotNormalAtomicFact(nnaf) => nnaf.rule_name_and_message_zh_hant(),
            Self::NotPrimeFact(npf) => npf.rule_name_and_message_zh_hant(),
            Self::NotProperSubsetFact(npsf) => npsf.rule_name_and_message_zh_hant(),
            Self::NotProperSupersetFact(npsf) => npsf.rule_name_and_message_zh_hant(),
            Self::NotSubsetFact(nsf) => nsf.rule_name_and_message_zh_hant(),
            Self::NotSupersetFact(nsf) => nsf.rule_name_and_message_zh_hant(),
            Self::NotSurjectiveFact(nsf) => nsf.rule_name_and_message_zh_hant(),
            Self::PrimeFact(pf) => pf.rule_name_and_message_zh_hant(),
            Self::ProperSubsetFact(psf) => psf.rule_name_and_message_zh_hant(),
            Self::ProperSupersetFact(psf) => psf.rule_name_and_message_zh_hant(),
            Self::SubsetFact(sf) => sf.rule_name_and_message_zh_hant(),
            Self::SupersetFact(sf) => sf.rule_name_and_message_zh_hant(),
            Self::SurjectiveFact(sf) => sf.rule_name_and_message_zh_hant(),
        }
    }

    pub fn rule_name_and_message_fr(&self) -> BuiltinRuleText {
        match self {
            Self::BijectiveFact(bf) => bf.rule_name_and_message_fr(),
            Self::CoprimeFact(cf) => cf.rule_name_and_message_fr(),
            Self::DvdFact(df) => df.rule_name_and_message_fr(),
            Self::GreaterEqualFact(gef) => gef.rule_name_and_message_fr(),
            Self::GreaterFact(gf) => gf.rule_name_and_message_fr(),
            Self::InFact(if_) => if_.rule_name_and_message_fr(),
            Self::InjectiveFact(if_) => if_.rule_name_and_message_fr(),
            Self::IsCartFact(icf) => icf.rule_name_and_message_fr(),
            Self::IsChoiceFunctionForFact(icfff) => icfff.rule_name_and_message_fr(),
            Self::IsFiniteSetFact(ifsf) => ifsf.rule_name_and_message_fr(),
            Self::IsNonemptySetFact(insf) => insf.rule_name_and_message_fr(),
            Self::IsSetFact(isf) => isf.rule_name_and_message_fr(),
            Self::IsTupleFact(itf) => itf.rule_name_and_message_fr(),
            Self::LessEqualFact(lef) => lef.rule_name_and_message_fr(),
            Self::LessFact(lf) => lf.rule_name_and_message_fr(),
            Self::NormalAtomicFact(naf) => naf.rule_name_and_message_fr(),
            Self::NotBijectiveFact(nbf) => nbf.rule_name_and_message_fr(),
            Self::NotCoprimeFact(ncf) => ncf.rule_name_and_message_fr(),
            Self::NotDvdFact(ndf) => ndf.rule_name_and_message_fr(),
            Self::NotEqualFact(nef) => nef.rule_name_and_message_fr(),
            Self::NotGreaterEqualFact(ngef) => ngef.rule_name_and_message_fr(),
            Self::NotGreaterFact(ngf) => ngf.rule_name_and_message_fr(),
            Self::NotInFact(nif) => nif.rule_name_and_message_fr(),
            Self::NotInjectiveFact(nif) => nif.rule_name_and_message_fr(),
            Self::NotIsCartFact(nicf) => nicf.rule_name_and_message_fr(),
            Self::NotIsChoiceFunctionForFact(nicfff) => nicfff.rule_name_and_message_fr(),
            Self::NotIsFiniteSetFact(nifsf) => nifsf.rule_name_and_message_fr(),
            Self::NotIsNonemptySetFact(ninsf) => ninsf.rule_name_and_message_fr(),
            Self::NotIsSetFact(nisf) => nisf.rule_name_and_message_fr(),
            Self::NotIsTupleFact(nitf) => nitf.rule_name_and_message_fr(),
            Self::NotLessEqualFact(nlef) => nlef.rule_name_and_message_fr(),
            Self::NotLessFact(nlf) => nlf.rule_name_and_message_fr(),
            Self::NotNormalAtomicFact(nnaf) => nnaf.rule_name_and_message_fr(),
            Self::NotPrimeFact(npf) => npf.rule_name_and_message_fr(),
            Self::NotProperSubsetFact(npsf) => npsf.rule_name_and_message_fr(),
            Self::NotProperSupersetFact(npsf) => npsf.rule_name_and_message_fr(),
            Self::NotSubsetFact(nsf) => nsf.rule_name_and_message_fr(),
            Self::NotSupersetFact(nsf) => nsf.rule_name_and_message_fr(),
            Self::NotSurjectiveFact(nsf) => nsf.rule_name_and_message_fr(),
            Self::PrimeFact(pf) => pf.rule_name_and_message_fr(),
            Self::ProperSubsetFact(psf) => psf.rule_name_and_message_fr(),
            Self::ProperSupersetFact(psf) => psf.rule_name_and_message_fr(),
            Self::SubsetFact(sf) => sf.rule_name_and_message_fr(),
            Self::SupersetFact(sf) => sf.rule_name_and_message_fr(),
            Self::SurjectiveFact(sf) => sf.rule_name_and_message_fr(),
        }
    }

    pub fn rule_name_and_message_ru(&self) -> BuiltinRuleText {
        match self {
            Self::BijectiveFact(bf) => bf.rule_name_and_message_ru(),
            Self::CoprimeFact(cf) => cf.rule_name_and_message_ru(),
            Self::DvdFact(df) => df.rule_name_and_message_ru(),
            Self::GreaterEqualFact(gef) => gef.rule_name_and_message_ru(),
            Self::GreaterFact(gf) => gf.rule_name_and_message_ru(),
            Self::InFact(if_) => if_.rule_name_and_message_ru(),
            Self::InjectiveFact(if_) => if_.rule_name_and_message_ru(),
            Self::IsCartFact(icf) => icf.rule_name_and_message_ru(),
            Self::IsChoiceFunctionForFact(icfff) => icfff.rule_name_and_message_ru(),
            Self::IsFiniteSetFact(ifsf) => ifsf.rule_name_and_message_ru(),
            Self::IsNonemptySetFact(insf) => insf.rule_name_and_message_ru(),
            Self::IsSetFact(isf) => isf.rule_name_and_message_ru(),
            Self::IsTupleFact(itf) => itf.rule_name_and_message_ru(),
            Self::LessEqualFact(lef) => lef.rule_name_and_message_ru(),
            Self::LessFact(lf) => lf.rule_name_and_message_ru(),
            Self::NormalAtomicFact(naf) => naf.rule_name_and_message_ru(),
            Self::NotBijectiveFact(nbf) => nbf.rule_name_and_message_ru(),
            Self::NotCoprimeFact(ncf) => ncf.rule_name_and_message_ru(),
            Self::NotDvdFact(ndf) => ndf.rule_name_and_message_ru(),
            Self::NotEqualFact(nef) => nef.rule_name_and_message_ru(),
            Self::NotGreaterEqualFact(ngef) => ngef.rule_name_and_message_ru(),
            Self::NotGreaterFact(ngf) => ngf.rule_name_and_message_ru(),
            Self::NotInFact(nif) => nif.rule_name_and_message_ru(),
            Self::NotInjectiveFact(nif) => nif.rule_name_and_message_ru(),
            Self::NotIsCartFact(nicf) => nicf.rule_name_and_message_ru(),
            Self::NotIsChoiceFunctionForFact(nicfff) => nicfff.rule_name_and_message_ru(),
            Self::NotIsFiniteSetFact(nifsf) => nifsf.rule_name_and_message_ru(),
            Self::NotIsNonemptySetFact(ninsf) => ninsf.rule_name_and_message_ru(),
            Self::NotIsSetFact(nisf) => nisf.rule_name_and_message_ru(),
            Self::NotIsTupleFact(nitf) => nitf.rule_name_and_message_ru(),
            Self::NotLessEqualFact(nlef) => nlef.rule_name_and_message_ru(),
            Self::NotLessFact(nlf) => nlf.rule_name_and_message_ru(),
            Self::NotNormalAtomicFact(nnaf) => nnaf.rule_name_and_message_ru(),
            Self::NotPrimeFact(npf) => npf.rule_name_and_message_ru(),
            Self::NotProperSubsetFact(npsf) => npsf.rule_name_and_message_ru(),
            Self::NotProperSupersetFact(npsf) => npsf.rule_name_and_message_ru(),
            Self::NotSubsetFact(nsf) => nsf.rule_name_and_message_ru(),
            Self::NotSupersetFact(nsf) => nsf.rule_name_and_message_ru(),
            Self::NotSurjectiveFact(nsf) => nsf.rule_name_and_message_ru(),
            Self::PrimeFact(pf) => pf.rule_name_and_message_ru(),
            Self::ProperSubsetFact(psf) => psf.rule_name_and_message_ru(),
            Self::ProperSupersetFact(psf) => psf.rule_name_and_message_ru(),
            Self::SubsetFact(sf) => sf.rule_name_and_message_ru(),
            Self::SupersetFact(sf) => sf.rule_name_and_message_ru(),
            Self::SurjectiveFact(sf) => sf.rule_name_and_message_ru(),
        }
    }

    pub fn rule_name_and_message_es(&self) -> BuiltinRuleText {
        match self {
            Self::BijectiveFact(bf) => bf.rule_name_and_message_es(),
            Self::CoprimeFact(cf) => cf.rule_name_and_message_es(),
            Self::DvdFact(df) => df.rule_name_and_message_es(),
            Self::GreaterEqualFact(gef) => gef.rule_name_and_message_es(),
            Self::GreaterFact(gf) => gf.rule_name_and_message_es(),
            Self::InFact(if_) => if_.rule_name_and_message_es(),
            Self::InjectiveFact(if_) => if_.rule_name_and_message_es(),
            Self::IsCartFact(icf) => icf.rule_name_and_message_es(),
            Self::IsChoiceFunctionForFact(icfff) => icfff.rule_name_and_message_es(),
            Self::IsFiniteSetFact(ifsf) => ifsf.rule_name_and_message_es(),
            Self::IsNonemptySetFact(insf) => insf.rule_name_and_message_es(),
            Self::IsSetFact(isf) => isf.rule_name_and_message_es(),
            Self::IsTupleFact(itf) => itf.rule_name_and_message_es(),
            Self::LessEqualFact(lef) => lef.rule_name_and_message_es(),
            Self::LessFact(lf) => lf.rule_name_and_message_es(),
            Self::NormalAtomicFact(naf) => naf.rule_name_and_message_es(),
            Self::NotBijectiveFact(nbf) => nbf.rule_name_and_message_es(),
            Self::NotCoprimeFact(ncf) => ncf.rule_name_and_message_es(),
            Self::NotDvdFact(ndf) => ndf.rule_name_and_message_es(),
            Self::NotEqualFact(nef) => nef.rule_name_and_message_es(),
            Self::NotGreaterEqualFact(ngef) => ngef.rule_name_and_message_es(),
            Self::NotGreaterFact(ngf) => ngf.rule_name_and_message_es(),
            Self::NotInFact(nif) => nif.rule_name_and_message_es(),
            Self::NotInjectiveFact(nif) => nif.rule_name_and_message_es(),
            Self::NotIsCartFact(nicf) => nicf.rule_name_and_message_es(),
            Self::NotIsChoiceFunctionForFact(nicfff) => nicfff.rule_name_and_message_es(),
            Self::NotIsFiniteSetFact(nifsf) => nifsf.rule_name_and_message_es(),
            Self::NotIsNonemptySetFact(ninsf) => ninsf.rule_name_and_message_es(),
            Self::NotIsSetFact(nisf) => nisf.rule_name_and_message_es(),
            Self::NotIsTupleFact(nitf) => nitf.rule_name_and_message_es(),
            Self::NotLessEqualFact(nlef) => nlef.rule_name_and_message_es(),
            Self::NotLessFact(nlf) => nlf.rule_name_and_message_es(),
            Self::NotNormalAtomicFact(nnaf) => nnaf.rule_name_and_message_es(),
            Self::NotPrimeFact(npf) => npf.rule_name_and_message_es(),
            Self::NotProperSubsetFact(npsf) => npsf.rule_name_and_message_es(),
            Self::NotProperSupersetFact(npsf) => npsf.rule_name_and_message_es(),
            Self::NotSubsetFact(nsf) => nsf.rule_name_and_message_es(),
            Self::NotSupersetFact(nsf) => nsf.rule_name_and_message_es(),
            Self::NotSurjectiveFact(nsf) => nsf.rule_name_and_message_es(),
            Self::PrimeFact(pf) => pf.rule_name_and_message_es(),
            Self::ProperSubsetFact(psf) => psf.rule_name_and_message_es(),
            Self::ProperSupersetFact(psf) => psf.rule_name_and_message_es(),
            Self::SubsetFact(sf) => sf.rule_name_and_message_es(),
            Self::SupersetFact(sf) => sf.rule_name_and_message_es(),
            Self::SurjectiveFact(sf) => sf.rule_name_and_message_es(),
        }
    }

    pub fn rule_name_and_message_ar(&self) -> BuiltinRuleText {
        match self {
            Self::BijectiveFact(bf) => bf.rule_name_and_message_ar(),
            Self::CoprimeFact(cf) => cf.rule_name_and_message_ar(),
            Self::DvdFact(df) => df.rule_name_and_message_ar(),
            Self::GreaterEqualFact(gef) => gef.rule_name_and_message_ar(),
            Self::GreaterFact(gf) => gf.rule_name_and_message_ar(),
            Self::InFact(if_) => if_.rule_name_and_message_ar(),
            Self::InjectiveFact(if_) => if_.rule_name_and_message_ar(),
            Self::IsCartFact(icf) => icf.rule_name_and_message_ar(),
            Self::IsChoiceFunctionForFact(icfff) => icfff.rule_name_and_message_ar(),
            Self::IsFiniteSetFact(ifsf) => ifsf.rule_name_and_message_ar(),
            Self::IsNonemptySetFact(insf) => insf.rule_name_and_message_ar(),
            Self::IsSetFact(isf) => isf.rule_name_and_message_ar(),
            Self::IsTupleFact(itf) => itf.rule_name_and_message_ar(),
            Self::LessEqualFact(lef) => lef.rule_name_and_message_ar(),
            Self::LessFact(lf) => lf.rule_name_and_message_ar(),
            Self::NormalAtomicFact(naf) => naf.rule_name_and_message_ar(),
            Self::NotBijectiveFact(nbf) => nbf.rule_name_and_message_ar(),
            Self::NotCoprimeFact(ncf) => ncf.rule_name_and_message_ar(),
            Self::NotDvdFact(ndf) => ndf.rule_name_and_message_ar(),
            Self::NotEqualFact(nef) => nef.rule_name_and_message_ar(),
            Self::NotGreaterEqualFact(ngef) => ngef.rule_name_and_message_ar(),
            Self::NotGreaterFact(ngf) => ngf.rule_name_and_message_ar(),
            Self::NotInFact(nif) => nif.rule_name_and_message_ar(),
            Self::NotInjectiveFact(nif) => nif.rule_name_and_message_ar(),
            Self::NotIsCartFact(nicf) => nicf.rule_name_and_message_ar(),
            Self::NotIsChoiceFunctionForFact(nicfff) => nicfff.rule_name_and_message_ar(),
            Self::NotIsFiniteSetFact(nifsf) => nifsf.rule_name_and_message_ar(),
            Self::NotIsNonemptySetFact(ninsf) => ninsf.rule_name_and_message_ar(),
            Self::NotIsSetFact(nisf) => nisf.rule_name_and_message_ar(),
            Self::NotIsTupleFact(nitf) => nitf.rule_name_and_message_ar(),
            Self::NotLessEqualFact(nlef) => nlef.rule_name_and_message_ar(),
            Self::NotLessFact(nlf) => nlf.rule_name_and_message_ar(),
            Self::NotNormalAtomicFact(nnaf) => nnaf.rule_name_and_message_ar(),
            Self::NotPrimeFact(npf) => npf.rule_name_and_message_ar(),
            Self::NotProperSubsetFact(npsf) => npsf.rule_name_and_message_ar(),
            Self::NotProperSupersetFact(npsf) => npsf.rule_name_and_message_ar(),
            Self::NotSubsetFact(nsf) => nsf.rule_name_and_message_ar(),
            Self::NotSupersetFact(nsf) => nsf.rule_name_and_message_ar(),
            Self::NotSurjectiveFact(nsf) => nsf.rule_name_and_message_ar(),
            Self::PrimeFact(pf) => pf.rule_name_and_message_ar(),
            Self::ProperSubsetFact(psf) => psf.rule_name_and_message_ar(),
            Self::ProperSupersetFact(psf) => psf.rule_name_and_message_ar(),
            Self::SubsetFact(sf) => sf.rule_name_and_message_ar(),
            Self::SupersetFact(sf) => sf.rule_name_and_message_ar(),
            Self::SurjectiveFact(sf) => sf.rule_name_and_message_ar(),
        }
    }

    pub fn rule_name_and_message_ja(&self) -> BuiltinRuleText {
        match self {
            Self::BijectiveFact(bf) => bf.rule_name_and_message_ja(),
            Self::CoprimeFact(cf) => cf.rule_name_and_message_ja(),
            Self::DvdFact(df) => df.rule_name_and_message_ja(),
            Self::GreaterEqualFact(gef) => gef.rule_name_and_message_ja(),
            Self::GreaterFact(gf) => gf.rule_name_and_message_ja(),
            Self::InFact(if_) => if_.rule_name_and_message_ja(),
            Self::InjectiveFact(if_) => if_.rule_name_and_message_ja(),
            Self::IsCartFact(icf) => icf.rule_name_and_message_ja(),
            Self::IsChoiceFunctionForFact(icfff) => icfff.rule_name_and_message_ja(),
            Self::IsFiniteSetFact(ifsf) => ifsf.rule_name_and_message_ja(),
            Self::IsNonemptySetFact(insf) => insf.rule_name_and_message_ja(),
            Self::IsSetFact(isf) => isf.rule_name_and_message_ja(),
            Self::IsTupleFact(itf) => itf.rule_name_and_message_ja(),
            Self::LessEqualFact(lef) => lef.rule_name_and_message_ja(),
            Self::LessFact(lf) => lf.rule_name_and_message_ja(),
            Self::NormalAtomicFact(naf) => naf.rule_name_and_message_ja(),
            Self::NotBijectiveFact(nbf) => nbf.rule_name_and_message_ja(),
            Self::NotCoprimeFact(ncf) => ncf.rule_name_and_message_ja(),
            Self::NotDvdFact(ndf) => ndf.rule_name_and_message_ja(),
            Self::NotEqualFact(nef) => nef.rule_name_and_message_ja(),
            Self::NotGreaterEqualFact(ngef) => ngef.rule_name_and_message_ja(),
            Self::NotGreaterFact(ngf) => ngf.rule_name_and_message_ja(),
            Self::NotInFact(nif) => nif.rule_name_and_message_ja(),
            Self::NotInjectiveFact(nif) => nif.rule_name_and_message_ja(),
            Self::NotIsCartFact(nicf) => nicf.rule_name_and_message_ja(),
            Self::NotIsChoiceFunctionForFact(nicfff) => nicfff.rule_name_and_message_ja(),
            Self::NotIsFiniteSetFact(nifsf) => nifsf.rule_name_and_message_ja(),
            Self::NotIsNonemptySetFact(ninsf) => ninsf.rule_name_and_message_ja(),
            Self::NotIsSetFact(nisf) => nisf.rule_name_and_message_ja(),
            Self::NotIsTupleFact(nitf) => nitf.rule_name_and_message_ja(),
            Self::NotLessEqualFact(nlef) => nlef.rule_name_and_message_ja(),
            Self::NotLessFact(nlf) => nlf.rule_name_and_message_ja(),
            Self::NotNormalAtomicFact(nnaf) => nnaf.rule_name_and_message_ja(),
            Self::NotPrimeFact(npf) => npf.rule_name_and_message_ja(),
            Self::NotProperSubsetFact(npsf) => npsf.rule_name_and_message_ja(),
            Self::NotProperSupersetFact(npsf) => npsf.rule_name_and_message_ja(),
            Self::NotSubsetFact(nsf) => nsf.rule_name_and_message_ja(),
            Self::NotSupersetFact(nsf) => nsf.rule_name_and_message_ja(),
            Self::NotSurjectiveFact(nsf) => nsf.rule_name_and_message_ja(),
            Self::PrimeFact(pf) => pf.rule_name_and_message_ja(),
            Self::ProperSubsetFact(psf) => psf.rule_name_and_message_ja(),
            Self::ProperSupersetFact(psf) => psf.rule_name_and_message_ja(),
            Self::SubsetFact(sf) => sf.rule_name_and_message_ja(),
            Self::SupersetFact(sf) => sf.rule_name_and_message_ja(),
            Self::SurjectiveFact(sf) => sf.rule_name_and_message_ja(),
        }
    }

    pub fn rule_name_and_message_ko(&self) -> BuiltinRuleText {
        match self {
            Self::BijectiveFact(bf) => bf.rule_name_and_message_ko(),
            Self::CoprimeFact(cf) => cf.rule_name_and_message_ko(),
            Self::DvdFact(df) => df.rule_name_and_message_ko(),
            Self::GreaterEqualFact(gef) => gef.rule_name_and_message_ko(),
            Self::GreaterFact(gf) => gf.rule_name_and_message_ko(),
            Self::InFact(if_) => if_.rule_name_and_message_ko(),
            Self::InjectiveFact(if_) => if_.rule_name_and_message_ko(),
            Self::IsCartFact(icf) => icf.rule_name_and_message_ko(),
            Self::IsChoiceFunctionForFact(icfff) => icfff.rule_name_and_message_ko(),
            Self::IsFiniteSetFact(ifsf) => ifsf.rule_name_and_message_ko(),
            Self::IsNonemptySetFact(insf) => insf.rule_name_and_message_ko(),
            Self::IsSetFact(isf) => isf.rule_name_and_message_ko(),
            Self::IsTupleFact(itf) => itf.rule_name_and_message_ko(),
            Self::LessEqualFact(lef) => lef.rule_name_and_message_ko(),
            Self::LessFact(lf) => lf.rule_name_and_message_ko(),
            Self::NormalAtomicFact(naf) => naf.rule_name_and_message_ko(),
            Self::NotBijectiveFact(nbf) => nbf.rule_name_and_message_ko(),
            Self::NotCoprimeFact(ncf) => ncf.rule_name_and_message_ko(),
            Self::NotDvdFact(ndf) => ndf.rule_name_and_message_ko(),
            Self::NotEqualFact(nef) => nef.rule_name_and_message_ko(),
            Self::NotGreaterEqualFact(ngef) => ngef.rule_name_and_message_ko(),
            Self::NotGreaterFact(ngf) => ngf.rule_name_and_message_ko(),
            Self::NotInFact(nif) => nif.rule_name_and_message_ko(),
            Self::NotInjectiveFact(nif) => nif.rule_name_and_message_ko(),
            Self::NotIsCartFact(nicf) => nicf.rule_name_and_message_ko(),
            Self::NotIsChoiceFunctionForFact(nicfff) => nicfff.rule_name_and_message_ko(),
            Self::NotIsFiniteSetFact(nifsf) => nifsf.rule_name_and_message_ko(),
            Self::NotIsNonemptySetFact(ninsf) => ninsf.rule_name_and_message_ko(),
            Self::NotIsSetFact(nisf) => nisf.rule_name_and_message_ko(),
            Self::NotIsTupleFact(nitf) => nitf.rule_name_and_message_ko(),
            Self::NotLessEqualFact(nlef) => nlef.rule_name_and_message_ko(),
            Self::NotLessFact(nlf) => nlf.rule_name_and_message_ko(),
            Self::NotNormalAtomicFact(nnaf) => nnaf.rule_name_and_message_ko(),
            Self::NotPrimeFact(npf) => npf.rule_name_and_message_ko(),
            Self::NotProperSubsetFact(npsf) => npsf.rule_name_and_message_ko(),
            Self::NotProperSupersetFact(npsf) => npsf.rule_name_and_message_ko(),
            Self::NotSubsetFact(nsf) => nsf.rule_name_and_message_ko(),
            Self::NotSupersetFact(nsf) => nsf.rule_name_and_message_ko(),
            Self::NotSurjectiveFact(nsf) => nsf.rule_name_and_message_ko(),
            Self::PrimeFact(pf) => pf.rule_name_and_message_ko(),
            Self::ProperSubsetFact(psf) => psf.rule_name_and_message_ko(),
            Self::ProperSupersetFact(psf) => psf.rule_name_and_message_ko(),
            Self::SubsetFact(sf) => sf.rule_name_and_message_ko(),
            Self::SupersetFact(sf) => sf.rule_name_and_message_ko(),
            Self::SurjectiveFact(sf) => sf.rule_name_and_message_ko(),
        }
    }

    pub fn rule_name_and_message_vi(&self) -> BuiltinRuleText {
        match self {
            Self::BijectiveFact(bf) => bf.rule_name_and_message_vi(),
            Self::CoprimeFact(cf) => cf.rule_name_and_message_vi(),
            Self::DvdFact(df) => df.rule_name_and_message_vi(),
            Self::GreaterEqualFact(gef) => gef.rule_name_and_message_vi(),
            Self::GreaterFact(gf) => gf.rule_name_and_message_vi(),
            Self::InFact(if_) => if_.rule_name_and_message_vi(),
            Self::InjectiveFact(if_) => if_.rule_name_and_message_vi(),
            Self::IsCartFact(icf) => icf.rule_name_and_message_vi(),
            Self::IsChoiceFunctionForFact(icfff) => icfff.rule_name_and_message_vi(),
            Self::IsFiniteSetFact(ifsf) => ifsf.rule_name_and_message_vi(),
            Self::IsNonemptySetFact(insf) => insf.rule_name_and_message_vi(),
            Self::IsSetFact(isf) => isf.rule_name_and_message_vi(),
            Self::IsTupleFact(itf) => itf.rule_name_and_message_vi(),
            Self::LessEqualFact(lef) => lef.rule_name_and_message_vi(),
            Self::LessFact(lf) => lf.rule_name_and_message_vi(),
            Self::NormalAtomicFact(naf) => naf.rule_name_and_message_vi(),
            Self::NotBijectiveFact(nbf) => nbf.rule_name_and_message_vi(),
            Self::NotCoprimeFact(ncf) => ncf.rule_name_and_message_vi(),
            Self::NotDvdFact(ndf) => ndf.rule_name_and_message_vi(),
            Self::NotEqualFact(nef) => nef.rule_name_and_message_vi(),
            Self::NotGreaterEqualFact(ngef) => ngef.rule_name_and_message_vi(),
            Self::NotGreaterFact(ngf) => ngf.rule_name_and_message_vi(),
            Self::NotInFact(nif) => nif.rule_name_and_message_vi(),
            Self::NotInjectiveFact(nif) => nif.rule_name_and_message_vi(),
            Self::NotIsCartFact(nicf) => nicf.rule_name_and_message_vi(),
            Self::NotIsChoiceFunctionForFact(nicfff) => nicfff.rule_name_and_message_vi(),
            Self::NotIsFiniteSetFact(nifsf) => nifsf.rule_name_and_message_vi(),
            Self::NotIsNonemptySetFact(ninsf) => ninsf.rule_name_and_message_vi(),
            Self::NotIsSetFact(nisf) => nisf.rule_name_and_message_vi(),
            Self::NotIsTupleFact(nitf) => nitf.rule_name_and_message_vi(),
            Self::NotLessEqualFact(nlef) => nlef.rule_name_and_message_vi(),
            Self::NotLessFact(nlf) => nlf.rule_name_and_message_vi(),
            Self::NotNormalAtomicFact(nnaf) => nnaf.rule_name_and_message_vi(),
            Self::NotPrimeFact(npf) => npf.rule_name_and_message_vi(),
            Self::NotProperSubsetFact(npsf) => npsf.rule_name_and_message_vi(),
            Self::NotProperSupersetFact(npsf) => npsf.rule_name_and_message_vi(),
            Self::NotSubsetFact(nsf) => nsf.rule_name_and_message_vi(),
            Self::NotSupersetFact(nsf) => nsf.rule_name_and_message_vi(),
            Self::NotSurjectiveFact(nsf) => nsf.rule_name_and_message_vi(),
            Self::PrimeFact(pf) => pf.rule_name_and_message_vi(),
            Self::ProperSubsetFact(psf) => psf.rule_name_and_message_vi(),
            Self::ProperSupersetFact(psf) => psf.rule_name_and_message_vi(),
            Self::SubsetFact(sf) => sf.rule_name_and_message_vi(),
            Self::SupersetFact(sf) => sf.rule_name_and_message_vi(),
            Self::SurjectiveFact(sf) => sf.rule_name_and_message_vi(),
        }
    }

    pub fn rule_name_and_message(&self, lang: OutputLanguage) -> BuiltinRuleText {
        match lang {
            OutputLanguage::English => self.rule_name_and_message_en(),
            OutputLanguage::Chinese => self.rule_name_and_message_zh(),
            OutputLanguage::ChineseTraditional => self.rule_name_and_message_zh_hant(),
            OutputLanguage::French => self.rule_name_and_message_fr(),
            OutputLanguage::Russian => self.rule_name_and_message_ru(),
            OutputLanguage::Spanish => self.rule_name_and_message_es(),
            OutputLanguage::Arabic => self.rule_name_and_message_ar(),
            OutputLanguage::Japanese => self.rule_name_and_message_ja(),
            OutputLanguage::Korean => self.rule_name_and_message_ko(),
            OutputLanguage::Vietnamese => self.rule_name_and_message_vi(),
        }
    }

    pub fn cite_fact_id(&self) -> Option<FactId> {
        cite_from_atomic_builtin_rule(self)
    }
}

mod order_complement;
