//! Isolated-environment well-definedness checks.

use crate::prelude::*;

impl Runtime {
    /// Mathematical contract: verify an object universally in the local
    /// context generated by the supplied typed parameters, without leaking
    /// those bound variables or assumptions to the caller's environment.
    pub fn verify_obj_well_defined_with_its_local_def(
        &mut self,
        params_def: impl Into<SetBoundParameterList>,
        binding_scope: BindingScope,
        obj: Obj,
    ) -> Result<(), RuntimeError> {
        let params_def = params_def.into();
        self.run_in_local_env(|rt| {
            for param_def in params_def.iter() {
                rt.define_params_with_set_in_scope(param_def, binding_scope)?;
            }
            rt.verify_obj_well_defined_and_store_cache(&obj, &ProofSearchState::initial())
        })
    }
}
