import Litex

namespace LitexCompiled.file_lean_x2f_examples_x2f_multiplication_x5f_distributes_x5f_over_x5f_addition_x2f_statement_x2e_lit

universe u v1 v2 v3
variable {M : Litex.Semantics.{u}}

theorem fact_1 : ∀ {_Host_i1 : Type v1} [_rep_i1 : Litex.Representation M _Host_i1] (_value_i1 : Litex.Obj (M := M) _Host_i1) (_h_param_i1 : Litex.In _value_i1 (Litex.C (M := M))) {_Host_i2 : Type v2} [_rep_i2 : Litex.Representation M _Host_i2] (_value_i2 : Litex.Obj (M := M) _Host_i2) (_h_param_i2 : Litex.In _value_i2 (Litex.C (M := M))) {_Host_i3 : Type v3} [_rep_i3 : Litex.Representation M _Host_i3] (_value_i3 : Litex.Obj (M := M) _Host_i3) (_h_param_i3 : Litex.In _value_i3 (Litex.C (M := M))), Litex.Same (Litex.mul _value_i1 (Litex.add _value_i2 _value_i3 _h_param_i2 _h_param_i3) _h_param_i1 (Litex.addInC _value_i2 _value_i3 _h_param_i2 _h_param_i3)) (Litex.add (Litex.mul _value_i1 _value_i2 _h_param_i1 _h_param_i2) (Litex.mul _value_i1 _value_i3 _h_param_i1 _h_param_i3) (Litex.mulInC _value_i1 _value_i2 _h_param_i1 _h_param_i2) (Litex.mulInC _value_i1 _value_i3 _h_param_i1 _h_param_i3)) :=
  (by
    intro _Host_i1 _rep_i1 _value_i1 _h_param_i1 _Host_i2 _rep_i2 _value_i2 _h_param_i2 _Host_i3 _rep_i3 _value_i3 _h_param_i3
    exact (Litex.NativeBridge.sameOfDenoteNumber (Litex.mul _value_i1 (Litex.add _value_i2 _value_i3 _h_param_i2 _h_param_i3) _h_param_i1 (Litex.addInC _value_i2 _value_i3 _h_param_i2 _h_param_i3)) (Litex.add (Litex.mul _value_i1 _value_i2 _h_param_i1 _h_param_i2) (Litex.mul _value_i1 _value_i3 _h_param_i1 _h_param_i3) (Litex.mulInC _value_i1 _value_i2 _h_param_i1 _h_param_i2) (Litex.mulInC _value_i1 _value_i3 _h_param_i1 _h_param_i3)) ((Litex.NativeBridge.asComplex _value_i1 _h_param_i1) * ((Litex.NativeBridge.asComplex _value_i2 _h_param_i2) + (Litex.NativeBridge.asComplex _value_i3 _h_param_i3))) (((Litex.NativeBridge.asComplex _value_i1 _h_param_i1) * (Litex.NativeBridge.asComplex _value_i2 _h_param_i2)) + ((Litex.NativeBridge.asComplex _value_i1 _h_param_i1) * (Litex.NativeBridge.asComplex _value_i3 _h_param_i3))) (Litex.NativeBridge.denoteMul _value_i1 (Litex.add _value_i2 _value_i3 _h_param_i2 _h_param_i3) _h_param_i1 (Litex.addInC _value_i2 _value_i3 _h_param_i2 _h_param_i3) (Litex.NativeBridge.asComplex _value_i1 _h_param_i1) ((Litex.NativeBridge.asComplex _value_i2 _h_param_i2) + (Litex.NativeBridge.asComplex _value_i3 _h_param_i3)) (Litex.NativeBridge.asComplex_spec _value_i1 _h_param_i1) (Litex.NativeBridge.denoteAdd _value_i2 _value_i3 _h_param_i2 _h_param_i3 (Litex.NativeBridge.asComplex _value_i2 _h_param_i2) (Litex.NativeBridge.asComplex _value_i3 _h_param_i3) (Litex.NativeBridge.asComplex_spec _value_i2 _h_param_i2) (Litex.NativeBridge.asComplex_spec _value_i3 _h_param_i3))) (Litex.NativeBridge.denoteAdd (Litex.mul _value_i1 _value_i2 _h_param_i1 _h_param_i2) (Litex.mul _value_i1 _value_i3 _h_param_i1 _h_param_i3) (Litex.mulInC _value_i1 _value_i2 _h_param_i1 _h_param_i2) (Litex.mulInC _value_i1 _value_i3 _h_param_i1 _h_param_i3) ((Litex.NativeBridge.asComplex _value_i1 _h_param_i1) * (Litex.NativeBridge.asComplex _value_i2 _h_param_i2)) ((Litex.NativeBridge.asComplex _value_i1 _h_param_i1) * (Litex.NativeBridge.asComplex _value_i3 _h_param_i3)) (Litex.NativeBridge.denoteMul _value_i1 _value_i2 _h_param_i1 _h_param_i2 (Litex.NativeBridge.asComplex _value_i1 _h_param_i1) (Litex.NativeBridge.asComplex _value_i2 _h_param_i2) (Litex.NativeBridge.asComplex_spec _value_i1 _h_param_i1) (Litex.NativeBridge.asComplex_spec _value_i2 _h_param_i2)) (Litex.NativeBridge.denoteMul _value_i1 _value_i3 _h_param_i1 _h_param_i3 (Litex.NativeBridge.asComplex _value_i1 _h_param_i1) (Litex.NativeBridge.asComplex _value_i3 _h_param_i3) (Litex.NativeBridge.asComplex_spec _value_i1 _h_param_i1) (Litex.NativeBridge.asComplex_spec _value_i3 _h_param_i3))) (by ring))
  )
end LitexCompiled.file_lean_x2f_examples_x2f_multiplication_x5f_distributes_x5f_over_x5f_addition_x2f_statement_x2e_lit
